### ISSUE TITLE
Whether support other monitoring methods

### ISSUE THREAD

**Issue by xiangbinwu-allen** [ntop/n2n#1003]
We use openwrt system to install edge
Due to device exitsed old version, which not support nc commands and python.
Would like to ask if there are other ways to obtain edge connection information. 
Known method :
1. The python scripts
2. nc -w1 -u localhost 5644

**Comment by Logan007** [comment]
Apart from evaluating the log output (which I do not recommend), I could only think of accessing the management port by ssh's port forwarding, e.g. `ssh -L 7777:localhost:5644 <openwrt system IP>` (only TCP). But then, as management port is UDP, you need to tunnel UDP through the forwarded TCP port for which you need `nc` again...

If you can install `n2n` on that system, I wonder if there really is no space for `nc` left?

**Comment by Logan007** [comment]
Considered answered. Please re-open if required.
