### ISSUE TITLE
A full-platform(macOS, iOS, Android, Windows, Synology and Cli) n2n based service 

### ISSUE THREAD

**Issue by yongqianme** [ntop/n2n#1005]
[OmniEdge](https://omniedge.io) is built on the protocol based on n2n

![macapp Dashboard-3 1](https://user-images.githubusercontent.com/93888/171026994-97890eb1-faed-4894-b27d-c4afbd13ab0c.png)

Find the code repo from below links:

+ [OmniEdge Android](https://github.com/omniedgeio/omniedge-android)
+ [OmniEdge macOS Gui](https://github.com/omniedgeio/omniedge-macOS)
+ [OmniEdge iOS](https://github.com/omniedgeio/omniedge-iOS)
+ [OmniEdge Windows](https://github.com/omniedgeio/omniedge-windows)
+ [OmniEdge Synology](https://github.com/omniedgeio/omniedge-synology)

**Comment by Logan007** [comment]
Thanks for letting us know.
