### ISSUE TITLE
ERROR: Bind error on local port 1968 [Address already in use]

### ISSUE THREAD

**Issue by CowSmiles** [ntop/n2n#1013]
When I tried to start two edge instance to connect different supernodes. I got the following error:
```
15/Jun/2022 10:21:33 [n2n.c:56] ERROR: Bind error on local port 1968 [Address already in use]
15/Jun/2022 10:21:33 [edge_utils.c:478] ERROR: socket setup failed
15/Jun/2022 10:21:33 [edge.c:1108] ERROR: failed in edge_init
```
does n2n support multiple edges? Or if there are some options to support this? 

My environments:

* n2n edge 3.0.0 May 20 2022 00:48:19
* MacOS Monterey 12.4 x86

Thanks.

**Comment by Logan007** [comment]
Yes, multiple edges are supported. You just should assign its own port such as `-p 1234` and its own management port, e.g. `-t 6543`.

The message you see is related to a multicast port (1968) which is used to detect local network area edges more easily. It is same for all edges. I have never seen it conflicting when starting several edges but might have escaped my attention. Has anyone else experienced this?

**Comment by CowSmiles** [comment]
@Logan007 Thank you very much. I have tried the parameter again and with no luck.

**Comment by Logan007** [comment]
Thank you for your feedback, I will check multicast socket again then. What system do you have it running on?

Meanwhile, there are several ways to disable the seemingly issue-triggering multicast detection:

- You could try to use `-e auto` or `-e <your_local_physical_ip_address>` which should disable multicast peer detection.
- Or, you compile with `-DSKIP_MULTICAST_PEERS_DISCOVERY` to completely disable that feature in your build.

**Comment by CowSmiles** [comment]
Thank for you kind help. My system is MacOS Monterey 12.4 x86.

I tried your suggestions. The second one worked. Thank you very much.

```sh
 ./configure CFLAGS="-DSKIP_MULTICAST_PEERS_DISCOVERY"
```

The parameter in the first one gives the same error message.
