### ISSUE TITLE
if A and B are in multiple level nat, is p2p communication between A and B possible? 

### ISSUE THREAD

**Issue by hustdc** [ntop/n2n#104]

**Comment by lucktu** [comment]
Yes, maybe.
 What you said is very uncertain, so the result is very difficult to have an answer.

**Comment by emanuele-f** [comment]
If any of the intermediate nat in a symmetric nat then it will not work

**Comment by emanuele-f** [comment]
Put in another way, `A -> B` p2p communication is only possible if all intermediate NAT in front of B are asymmetric. If you have other doubts please open a new issue.

**Comment by hustdc** [comment]
> Put in another way, `A -> B` p2p communication is only possible if all intermediate NAT in front of B are asymmetric. If you have other doubts please open a new issue.
Thanks.

**Comment by hustdc** [comment]
> Put in another way, `A -> B` p2p communication is only possible if all intermediate NAT in front of B are asymmetric. If you have other doubts please open a new issue.

thanks.
