### ISSUE TITLE
Do not want to install virtual network device (TAP)

### ISSUE THREAD

**Issue by huddhudd** [ntop/n2n#1043]
N2n is only applicable to port data channel, and IP MAC is no longer required. Installing network cards on many systems is not successful. This will affect some software registered with Mac

Therefore, I don't want to install virtual network devices, but only use n2n port for forwarding.

I don't know whether others have the same needs as me.

**Comment by hamishcoleman** [comment]
The entire purpose of n2n is to create a VPN with a virtual network device, so perhaps I do not fully understand your situation.  Are you able to explain in more details?

**Comment by Logan007** [comment]
Maybe an additional federated supernode could do instead then?

The idea of "nodes without virtual TAP" will not become reality before 4.0 for which we plan all equal nodes, some with and some without TAP, the latter replacing the supernodes.

**Comment by Smallthing** [comment]
is there a wintun.dll version? thank you

**Comment by hamishcoleman** [comment]
@Smallthing wintun is a layer3 solution but n2n is a layer2 VPN, so it is not compatible as such.  Can you explain your use case?

**Comment by huddhudd** [comment]
https://github.com/mudler/edgevpn 这个项目好象可以实现

______
Note from the editor: _"This project seems to be achievable" (google translate)_
Please use English as common bridging language around here. Thank you!
Best regards, Logan
