### ISSUE TITLE
How can I view the IP addresses automatically assigned by supernodes

### ISSUE THREAD

**Issue by wacalei** [ntop/n2n#1046]

**Comment by Logan007** [comment]
Hi there!

The TAP's IP address is output to the log, message should look like

```
... created local tap device IP: 10.xxx.xxx.xxx, Mask: 255.255.255.0, MAC: 6E:CD:D5:3F:32:6C
```

However, you cannot be exactly sure if this is the exact same address as submitted by the supernode. There currently is no output of that specific REGISTER_SUPER payload detail, not even with `-vvvvv` option. So, we might add this pretty soon.
