### ISSUE TITLE
will you integrate kcp protocol with n2n?

### ISSUE THREAD

**Issue by renothing** [ntop/n2n#105]
KCP is a fast and reliable protocol that can achieve the transmission effect of a reduction of the average latency by 30% to 40% and reduction of the maximum delay by a factor of three, at the cost of 10% to 20% more bandwidth wasted than TCP. 

here it is:
https://github.com/skywind3000/kcp/blob/master/README.en.md

**Comment by emanuele-f** [comment]
Hi, n2n uses a generic UDP tunnel. Inside you can encapsulate any transport protocol based on IP, e.g. TCP, UDP or KCP
