### ISSUE TITLE
Supernode as Daemon

### ISSUE THREAD

**Issue by RandomForestGump** [ntop/n2n#1051]
Hi,

I am looking to run supernode without -f as it's my system requirement. I am running supernode by compiling a binary from git 3.0 stable branch.

I am using ansible pipeline to execute n2n edge/ supernode setup and see that the supernode process is not running in the server. If I do the same command with a -f argument for foreground my system works and supernode process visible in ps -aux, but I have issues in my pipeline as it runs indefinitely.

Can you please suggest a way/ code to run supernode as a service so it runs in background without "-f"?

My command (supernode -p 5600  -v)

**Comment by Logan007** [comment]
There is a supernode service file for systemd in `packages/etc/system/systemd/` directory.
