### ISSUE TITLE
For serverless, here is a solution

### ISSUE THREAD

**Issue by huddhudd** [ntop/n2n#1053]
For serverless, here is a solution
After the trial, I thought the experience was very good.

https://github.com/mudler/edgevpn

I hope that N2n can have this convenient development

**Comment by Logan007** [comment]
Not sure for the GUI part... but if things turn out the way outlined, version 4.0 (far away) might make n2n somewhat easier to use, see discussion over [there](https://github.com/ntop/n2n/issues/920).
