### ISSUE TITLE
Use cases?

### ISSUE THREAD

**Issue by 621625** [ntop/n2n#1056]
Hello,

I'm BM. A very nice and polite guy. 

I'm a tester and I would like to test n2n. But I would like to know some use cases. Could you please mention 5 or 10 use cases for this package?

It's possible to ping the other computer you say. So is it also possible to SSH to it?
Is torrenting possible with this package?

Other interesting use cases?

**Comment by 621625** [comment]
Installed from stable release and tried SSH'ing. I can ping but if I SSH I get access denied error even though authorized_keys file has been updated. Anyone knows why? Am I supposed to be able to SSH with n2n?

**Comment by Logan007** [comment]
n2n is meant to establish VPN network connection as if the connected computers were in the same LAN, so ping and ssh and everything else is supposed to work. An `access denied` error looks like connection is possible but your `ssh` or firewall might need some adjustment.
