### ISSUE TITLE
Pending_peers is never purged

### ISSUE THREAD

**Issue by realjiangms** [ntop/n2n#106]
In int run_edge_loop(n2n_edge_t * eee, int *keep_running) we purge peer lists as following:

l1:  numPurged =  purge_expired_registrations(&(eee->known_peers));
l2:   numPurged += purge_expired_registrations(&(eee->pending_peers));

However "static time_t last_purge"  in size_t purge_expired_registrations(struct peer_info ** peer_list) is global shared and will be updated in l1. So eee->pending_peers is never purge.

Enable -v on edge could easily notice that

**Comment by realjiangms** [comment]
I raised an PR #109 as suggestion of solution

**Comment by emanuele-f** [comment]
Pull request merged
