### ISSUE TITLE
select-rtt option bug report

### ISSUE THREAD

**Issue by codercaizh** [ntop/n2n#1060]
description: When the federated mode is used and the "--select-rtt" option is enabled on the edge, once the connected supernode goes offline, the edge will not perform failover
edge startup command：
`/usr/bin/n2n-edge -f -H --select-rtt -A3 -d n2n0 -a static:10.0.2.2/24 -c cai -l ***:** -k **** -M 1400 -r`

one of the edges netcat screenshot
<img width="788" alt="image" src="https://user-images.githubusercontent.com/17381647/202737579-0f731fed-8143-4124-a1c1-4939765768f1.png">
The supernode with IP '116.26.*.*' is offline，but it is still in the first line of the supernode list and still seems to be selected

one of the supernodes netcat screenshot
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/17381647/202739303-a258d43e-e7c3-429d-abe0-13d01e770c90.png">
The IP '116.26.*.*' supernode does not appear in the federate list

guess: edge uses the first item in the supernode list by default, and when the "select-rtt" option is used, the supernode list will be sorted by rtt. When the supernode is offline, its rtt is empty, but the result is still ranked first, causing the edge to still try to connect to it, and ultimately fail to failover

suggestion: When using the "select-rtt" option, prioritize the supernodes whose rtt is not empty according to the existing rules at the front of the list, and put the supernodes whose rtt is empty at the end of the list, so that the edge can normally connect to the non-faulty supernode

**Comment by codercaizh** [comment]
After testing, even if the SLECT-RTT option is not added, a similar problem will occur with the default LOAD option, and I find that there will be a "." Character after the corresponding supernode name. What does this mean?
![IMG_20221119_074354](https://user-images.githubusercontent.com/17381647/202821191-316036ad-d348-4670-a220-250ccf4fba6e.jpg)
![IMG_20221119_074420](https://user-images.githubusercontent.com/17381647/202821194-43e98d98-7e80-44e0-a9ad-f56540eead22.jpg)

**Comment by GreatMichaelLee** [comment]
seems your first supernode run with different build version as there is no build version displayed like below two supernodes  in the first snapshot pic.

**Comment by codercaizh** [comment]
> seems your first supernode run with different build version as there is no build version displayed like below two supernodes in the first snapshot pic.

After many attempts, I found that as long as the edge is working in p2p, the failover of the supernode will not take effect. I try to directly kill the supernode that is being connected to the edge in Federated (the name ends with a * character). In the netcat of the edge, the status of the supernode only changes to the end with '.', and from the log, the edge It will only repeatedly try to connect to the supernode that has been killed, instead of connecting to another available supernode. May I ask why you want to design it this way?

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/17381647/202860331-6f4e16d4-2366-4fe1-a800-778cd06b9832.png">

**Comment by Logan007** [comment]
Hello, could you please try the current _dev_ branch for supernodes and edges? I remember some issues with supernode selection being fixed after 3.0 release.

**Comment by codercaizh** [comment]
When I compile a new Edge with the DEV branch, I found that it can work as expected. In the P2P mode, one supernode in manual Kill, Edge connected to other supernode after a period of time. So what is the reason for this problem? Which Commit is solved?

> Hello, could you please try the current _dev_ branch for supernodes and edges? I remember some issues with supernode selection being fixed after 3.0 release.

![IMG_20221123_015838](https://user-images.githubusercontent.com/17381647/203388994-98895fd3-23b8-4b35-b3ac-6acd95d4ac86.jpg)

![IMG_20221123_015955](https://user-images.githubusercontent.com/17381647/203388938-14067815-c02b-4417-b94a-11cd804fffaf.jpg)

**Comment by Logan007** [comment]
> When I compile a new Edge with the DEV branch, I found that it can work as expected.

So, current _dev_ solves it for you completely?

> So what is the reason for this problem?

Bugs :wink:

> Which Commit is solved?

Several... you might be able to retrieve them in the commit [history](https://github.com/ntop/n2n/commits/dev) if this is of specific interest to you as we try to keep commits descriptive.
