### ISSUE TITLE
supernode problem

### ISSUE THREAD

**Issue by dwj0** [ntop/n2n#1062]
In the latest version (ec15ebb80c3a656d368adf4b1b25701b8758b4f1), there is a problem with the supernode. The client keeps reporting "MAC or IP address already in use or not released yet by supernode". The supernode cannot forget this edge after two minutes.

3.0 Stable Release does not have this problem, but when this version of edge sets the supernode as DDNS, if the IP of the supernode changes, it will always fail to connect

Note, I compiled it in openwrt, others are unknown

**Comment by Logan007** [comment]
Thank you for reporting. You could try `-M` on the supernode(s) as a quick fix (omitting these checks). Not sure if openwrt-related (I cannot check on that), but Linux PC compile has not been showing this issue so far.

Does it happen just for a certain edge? And, I have to ask this, do all edges really have distinct MAC/IP addresses if even manually assigned?

> 3.0 Stable Release does not have this problem, but when this version of edge sets the supernode as DDNS, if the IP of the supernode changes, it will always fail to connect

It sounds as if there is some issue with the DNS resolver thread. Is it compiled with pthread support?

**Comment by dwj0** [comment]
I solved the problem with -M parameter
I found that kill edge does not have this problem without using -9
thanks.

**Comment by Logan007** [comment]
We actually have a hint to that in [one of our documents](https://github.com/ntop/n2n/blob/dev/doc/Faq.md#the-edge-repeatedly-throws-an-authentication-error-mac-or-ip-address-already-in-use-or-not-released-yet-by-supernode-message-what-is-wrong).
