### ISSUE TITLE
build the project in Centos 7

### ISSUE THREAD

**Issue by bluesky2319** [ntop/n2n#1063]
Hello,
I am trying to compile the project (v_3.1.1) in Centos 7 by enabling zstd and OpenSSL. I got an error during compilation. I want to know how I can fix the error.
I'd appreciate any assistance.

![image](https://user-images.githubusercontent.com/98977472/208423965-60841eec-5348-4cf2-9572-94dcd3e1c049.png)

**Comment by Logan007** [comment]
Not sure if it helps but openssl shows version 3.0.7 on my computer. Do you have an opportunity to upgrade it?

**Comment by sharuzzaman** [comment]
Install openssl-devel to get the library and then compile again

**Comment by bluesky2319** [comment]
Thank you for your reply. I upgraded OpenSSL to 3.0.7, but I faced the same error.

![image](https://user-images.githubusercontent.com/98977472/208465441-6fd1a5dc-24c7-40a0-b967-cfbf1567fe9e.png)

**Comment by sharuzzaman** [comment]
> Thank you for your reply. I upgraded OpenSSL to 3.0.7, but I faced the same error.
> 
> ![image](https://user-images.githubusercontent.com/98977472/208465441-6fd1a5dc-24c7-40a0-b967-cfbf1567fe9e.png)

Install the openssl-devel package for whatever openssl version that you install. Also, make sure you don't just install any random RPM you found on the Internet because if you do that, the binary that you compile is not transferable to other CentOS server that you might have

**Comment by bluesky2319** [comment]
I tried it again with the latest version, but the same error. I compiled the OpenSSL project, and the "make test" was passed.

![image](https://user-images.githubusercontent.com/98977472/208470211-6730cc85-e87d-4bd1-a80f-4a18cfce7a64.png)

**Comment by hamishcoleman** [comment]
Have you tried running `yum install openssl-devel` before running the configure? - this is what sharuzzaman is suggesting, which should provide the missing part that the configure is looking for.

**Comment by bluesky2319** [comment]
I run it and saw this message:
```
Package 1:openssl-devel-1.0.2k-25.el7_9.x86_64 already installed and latest version
Nothing to do
```

**Comment by hamishcoleman** [comment]
Since you have the openssl-devel package installed, my next assumption is that the version of that package is too old to support the features used in n2n - you can check the details in the config.log output to see why it decided that the library was not found.  (Centos 7 is quite old, so I would not be surprised at this)

Alternatively, you dont need to use the openssl library to compile and use n2n, so you could just compile without it (it has been designed to still work in this case)
