### ISSUE TITLE
-z2 = zstdPrompt for unsupported parameters

### ISSUE THREAD

**Issue by omaidb** [ntop/n2n#1079]
Centos7 has installed the zstd package
```shell
yum install zstd -y
```
After edge starts, the prompt：-z2 = zstdPrompt for unsupported parameters

**Comment by Logan007** [comment]
Hi there,

`zstd` support is not included by default; not only has the lib to be installed, it also needs to be configured during build time. May I refer you to [our build documentation](https://github.com/ntop/n2n/blob/dev/doc/BuildConfig.md#configuration-at-build-time) for this one?

**Comment by omaidb** [comment]
@Logan007 
Thanks brother, I use Centos7 to install n2n from the yum source, but it does not include zstd when it is built?
感谢兄弟，我使用Centos7从yum源中安装的n2n,它在构建时竟然不包含zstd？

**Comment by Logan007** [comment]
I am not sure about how that specific packet is built, but it is most likely that it does not include `zstd` support (because packet maintainer can't be sure if `zstd ` available on target system or not).

If you need `zstd` support, you would have to build your version yourself probably.

**Comment by omaidb** [comment]
I wonder, who built n2n in the yum source.
Can the rpm package after building zstd be updated to the yum source warehouse synchronously, this is the complete product release process.

我想知道，yum源中的n2n由谁来构建。
可否将构建zstd后的rpm包同步更新到yum源仓库中，这才是完整的产品发布流程。
