### ISSUE TITLE
Can I use a Wintun virtual network card in Edge?

### ISSUE THREAD

**Issue by AlexFugui** [ntop/n2n#1086]
Wintun dynamically adding network cards can better reduce management costs

Do we have a Windows version that supports Wintun?

**Comment by hamishcoleman** [comment]
Wintun provides a layer-3 virtual network card, however N2N is a layer-2 system.

While it is theoretically possible to write a layer-2 emulation to allow the two to interoperate, nobody has done this.

**Comment by AlexFugui** [comment]
thk for you explanation 
sry I am an outsider  not consider tha N2N is a layer2 system
because I am writing an open-source windows program to reduce user operations on virtual network cards, the dynamic loading of Wintun is an ideal state

**Comment by AlexFugui** [comment]
> Wintun provides a layer-3 virtual network card, however N2N is a layer-2 system.
> 
> While it is theoretically possible to write a layer-2 emulation to allow the two to interoperate, nobody has done this.


thk for you explanation
sry I am an outsider not consider tha N2N is a layer2 system
because I am writing an open-source windows program to reduce user operations on virtual network cards, the dynamic loading of Wintun is an ideal state

and another question
in the client, I would like to know which users are in the community and their connection types
how should I do?

**Comment by Logan007** [comment]
The `edge` only is aware of nodes to which it currently connects and forgets them after some time without active data flow. This helps scalability. The `supernode`(s) however have a more complete view. The [management port](https://github.com/ntop/n2n/blob/dev/doc/Faq.md#can-i-get-a-list-of-connected-edge-nodes-and-their-community-and-source-ip-address-from-the-supernode) and the [management port API](https://github.com/ntop/n2n/blob/dev/doc/ManagementAPI.md#management-api) provide available information.

The `n2n-httpd` and `n2n-ctl` scripts from the `srcipts/` directory might be of further support there.
