### ISSUE TITLE
Windows client warning no IGD UPnP found on the network

### ISSUE THREAD

**Issue by Klutton** [ntop/n2n#1095]
some windows 7 users give me feed back that this error shows in the log and then the edge could not ping other devices in n2n community network
What I want to know is that, in which cases will this warning message show up

**Comment by hamishcoleman** [comment]
This is just an informational message to do with discovering what resources are available.  The software does not need this and will work normally without it.

Any issues with connectivity are unrelated to this message.

N2N will attempt to enhance the success rate of peer-to-peer connections by looking for two types of UPnP gateway on the local network.  Many home routers do not support this and many modern internet connections also do not support it.  Thus there will often be a couple of error messages related to not finding any UPnP devices.  The VPN will still attempt to establish peer-to-peer connections and will also still fall back to sending data via the supernode.
