### ISSUE TITLE
High-Speed TAP (driver) in Windows?

### ISSUE THREAD

**Issue by bluesky2319** [ntop/n2n#1096]
Question: Is there any alternative to OpenVPN TAP in Windows?
OpenVPN speed is limited, and based on my test is around 250-300Mbps. 

The desired speed is 800-900 Mbps.

**Comment by hamishcoleman** [comment]
There is not currently any other option on Windows.  I am interested in what your use case is though?

**Comment by bluesky2319** [comment]
> There is not currently any other option on Windows. I am interested in what your use case is though?

Thanks for your reply. I have access to high-speed internet (1 Gbps), and when I use n2n my speed is dropped from 850-900Mbps to the lower numbers. I read in some forums which Wirequard or NordVPN have higher transmission speeds, they support more than 900 Mbps in Windows. Are there any other ways to speed up the transmission?

**Comment by hamishcoleman** [comment]
You can carefully select the encryption and compression settings that you are using to tune the speed for the hardware that you are using - have a look at the `doc/Crypto.md` document and the `tools/n2n-benchmark` test tool.

You can also compile with various optimisations to try and get more speed - have a look at `doc/BuildConfig.md` for some starting points.

However, none of these are going to change the tap interface - so if you have correctly identified the OpenVPN TAP interface as your bottleneck, it will not help your situation.

Some testing and benchmarking is definitely recommended - and we would be interested to hear what kind of speedup percentages you manage to achieve - I dont know that anyone has spent the time to write down benchmark results
