### ISSUE TITLE
openwrt LEDE build n2n fail 

### ISSUE THREAD

**Issue by GreatMichaelLee** [ntop/n2n#1099]
I see you removed the CMake part, this looks lead to the n2n build fail on my openwrt LEDE repo, so how can I change the make file adaptively?

_SOURCE=1 -Wl,-z,now -Wl,-z,relro " LDFLAGS="-L/home/builder/lede_x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/home/builder/lede_x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib -znow -zrelro " cmake -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_VERSION=1 -DCMAKE_SYSTEM_PROCESSOR=x86_64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS_RELEASE="-DNDEBUG" -DCMAKE_CXX_FLAGS_RELEASE="-DNDEBUG" -DCMAKE_C_COMPILER_LAUNCHER="" -DCMAKE_C_COMPILER="/home/builder/lede_x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/bin/x86_64-openwrt-linux-musl-gcc" -DCMAKE_CXX_COMPILER_LAUNCHER="" -DCMAKE_CXX_COMPILER="/home/builder/lede_x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/bin/x86_64-openwrt-linux-musl-g++" -DCMAKE_ASM_COMPILER_LAUNCHER="" -DCMAKE_ASM_COMPILER="/home/builder/lede_x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/bin/x86_64-openwrt-linux-musl-gcc" -DCMAKE_EXE_LINKER_FLAGS:STRING="-L/home/builder/lede_x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/home/builder/lede_x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib -znow -zrelro" -DCMAKE_MODULE_LINKER_FLAGS:STRING="-L/home/builder/lede_x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/home/builder/lede_x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib -znow -zrelro -Wl,-Bsymbolic-functions" -DCMAKE_SHARED_LINKER_FLAGS:STRING="-L/home/builder/lede_x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/usr/lib -L/home/builder/lede_x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/lib -znow -zrelro -Wl,-Bsymbolic-functions" -DCMAKE_AR="/home/builder/lede_x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/bin/x86_64-openwrt-linux-musl-gcc-ar" -DCMAKE_NM="/home/builder/lede_x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/bin/x86_64-openwrt-linux-musl-gcc-nm" -DCMAKE_RANLIB="/home/builder/lede_x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl/bin/x86_64-openwrt-linux-musl-gcc-ranlib" -DCMAKE_FIND_ROOT_PATH="/home/builder/lede_x86/staging_dir/target-x86_64_musl/usr;/home/builder/lede_x86/staging_dir/toolchain-x86_64_gcc-11.3.0_musl" -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=BOTH -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_STRIP=: -DCMAKE_INSTALL_PREFIX=/usr -DDL_LIBRARY=/home/builder/lede_x86/staging_dir/target-x86_64_musl -DCMAKE_PREFIX_PATH=/home/builder/lede_x86/staging_dir/target-x86_64_musl -DCMAKE_SKIP_RPATH=TRUE -DCMAKE_EXPORT_PACKAGE_REGISTRY=FALSE -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=TRUE -DCMAKE_FIND_USE_PACKAGE_REGISTRY=FALSE -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=TRUE -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=FALSE -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=TRUE -DCMAKE_GENERATOR="Ninja" -DCMAKE_BUILD_TYPE=Release -DN2N_OPTION_USE_PTHREAD=ON -DN2N_OPTION_USE_OPENSSL=ON -DN2N_OPTION_USE_PCAPLIB=ON -DN2N_OPTION_USE_ZSTD=ON -DN2N_OPTION_USE_PORTMAPPING=ON -Wno-dev /home/builder/lede_x86/build_dir/target-x86_64_musl/n2n-3.1.1_dev_git-b07eed3f84bb03acd047bfbbc938ca172ec150bb )
CMake Warning:
  Ignoring extra path from command line:

   "/home/builder/lede_x86/build_dir/target-x86_64_musl/n2n-3.1.1_dev_git-b07eed3f84bb03acd047bfbbc938ca172ec150bb"

CMake Error: The source directory "/home/builder/lede_x86/build_dir/target-x86_64_musl/n2n-3.1.1_dev_git-b07eed3f84bb03acd047bfbbc938ca172ec150bb" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make[3]: *** [Makefile:96: /home/builder/lede_x86/build_dir/target-x86_64_musl/n2n-3.1.1_dev_git-b07eed3f84bb03acd047bfbbc938ca172ec150bb/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 1
make[3]: Leaving directory '/home/builder/lede_x86/feeds/packages/net/n2n'
time: package/feeds/packages/n2n/compile#3.27#0.34#10.09
    ERROR: package/feeds/packages/n2n failed to build.
make[2]: *** [package/Makefile:116: package/feeds/packages/n2n/compile] Error 1
make[2]: Leaving directory '/home/builder/lede_x86'
make[1]: *** [package/Makefile:110: /home/builder/lede_x86/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/builder/lede_x86'
make: *** [/home/builder/lede_x86/include/toplevel.mk:231: world] Error 2

**Comment by GreatMichaelLee** [comment]
can we seriously double consider removing any global impact enviroment setting like building config etc and think about its necessary to users but not only maintenance purpose? this cmake removal is really get me sad ...

**Comment by hamishcoleman** [comment]
This change was discussed and examined since July last year (We did double consider it)  The cmake system was marked as deprecated for that entire time.  None of this should be a surprise if you are following the development of n2n.

The working build process for Openwrt is documented in the repository and there are two examples in the github actions that successfully build Openwrt.  We dont use or support Lede or other non mainline Openwrt derivatives, so I can only point you at the working builds.

**Comment by GreatMichaelLee** [comment]
oh…I am sorry to hear that…
