### ISSUE TITLE
[dev branch]How to build on Windows

### ISSUE THREAD

**Issue by Mike4Feet** [ntop/n2n#1104]
![1](https://user-images.githubusercontent.com/106004829/236874338-3e013848-4f7a-4eeb-8527-ee1782cd1589.png)

The n2n/doc/Building.md Doesn't work. When I run ./scripts/hack_fakeautoconf.sh from inside a bash shell ("C:\Program Files\Git\usr\bin\bash.exe"), it mentions "command not found" 
![2](https://user-images.githubusercontent.com/106004829/236874744-d7abf023-baa6-4914-b392-32f480ec1f53.png)

**Comment by hamishcoleman** [comment]
There appears to be something wrong with your configuration.  The commands that are not found are all standard tools that should be available within the bash environment.

You could try checking some things:

```
echo PATH=$PATH
type bash
type sh
type cat
```

**Comment by hamishcoleman** [comment]
I believe I have a suggestion that will help your issue.

Please start your bash prompt by clicking on the "Git Bash" start menu item.

I have updated the build instructions to make that clear

**Comment by GreatMichaelLee** [comment]
I have a question for building on windows MINGW, how can I enable those natmap/miniupnpc features by adding the compile parameter like --enable-xxx under linux compiling  during running the ./configure and append them? seems no options and place to add such things...

**Comment by hamishcoleman** [comment]
@GreatMichaelLee this would have been much better in a new issue, as it is basically unrelated to the original question.

Yes, as you have discovered, building with the extra libraries on a windows system is not perfect in the development branch.  This situation is intended to improve as the build system is continued to be refactored.

**Comment by Mike4Feet** [comment]
> There appears to be something wrong with your configuration. The commands that are not found are all standard tools that should be available within the bash environment.
> 
> You could try checking some things:
> 
> ```
> echo PATH=$PATH
> type bash
> type sh
> type cat
> ```

It works，Thanks so much

**Comment by GreatMichaelLee** [comment]
> @GreatMichaelLee this would have been much better in a new issue, as it is basically unrelated to the original question.
> 
> Yes, as you have discovered, building with the extra libraries on a windows system is not perfect in the development branch. This situation is intended to improve as the build system is continued to be refactored.

OK, I will raise a new issue for your reference and resolving:)
