### ISSUE TITLE
Local discovery by multicast stop working after a while

### ISSUE THREAD

**Issue by realjiangms** [ntop/n2n#111]
We use multicast for local p2p registration.
1. Start edge on A and B in local
2. Ping A -> B, p2p communication created successfully.
3. Leave network quiet, stop ping or other traffic for some while (for example, 30min)
4. Ping A-> B, not p2p communication can no longer established between A and B. I checked log on both edge and found multicast registration still happens, but somehow they can not recieve multicast message from peer.

5. Start edge on another C in local, and everything work fine again.

I'm not quite familiar with multicast, it feels like that multicast is deactivated and need a 3rd one to reactive it. Not sure whether the usage of multicast in n2n is wrong or not.

I checked meyerd's solution. Why do we think recording local ip/port on supernode is bad idea for local p2p connection? Is it for security concern? It seems to me that this solution even works fine in some multi-layered nat environment without any special requirements. Suppose following situation:
1. First level nat behind public ip: 192.168.1.0/24
2. Second level nat behind 192.168.1.100: 192.168.2.0/24
If there are nodes 192.168.1.10 and 192.168.2.10, they can create p2p connection on meyerd's solution as udp message from 192.168.2.10 to 192.168.1.10 is always OK.  (Alghouth it still breaks if we have both nodes in 192.168.2.0/24)

However multicast solution needs PIM-SM enabled on switch/router for above case

**Comment by Logan007** [comment]
One of the good things about n2n architecture is that the supernode does not publicly share private details about your internal network layout. 

To achieve the outlined goal in a secure way the detailed network information could be held by the edge nodes and distributed and updated periodically or on new connects via regular n2n encrypted communication (in this case: initiated by the n2n edge itself). Edge nodes would need to know how to handle this information, i.e. updating their internal node list, using it for local lookup or hole punching. It could be the supernode that announces just the triggering event.

I haven't observed the described behavior yet. It runs quite stable over a period of several days and nights (those without traffic) here. Local hosts are instantly able to find each other next morning. Maybe I am just lucky...

P. S. _An "edge management message channel" based on exchanging data telegrams between nodes definitely should be protected by some sort of replay prevention..._ :wink:

**Comment by realjiangms** [comment]
I figured out the reason by tcpdump and introduce more node.. It's because my A and B is in different switch, although they are in same subnet. When a new node join, all multicast traffic reaches all nodes in 2 different switches. I guess it is related to the IGMP message boardcasted in network while a new node joins. But after 1-2 minutes, only nodes in same switch can hear each other.  

I don't know whether it is correct behavior, but it seems more like network device issue (bug or configuration error) instead of n2n. As I mentioned in previous note multicast solution might relay on underlying switch/router setting. However I would vote for this solution according to the note about security part from @Logan008.

I would close the issue. Maybe we could add some release notes in readme for local peer discovery in complex network topology, so that next time someone meets the issue I met could understand that it is more environment issue insteadof n2n
