### ISSUE TITLE
Run N2N from CLI on Android

### ISSUE THREAD

**Issue by gky008** [ntop/n2n#112]
一直用您的n2n，感觉很实用，希望能有一个安卓命令行运行的edge，而不是apk。大神能不能编译一个呢。

**Comment by gky008** [comment]
我用的v1版本很稳定，但安卓手机不能用命令行开机自动启动很麻烦

**Comment by Logan007** [comment]
[hin2n](https://github.com/switch-iot/hin2n/wiki/Welcome-to-hin2n)有用吗？

**Comment by gky008** [comment]
hin2n要占用vpn接口，更不喜欢

**Comment by Logan007** [comment]
我明白了!

**Comment by gky008** [comment]
Sebbene tu abbia cambiato il titolo del mio messaggio, ma non hai risposto positivamente alla mia domanda. Puoi aiutarmi a compilare un edge che gira sulla riga di comando di Android? Sto usando la versione v1. C'è un gruppo in Cina che sta guardando i tuoi progressi!

**Comment by gky008** [comment]
Diamo un'occhiata a questo attraverso Google Translate

**Comment by emanuele-f** [comment]
Hi, please post in english if possible! Regarding the question, I'm not very familiar with n2n on android, I think @switch-st may help you

**Comment by gky008** [comment]
Several Android versions of the edge have been compiled. But all can create virtual network cards, but they can't communicate. Switch-st is based on the vpn interface, personally do not like this way

**Comment by emanuele-f** [comment]
Do you mean that if you have two android devices using N2N they cannot communicate each other with hin2n? I think that a VPN interface is needed in android in order to make N2N work, but I have no experience on this sorry.

**Comment by gky008** [comment]
No! Hin2n needs to occupy the vpn interface, which is very bad, my request is to compile a separate binary file running in Android, run it with the command line!

**Comment by Logan007** [comment]
As far as I understood, hin2n works on layer 3 - unlike n2n working on layer 2. On the other hand, it does not require a rooted device; that seems to be the trade-off.

**Comment by emanuele-f** [comment]
@gky008 with VPN interface you mean the standard android API for VPN (the key icon in the picture below)?

![2019-05-29_12-55](https://user-images.githubusercontent.com/5488003/58551739-4c1b9e00-8200-11e9-9ded-54b2f2cac16d.png)

**Comment by gky008** [comment]
Don't vpn

**Comment by emanuele-f** [comment]
To wrap up, using the Android VPN API seems a must if we don't want to deal with root privileges (and we don't really want). However, if someone is interested in developing this and provides a PR it's fine. I'm closing this issue for now.

**Comment by YCJDWCJI** [comment]
If you have ROOT, you can use `termux`.

> 如果你有 ROOT 权限，可以使用 `termux`。

```Bash
pkg update
pkg install n2n
sudo edge -f -c xxx -l 1.1.1.1:111 -a 10.10.10.10……
```
