### ISSUE TITLE
OpenWRT package

### ISSUE THREAD

**Issue by emanuele-f** [ntop/n2n#113]
N2N should become easily available in OpenWRT. At least, the makefile should be updated. We could also budle it in some standard way, e.g. via OpenWRT feeds

**Comment by emanuele-f** [comment]
With fa695e9f2b5eae2523ef6c055a579006ac0bf146 n2n can now be built by following the instructions at https://github.com/ntop/n2n/tree/dev/packages/openwrt . I've tested the supernode service and it's working fine, @lucktu can you test the edge node? My device is missing the kmod-tun module so I have to rebuild the full image before being able to test it.

Todo: start the supernode as "nobody" (currently it runs as root). I've tried changing the user from the procd params but then it fails to start

Note: A request for n2n+luci was published in openwrt (https://github.com/openwrt/packages/pull/4009) but then rejected, but I would retry once we get this working

Edit: I just tested the edge node and it works fine for me. More tests in different environments are welcome

**Comment by lucktu** [comment]
I'm sorry I'm late.

The current source code is estimated to be a problem. I actually did not succeed on Ubuntu. My friends all said that it did not succeed.

Then I went on following the instructions above, and there was this error:
root@OpenWrt:/tmp/n2n-dev/packages/n2n# make menuconfig
Makefile:5: /rules.mk: No such file or directory
Makefile:24: /package.mk: No such file or directory
make: *** No rule to make target `/package.mk'.  Stop.

**Comment by emanuele-f** [comment]
What is the problem you are experiencing with ubuntu? Regarding openwrt, you need to compile n2n within the openwrt directory structure. For example, in order to compile it for my mikrotic, I had to download the openwrt-sdk from https://downloads.openwrt.org/releases/18.06.4/targets/ar71xx/mikrotik/ , build it, and then followed the procedure above to compile n2n, so basically this is intended to be used in a cross-compiled environment

**Comment by lucktu** [comment]
I didn't download openwrt-sdk. I haven't used OpenWRT for a long time. It's a little rusty, I can try again. 

 I mean, it can't be compiled for Ubuntu. this is the easiest and easiest to succeed, but it failed..

**Comment by emanuele-f** [comment]
These instructions won't work outside the sdk (I've updated the readme). I think you normally compile n2n inside the arm device itself so in that case this feature won't be useful to you. You can just compile it as a normal linux system and you are fine with it

**Comment by lucktu** [comment]
I am sorry for my careless, there's an extra "./configure". add this and compile it properly.

My method of compiling for OpenWRT is done automatically using a program that a friend made for me in ubuntu. actually, that program is for padavan, but  it can be used on OpenWRT.

Now I use my method, which has been compiled and can be used normally on OpenWRT.

**Comment by emanuele-f** [comment]
Yes now `./autogen.sh` does not run `./configure`, it must be run manually.

**Comment by lucktu** [comment]
When my friend compiled the router firmware, he verified that the method here was feasible.

**Comment by emanuele-f** [comment]
Closing this for now as the OpenWRT support is now fixed and available. If anyone is interested in promoting this on the official OpenWRT packages please go on!
