### ISSUE TITLE
Remove nonce

### ISSUE THREAD

**Issue by Logan007** [ntop/n2n#116]
While working on the changes required for #101, I found that the nonce still seems to be in the code. With a view to the current IV implementation, it probably became obsolete allowing for a 4 bytes savings in the packet.

**Comment by emanuele-f** [comment]
I agree that's useless right now and can be removed in aes (in twofish it should remain to keep compatibility, see https://github.com/ntop/n2n/milestone/1).

**Comment by Logan007** [comment]
~~Would you mind if I solved it together with #101?~~ I better put it into another pull request as soon as the other one is merged.

**Comment by Logan007** [comment]
~~#119~~
