### ISSUE TITLE
Random Numbers

### ISSUE THREAD

**Issue by Logan007** [ntop/n2n#117]
As of now, random numbers get generated for use in nonce or IV seed using rand() .

For one of the future releases, we should discuss whether it is worth considering another, cryptographically more secure random number generator.

**Comment by emanuele-f** [comment]
The nonce will be removed so let's just ignore it. Regarding the IV seed, do you think there is an issue using rand here? The openssl random generator is very expensive as we saw in the benchmarks

**Comment by Logan007** [comment]
The way rand() generates pseudo random numbers is not considered cryptographically strong. It's max period is "only" 2 ^ 32 (or probably: 2 ^ 31 as unsigned). I wouldn't be surprised if there somewhere were a 32 bit x 4G = 16G file containing all rand() values in their sequence of occurence. Even though rand() gets seeded with a timer value (eee->start_time), this just changes the starting point of the sequence.

That makes the random numbers, i.e. our IV seed, somewhat predictable (their transmission is not encrypted). There is an attack described in the second part of [this](https://en.wikipedia.org/wiki/Initialization_vector#Properties) which highlights the need for true randomness. Although, our AES-ECB 128 bit encryption step before use complicates things for an attacker: the described XOR will not work, but still a start. A lot of assumptions and thus maybe just a theoretical problem.

For now, it just feels wrong to use such a predictable sequence where random numbers are expected. This is extremely unusual for cryptographic applications.

Alternatives could be openssl (indeed costly with a view to performance), some AES based PRNG method (performance to be evaluated), hash based PRNG (probably more costly than the AES based), or a Mersenne Twister (much longer period than rand() and thus less predictable, but without modifications also not considered cryptographically secure).

If we decided to look into alternatives, I would investigate some AES based solution as it is hardware accelerated on some platforms.

**Comment by emanuele-f** [comment]
A more robust generator would be better, but the performance impact of the openssl random_bytes is too much for the use in IV seed

**Comment by Logan007** [comment]
I would suggest to use AES (1 block, CTR mode, 128 bit key) with some key derived from the PSK, seeded **once** from XORing somewhat entropy-considered data, i.e. the seconds-fraction of current time, processor time, as well as full (unix) time stamp, and finally RDRAND (if available) or openssl's random_bytes.

**Comment by Logan007** [comment]
The [xorshift](https://en.wikipedia.org/wiki/Xorshift)-family is extremly interesting. Even though these algorithms do not offer complete cryptographic secure pseudo random numbers, they have longer period and are way less linear than C's rand. Performance probably is on par.

Please find [attached](https://github.com/ntop/n2n/files/3415004/random_numbers.txt) a draft implementation of [XORSHIFT128+](https://en.wikipedia.org/wiki/Xorshift#xorshift+), which seems to be a good compromise of performance (they say: 10 cycles on current CPUs) and (low, but better than rand) security.

The idea is to keep it flexible: we would need to also implement additional, more secure options. Those could kick in when higher security needs are required - for example based on input key length. [_As AES users with longer input keys already have decided to sacrifice performance for security, they would also want more secure random numbers, no matter if it costs even (a little) more performance._] XORSHIFT128+ could be considered level **0**.

Any thoughts?

**Comment by Logan007** [comment]
For level **1,** I would plan for some [AES-CTR](https://en.wikipedia.org/wiki/Cryptographically_secure_pseudorandom_number_generator#Designs_based_on_cryptographic_primitives) variant as it might benefit from hardware acceleration where available. Using 64 bit output of the internal 128 bit block length should even help to keep it indistinguishable. 

It should be faster than [openSSL](https://wiki.openssl.org/index.php/Random_Numbers)'s random numbers which would be level **2**. The good thing about openSSL is that (after proper initilization) it's random number generator is able to use intel's hardware noise random number generator (asm: rdrand) where available - providing extremly high entropy.

Any objections if I go for a pull request?

**Comment by Logan007** [comment]
#170 provides an implementation of xorshift+ as rand()-replacement. If accepted, I will proceed to also add the others. Let me know.

**Comment by Logan007** [comment]
I have closed the pull request as current dev has shifted away a little bit meanwhile. Still, I think n2n requires a cryptographically more secure random number generator than C's `rand()` – especially with a view to _ChaCha20_ (#230, #235) and its IVs.

Thus, I will renew my offer of implementing XORSHIFT128+ including a more entropy-loaded initialization as soon as _ChaCha20_ should be merged. Just let me know.
