### ISSUE TITLE
Traffic Restrictions could be configured in supernode or only edge?

### ISSUE THREAD

**Issue by crazyvest** [ntop/n2n#1172]
Thanks for the codes.
Any way to config Traffic Restrictions on supernode server side? Traffic Restrictions could be configured in supernode or only edge?

**Comment by hamishcoleman** [comment]
This project only has a very small amount of activity, but if you would like to try out the new fork [n3n](https://github.com/n42n/n3n), we could discus your issue in a ticket over there.

**Comment by crazyvest** [comment]
thanks i would try on n3n.

**Comment by crazyvest** [comment]
closed.
