### ISSUE TITLE
AES: fields in packet for 2.6 (SA?)

### ISSUE THREAD

**Issue by Logan007** [ntop/n2n#120]
While removing the nonce for #119, I stumbled on the SA field in the packet: Do we still need it?

If it comes to a stable 2.6 in the near future that introduces AES, do we need to think about how to make it future proof?

Do we accept that we probably already might break AES mode compatibility with release 2.8 again? If **yes**, we now could also get rid of SA field as potential upcoming features (DH key generation, MAC, ...) we probably will require some packet changes anyway. If **no**, we should think of the packet design more thoroughly.

**Comment by emanuele-f** [comment]
We don't need it and compatibility of aes is not a problem. It can be removed to save space.
