### ISSUE TITLE
Launch parameters

### ISSUE THREAD

**Issue by wmdfy** [ntop/n2n#121]
Dear Mr.
I just a won't programming user, I want to know how to read the configuration file from a file to start the super node and edge node, rather than through the command line arguments.
In addition, if you can make it dynamic link library (DLL)? On Windows, there is a black window don't look good.

thanks.
ps:I am a Chinese, this text is through the translation software to write

**Comment by emanuele-f** [comment]
Hi, on Windows there is the https://sourceforge.net/projects/n2nedgegui project which is quite easy to use but it's not maintained by us so it may be outdated.

**Comment by wmdfy** [comment]
yeah,i konw that project.But that's not what I want.
I am trying to use "E language" (a Chinese programming software) to write a small program, but because I don't have programming foundation, has studied the C language, so I would like to request you master, whether n2n made a dynamic link library, for other programs call, I think there should be a lot of people have such requirements.
thanks.

**Comment by emanuele-f** [comment]
The n2n build on windows should already create a library (maybe a static library) see https://github.com/ntop/n2n/blob/dev/CMakeLists.txt#L51 . You can build N2N on windows by following the instructions at
https://github.com/ntop/n2n/blob/dev/doc/Windows.md

**Comment by wmdfy** [comment]
thanks,I went to give it a try

**Comment by wmdfy** [comment]
> windows上的n2n构建应该已经创建了一个库（可能是一个静态库），请参阅https://github.com/ntop/n2n/blob/dev/CMakeLists.txt#L51。您可以按照[https://github.com/ntop/n2n/blob/dev/doc/Windows.md上](https://github.com/ntop/n2n/blob/dev/doc/Windows.md)的说明在Windows上构建N2N。
> [](https://github.com/ntop/n2n/blob/dev/doc/Windows.md)

I try to learn how to modify the source code, but I failed, whether can develop a dynamic link library branches, in order to convenient to integrate the "N2N" into other software?
thanks

**Comment by emanuele-f** [comment]
Ok, I will try build a DLL

**Comment by wmdfy** [comment]
thanks

**Comment by emanuele-f** [comment]
Check out https://github.com/ntop/n2n/blob/dev/dll/n2n.dll

**Comment by wmdfy** [comment]
> Check out https://github.com/ntop/n2n/blob/dev/dll/n2n.dll

emmmmmmmmm,I don't like find public function?

**Comment by emanuele-f** [comment]
Do you mean https://github.com/ntop/n2n/blob/dev/n2n.h ? Here is how to integrate quickly: https://github.com/ntop/n2n/blob/dev/example_edge_embed.c

**Comment by wmdfy** [comment]
Probably because I am not a programmer, expression is not accurate. In my understanding, the DLL should have some public functions for other program calls, but I did not find in the compiled DLL you open function, so I don't know how to call it ".h" files, because I don't use the C language, so I can't use it.
I'm sorry to bring you so much extra work.
Finally, thank you for your patience .

**Comment by fengdaolong** [comment]
The dll target should be built by cmake instead of putting the dll file in the source code. I hope the source code should be kept clean.

**Comment by Teteros** [comment]
Maybe add the standard options
- `allow_routing` (-r on command-line)
- `drop_multicast` (-E)
to `quick_edge_init` in the embed example?

I think that's the only ones missing from a basic edge set up there.

**Comment by emanuele-f** [comment]
> Maybe add the standard options
> 
>     * `allow_routing` (-r on command-line)
> 
>     * `drop_multicast` (-E)
>       to `quick_edge_init` in the embed example?
> 
> 
> I think that's the only ones missing from a basic edge set up there.

We should expose the n2n_edge_conf_t as a parameter of quick_edge_init (https://github.com/ntop/n2n/blob/365dd29b1296ccb5d8453c84a88bf38f9fefa772/n2n.h#L196). Can you open a separate issue?

**Comment by emanuele-f** [comment]
> The dll target should be built by cmake instead of putting the dll file in the source code. I hope the source code should be kept clean.

@wmdfy  I've uploaded it here https://filebin.ca/4k805LnJkOdq/n2n.dll , but both for security reasons and in order to get the latest code you should try to build it yourself via cmake as suggested. The .h file gives you the API which you can call from the DLL file.

**Comment by wmdfy** [comment]
> > The dll target should be built by cmake instead of putting the dll file in the source code. I hope the source code should be kept clean.
> 
> @wmdfy I've uploaded it here https://filebin.ca/4k805LnJkOdq/n2n.dll , but both for security reasons and in order to get the latest code you should try to build it yourself via cmake as suggested. The .h file gives you the API which you can call from the DLL file.

I'll try! Thank you very much
