### ISSUE TITLE
P2P connection stalls after some time

### ISSUE THREAD

**Issue by emanuele-f** [ntop/n2n#125]
As reported in #93 . Needs to be investigated

**Comment by lucktu** [comment]
If the established p2p does not communicate for a period of time, the original links will be lost,So the new connection may not be p2p again, which is normal.

Therefore, I recommend that it always check whether that can create P2P, and if possible, try to establish P2P until successful.

**Comment by emanuele-f** [comment]
This is fixed in 0e6db6361ec6793851c506ae7acb763f14a9e446 . Further work will follow about p2p registration

**Comment by lucktu** [comment]
Now it's like this: after a while, it becomes P2P, but the time is too long, 1~15 minutes.

Compile time: Jun  9 2019 07:56:00

Please refer to the following post for more details:
https://github.com/ntop/n2n/issues/93
