### ISSUE TITLE
Ping is not in sync with data transmission about p2p.

### ISSUE THREAD

**Issue by lucktu** [ntop/n2n#126]
Judging from Ping, it is already P2P, but the transmission data (FTP) is not P2P.

**Comment by emanuele-f** [comment]
Please checkout the new version f36814b152f3a8d6a47e94f3735df507e52147a4

Note: you need to update the supernode too

**Comment by lucktu** [comment]
Please refer to the following post for the latest test: https://github.com/ntop/n2n/issues/93
