### ISSUE TITLE
An app for android without root is coming !

### ISSUE THREAD

**Issue by lucktu** [ntop/n2n#13]
https://github.com/switch-iot/n2n_vLTS

**Comment by lucaderi** [comment]
hi @lucktu can we merge your app 9that looks very interesting) with the n2n repository in order to avoid keeping files in multiple places?

**Comment by switch-st** [comment]
> hi @lucktu can we merge your app (that looks very interesting) with the n2n repository in order to avoid keeping files in multiple places?

Thank you for your attention. I am very exciting to merge this app to n2n repo. However, in my project(https://github.com/switch-iot/n2n_vLTS), the app code and the n2n code are separate. Because I want to support multiple versions of the n2n protocol(like v1, v2). And now only the n2n version of the meryd's branch is supported by the app hin2n. I'll find a way to merge hin2n to n2n repo in several days. Do you have any suggestions for merging this app to n2n?

**Comment by lucaderi** [comment]
Personally I am not interested in v1, only in v2.
Please let me know if you want to send me a merge request, or if you have something else in mind. Thank you for your contributions

**Comment by switch-st** [comment]
I want to send a PR and I will do it on this weekend.

**Comment by lucktu** [comment]
First of all, It's very nise to see your return, very !!!

Then, In actually, V1 is used by most people for it's faster and stable.

**Comment by switch-st** [comment]
@lucaderi I send a PR(https://github.com/ntop/n2n/pull/14). I hope you can accept it.

**Comment by lucaderi** [comment]
Sure thank you.
What I miss is how to build the application and create a package. Can you please elaborate not this?

**Comment by switch-st** [comment]
You should prepare android development environment.
1. Install jdk.
2. Generate app keystore by commond **keytool -genkey -alias Hin2n -keystore Hin2n.jks**. And remember these two passwords.
3. Move Hin2n.jks to `android/Hin2n/app` directory. We will use this file to sign the application.
4. Download android tools from `https://developer.android.com/`, and unzip it.
5. Install android development environment.
> echo y | ./tools/bin/sdkmanager tools
> echo y | ./tools/bin/sdkmanager platform-tools
> echo y | ./tools/bin/sdkmanager ndk-bundle
> echo y | ./tools/bin/sdkmanager "cmake;3.6.4111459"
> echo y | ./tools/bin/sdkmanager "lldb;3.1"
6. Setting environment variables
> export ANDROID_HOME=`YOUE_ANDROID_DEV_HOME`
> export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
> export HIN2N_KSTOREPWD=`YOUR_APP_KEYSTORE_PASSWORD`
> export HIN2N_KEYPWD=`YOUR_APP_KEY_PASSWORD`
7. Comple the app.
> cd `android/Hin2n`
> ./gradlew assemble
8. You will get the app in `android/Hin2n/app/build/outputs/apk/` directory.

Of course, you can also install android studio IDE to compile this app. That's may be easier.

**Comment by lucaderi** [comment]
See https://github.com/ntop/n2n/commit/35815e5357f03637664a11571f458ba4f7908619

Thank you
