### ISSUE TITLE
Why additional "n2n.dll" in the source code?

### ISSUE THREAD

**Issue by fengdaolong** [ntop/n2n#130]
Why additional "n2n.dll" in the source code，what is it used for?
Why not try to modify the build script "CMakeLists.txt" to generate it?

**Comment by emanuele-f** [comment]
It is a request from this user: #121 . It is easy to generate the DLL via cmake

**Comment by fengdaolong** [comment]
The dll target should be built by cmake instead of putting the dll file in the source code. I hope the source code should be kept clean.

**Comment by emanuele-f** [comment]
I agree, the DLL and exe could be part of a github "release", so the source code remains clean (see also #79)

**Comment by emanuele-f** [comment]
Removed

**Comment by fengdaolong** [comment]
Thank you for your patience and answer to everyone.
