### ISSUE TITLE
Camo Style for Privacy

### ISSUE THREAD

**Issue by Logan007** [ntop/n2n#131]
- Startled by [current](https://gizmodo.com/russia-plans-to-block-major-vpns-as-next-step-in-closin-1835326332) news of which similar ones seem to lately pop up more and more often,
- valuing privacy,
- being somewhat impressed by [professional](https://wikileaks.org/vault8/#Hive) ideas of effective cover, and
- remembering the former `-t` option of n2n v1, ...

...I was wondering if there is need for (optionally) putting some camouflage on n2n's traffic between edges but also _between edges and supernode(s)_; of which the latter does not seem to be encrypted at all. Also, I was thinking about how to provide supernode functionality only to authorized edges while offering a different service to non-authorized users.

Is there any need for such a feature set? Would https-tunneling be a useful option to consider?

#30 might be related.

**Comment by emanuele-f** [comment]
I think HTTPS tunneling would add complexity and dependencies, maybe a full packet encryption is more appropriate. We can see what similar project do, but we should not sacrifice n2n portability and ease of use.

**Comment by Logan007** [comment]
I fully agree. This is more a long term idea which should evolve by further discussion.

Also, I support the mentioned thought about portability as well as the ease-of-use philosophy. These features could only be integrated if they were implemented in a seamless way.

**Comment by Logan007** [comment]
Just want to share the following experience: I was on a trip that other weekend and the hotel's wifi router did not pass anything else than http(s) and eMail and ping and dns - I did not check qotd, though. Thus, no connection to n2n network which uses some other port on the supernode side in my case.

Camo or not...  some kind of tunneling option seems to be necessary if wanting to stay connected in certain places.
