### ISSUE TITLE
Examples: Expose n2n_edge_conf_t in quick_edge_init

### ISSUE THREAD

**Issue by Teteros** [ntop/n2n#132]
> Maybe add the standard options
> 
>     * `allow_routing` (-r on command-line)
> 
>     * `drop_multicast` (-E)
>       to `quick_edge_init` in the embed example?
> 
> 
> I think that's the only ones missing from a basic edge set up there.

We should expose the n2n_edge_conf_t as a parameter of quick_edge_init https://github.com/ntop/n2n/blob/365dd29b1296ccb5d8453c84a88bf38f9fefa772/n2n.h#L196
_Originally posted by @emanuele-f in https://github.com/ntop/n2n/issues/121#issuecomment-500429985_

**Comment by Teteros** [comment]
I could be wrong (sorry, C newbie) but it also looks like subnet mask is currently hardcoded to a /24? (`255.255.255.0`) https://github.com/ntop/n2n/blob/dev/edge_utils.c#L1827
and there is no MTU setting in the `n2n_edge_conf` struct?

How could I edit `quick_edge_init` or use `edge_init` in the example to replicate the following command-line parameters?

`edge -d tap0 -a dhcp:0.0.0.0 -c community -l supernode.example.com:7654 -p 1970 -M 1300 -s 255.255.0.0 -r`

The first four parameters are already exposed and are configurable.

**Comment by emanuele-f** [comment]
For full configurability please call `edge_init` directly. Let's keep quick_edge_init like it is for now
