### ISSUE TITLE
P2P can not be formed in the LAN

### ISSUE THREAD

**Issue by lucktu** [ntop/n2n#133]
Some people say there is no need to waste too much time building P2P in the LAN (It's actually very complicated), I agree.

If it is convenient, you can optimize it (It is best not to use parameters to complete, for example -L, it better be automatic).

Otherwise, ignore the proposal please.

**Comment by emanuele-f** [comment]
Lan p2p already occurs by using multicast

**Comment by lucktu** [comment]
Today, other friends also said, no problem.
That's great!  
Thank you!

**Comment by lucktu** [comment]
It's not really working

**Comment by Logan007** [comment]
Note that multicast has been disabled in Windows version (#65). A fix is under [discussion](https://github.com/ntop/n2n/issues/567#issuecomment-753758330).

**Comment by Logan007** [comment]
#576 seems to solve it. If #576 does not work for you, please open a new issue.
