### ISSUE TITLE
supernode build failed in MSVC:  "uint": Undeclared identifier

### ISSUE THREAD

**Issue by HorseLuke** [ntop/n2n#134]
Description:

When build supernode in MSVC, it failed and said:

> 6>r:\n2n\sn.c(333): error C2065: "uint": Undeclared identifier.

Change to u_int fix the problem.

Is this typo?

**Comment by emanuele-f** [comment]
can you provide a pull request? They are usually aliases

**Comment by emanuele-f** [comment]
Fixed in #136
