### ISSUE TITLE
Why ping is normal, but N2N is not properly connected to it.

### ISSUE THREAD

**Issue by lucktu** [ntop/n2n#138]
Router A (edge A runs inside ) ping supernode is normal, continuous,
Router B (edge B runs inside ) ping supernode is normal, continuous too,
but PC (under router B) ping Edge A's IP is intermittent, even disconnected.

Router A's network environment is very poor. Others can‘t P2P with it. Why ping is normal, but N2N is not properly connected to it. I found that the same was true of meyerd's edge.

![image](https://github.com/lucktu/other/raw/master/image/speed/19061401.png)

**Comment by emanuele-f** [comment]
Can you provide pcap captures of the traffic while this occurs?

1. pcap on the n2n interface on edge A
2. pcap on the n2n interface on edge B
3. pcap on the internet interface of PC under router B

You can create a pcap of icmp traffic like this: `sudo tcpdump -i n2n0 -s0 -w a.pcap icmp`. You can send me the pcaps via email if you prefer.

**Comment by lucktu** [comment]
I have sent email, please pay attention to the receipt, thank you!

I have captured the following two records now. Please download them at the location indicated by the mailbox.

1. From break to normal
2. From normal to break to normal

Thank you again!

**Comment by lucktu** [comment]
Proposal: Let this question go for a while. 

because this problem may be difficult to locate, in the context of Router A, the port connected to it may change every second, and N2N has not yet had time to shake hands.

The latest test. For reference only.
![image](https://github.com/lucktu/other/raw/master/image/speed/19061701.png)

For ease of reading, I added an X to the following two image names so that he would not show them
![image](https://github.com/lucktu/other/raw/master/image/speed/19061801X.png)

![image](https://github.com/lucktu/other/raw/master/image/speed/19061802X.png)

**Comment by emanuele-f** [comment]
Inspecting the pcap files in the directory 19061503, both edge A and edge B can see the ICMP requests (e.g. look at the icmp req with sequence number 1603/17158) so this means that such ICMP request is not lost in the network path between A and B. Moreover, no ICMP response for such request is seen in any of the two pcap, so it seems like host 10.3.1.2 does not get the request or its response is lost, so the problem seems to be on the path between 10.3.1.2 and its router.

**Comment by lucktu** [comment]
In the same environment, I did a new test and found that v1 works very well, and v2 / v2s(meyerd's n2n) / tinc is not normal. Will it be related to their pure UDP communication?

I 've create a pcap of icmp traffic (v1/v2). Please check it from here:
https://github.com/lucktu/other/tree/master/Temp

**Comment by lucktu** [comment]
In the same environment, I did a new test and found that v1 works well, and v2 / v2s(meyerd's n2N) / tinc(1.1pre17) are not normal. 

When v1 is connectable and v2 is not connectable, I 've create same pcapes of icmp traffic (v1/v2). Please check it from here:
https://github.com/lucktu/other/tree/master/Temp

In the process, both edges ping supernode are smooth.

The chart below shows the changes I 've recorded (edge B ping edge A, 1 means that it can reach each other by ping, and 0 means no).
![image](https://github.com/lucktu/other/raw/master/image/speed/19062701.png)

Using distant supernode(above)  will not be smooth, but using another closer supernode does not have this problem, it's smooth.

**Comment by emanuele-f** [comment]
Can you recheck this by running the ping directly from A to B without the PC? I've done a quick test adding artificial packet drops with the command below but the ping loss percentage is about the same as the simulated drop (33%) and ping continues to run.

`tc qdisc add dev wlan0 root netem delay 200ms 40ms 25% loss 35.3% 25% duplicate 1% corrupt 0.1% reorder 5% 50`

**Comment by lucktu** [comment]
OK! 
Remind me, A has a poor network.   v2s -- meyerd's edgev2

edge B ping edge A (Continuous, without interruption)
![image](https://github.com/lucktu/other/raw/master/image/speed/19070101.PNG)

edge A ping edge B (Continuous, without interruption)
![image](https://github.com/lucktu/other/raw/master/image/speed/19070102.PNG)

edge A ping edge B & edge B ping edge A (Continuous, without interruption)
![image](https://github.com/lucktu/other/raw/master/image/speed/19070103.PNG)

V2 and V2s respond faster.
B ping A, V1 is doing better. The rest doesn't seem to make any difference.

**Comment by emanuele-f** [comment]
Can you verify with the `arp` command if the non-responding peer is missing an ARP table entry for the n2n peer while this occurs? If you manually set a static MAC address on both the peers with the `-m` option of n2n, does this still occur?

**Comment by lucktu** [comment]
The -m parameter seems to be invalid.

When ping fails, there is no opponent on router B (using arp), or there is a hint with incomplete (no MAC number, display incomplete ), but there is opponent on router A (Router A's network environment is poor). but sometimes it's the other way around (less often).

**Remind**: 
1, Router A and B are not together, and A is in another city. Between A and B, two Supernodes are used, there are two sets of lines. one supernode(C) is closer, and the other(D) is farther away, supernode D is abroad and is not smooth enough. My tests above are based on supercode D (including tinc).  

2, Under supercode C, everything is normal and continuous (including edge_v1,v2,v2s,tinc), and I am now checking router A via TINC(supercode C's router is server).

**Comment by emanuele-f** [comment]
That's strange, here is the -m option from the edge --help:

`-m <MAC address>         | Fix MAC address for the TAP interface (otherwise it may be random)`

Please ensure that the MAC address of the edges does not change during the tests, I suspect this is the problem.

**Comment by lucktu** [comment]
The same test, all forwards.
I 'll verify it again (with -m).
![image](https://github.com/lucktu/other/raw/master/image/speed/19070801.png)

**Comment by lucktu** [comment]
Even if a fixed MAC address is added, it is the same. (I'm sure)

edge2 -d N7 -a 10.7.0.100 -c ntop -k test3 -l c1.smsq.ml:10086 -p 37587 -brEf -t 37500 -m 3A:91:C6:41:F0:29 &

? (10.7.0.100) at b2:bc:e7:f6:2a:ec [ether]  on N7
or
10.7.0.10  0x1  0x0  3a:91:c6:41:f0:29  *  N7

 In the figure below, The same test, all forwards. The arp command can be used to see the other party's information. Routers A and B can see each other's information. 
![image](https://github.com/lucktu/other/raw/master/image/speed/19070802.png)

After a complete break, you may not be able to see each other with arp (one or both), or display "incomplete". router A has a better chance of seeing B (Router A's network environment is poor).
   10.7.0.10  0x1  0x0  3a:91:c6:41:f0:29  *  N7  # in router A
? (10.7.0.100) at incomplete on N7                     # in router B

**Comment by lucktu** [comment]
Again, the results were the same as before :
This time I changed the system (routerA + B). Before, it was "padavan<-->openwrt". this time, it was "openwrt<-->openwrt"

1. There is no change in the use of -m;
2. v1 performs better than v2 (v2dev & v2s)
3. Tinc does better.
4. The MAC address of the edges does not change during the tests. (Never noticed before)

**Comment by lucktu** [comment]
The new discovery: 

If padavan routers A and B are up and down, they are connected by DHCP-IP, and they run 2 edge_v1, 5 v2_dev and 3 v2_meyerd internally (See #93), both v1 can be ping, one v2_dev can be ping. all the edge's connections are forwards. It's like #133

I think that this is also relevant to this post. Router A and B have a good network environment. Maybe their problems are solved and the issues is solved. It's easy to test like this (using padavan or openwrt router).

---------------------
After several tests, 
1. It was found that v2s was directly connected (p2p), v1 and v2_dev are always forwards.
2. With -E gone, the connectivity is much better.

Maybe it's quite a complicated question. I 'd like to let it go for a while.

**Comment by lucktu** [comment]
This is what happens when I remove the "-E", Now it seems that v1, v2_dev, tinc is about the same, all forwards.
Keep watching, ... ...
![image](https://github.com/lucktu/other/raw/master/image/speed/19071001.PNG)

**Comment by emanuele-f** [comment]
Removing the -E option should only reduce the amount of traffic sent through n2n (all the generated multicast traffic is not forwarded). I think this issue is linked with the characteristic of your network and it's a good opportunity to make n2n more robust. I need a good idea to spot the problem and/or collect some useful log in your environment (the current log with `-v` is too much verbose)

**Comment by lucktu** [comment]
From the result of Ping alone, the network is good, but why does it always show "WARNING: Supernode not responding - moving to 0 of 1"?

#### Is it for ICMP/TCP/UDP?
![image](https://github.com/lucktu/other/raw/master/image/speed/19071101.PNG)

**Comment by lucktu** [comment]
I suggest we let the issue go from v2.6.0 (We 'll study it later), because I think it's a complicated problem and it's not easy to solve. If we keep our eye on it, we might not be able to do anything else. 

for
1. Tinc has a similar problem.
2. The network is too complicated, perhaps related to icmp/tcp/udp. ping uses icmp, n2n only uses udp.
3. First, solve the problem of Mac's easy to change in communication. Here's the message I saw from supercode. It's hard to p2p.
<pre>
30/Jul/2019 04:20:08 [sn.c:155] update_edge created 9E:13:7A:3B:FB:D4 ==> 182.136.20.18:48923
30/Jul/2019 04:22:11 [sn.c:155] update_edge created 6A:0D:D5:D3:05:30 ==> 182.136.20.18:48072
30/Jul/2019 04:25:05 [sn.c:155] update_edge created 12:36:EC:23:4C:CD ==> 182.136.20.18:51055
30/Jul/2019 04:26:02 [sn.c:155] update_edge created 26:E3:75:08:8B:B0 ==> 182.136.20.18:51398
30/Jul/2019 04:30:01 [sn.c:155] update_edge created 82:EA:FA:08:15:AF ==> 182.136.20.18:42276
30/Jul/2019 04:32:01 [sn.c:155] update_edge created BA:C8:60:29:4A:54 ==> 182.136.20.18:51398
30/Jul/2019 04:34:02 [sn.c:155] update_edge created 56:F3:D5:C3:4A:93 ==> 182.136.20.18:59747
30/Jul/2019 04:36:01 [sn.c:155] update_edge created 1E:F1:8E:31:10:D5 ==> 182.136.20.18:34461
30/Jul/2019 04:38:02 [sn.c:155] update_edge created 4E:2C:3F:41:62:67 ==> 182.136.20.18:50045
30/Jul/2019 04:40:12 [sn.c:155] update_edge created FA:A3:06:66:AF:9C ==> 182.136.20.18:35660
30/Jul/2019 04:42:01 [sn.c:155] update_edge created B6:CF:25:3E:4C:02 ==> 182.136.20.18:41565
30/Jul/2019 04:46:03 [sn.c:155] update_edge created 86:69:CB:89:1F:DC ==> 182.136.20.18:59785
30/Jul/2019 04:48:03 [sn.c:155] update_edge created 22:8D:37:C9:55:6F ==> 182.136.20.18:44068
30/Jul/2019 04:50:04 [sn.c:155] update_edge created 4E:99:ED:2C:16:76 ==> 182.136.20.18:48007
30/Jul/2019 04:52:02 [sn.c:155] update_edge created 8A:3B:A5:E7:61:CF ==> 182.136.20.18:53398
30/Jul/2019 04:56:02 [sn.c:155] update_edge created EE:08:A2:EA:40:6B ==> 182.136.20.18:35274
30/Jul/2019 05:00:08 [sn.c:155] update_edge created 5E:2C:DE:71:33:9D ==> 182.136.20.18:35770
30/Jul/2019 05:02:01 [sn.c:155] update_edge created 3E:81:57:52:57:BE ==> 182.136.20.18:50001
30/Jul/2019 05:06:04 [sn.c:155] update_edge created 72:10:98:AE:18:6C ==> 182.136.20.18:44374
30/Jul/2019 05:09:01 [sn.c:155] update_edge created 2E:FB:F0:9B:93:7A ==> 182.136.20.18:45421
30/Jul/2019 05:11:00 [sn.c:155] update_edge created AE:8C:81:A6:7B:91 ==> 182.136.20.18:59141
30/Jul/2019 05:12:05 [sn.c:155] update_edge created FA:01:DF:90:1E:3B ==> 182.136.20.18:40088
30/Jul/2019 05:14:02 [sn.c:155] update_edge created 7E:8D:5E:2D:20:94 ==> 182.136.20.18:43709
30/Jul/2019 05:16:04 [sn.c:155] update_edge created 82:86:BA:95:36:47 ==> 182.136.20.18:42507
30/Jul/2019 05:19:01 [sn.c:155] update_edge created C6:D5:16:B5:BD:9E ==> 182.136.20.18:57684
30/Jul/2019 05:20:10 [sn.c:155] update_edge created 0E:BD:6A:CC:17:E2 ==> 182.136.20.18:52190
30/Jul/2019 05:24:02 [sn.c:155] update_edge created 76:99:01:0B:2D:E2 ==> 182.136.20.18:35490
30/Jul/2019 05:27:01 [sn.c:155] update_edge created EA:61:FB:AC:88:2E ==> 182.136.20.18:33996
30/Jul/2019 05:28:04 [sn.c:155] update_edge created 12:A2:49:34:14:22 ==> 182.136.20.18:34960
30/Jul/2019 05:32:01 [sn.c:155] update_edge created 72:DC:53:4F:57:15 ==> 182.136.20.18:53573
30/Jul/2019 05:38:01 [sn.c:155] update_edge created 3A:82:00:DB:9C:E5 ==> 182.136.20.18:45403
30/Jul/2019 05:40:07 [sn.c:155] update_edge created 1A:E0:35:F1:A1:F2 ==> 182.136.20.18:56567
30/Jul/2019 05:46:01 [sn.c:155] update_edge created 6A:4C:03:79:D0:6A ==> 182.136.20.18:36396
30/Jul/2019 05:48:01 [sn.c:155] update_edge created 42:A3:D9:51:13:A9 ==> 182.136.20.18:36034
30/Jul/2019 05:52:01 [sn.c:155] update_edge created 6E:9C:B8:39:45:46 ==> 182.136.20.18:59687
30/Jul/2019 05:54:01 [sn.c:155] update_edge created 56:77:AF:29:E1:FE ==> 182.136.20.18:55152
30/Jul/2019 05:58:01 [sn.c:155] update_edge created 7A:98:B7:7F:23:85 ==> 182.136.20.18:34420
</pre>

Besides, it has nothing to do without -E, what I said before was wrong.

Thank you!

**Comment by lucktu** [comment]
I suggest we let the issue go from v2.6 (We'll study it later), because I think it's a complicated problem and it's not easy to solve. If we keep our eyes on it, we might not be able to do anything else. 

for
1. Tinc has a similar problem.
2. The network is too complicated, perhaps related to icmp/tcp/udp. ping uses icmp, n2n only uses udp.
3. Optimize the following problem: mac and port are easy to change, so it is difficult to p2p (It's not my network, it's a guest's).
<pre>
30/Jul/2019 04:20:08 [sn.c:155] update_edge created 9E:13:7A:3B:FB:D4 ==> 182.136.20.18:48923
30/Jul/2019 04:22:11 [sn.c:155] update_edge created 6A:0D:D5:D3:05:30 ==> 182.136.20.18:48072
30/Jul/2019 04:25:05 [sn.c:155] update_edge created 12:36:EC:23:4C:CD ==> 182.136.20.18:51055
30/Jul/2019 04:26:02 [sn.c:155] update_edge created 26:E3:75:08:8B:B0 ==> 182.136.20.18:51398
30/Jul/2019 04:30:01 [sn.c:155] update_edge created 82:EA:FA:08:15:AF ==> 182.136.20.18:42276
30/Jul/2019 04:32:01 [sn.c:155] update_edge created BA:C8:60:29:4A:54 ==> 182.136.20.18:51398
30/Jul/2019 04:34:02 [sn.c:155] update_edge created 56:F3:D5:C3:4A:93 ==> 182.136.20.18:59747
30/Jul/2019 04:36:01 [sn.c:155] update_edge created 1E:F1:8E:31:10:D5 ==> 182.136.20.18:34461
30/Jul/2019 04:38:02 [sn.c:155] update_edge created 4E:2C:3F:41:62:67 ==> 182.136.20.18:50045
30/Jul/2019 04:40:12 [sn.c:155] update_edge created FA:A3:06:66:AF:9C ==> 182.136.20.18:35660
30/Jul/2019 04:42:01 [sn.c:155] update_edge created B6:CF:25:3E:4C:02 ==> 182.136.20.18:41565
30/Jul/2019 04:46:03 [sn.c:155] update_edge created 86:69:CB:89:1F:DC ==> 182.136.20.18:59785
30/Jul/2019 04:48:03 [sn.c:155] update_edge created 22:8D:37:C9:55:6F ==> 182.136.20.18:44068
30/Jul/2019 04:50:04 [sn.c:155] update_edge created 4E:99:ED:2C:16:76 ==> 182.136.20.18:48007
30/Jul/2019 04:52:02 [sn.c:155] update_edge created 8A:3B:A5:E7:61:CF ==> 182.136.20.18:53398
30/Jul/2019 04:56:02 [sn.c:155] update_edge created EE:08:A2:EA:40:6B ==> 182.136.20.18:35274
30/Jul/2019 05:00:08 [sn.c:155] update_edge created 5E:2C:DE:71:33:9D ==> 182.136.20.18:35770
30/Jul/2019 05:02:01 [sn.c:155] update_edge created 3E:81:57:52:57:BE ==> 182.136.20.18:50001
30/Jul/2019 05:06:04 [sn.c:155] update_edge created 72:10:98:AE:18:6C ==> 182.136.20.18:44374
30/Jul/2019 05:09:01 [sn.c:155] update_edge created 2E:FB:F0:9B:93:7A ==> 182.136.20.18:45421
30/Jul/2019 05:11:00 [sn.c:155] update_edge created AE:8C:81:A6:7B:91 ==> 182.136.20.18:59141
30/Jul/2019 05:12:05 [sn.c:155] update_edge created FA:01:DF:90:1E:3B ==> 182.136.20.18:40088
30/Jul/2019 05:14:02 [sn.c:155] update_edge created 7E:8D:5E:2D:20:94 ==> 182.136.20.18:43709
30/Jul/2019 05:16:04 [sn.c:155] update_edge created 82:86:BA:95:36:47 ==> 182.136.20.18:42507
30/Jul/2019 05:19:01 [sn.c:155] update_edge created C6:D5:16:B5:BD:9E ==> 182.136.20.18:57684
30/Jul/2019 05:20:10 [sn.c:155] update_edge created 0E:BD:6A:CC:17:E2 ==> 182.136.20.18:52190
30/Jul/2019 05:24:02 [sn.c:155] update_edge created 76:99:01:0B:2D:E2 ==> 182.136.20.18:35490
30/Jul/2019 05:27:01 [sn.c:155] update_edge created EA:61:FB:AC:88:2E ==> 182.136.20.18:33996
30/Jul/2019 05:28:04 [sn.c:155] update_edge created 12:A2:49:34:14:22 ==> 182.136.20.18:34960
30/Jul/2019 05:32:01 [sn.c:155] update_edge created 72:DC:53:4F:57:15 ==> 182.136.20.18:53573
30/Jul/2019 05:38:01 [sn.c:155] update_edge created 3A:82:00:DB:9C:E5 ==> 182.136.20.18:45403
30/Jul/2019 05:40:07 [sn.c:155] update_edge created 1A:E0:35:F1:A1:F2 ==> 182.136.20.18:56567
30/Jul/2019 05:46:01 [sn.c:155] update_edge created 6A:4C:03:79:D0:6A ==> 182.136.20.18:36396
30/Jul/2019 05:48:01 [sn.c:155] update_edge created 42:A3:D9:51:13:A9 ==> 182.136.20.18:36034
30/Jul/2019 05:52:01 [sn.c:155] update_edge created 6E:9C:B8:39:45:46 ==> 182.136.20.18:59687
30/Jul/2019 05:54:01 [sn.c:155] update_edge created 56:77:AF:29:E1:FE ==> 182.136.20.18:55152
30/Jul/2019 05:58:01 [sn.c:155] update_edge created 7A:98:B7:7F:23:85 ==> 182.136.20.18:34420
</pre>

Besides, it has nothing to do without -E, what I said before was wrong.

Thank you!

**Comment by Logan007** [comment]
Does this issue still persist with current dev?

**Comment by Logan007** [comment]
Considered solved as no news. Please re-open if required.
