### ISSUE TITLE
Fails to compile: error: "n2n_keyfile.h": No such file or directory

### ISSUE THREAD

**Issue by VergLsm** [ntop/n2n#140]
### log:
```
[ 72%] Building C object CMakeFiles/test.dir/test.c.obj
test.c
F:\Users\***\Desktop\n2n\test.c(20): fatal error C1083: 无法打开包括文件: “n2n_keyfile.h”: No such file or directory
```

I saw that this file was moved to the legacy directory and have been dropped. 
Should test.c also be removed from cMakeList.txt?

**Comment by emanuele-f** [comment]
Removed in 4ca0ae34a4fafd9f3649dd25a610287f638db6da, thank you
