### ISSUE TITLE
Problem with multiple supernode

### ISSUE THREAD

**Issue by baptisteMD** [ntop/n2n#141]
Hello,
In order to improve the redundancy of the system based on n2n, I'm trying to use multiple supernodes.
I have 2 supernodes and 2 edge nodes (each on a different hosts).
All my edge nodes register to both supernodes.

The problem I'm facing is that it's the second supernode I declare which etablish links between edge nodes and not the first one.
It will be OK if when the supernode (which etablish links between edge nodes) stop working the other take his place, but it's not the case.

That's why I would like to know if there are some others parameters to put or not.

(I have try with the master branch and the dev branch and I have the same result with both branches)

**Comment by emanuele-f** [comment]
This is a known issue that must be fixed, see https://github.com/ntop/n2n/issues/45

**Comment by emanuele-f** [comment]
Please refer to the issue above for discussion or updates
