### ISSUE TITLE
Is there an option for less message of "Rx REGISTER_SUPER_ACK myMAC=xxx"

### ISSUE THREAD

**Issue by billypon** [ntop/n2n#145]
I started edge as service in OpenWRT, but I found edge output many many many "Rx REGISTER_SUPER_ACK myMAC=xxx" log, my system log is almost full of it.

**Comment by lucktu** [comment]
Please try adding -f parameter

**Comment by billypon** [comment]
Still have this log with/without -f parameter. OpenWRT service will capture all application's output message, then write  it to system log.

**Comment by lucktu** [comment]
On my router, it is true that there is no such problem. My router has padavan and OpenWRT. It is normal.

Do not use the -f parameter on v1, but need it on v2. After processing, the background is clean and there is no one. Otherwise, maybe one per minute is really ugly.

**Comment by emanuele-f** [comment]
@billypon I think you are using an old n2n version, the new one does not have so many logs. Are you installing it from a package feed or what else?

**Comment by billypon** [comment]
@emanuele-f I use this version: https://github.com/ntop/n2n/releases/tag/2.4

**Comment by emanuele-f** [comment]
Please download the latest code from git. If you want to contribute and update the openwrt build script you are welcome, please see https://github.com/ntop/n2n/issues/113

**Comment by billypon** [comment]
My idea is add a log level parameter, use this parameter to hide this log

**Comment by emanuele-f** [comment]
All the log in the latest dev is very minimal (unless `-v` is specified). You are not using the dev version but the stable one (2.4), so I suggest you to switch to the dev version.

**Comment by billypon** [comment]
OK, thanks, I will try the lastest dev version

**Comment by billypon** [comment]
Is there a plan for new stable version? I prefer to wait for the new version, if it's soon.

**Comment by emanuele-f** [comment]
This is the milestone for the new stable https://github.com/ntop/n2n/milestone/1
