### ISSUE TITLE
>>>>>>>>>> Speed comparison <<<<<<<<<<

### ISSUE THREAD

**Issue by lucktu** [ntop/n2n#146]
Test environment
![image](https://github.com/lucktu/other/raw/master/image/speed/19092001.PNG)

In the same environment, the speed of several connections in P2P mode shows that the progress of n2n_v2_dev is great. The reason for this small speed is because the CPU's computing power is limited (MTK 7620/7621, padavan router).

When it is convenient, I will continue to do such a comparative experiment and provide it on this page to witness the official progress.

![image](https://github.com/lucktu/other/raw/master/image/speed/19062501.png)

The comparison between v2_master and v2_dev is both P2P, v2_master is updated on 2018-9-29
v2_dev_no_encryption's speed is highly volatile, between 1.4 ~ 2.1 MB/s, this test is 1.4 MB/s.
![image](https://github.com/lucktu/other/raw/master/image/speed/19070701.png)

Other test
![image](https://github.com/lucktu/other/raw/master/image/speed/19062601.png)
<pre>
edge_v1_______: edge1  -d M1 -a 10.10.10.100 -c ntop1 -k n2n -l n2n.lucktu.com:10082 -p 30000 -br
edge_v2_master: edge2  -d M2 -a 10.10.20.100 -c ntop2 -k n2n -l n2n.lucktu.com:10086 -p 30001 -brf
edge_v2_meyerd: edge2s -d M3 -a 10.10.30.100 -c ntop3 -k n2n -l n2n.lucktu.com:10088 -p 30002 -brEf
edge_v2_dev_T_: edge2d -d M4 -a 10.10.40.100 -c ntop4 -k n2n -l n2n.lucktu.com:10086 -p 30003 -brEf
edge_v2_dev_A_: edge2d -d M5 -a 10.10.50.100 -c ntop5 -k n2n -l n2n.lucktu.com:10086 -p 30004 -brEfA
edge_v2_dev_0_: edge2d -d M6 -a 10.10.60.100 -c ntop6        -l n2n.lucktu.com:10086 -p 30005 -brEf
</pre>
Tinc(v1.1pre17) uses the default encryption method: blowfish

The average speed (such as 1.9MB/s) was measured using the 8uftp (from 8uftp).

**Comment by emanuele-f** [comment]
Thank you! You are using n2n with encryption, right?

**Comment by lucktu** [comment]
Yeah, it's -A, Let me add something on top.

**Comment by lucktu** [comment]
The speed of p2p in Lan is all restricted by the CPU of synology, the router is Padavan (7621 CPU) , the equipment is HP tpn-q171 ( i5 + windows10x64 ) and synology DS-213J (armada370 + dsm6.1.7, is equal to intel N270 ) respectively. 

Software version:  edge_v2_r243  /   edge_v2s_r124

<strong>0.71：1.41 MB/s</strong>:  edge2 -a 172.0.0.X -c n2n -k test -l xxx.xxx.xxx:10086
![image](https://github.com/lucktu/other/raw/master/image/speed/1912047.png)

<strong>3.36：6.06 MB/s</strong>:  edge2 -a 172.0.0.X -c n2n -k test -l xxx.xxx.xxx:10086 -A
![image](https://github.com/lucktu/other/raw/master/image/speed/1912043.png)

<strong>3.62：6.52 MB/s</strong>:  edge2 -a 172.0.0.X -c n2n            -l xxx.xxx.xxx:10086
![image](https://github.com/lucktu/other/raw/master/image/speed/1912044.png)

<strong>0.71：1.39 MB/s</strong>:  edge2s -a 172.0.0.X -c n2n -k test -l xxx.xxx.xxx:10088
![image](https://github.com/lucktu/other/raw/master/image/speed/1912049.png)

<strong>3.12：2.40 MB/s</strong>:  Tinc (special: one is on router, the other is on synology)(v1.1pre14 / v1.0.24 )
![image](https://github.com/lucktu/other/raw/master/image/speed/1912042.png)

<strong>0.92：2.38 MB/s</strong>:  zerotier ( windows10: 1.2.8 / synology: v1.2.12 )
![image](https://github.com/lucktu/other/raw/master/image/speed/1912041.png)

Overall, the tinc and n2n's speeds are stable (the display is unstable, that's because I do other operations) , and the zerotier is unstable.
