### ISSUE TITLE
UPnP / NAT-PMP support

### ISSUE THREAD

**Issue by Teteros** [ntop/n2n#147]
The [repository](https://github.com/ntop/n2n/search?q=upnp%7Cpmp%7Cpcp) or the [white paper](http://luca.ntop.org/n2n.pdf) do not mention UPnP / NAT-PMP / PCP at all.

Was wondering if these supporting techniques of NAT traversal are on the todo list or were scrapped to keep the edge codebase slim and portable?

Comparable P2P/Mesh VPNs such as Tinc, Zerotier and FreeLAN all support at least UPnP which makes the VPN much more likely to work out of the box as most consumer routers I've come across have it enabled by default.

I think these projects make use of the cross-platform [MiniUPnPc](http://miniupnp.free.fr) library.

As is, edges rely on the user manually port forwarding and will most likely fail on symmetric NAT (or will rely on supernode relaying.)

**Comment by emanuele-f** [comment]
Currently not implemented but it would be quite easy to do via a UPnP library.

**Comment by emanuele-f** [comment]
@Teteros would you like to implement support for UPnP?

**Comment by Teteros** [comment]
I don't have much C programming experience, sorry.

**Comment by lucktu** [comment]
We all feel the need to do this, so let’s do it.
It’s been too long.

**Comment by lucktu** [comment]
![image](https://github.com/lucktu/other/raw/master/image/2021/21100201.png)
Note:  **R1/R2/R21, Router(openwrt);    c92, PC(ubuntu18);    A82, PC(windows);**

![image](https://github.com/lucktu/other/raw/master/image/2021/21100202.png)

**Test time: 2021-10-02**. the current version of n2n is **v2.9.0_r1001**

My test network conditions are relatively good, the results are still very low success rate of p2p. no upnp, **only 7%--11%**, I am very sorry. however, by adding upnp (manually add port to router by ./upnpc-static ...), the success rate changes **from 7% to 89%.** 

Note:
1. Italics, which means start testing from there;
2. C92 with upnp, c920 without upnp;
3. Suddenly, its p2p, give 1, many times before it became p2p, give 0.5, or give 0.
4. There is no edge in R3 & A82.
