### ISSUE TITLE
AES packet version

### ISSUE THREAD

**Issue by Logan007** [ntop/n2n#150]
AES packet version starts counting from 1. Why not starting from 0 - not wasting one of the precious available 8-bit version numbers? 

The only danger I can see is that an uninitialized value might not be detected... which has not been checked for anyway so far.

**Comment by emanuele-f** [comment]
Going back in numbering is usually a bad idea, losing 1 value is not a problem

**Comment by Logan007** [comment]
I basically agree. But so far aes has been a dev only feature, that's why it's now or never.
