### ISSUE TITLE
Support setting MTU on Windows

### ISSUE THREAD

**Issue by Teteros** [ntop/n2n#153]
`-M` switch does not currently do anything on Windows.
https://github.com/ntop/n2n/blob/dev/win32/wintap.c#L181-L182

So you need to run something like:
`netsh interface ipv4 set subinterface n2n mtu=1300 store=persistent`

to workaround issue #123

As an aside note, MTU is behaviour is pretty strange on Windows, these two commands can return two different values:

In powershell:
`Get-NetAdapterAdvancedProperty -DisplayName MTU`

Or from cmd:
`netsh interface ipv4 show subinterface`

I'm guessing they're two different APIs.

**Comment by emanuele-f** [comment]
Now implemented, yhank you for the hints.
