### ISSUE TITLE
API to deploy app on the network

### ISSUE THREAD

**Issue by omkarjc27** [ntop/n2n#156]
Is there a way to do all p2p backend stuff (like nat traversal etc) of a p2p app using n2n. If there is pls inform and if not, can it be done by doing something else on this network

**Comment by emanuele-f** [comment]
Please check out https://github.com/ntop/n2n/blob/dev/example_edge_embed.c . If you need a more fined tuning you can call `run_edge_loop` instead https://github.com/ntop/n2n/blob/1512f20eaa1d02a673c08a5ad07fd7e5dc7af9ef/edge_utils.c#L1835

**Comment by omkarjc27** [comment]
> Please check out https://github.com/ntop/n2n/blob/dev/example_edge_embed.c . If you need a more fined tuning you can call `run_edge_loop` instead
> 
> https://github.com/ntop/n2n/blob/1512f20eaa1d02a673c08a5ad07fd7e5dc7af9ef/edge_utils.c#L1835

Thanks,
Also is there any function to transfer packets rather than just using ping. And if there are more functions that I can use is there any documentation that I can refer to..(Sorry If this sounds dumb I just came accross this project and I find it really useful)

**Comment by emanuele-f** [comment]
There is no official documentation but the quick_edge_init implementation linked above is a good starting point. You can find the public functions in n2n.h https://github.com/ntop/n2n/blob/1512f20eaa1d02a673c08a5ad07fd7e5dc7af9ef/n2n.h . Currently packets are read from the linux stack in readFromTAPSocket (via the TAP interface) and sent out with send_packet2net . If you want to inject a custom packet you should call send_packet2net .

**Comment by omkarjc27** [comment]
Can't I just pass messages using TCP or UDP like one would do on a LAN would that be supported and if yes what port should I send the messages to.

**Comment by emanuele-f** [comment]
When n2n is activated, a TAP interface is created (e.g. edge0) with an IP address, say 192.168.10.5 . Your custom program can generate packets with a destination inside the 192.168.10.0/24 network and send them out, the linux routing will then take care of everything and the packet will go into n2n.

**Comment by omkarjc27** [comment]
Can I please get one example of each sending and receiving message from one node to another

**Comment by emanuele-f** [comment]
This is not something specific of n2n, this is basic networking. You have an interface with an IP address and a netmask (e.g. network `192.168.10.0/24`). You just need to send a packet with a destination address in such network (for example with `ping 192.168.10.1`). You can generate artificial packets with scapy, but this is outside of the scope of n2n.

**Comment by omkarjc27** [comment]
**I am assuming here that I cannot use TCP/UDP, as that is what I got from one of your previous answers.** 

Please give me one example of how to do it  programmatically using C
Any link for a tutorial on how to do it would also be useful
Or one example of how to exchange messages between nodes using functions like send_packet2net and receiveFromTAPsocket
I just want nodes on this network initiated by my program to exchange messages

**Comment by emanuele-f** [comment]
You can use TCP/UDP. As explained earlier, the n2n interface is seen as a standard network interface by linux, so TCP/UDP/ICMP/IP will work.

**Comment by omkarjc27** [comment]
When I run
on First machine
```
sudo edge -c network -k secretpass -a 192.168.100.1 -f -l supernode.ntop.org:7777
```
and on Second machine
```
sudo edge -c network -k secretpass -a 192.168.100.2 -f -l supernode.ntop.org:7777
```
And when they ping each other I get
```
Destination Host Unreachable
```
(Also when I try UDP I can't connect both of them, Pls tell what I'm doing wrong)

**Comment by emanuele-f** [comment]
Please use a separate community and encryption key, otherwise your connection will not be secure. Please also post the output of the two edge commands. Can you post the exact ping command that you are using?

**Comment by omkarjc27** [comment]
when I'm on the first machine I ping the address of second machine
i.e.```ping 192.168.100.2```

**Comment by Logan007** [comment]
Is this still an issue with current version?

**Comment by Logan007** [comment]
Considered deprecated, please re-open if required.
