### ISSUE TITLE
If there is no network when booting, n2n's booting is easy to fail

### ISSUE THREAD

**Issue by lucktu** [ntop/n2n#159]
In my padavan router, at boot time, some N2N startup tasks were added. If the router is not connected to the network at boot time, then n2n_v2 is easy to exit, while v1 and meyerd's v2 are normal.

The following is the running log for the same time period:
n2n_v1
<pre>
04/Jul/2019 15:16:35 [     edge.c:1140] WARNING: Failed to resolve supernode host n2n.lucktu.com, assuming numeric
04/Jul/2019 15:16:35 [     edge.c:1144] Using supernode 255.255.255.255:10082
04/Jul/2019 15:16:35 [tuntap_linux.c:  38] Interface N0 has MAC 5E:34:12:A5:8F:DB
04/Jul/2019 15:16:35 [     edge.c:1351] Binding to local port 31230
04/Jul/2019 15:16:35 [     edge.c: 672] Registering with supernode
04/Jul/2019 15:16:35 [     edge.c:1140] WARNING: Failed to resolve supernode host n2n.lucktu.com, assuming numeric
04/Jul/2019 15:16:35 [     edge.c:1144] Using supernode 255.255.255.255:10082
04/Jul/2019 15:16:35 [      n2n.c: 285] WARNING: sendto() [sent=-1][attempted_to_send=84] [Network is unreachable]
04/Jul/2019 15:16:35 [     edge.c:1376] 
04/Jul/2019 15:16:35 [     edge.c:1377] Ready
04/Jul/2019 15:16:45 [     edge.c:1443] STATUS: pending=0, operational=0
</pre>

n2n_v2
<pre>
04/Jul/2019 15:16:35 [edge.c:611] Starting n2n edge 2.5.0 Jun 24 2019 11:07:32
04/Jul/2019 15:16:35 [edge_utils.c:1815] Adding supernode[0] = n2n.lucktu.com:10086
04/Jul/2019 15:16:35 [edge.c:630] ip_mode='static'
04/Jul/2019 15:16:35 [tuntap_linux.c:43] Interface N2 has MAC F6:BC:72:BB:53:EB
04/Jul/2019 15:16:35 [edge_utils.c:187] supernode 0 => n2n.lucktu.com:10086
04/Jul/2019 15:16:35 [edge_utils.c:314] WARNING: Failed to resolve supernode host n2n.lucktu.com, assuming numeric
04/Jul/2019 15:16:35 [edge_utils.c:1731] Binding to local port 31542
04/Jul/2019 15:16:35 [edge_utils.c:1771] ERROR: Failed to bind to local multicast group 224.0.0.68:1968 [errno 19]
04/Jul/2019 15:16:35 [edge_utils.c:215] ERROR: Error: socket setup failed
04/Jul/2019 15:16:35 [edge.c:656] ERROR: Failed in edge_init
</pre>

n2n_v2 (meyerd)
<pre>
04/Jul/2019 15:16:35 [     edge.c:2610] Starting n2n edge 2.1.0 Jun 24 2019 12:59:57
04/Jul/2019 15:16:35 [     edge.c:2615] supernode 0 => n2n.lucktu.com:10088
04/Jul/2019 15:16:35 [     edge.c:2615] supernode 1 => 
04/Jul/2019 15:16:35 [     edge.c:2111] WARNING: Failed to resolve supernode host n2n.lucktu.com, assuming numeric
04/Jul/2019 15:16:35 [     edge.c:2662] ip_mode='static'
04/Jul/2019 15:16:35 [tuntap_linux.c:  38] Interface N8 has MAC 86:C3:C2:30:CF:05
04/Jul/2019 15:16:35 [     edge.c:2680] Binding to local port 36572
04/Jul/2019 15:16:35 [     edge.c:2721] edge started
04/Jul/2019 15:16:35 [     edge.c:2111] WARNING: Failed to resolve supernode host n2n.lucktu.com, assuming numeric
04/Jul/2019 15:16:35 [     edge.c: 588] ERROR: sendto 255.255.255.255:10088 failed (128) Network is unreachable
04/Jul/2019 15:16:40 [     edge.c: 417] Chose new tx_transop_idx=1
04/Jul/2019 15:16:40 [     edge.c:2111] WARNING: Failed to resolve supernode host n2n.lucktu.com, assuming numeric
04/Jul/2019 15:16:40 [     edge.c: 588] ERROR: sendto 255.255.255.255:10088 failed (128) Network is unreachable
04/Jul/2019 15:16:45 [     edge.c:2111] WARNING: Failed to resolve supernode host n2n.lucktu.com, assuming numeric
04/Jul/2019 15:16:45 [     edge.c: 588] ERROR: sendto 255.255.255.255:10088 failed (128) Network is unreachable
04/Jul/2019 15:16:50 [     edge.c:1084] WARNING: Supernode not responding - moving to 0 of 1
04/Jul/2019 15:16:50 [     edge.c:2111] WARNING: Failed to resolve supernode host n2n.lucktu.com, assuming numeric
04/Jul/2019 15:16:50 [     edge.c: 588] ERROR: sendto 255.255.255.255:10088 failed (128) Network is unreachable
04/Jul/2019 15:16:55 [     edge.c:2111] WARNING: Failed to resolve supernode host n2n.lucktu.com, assuming numeric
04/Jul/2019 15:16:55 [     edge.c: 588] ERROR: sendto 255.255.255.255:10088 failed (128) Network is unreachable
04/Jul/2019 15:17:00 [     edge.c:2111] WARNING: Failed to resolve supernode host n2n.lucktu.com, assuming numeric
04/Jul/2019 15:17:00 [     edge.c: 588] ERROR: sendto 255.255.255.255:10088 failed (128) Network is unreachable
04/Jul/2019 15:17:05 [     edge.c:2111] WARNING: Failed to resolve supernode host n2n.lucktu.com, assuming numeric
04/Jul/2019 15:17:05 [     edge.c: 588] ERROR: sendto 255.255.255.255:10088 failed (128) Network is unreachable
04/Jul/2019 15:17:10 [     edge.c:1084] WARNING: Supernode not responding - moving to 0 of 1
04/Jul/2019 15:17:10 [     edge.c:2111] WARNING: Failed to resolve supernode host n2n.lucktu.com, assuming numeric
04/Jul/2019 15:17:10 [     edge.c: 588] ERROR: sendto 255.255.255.255:10088 failed (128) Network is unreachable
04/Jul/2019 15:17:16 [     edge.c:2111] WARNING: Failed to resolve supernode host n2n.lucktu.com, assuming numeric
04/Jul/2019 15:17:16 [     edge.c: 588] ERROR: sendto 255.255.255.255:10088 failed (128) Network is unreachable
04/Jul/2019 15:17:21 [     edge.c:2111] WARNING: Failed to resolve supernode host n2n.lucktu.com, assuming numeric
04/Jul/2019 15:17:21 [     edge.c: 588] ERROR: sendto 255.255.255.255:10088 failed (128) Network is unreachable
</pre>

**Comment by lucktu** [comment]
But, no problem with manual startup edge_v2 when there is no network in ssh, and it is still in memory.

**Comment by Logan007** [comment]
Same here. Even `After=network.target` in systemd unit did not help... I have not tried `network-online.target` or `Required=...` yet. For now, I have put some `sleep` in my startup script - not too long (below 90 seconds?), the unit will fail to start otherwise.

P. S. Startup script gets called by systemd unit.

**Comment by emanuele-f** [comment]
network-online.target is already used in our packages (See https://github.com/ntop/n2n/blob/dev/packages/etc/systemd/system/edge.service.in) but often this does not help in ensuring that the network is really up.

I've made this fix 1c9e029b88b7acab1552405f87de8bf93304afc5 , please confirm that it's working properly now.

**Comment by lucktu** [comment]
After testing, it's already OK.

Thank you very much!
