### ISSUE TITLE
Recommendations on version numbers

### ISSUE THREAD

**Issue by lucktu** [ntop/n2n#160]
After June 22nd, Aes(-A) was changed and incompatible with the previous version, but their version numbers are still 2.5.0, no change, is it more appropriate for 2.6.0? 

This will cause some confusion, Especially here, More obvious.
https://github.com/lucktu/n2n

For some small changes, 2.5.1, 2.5.2 is recommended, or it doesn't change.
Or add a modified log and note.

For reference only.

Thank you very much!

**Comment by emanuele-f** [comment]
Once the stable version will be released it will have a stable AES version. On the development branch we may still need to change the packet format to optimize it. Adding a note in the commit message is the easiest way to signal the users that format has changed. The ambiguous is a known issue, please check out #84 .

**Comment by lucktu** [comment]
Well, I hope it's done as soon as possible (even before 2.6), easy to distinguish and communicate.

Thank you!

**Comment by lucktu** [comment]
#### On ubuntu, edge -h
02/Sep/2019 12:22:45 [edge.c:628] Starting n2n edge 2.5.1 Jul  7 2019 09:53:39
Welcome to n2n v.2.5.1.r198.4d36f9f for Debian stretch/sid
Built on Jul  7 2019 09:53:37
Copyright 2007-19 - ntop.org and contributors

suggestion to
Welcome to n2n v2.5.1_r198 for Debian stretch/sid (or v2.5.1_r198.4d36f9f)
Built on Jul  7 2019 09:53:37
Copyright 2007-19 - ntop.org and contributors

#### On windows, edge -h
Welcome to n2n v.2.5.1 for Windows-10.0.18362
Built on Jul  7 2019 09:53:37
Copyright 2007-19 - ntop.org and contributors

suggestion to
Welcome to n2n v2.5.1_r198 for Windows-10.0.18362 (or v2.5.1_r198.4d36f9f)
Built on Jul  7 2019 09:53:37
Copyright 2007-19 - ntop.org and contributors

In addition, when there is something new (for example, after removing -b option), use v2.5.2 (2.5.3/2.5.4/.../2.5.1000...) please
https://github.com/lucktu/n2n

Thank you very much!

**Comment by emanuele-f** [comment]
I agree that the revision number on linux is a little bit weird now. Have to check how to extract revision/commit number in windows

**Comment by Logan007** [comment]
Is versioning still an issue?
