### ISSUE TITLE
Compiling with MingW-W64 GCC-8.1.0 fails under windows 10

### ISSUE THREAD

**Issue by fengdaolong** [ntop/n2n#162]
Compiling with MingW-W64 GCC-8.1.0 fails under windows 10, please fix errors and warnings.
The error log is as follows:

====================[ Build | all | Default ]===================================
"D:\Program Files\CMake\bin\cmake.exe" --build D:\USER\Documents\Code_Projects\C\ntop\n2n\cmake-build-default --target all -- -j 4
"D:\Program Files\CMake\bin\cmake.exe" -SD:\USER\Documents\Code_Projects\C\ntop\n2n -BD:\USER\Documents\Code_Projects\C\ntop\n2n\cmake-build-default --check-build-system CMakeFiles\Makefile.cmake 0
"D:\Program Files\CMake\bin\cmake.exe" -E cmake_progress_start D:\USER\Documents\Code_Projects\C\ntop\n2n\cmake-build-default\CMakeFiles D:\USER\Documents\Code_Projects\C\ntop\n2n\cmake-build-default\CMakeFiles\progress.marks
D:/PROGRA~1/MinGW/bin/mingw32-make.exe -f CMakeFiles\Makefile2 all
mingw32-make.exe[1]: Entering directory 'D:/USER/Documents/Code_Projects/C/ntop/n2n/cmake-build-default'
D:/PROGRA~1/MinGW/bin/mingw32-make.exe -f win32\CMakeFiles\n2n_win32.dir\build.make win32/CMakeFiles/n2n_win32.dir/depend
mingw32-make.exe[2]: Entering directory 'D:/USER/Documents/Code_Projects/C/ntop/n2n/cmake-build-default'
"D:\Program Files\CMake\bin\cmake.exe" -E cmake_depends "MinGW Makefiles" D:\USER\Documents\Code_Projects\C\ntop\n2n D:\USER\Documents\Code_Projects\C\ntop\n2n\win32 D:\USER\Documents\Code_Projects\C\ntop\n2n\cmake-build-default D:\USER\Documents\Code_Projects\C\ntop\n2n\cmake-build-default\win32 D:\USER\Documents\Code_Projects\C\ntop\n2n\cmake-build-default\win32\CMakeFiles\n2n_win32.dir\DependInfo.cmake --color=
Scanning dependencies of target n2n_win32
mingw32-make.exe[2]: Leaving directory 'D:/USER/Documents/Code_Projects/C/ntop/n2n/cmake-build-default'
D:/PROGRA~1/MinGW/bin/mingw32-make.exe -f win32\CMakeFiles\n2n_win32.dir\build.make win32/CMakeFiles/n2n_win32.dir/build
mingw32-make.exe[2]: Entering directory 'D:/USER/Documents/Code_Projects/C/ntop/n2n/cmake-build-default'
[  4%] Building C object win32/CMakeFiles/n2n_win32.dir/wintap.c.obj
cd /d D:\USER\Documents\Code_Projects\C\ntop\n2n\cmake-build-default\win32 && D:\PROGRA~1\MinGW\bin\gcc.exe -DN2N_HAVE_AES -DN2N_OSNAME=\"Windows\" -DN2N_VERSION=\"2.5.1\" @CMakeFiles/n2n_win32.dir/includes_C.rsp -O3 -DNDEBUG -static   -o CMakeFiles\n2n_win32.dir\wintap.c.obj   -c D:\USER\Documents\Code_Projects\C\ntop\n2n\win32\wintap.c
D:\USER\Documents\Code_Projects\C\ntop\n2n\win32\wintap.c: In function 'win_print_available_adapters':
D:\USER\Documents\Code_Projects\C\ntop\n2n\win32\wintap.c:108:32: warning: passing argument 1 of 'iterate_win_network_adapters' from incompatible pointer type [-Wincompatible-pointer-types]
   iterate_win_network_adapters(print_adapter_callback, NULL);
                                ^~~~~~~~~~~~~~~~~~~~~~
D:\USER\Documents\Code_Projects\C\ntop\n2n\win32\wintap.c:44:11: note: expected 'int (*)(struct win_adapter_info *, struct tuntap_dev *)' but argument is of type 'int (*)(struct win_adapter_info *, void *)'
     int (*callback)(struct win_adapter_info*, struct tuntap_dev *),
     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
D:\USER\Documents\Code_Projects\C\ntop\n2n\win32\wintap.c: In function 'set_interface_mac':
D:\USER\Documents\Code_Projects\C\ntop\n2n\win32\wintap.c:161:19: error: 'u_int8_t' undeclared (first use in this function); did you mean 'uint8_t'?
   uint8_t *ptr = (u_int8_t*)&mac;
                   ^~~~~~~~
                   uint8_t
D:\USER\Documents\Code_Projects\C\ntop\n2n\win32\wintap.c:161:19: note: each undeclared identifier is reported only once for each function it appears in
D:\USER\Documents\Code_Projects\C\ntop\n2n\win32\wintap.c:161:28: error: expected expression before ')' token
   uint8_t *ptr = (u_int8_t*)&mac;
                            ^
D:\USER\Documents\Code_Projects\C\ntop\n2n\win32\wintap.c: In function 'open_wintap':
D:\USER\Documents\Code_Projects\C\ntop\n2n\win32\wintap.c:234:23: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
   device->device_name = devname[0] ? devname : NULL;
                       ^
D:\USER\Documents\Code_Projects\C\ntop\n2n\win32\wintap.c:238:32: warning: passing argument 1 of 'iterate_win_network_adapters' from incompatible pointer type [-Wincompatible-pointer-types]
   iterate_win_network_adapters(choose_adapter_callback, device);
                                ^~~~~~~~~~~~~~~~~~~~~~~
D:\USER\Documents\Code_Projects\C\ntop\n2n\win32\wintap.c:44:11: note: expected 'int (*)(struct win_adapter_info *, struct tuntap_dev *)' but argument is of type 'int (*)(struct win_adapter_info *, void *)'
     int (*callback)(struct win_adapter_info*, struct tuntap_dev *),
     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
D:\USER\Documents\Code_Projects\C\ntop\n2n\win32\wintap.c:257:67: warning: passing argument 7 of 'DeviceIoControl' from incompatible pointer type [-Wincompatible-pointer-types]
                       device->mac_addr, sizeof(device->mac_addr), &len, 0)) {
                                                                   ^~~~
In file included from D:/PROGRA~1/MinGW/x86_64-w64-mingw32/include/winbase.h:21,
                 from D:/PROGRA~1/MinGW/x86_64-w64-mingw32/include/windows.h:70,
                 from D:/PROGRA~1/MinGW/x86_64-w64-mingw32/include/winsock2.h:23,
                 from D:/USER/Documents/Code_Projects/C/ntop/n2n/win32/n2n_win32.h:22,
                 from D:/USER/Documents/Code_Projects/C/ntop/n2n/n2n.h:39,
                 from D:\USER\Documents\Code_Projects\C\ntop\n2n\win32\wintap.c:5:
D:/PROGRA~1/MinGW/x86_64-w64-mingw32/include/ioapiset.h:22:175: note: expected 'LPDWORD' {aka 'long unsigned int *'} but argument is of type 'int *'
   WINBASEAPI WINBOOL WINAPI DeviceIoControl (HANDLE hDevice, DWORD dwIoControlCode, LPVOID lpInBuffer, DWORD nInBufferSize, LPVOID lpOutBuffer, DWORD nOutBufferSize, LPDWORD lpBytesReturned, LPOVERLAPPED lpOverlapped);
                                                                                                                                                                       ~~~~~~~~^~~~~~~~~~~~~~~
D:\USER\Documents\Code_Projects\C\ntop\n2n\win32\wintap.c:310:30: warning: passing argument 7 of 'DeviceIoControl' from incompatible pointer type [-Wincompatible-pointer-types]
    &status, sizeof (status), &len, NULL))
                              ^~~~
In file included from D:/PROGRA~1/MinGW/x86_64-w64-mingw32/include/winbase.h:21,
                 from D:/PROGRA~1/MinGW/x86_64-w64-mingw32/include/windows.h:70,
                 from D:/PROGRA~1/MinGW/x86_64-w64-mingw32/include/winsock2.h:23,
                 from D:/USER/Documents/Code_Projects/C/ntop/n2n/win32/n2n_win32.h:22,
                 from D:/USER/Documents/Code_Projects/C/ntop/n2n/n2n.h:39,
                 from D:\USER\Documents\Code_Projects\C\ntop\n2n\win32\wintap.c:5:
D:/PROGRA~1/MinGW/x86_64-w64-mingw32/include/ioapiset.h:22:175: note: expected 'LPDWORD' {aka 'long unsigned int *'} but argument is of type 'int *'
   WINBASEAPI WINBOOL WINAPI DeviceIoControl (HANDLE hDevice, DWORD dwIoControlCode, LPVOID lpInBuffer, DWORD nInBufferSize, LPVOID lpOutBuffer, DWORD nOutBufferSize, LPDWORD lpBytesReturned, LPOVERLAPPED lpOverlapped);
                                                                                                                                                                       ~~~~~~~~^~~~~~~~~~~~~~~
mingw32-make.exe[2]: Leaving directory 'D:/USER/Documents/Code_Projects/C/ntop/n2n/cmake-build-default'
mingw32-make.exe[2]: *** [win32\CMakeFiles\n2n_win32.dir\build.make:94: win32/CMakeFiles/n2n_win32.dir/wintap.c.obj] Error 1
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:244: win32/CMakeFiles/n2n_win32.dir/all] Error 2
mingw32-make.exe[1]: Leaving directory 'D:/USER/Documents/Code_Projects/C/ntop/n2n/cmake-build-default'
mingw32-make.exe: *** [Makefile:132: all] Error 2

**Comment by emanuele-f** [comment]
Please check if 1b1900358b3f2728d97699fc38ceb8ba79a4b20e solved the problems

**Comment by fengdaolong** [comment]
The new error is as follows:






====================[ Build | all | Default ]===================================
"D:\Program Files\CMake\bin\cmake.exe" --build D:\USER\Documents\Code_Projects\C\ntop\n2n\cmake-build-default --target all -- -j 4
"D:\Program Files\CMake\bin\cmake.exe" -SD:\USER\Documents\Code_Projects\C\ntop\n2n -BD:\USER\Documents\Code_Projects\C\ntop\n2n\cmake-build-default --check-build-system CMakeFiles\Makefile.cmake 0
"D:\Program Files\CMake\bin\cmake.exe" -E cmake_progress_start D:\USER\Documents\Code_Projects\C\ntop\n2n\cmake-build-default\CMakeFiles D:\USER\Documents\Code_Projects\C\ntop\n2n\cmake-build-default\CMakeFiles\progress.marks
D:/PROGRA~1/MinGW/bin/mingw32-make.exe -f CMakeFiles\Makefile2 all
mingw32-make.exe[1]: Entering directory 'D:/USER/Documents/Code_Projects/C/ntop/n2n/cmake-build-default'
D:/PROGRA~1/MinGW/bin/mingw32-make.exe -f win32\CMakeFiles\n2n_win32.dir\build.make win32/CMakeFiles/n2n_win32.dir/depend
mingw32-make.exe[2]: Entering directory 'D:/USER/Documents/Code_Projects/C/ntop/n2n/cmake-build-default'
"D:\Program Files\CMake\bin\cmake.exe" -E cmake_depends "MinGW Makefiles" D:\USER\Documents\Code_Projects\C\ntop\n2n D:\USER\Documents\Code_Projects\C\ntop\n2n\win32 D:\USER\Documents\Code_Projects\C\ntop\n2n\cmake-build-default D:\USER\Documents\Code_Projects\C\ntop\n2n\cmake-build-default\win32 D:\USER\Documents\Code_Projects\C\ntop\n2n\cmake-build-default\win32\CMakeFiles\n2n_win32.dir\DependInfo.cmake --color=
mingw32-make.exe[2]: Leaving directory 'D:/USER/Documents/Code_Projects/C/ntop/n2n/cmake-build-default'
D:/PROGRA~1/MinGW/bin/mingw32-make.exe -f win32\CMakeFiles\n2n_win32.dir\build.make win32/CMakeFiles/n2n_win32.dir/build
mingw32-make.exe[2]: Entering directory 'D:/USER/Documents/Code_Projects/C/ntop/n2n/cmake-build-default'
[  4%] Building C object win32/CMakeFiles/n2n_win32.dir/getopt.c.obj
[  8%] Building C object win32/CMakeFiles/n2n_win32.dir/getopt1.c.obj
cd /d D:\USER\Documents\Code_Projects\C\ntop\n2n\cmake-build-default\win32 && D:\PROGRA~1\MinGW\bin\gcc.exe -DN2N_HAVE_AES -DN2N_OSNAME=\"Windows\" -DN2N_VERSION=\"2.5.1\" @CMakeFiles/n2n_win32.dir/includes_C.rsp -O3 -DNDEBUG -static   -o CMakeFiles\n2n_win32.dir\getopt.c.obj   -c D:\USER\Documents\Code_Projects\C\ntop\n2n\win32\getopt.c
[ 13%] Building C object win32/CMakeFiles/n2n_win32.dir/wintap.c.obj
cd /d D:\USER\Documents\Code_Projects\C\ntop\n2n\cmake-build-default\win32 && D:\PROGRA~1\MinGW\bin\gcc.exe -DN2N_HAVE_AES -DN2N_OSNAME=\"Windows\" -DN2N_VERSION=\"2.5.1\" @CMakeFiles/n2n_win32.dir/includes_C.rsp -O3 -DNDEBUG -static   -o CMakeFiles\n2n_win32.dir\getopt1.c.obj   -c D:\USER\Documents\Code_Projects\C\ntop\n2n\win32\getopt1.c
cd /d D:\USER\Documents\Code_Projects\C\ntop\n2n\cmake-build-default\win32 && D:\PROGRA~1\MinGW\bin\gcc.exe -DN2N_HAVE_AES -DN2N_OSNAME=\"Windows\" -DN2N_VERSION=\"2.5.1\" @CMakeFiles/n2n_win32.dir/includes_C.rsp -O3 -DNDEBUG -static   -o CMakeFiles\n2n_win32.dir\wintap.c.obj   -c D:\USER\Documents\Code_Projects\C\ntop\n2n\win32\wintap.c
[ 17%] Linking C static library libn2n_win32.a
cd /d D:\USER\Documents\Code_Projects\C\ntop\n2n\cmake-build-default\win32 && "D:\Program Files\CMake\bin\cmake.exe" -P CMakeFiles\n2n_win32.dir\cmake_clean_target.cmake
cd /d D:\USER\Documents\Code_Projects\C\ntop\n2n\cmake-build-default\win32 && "D:\Program Files\CMake\bin\cmake.exe" -E cmake_link_script CMakeFiles\n2n_win32.dir\link.txt --verbose=1
D:\PROGRA~1\MinGW\bin\ar.exe qc libn2n_win32.a  CMakeFiles/n2n_win32.dir/getopt1.c.obj CMakeFiles/n2n_win32.dir/getopt.c.obj CMakeFiles/n2n_win32.dir/wintap.c.obj
D:\PROGRA~1\MinGW\bin\ranlib.exe libn2n_win32.a
mingw32-make.exe[2]: Leaving directory 'D:/USER/Documents/Code_Projects/C/ntop/n2n/cmake-build-default'
[ 17%] Built target n2n_win32
D:/PROGRA~1/MinGW/bin/mingw32-make.exe -f CMakeFiles\n2n.dir\build.make CMakeFiles/n2n.dir/depend
mingw32-make.exe[2]: Entering directory 'D:/USER/Documents/Code_Projects/C/ntop/n2n/cmake-build-default'
"D:\Program Files\CMake\bin\cmake.exe" -E cmake_depends "MinGW Makefiles" D:\USER\Documents\Code_Projects\C\ntop\n2n D:\USER\Documents\Code_Projects\C\ntop\n2n D:\USER\Documents\Code_Projects\C\ntop\n2n\cmake-build-default D:\USER\Documents\Code_Projects\C\ntop\n2n\cmake-build-default D:\USER\Documents\Code_Projects\C\ntop\n2n\cmake-build-default\CMakeFiles\n2n.dir\DependInfo.cmake --color=
mingw32-make.exe[2]: Leaving directory 'D:/USER/Documents/Code_Projects/C/ntop/n2n/cmake-build-default'
D:/PROGRA~1/MinGW/bin/mingw32-make.exe -f CMakeFiles\n2n.dir\build.make CMakeFiles/n2n.dir/build
mingw32-make.exe[2]: Entering directory 'D:/USER/Documents/Code_Projects/C/ntop/n2n/cmake-build-default'
[ 21%] Building C object CMakeFiles/n2n.dir/n2n.c.obj
[ 26%] Building C object CMakeFiles/n2n.dir/edge_utils.c.obj
D:\PROGRA~1\MinGW\bin\gcc.exe -DN2N_HAVE_AES -DN2N_OSNAME=\"Windows\" -DN2N_VERSION=\"2.5.1\" @CMakeFiles/n2n.dir/includes_C.rsp -O3 -DNDEBUG -static   -o CMakeFiles\n2n.dir\n2n.c.obj   -c D:\USER\Documents\Code_Projects\C\ntop\n2n\n2n.c
[ 30%] Building C object CMakeFiles/n2n.dir/wire.c.obj
D:\PROGRA~1\MinGW\bin\gcc.exe -DN2N_HAVE_AES -DN2N_OSNAME=\"Windows\" -DN2N_VERSION=\"2.5.1\" @CMakeFiles/n2n.dir/includes_C.rsp -O3 -DNDEBUG -static   -o CMakeFiles\n2n.dir\edge_utils.c.obj   -c D:\USER\Documents\Code_Projects\C\ntop\n2n\edge_utils.c
[ 34%] Building C object CMakeFiles/n2n.dir/minilzo.c.obj
D:\PROGRA~1\MinGW\bin\gcc.exe -DN2N_HAVE_AES -DN2N_OSNAME=\"Windows\" -DN2N_VERSION=\"2.5.1\" @CMakeFiles/n2n.dir/includes_C.rsp -O3 -DNDEBUG -static   -o CMakeFiles\n2n.dir\wire.c.obj   -c D:\USER\Documents\Code_Projects\C\ntop\n2n\wire.c
D:\PROGRA~1\MinGW\bin\gcc.exe -DN2N_HAVE_AES -DN2N_OSNAME=\"Windows\" -DN2N_VERSION=\"2.5.1\" @CMakeFiles/n2n.dir/includes_C.rsp -O3 -DNDEBUG -static   -o CMakeFiles\n2n.dir\minilzo.c.obj   -c D:\USER\Documents\Code_Projects\C\ntop\n2n\minilzo.c
[ 39%] Building C object CMakeFiles/n2n.dir/twofish.c.obj
D:\PROGRA~1\MinGW\bin\gcc.exe -DN2N_HAVE_AES -DN2N_OSNAME=\"Windows\" -DN2N_VERSION=\"2.5.1\" @CMakeFiles/n2n.dir/includes_C.rsp -O3 -DNDEBUG -static   -o CMakeFiles\n2n.dir\twofish.c.obj   -c D:\USER\Documents\Code_Projects\C\ntop\n2n\twofish.c
D:\USER\Documents\Code_Projects\C\ntop\n2n\edge_utils.c: In function 'check_join_multicast_group':
D:\USER\Documents\Code_Projects\C\ntop\n2n\edge_utils.c:580:10: error: 'n2n_edge_t' {aka 'struct n2n_edge'} has no member named 'multicast_joined'
   if(!eee->multicast_joined) {
          ^~
D:\USER\Documents\Code_Projects\C\ntop\n2n\edge_utils.c:585:24: error: 'n2n_edge_t' {aka 'struct n2n_edge'} has no member named 'udp_multicast_sock'; did you mean 'udp_mgmt_sock'?
     if(setsockopt(eee->udp_multicast_sock, IPPROTO_IP, IP_ADD_MEMBERSHIP, (char *)&mreq, sizeof(mreq)) < 0) {
                        ^~~~~~~~~~~~~~~~~~
                        udp_mgmt_sock
D:\USER\Documents\Code_Projects\C\ntop\n2n\edge_utils.c:595:10: error: 'n2n_edge_t' {aka 'struct n2n_edge'} has no member named 'multicast_joined'
       eee->multicast_joined = 1;
          ^~
mingw32-make.exe[2]: *** [CMakeFiles\n2n.dir\build.make:80: CMakeFiles/n2n.dir/edge_utils.c.obj] Error 1
mingw32-make.exe[2]: *** Waiting for unfinished jobs....
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:75: CMakeFiles/n2n.dir/all] Error 2
mingw32-make.exe[2]: Leaving directory 'D:/USER/Documents/Code_Projects/C/ntop/n2n/cmake-build-default'
mingw32-make.exe: *** [Makefile:132: all] Error 2
mingw32-make.exe[1]: Leaving directory 'D:/USER/Documents/Code_Projects/C/ntop/n2n/cmake-build-default'

**Comment by emanuele-f** [comment]
Please check out 8880330c4124c90bf9ea9647ee723f9643b3bcfa

**Comment by fengdaolong** [comment]
Ok, now patching is successful, it has been compiled normally, thank you!

**Comment by emanuele-f** [comment]
Thank you for reporting!
