### ISSUE TITLE
Make edge automatically read edge.conf if no option is given

### ISSUE THREAD

**Issue by jakeecn** [ntop/n2n#165]
The edge.conf file cannot be read, edge for windows？

**Comment by jakeecn** [comment]
When running edge.exe, it is determined that if there is edge.conf in the program directory, it will be read automatically, and the version information will be displayed if there is no edge.conf in the program directory.

**Comment by emanuele-f** [comment]
Please try "edge.exe edge.conf" after fix in 9cc2aee7fc232b4b393be8f0c91806da4fd61000

**Comment by jakeecn** [comment]
Thank you! 
1、Can you enable the running edge.exe to automatically read the edge.conf by default？
2、Whether registration as a windows service can be implemented？

**Comment by lucktu** [comment]
Yes, it can read edge.conf.
However, the version number will not change? 2.5.0

**Comment by jakeecn** [comment]
D:\software\Remote\n2n>edge.exe
Welcome to n2n v.2.5.1 for Windows
Built on Jul  8 2019 23:18:29
Copyright 2007-19 - ntop.org and contributors

edge <config file> (see edge.conf)
or
edge -d <tun device> -a [static:|dhcp:]<tun IP address> -c <community> [-k <encr
ypt key>]
    [-s <netmask>] [-m <MAC address>] -l <supernode host:port>
    [-p <local port>] [-M <mtu>] [-r] [-E] [-v] [-i <reg_interval>] [-t <mgmt po
rt>] [-b] [-A] [-h]

-d <tun device>          | tun device name
-a <mode:address>        | Set interface address. For DHCP use '-r -a dhcp:0.0.0
.0'
-c <community>           | n2n community name the edge belongs to.
-k <encrypt key>         | Encryption key (ASCII) - also N2N_KEY=<encrypt key>.
-s <netmask>             | Edge interface netmask in dotted decimal notation (25
5.255.255.0).
-l <supernode host:port> | Supernode IP:port
-i <reg_interval>        | Registration interval, for NAT hole punching (default
 20 seconds)
-b                       | Periodically resolve supernode IP
                         | (when supernodes are running on dynamic IPs)
-p <local port>          | Fixed local UDP port.
-m <MAC address>         | Fix MAC address for the TAP interface (otherwise it m
ay be random)
                         | eg. -m 01:02:03:04:05:06
-M <mtu>                 | Specify n2n MTU of edge interface (default 1400).
-r                       | Enable packet forwarding through n2n community.
-A                       | Use AES CBC for encryption (default=use twofish).
-E                       | Accept multicast MAC addresses (default=drop).
-v                       | Make more verbose. Repeat as required.
-t <port>                | Management UDP Port (for multiple edges on a machine)
.

Environment variables:
  N2N_KEY                | Encryption key (ASCII). Not with -k.


	
Running edge.exe does not read the configuration file [edge.conf] by default？

**Comment by jakeecn** [comment]
D:\software\Remote\n2n 
2019-07-08  23:30    <DIR>          .
2019-07-08  23:30    <DIR>          ..
2019-07-08  17:22                52 edge.bat
2019-07-08  23:32             1,063 edge.conf
2019-07-08  23:18           420,626 edge.exe

**Comment by lucktu** [comment]
OK, I see. Very good!
It's for my compiler.
Run edge, display help. ^_^

**Comment by emanuele-f** [comment]
I've changed the title. In essence this is useful in Windows because it makes it easy to run edge without an additional edge.bat script. However, maybe this behavior should be common between linux and windows. A pull request for windows is already provided in #166

**Comment by jakeecn** [comment]
Thank you so much！

**Comment by emanuele-f** [comment]
Implemented in 0b965c37c0e2b98f2b14592bdfc6e7f68bf8ac4b
