### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by zuurw** [ntop/n2n#171]
Hi, how are you? I'd like to collaborate on your open source project and propose free logo/icon design for this project. If it's something you're interested in, please, let me know!
Best Regards
Zuur

**Comment by emanuele-f** [comment]
Hi Zuur, thank you for your interest. Do you already have an idea to propose? N2n does not currently have an official graphical logo (it's mainly a cli tool, there was no necessity so far), but it would be useful. However the Android port of n2n https://github.com/switch-iot/Hin2n has one

**Comment by zuurw** [comment]
Hi, I would like to know what do you want for this logo, can you give me something to get inspired?

Thank you!
Best Regards!

**Comment by emanuele-f** [comment]
The logo should be something related to the ability of n2n to cross the internet bounds to connect the devices together
