### ISSUE TITLE
Running edge as a service,  the edge process not running, in CentOS7

### ISSUE THREAD

**Issue by wangchaowei** [ntop/n2n#173]

**Comment by wangchaowei** [comment]
I run `sudo systemctl start edge` but edge not start.
When `sudo edge -c mynetwork -k mysecretpass -a 192.168.100.1 -f -l supernode.ntop.org:7777` it was worked.

**Comment by emanuele-f** [comment]
Hi, have you edited `/etc/n2n/edge.conf` with your configuration options?

**Comment by wangchaowei** [comment]
Oh! thx!  it is Working!
It is `/etc/n2n/edge.conf`
But in README.md it is `/etc/n2n/edge`

**Comment by emanuele-f** [comment]
Fixed in 024dca79af035c81597f4cd863cacf2336ad5ebf . Thank you for reporting it
