### ISSUE TITLE
Idle community auto-purging breaks community whitelist file.

### ISSUE THREAD

**Issue by ddscentral** [ntop/n2n#175]
Idle community auto-purging should be disabled when using an allowed community whitelist file.
When supernode starts, it correctly creates all the communities specified in the whitelist. But because of auto-purging, those communities immediately get removed. As there's no way to create new communities when using a whitelist, supernode essentially becomes unusable.
For now, I have patched-out community auto-purging in my n2n builds, but it would be nice to have a proper fix for this bug.

**Comment by emanuele-f** [comment]
Thank you for reporting!
