### ISSUE TITLE
Recommended cancellation -b in future

### ISSUE THREAD

**Issue by lucktu** [ntop/n2n#176]
Because I find that it easy to ignore it for many people, I recommend canceling this parameter in the future (let the program judge automatically), for example when n2n_v3 arrives. it's good for stability.

Objective: To be able to work normally and stably under the most basic elements.

For reference only

**Comment by emanuele-f** [comment]
`-b` removed in 49f1f1b886b3fccc72ac45258be3594a4b285192 as supernode address is always resolved during registration. Thank you
