### ISSUE TITLE
mac install: error: use of undeclared identifier 'IP_PMTUDISC_DONT'

### ISSUE THREAD

**Issue by twolao** [ntop/n2n#180]
mac os:10.14.6 Mojave
--------
brew install autoconf
brew install automake
sudo spctl --master-disable
brew tap homebrew/cask
brew cask install tuntap
cd /usr/local/include
ln -s ../opt/openssl/include/openssl .
git clone https://github.com/ntop/n2n.git
cd n2n
./autogen
./configure
make

error：
-----------------
$ make
cc -g3  -Wall   -c n2n.c -o n2n.o
cc -g3  -Wall   -c wire.c -o wire.o
cc -g3  -Wall   -c minilzo.c -o minilzo.o
cc -g3  -Wall   -c twofish.c -o twofish.o
cc -g3  -Wall   -c edge_utils.c -o edge_utils.o
edge_utils.c:1819:50: error: use of undeclared identifier 'IP_PMTUDISC_DONT'
  sockopt = (eee->conf.disable_pmtu_discovery) ? IP_PMTUDISC_DONT : IP_PMTUDISC_DO;
                                                 ^
edge_utils.c:1819:69: error: use of undeclared identifier 'IP_PMTUDISC_DO'
  sockopt = (eee->conf.disable_pmtu_discovery) ? IP_PMTUDISC_DONT : IP_PMTUDISC_DO;
                                                                    ^
edge_utils.c:1821:44: error: use of undeclared identifier 'IP_MTU_DISCOVER'
  if(setsockopt(eee->udp_sock, IPPROTO_IP, IP_MTU_DISCOVER, &sockopt, sizeof(sockopt)) < 0)
                                           ^
3 errors generated.
make: *** [edge_utils.o] Error 1

------------------

**Comment by emanuele-f** [comment]
Should be fixed in 1b49b37a75efbfe4f7ba35fa7b9dfa5426de17e8 , please double check

**Comment by twolao** [comment]
> Should be fixed in [1b49b37](https://github.com/ntop/n2n/commit/1b49b37a75efbfe4f7ba35fa7b9dfa5426de17e8) , please double check

thanx, Although there are still some errors, it can be ignored and run from the client.


---------------

$ cd ~/go/src/n2n/
n2n $ vim edge.c
n2n $ vim edge_utils.c
n2n $ ./autogen.sh
Wait please...

Now run ./configure



n2n $ ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for AES_cbc_encrypt in -lcrypto... no
Building n2n without AES support
checking for pcap_open_live in -lpcap... yes
checking for pcap_set_immediate_mode in -lpcap... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating tools/Makefile
config.status: creating config.h


n2n $ make
cc -g3  -Wall   -c edge_utils.c -o edge_utils.o
cc -g3  -Wall   -c transform_null.c -o transform_null.o
cc -g3  -Wall   -c transform_tf.c -o transform_tf.o
cc -g3  -Wall   -c transform_aes.c -o transform_aes.o
cc -g3  -Wall   -c tuntap_freebsd.c -o tuntap_freebsd.o
cc -g3  -Wall   -c tuntap_netbsd.c -o tuntap_netbsd.o
cc -g3  -Wall   -c tuntap_linux.c -o tuntap_linux.o
cc -g3  -Wall   -c tuntap_osx.c -o tuntap_osx.o
ar rcs libn2n.a n2n.o wire.o minilzo.o twofish.o edge_utils.o transform_null.o transform_tf.o transform_aes.o tuntap_freebsd.o tuntap_netbsd.o tuntap_linux.o tuntap_osx.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libn2n.a(transform_aes.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libn2n.a(tuntap_freebsd.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libn2n.a(tuntap_netbsd.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libn2n.a(tuntap_linux.o) has no symbols
cc -g3  -Wall   edge.c libn2n.a  -o edge
edge.c:597:13: warning: unused function 'term_handler' [-Wunused-function]
static void term_handler(int sig)
            ^
1 warning generated.
cc -g3  -Wall   sn.c libn2n.a  -o supernode
sn.c:916:13: warning: unused function 'dump_registrations' [-Wunused-function]
static void dump_registrations(int signo) {
            ^
sn.c:952:13: warning: unused function 'term_handler' [-Wunused-function]
static void term_handler(int sig)
            ^
2 warnings generated.
cc -g3  -Wall   example_edge_embed.c libn2n.a  -o example_edge_embed
gzip -c edge.8 > edge.8.gz
gzip -c supernode.1 > supernode.1.gz
gzip -c n2n.7 > n2n.7.gz
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C tools
cc -I.. -g3  -Wall benchmark.c ../libn2n.a  -o n2n-benchmark
cc -I.. -g3  -Wall n2n_decode.c ../libn2n.a  -lpcap -o n2n-decode
n2n_decode.c:61:13: warning: unused function 'term_handler' [-Wunused-function]
static void term_handler(int sig)
            ^
1 warning generated.


$ sudo make install
Password:
echo "MANDIR=/usr/share/man"
MANDIR=/usr/share/man
mkdir -p /usr/local/sbin /usr/share/man/man1 /usr/share/man/man7 /usr/share/man/man8
install -m755 supernode /usr/local/sbin/
install -m755 edge /usr/local/sbin/
install -m644 edge.8.gz /usr/share/man/man8/
install -m644 supernode.1.gz /usr/share/man/man1/
install -m644 n2n.7.gz /usr/share/man/man7/
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C tools install
install -m755 n2n-benchmark n2n-decode /usr/sbin/
install: /usr/sbin//n2n-benchmark: Operation not permitted
make[1]: *** [install] Error 71
make: *** [install] Error 2
