### ISSUE TITLE
Error compiling with MingW-W64 GCC-8.1.0 under Windows 10

### ISSUE THREAD

**Issue by fengdaolong** [ntop/n2n#182]
Error compiling with mingw under Windows 10
As part of the error log, 'IP_PMTUDISC_DONT', 'IP_PMTUDISC_DO' and 'IP_MTU_DISCOVER' undeclared.

>D:\USER\Documents\Code_Projects\C\ntop\n2n\n2n.c: In function 'open_socket':
>D:\USER\Documents\Code_Projects\C\ntop\n2n\n2n.c:50:49: warning: passing argument 4 of 'setsockopt' from incompatible pointer type [-Wincompatible-pointer-types]
>   setsockopt(sock_fd, SOL_SOCKET, SO_REUSEADDR, &sockopt, sizeof(sockopt));
>                                                 ^~~~~~~~
>In file included from D:\USER\Documents\Code_Projects\C\ntop\n2n\win32/n2n_win32.h:22,
>                 from D:\USER\Documents\Code_Projects\C\ntop\n2n\n2n.h:39,
>                 from D:\USER\Documents\Code_Projects\C\ntop\n2n\n2n.c:19:
>D:/PROGRA~1/MinGW/x86_64-w64-mingw32/include/winsock2.h:999:88: note: expected 'const char *' but argument is of type 'int *'
>   WINSOCK_API_LINKAGE int WSAAPI setsockopt(SOCKET s,int level,int optname,const char *optval,int optlen);
>                                                                            ~~~~~~~~~~~~^~~~~~
>D:\USER\Documents\Code_Projects\C\ntop\n2n\edge_utils.c: In function 'edge_init_sockets':
>D:\USER\Documents\Code_Projects\C\ntop\n2n\edge_utils.c:1813:54: warning: passing argument 4 of 'setsockopt' from incompatible pointer type [-Wincompatible-pointer-types]
>     if(setsockopt(eee->udp_sock, IPPROTO_IP, IP_TOS, &sockopt, sizeof(sockopt)) == 0)
>                                                      ^~~~~~~~
>In file included from D:\USER\Documents\Code_Projects\C\ntop\n2n\win32/n2n_win32.h:22,
>                 from D:\USER\Documents\Code_Projects\C\ntop\n2n\n2n.h:39,
>                 from D:\USER\Documents\Code_Projects\C\ntop\n2n\edge_utils.c:19:
>D:/PROGRA~1/MinGW/x86_64-w64-mingw32/include/winsock2.h:999:88: note: expected 'const char *' but argument is of type 'int *'
>   WINSOCK_API_LINKAGE int WSAAPI setsockopt(SOCKET s,int level,int optname,const char *optval,int optlen);
>                                                                            ~~~~~~~~~~~~^~~~~~
>D:\USER\Documents\Code_Projects\C\ntop\n2n\edge_utils.c:1820:50: error: 'IP_PMTUDISC_DONT' undeclared (first use in this function)
>   sockopt = (eee->conf.disable_pmtu_discovery) ? IP_PMTUDISC_DONT : IP_PMTUDISC_DO;
>                                                  ^~~~~~~~~~~~~~~~
>D:\USER\Documents\Code_Projects\C\ntop\n2n\edge_utils.c:1820:50: note: each undeclared identifier is reported only once for each function it appears in
>D:\USER\Documents\Code_Projects\C\ntop\n2n\edge_utils.c:1820:69: error: 'IP_PMTUDISC_DO' undeclared (first use in this function); did you mean 'IP_PKTINFO'?
>   sockopt = (eee->conf.disable_pmtu_discovery) ? IP_PMTUDISC_DONT : IP_PMTUDISC_DO;
>                                                                     ^~~~~~~~~~~~~~
>                                                                     IP_PKTINFO
>D:\USER\Documents\Code_Projects\C\ntop\n2n\edge_utils.c:1822:44: error: 'IP_MTU_DISCOVER' undeclared (first use in this function)
>   if(setsockopt(eee->udp_sock, IPPROTO_IP, IP_MTU_DISCOVER, &sockopt, sizeof(sockopt)) < 0)
>                                            ^~~~~~~~~~~~~~~
>D:\USER\Documents\Code_Projects\C\ntop\n2n\edge_utils.c:1822:61: warning: passing argument 4 of 'setsockopt' from incompatible pointer type [-Wincompatible-pointer-types]
>   if(setsockopt(eee->udp_sock, IPPROTO_IP, IP_MTU_DISCOVER, &sockopt, sizeof(sockopt)) < 0)
>                                                             ^~~~~~~~
>In file included from D:\USER\Documents\Code_Projects\C\ntop\n2n\win32/n2n_win32.h:22,
>                 from D:\USER\Documents\Code_Projects\C\ntop\n2n\n2n.h:39,
>                 from D:\USER\Documents\Code_Projects\C\ntop\n2n\edge_utils.c:19:
>D:/PROGRA~1/MinGW/x86_64-w64-mingw32/include/winsock2.h:999:88: note: expected 'const char *' but argument is of type 'int *'
>   WINSOCK_API_LINKAGE int WSAAPI setsockopt(SOCKET s,int level,int optname,const char *optval,int optlen);
>                                                                            ~~~~~~~~~~~~^~~~~~
>[ 43%] Building C object CMakeFiles/n2n.dir/transform_null.c.obj
>mingw32-make.exe[2]: *** [CMakeFiles\n2n.dir\build.make:80: CMakeFiles/n2n.dir/edge_utils.c.obj] Error 1
>mingw32-make.exe[2]: *** Waiting for unfinished jobs....
>D:\PROGRA~1\MinGW\bin\gcc.exe -DCMAKE_BUILD -DN2N_HAVE_AES -DN2N_OSNAME=\"Windows\" -DN2N_VERSION=\"2.5.1\" @CMakeFiles/n2n.dir/includes_C.rsp -O3 -DNDEBUG -static   -o CMakeFiles\n2n.dir\transform_null.c.obj   -c D:\USER\Documents\Code_Projects\C\ntop\n2n\transform_null.c
>mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:82: CMakeFiles/n2n.dir/all] Error 2
>mingw32-make.exe[2]: Leaving directory 'D:/USER/Documents/Code_Projects/C/ntop/n2n/cmake-build-default'
>mingw32-make.exe[1]: Leaving directory 'D:/USER/Documents/Code_Projects/C/ntop/n2n/cmake-build-default'
>mingw32-make.exe: *** [Makefile:132: all] Error 2

**Comment by emanuele-f** [comment]
Do you have an `#ifdef mingw` or similar to remove that problematic code with mingw? Compiling with visual studio works fine

**Comment by fengdaolong** [comment]
'IP_PMTUDISC_DONT', 'IP_PMTUDISC_DO' and 'IP_MTU_DISCOVER' are defined in “linux/in.h”, however mingw for windows does not include this file.

**Comment by emanuele-f** [comment]
Please check if 7e7782f965c521bb70a08856864ab3ca1d0cab83 solves the issue

**Comment by fengdaolong** [comment]
OK，Now compiled normally，Thanks!
