### ISSUE TITLE
Improve perfomance/speed documentation

### ISSUE THREAD

**Issue by pojntfx** [ntop/n2n#184]
After playing around with N2N for quite a bit, I was at first a bit disappointed by the performance - 20 Mbit/s on a gigabit connection? Well, at first I didn't enable AES (after adding `-A`, I was able to go to 50 Mbit/s), then I checked the CPU, which was at 100% (a 1 CPU instance). Upgraded the node to 2 CPUs, 100 Mbit/s. We're getting there! Now, I used `-v` to get some more details; I did not think that adding logging would reduce speed drastically. After removing `-v`, the speed went up to 300 Mbit/s. Now, I though about some more options, so I ran another `edge`. Yet another speed improvement, this time I was able to achieve 430 Mbits, which is really quite impressive for a _userspace_ VPN.

It would be awesome if there would be a specific section on perfomance. Having such simple changes literally allowing N2N to have _22x_ the speed is a thing that some emphasis should be put on IMHO.

Anyways, thanks so much for developing this! N2N is awesome!

**Comment by mrbluecoat** [comment]
Also, a benchmark comparing WireGuard would be useful.

**Comment by lucktu** [comment]
@pojntfx, Can I see your running code now?
Such as: edge2 -a 10.10.0.100 -c n2n -k test -l n2n.lucktu.com:10086 -brEfA
Thank you!

**Comment by emanuele-f** [comment]
@pojntfx thank you for the suggestion. Please share more details on your tests and your performance tips. Please also check out `tools/n2n-benchmark`.

@mrbluecoat please note that wireguard is kernel space vpn, so it is not comparable with n2n (which is userspace).

**Comment by pojntfx** [comment]
@emanuele-f Sure, I'll be adding those next weekend; I'm currently thinking of creating a "meta cli" for N2N (for supporting `pm2`-managed multiple edges, easier management, multiple parallel instances etc.)
@mrbluecoat I agree with @emanuele-f that the performance is not really comparable; N2N is much faster than `wireguard-go`, which is WireGuard's userspace implementation, though. I'd be happy to add some `iperf`/`tools/n2n-benchmark` stats next weekend.

**Comment by pojntfx** [comment]
> @pojntfx, Can I see your running code now?
> Such as: edge2 -a 10.10.0.100 -c n2n -k test -l n2n.lucktu.com:10086 -brEfA
> Thank you!

Sorry, I didn't get your comment fast enough. Feel free to hit me up on <felix@pojtinger.com> and I'd be happy to provide you with some output.

**Comment by lucktu** [comment]
I 've got it. Thank you!

**Comment by lucktu** [comment]
And? @pojntfx

**Comment by pojntfx** [comment]
@lucktu Sorry for taking so long! I was busy at work and also working on some other personal projects privately ([dibs](https://github.com/pojntfx/dibs), [gomather](https://github.com/pojntfx/gomather), [...](https://github.com/pojntfx?tab=repositories)). I just started writing [Go bindings for n2n](https://github.com/pojntfx/gon2n) though; I'll add a custom "launcher" there (for launching multiple edges, running an embedded DHCP server, running `sysctl` to enable forwarding, etc.) and if I can find the time I'll add some integration tests that will show the perfomance optimizations.

**Comment by pojntfx** [comment]
@lucktu I wrote a n2n management daemon with a gRPC API (https://github.com/pojntfx/gon2n); I'm still working the embedded dhcp server though.

**Comment by lucktu** [comment]
@pojntfx That's all right. Thanks for your test.
