### ISSUE TITLE
"invalid option -- 'A'" cant use AES on x86_64 Ubuntu 19.10

### ISSUE THREAD

**Issue by frenchfaso** [ntop/n2n#187]
While trying to use AES with the -A option, I get the following error upon starting edge:
invalid option -- 'A'
the weird thing is that it works well on a RaspberryPi Zero, with latest Raspbian but not on my laptop with Ubuntu 19.10 x86_64.
Both n2n are version 2.5.1.
Thanks for the help and for this awesome vpn!

**Comment by emanuele-f** [comment]
You need to install the openssl libraries (it should be `libssl-dev`). Then `./configure` and `make` again.

**Comment by fengdaolong** [comment]
The advantage of n2n is simple and convenient. 
Static compilation is too important for n2n.
Can do that is open use, efficient operation.
No need to consider any dependencies.
Please fix its static compilation problem #183  .
@emanuele-f

**Comment by emanuele-f** [comment]
Please note that static compilation is not the problem for this issue. Installing the openssl development library is a required in order to compile n2n (static or dynamic).

**Comment by fengdaolong** [comment]
The openssl dependency library can be included in n2n during static compilation.

**Comment by frenchfaso** [comment]
> You need to install the openssl libraries (it should be `libssl-dev`). Then `./configure` and `make` again.

Hy Emanuele, thanks for your help! 
just tried that and now I get the following errors after starting edge with -A:
ERROR: Transop init failed
ERROR: Failed in edge_init
without the -A it works fine.

UPDATE 1
nevermind! I might have forgotten to do a "make clean"..

UPDATE 2
yep! a "make clean" did the trick, it works fine now with the -A option

**Comment by emanuele-f** [comment]
Good. Closing the issue.

@fengdaolong openssl is a critical library which must kept up to date. Bundling it statically for me it's an error. In general bundling libraries statically is not good for many reasons (for example, executable size, runtime RAM usage) so definitely I won't switch to static libraries as the default. The issue that you have outlined which is static compilation not working, however, must be fixed.

**Comment by fengdaolong** [comment]
Thank you!

Sometimes we need to one compile and run everywhere, sometimes we need to consider the memory footprint. In short, it can choose static compilation or dynamic compilation depending on the usage scenario.

**Comment by Logan007** [comment]
Sorry for bringing up old discussions... but do you think there is a need for a native CPU based AES / SHA implementation as a kind of fall-back option in case of openSSL not being available – just like the twofish encryption?
