### ISSUE TITLE
loosing network before REGISTER_SUPER_ACK

### ISSUE THREAD

**Issue by praiskup** [ntop/n2n#191]
```
$ while :; do ssh root@<IP_ADDRESS_OF_OTHER_BOX> ls / -d ; sleep 60; done
/
ssh: connect to host IP_ADDRESS_OF_OTHER_BOX port 22: No route to host
/
ssh: connect to host IP_ADDRESS_OF_OTHER_BOX port 22: No route to host
/
/
ssh: connect to host IP_ADDRESS_OF_OTHER_BOX port 22: No route to host
/
ssh: connect to host IP_ADDRESS_OF_OTHER_BOX port 22: No route to host
ssh: connect to host IP_ADDRESS_OF_OTHER_BOX port 22: No route to host
/
ssh: connect to host IP_ADDRESS_OF_OTHER_BOX port 22: No route to host
ssh: connect to host IP_ADDRESS_OF_OTHER_BOX port 22: No route to host
ssh: connect to host IP_ADDRESS_OF_OTHER_BOX port 22: No route to host
ssh: connect to host IP_ADDRESS_OF_OTHER_BOX port 22: No route to host
ssh: connect to host IP_ADDRESS_OF_OTHER_BOX port 22: No route to host
ssh: connect to host IP_ADDRESS_OF_OTHER_BOX port 22: No route to host
ssh: connect to host IP_ADDRESS_OF_OTHER_BOX port 22: No route to host
...
```

So there are moments when the networking works, and when it doesn't.
I started edge like:

```
sudo /usr/sbin/edge -c XXX -d XXX -k MYPASS \
  -l HOST:PORT \
  -a MY_IP \
  -m MY_MAC \
  -f -v
```

And supernode like:
```
/usr/sbin/supernode -l PORT -v -f
```

And I see that the networking starts working right after re-registering
(Rx REGISTER_SUPER_ACK message printed).

I don't really know what to look for in the logs, any hints please?

**Comment by emanuele-f** [comment]
The `REGISTER_SUPER_ACK` message is sent by the supernode to confirm that the edge node can now communicate with it. Registration should occur as soon as the edge node is started, normally in 1-3 seconds, and then it's performed periodically. First of all, are you using the latest dev version from this repo? If so, can you check if running a continuous ping against the target host makes the connection more stable?

**Comment by praiskup** [comment]
> First of all, are you using the latest dev version from this repo? 

I run the version 2.1.0 from Fedora package, so not a development version.
Anything important happened since `n2n-2.1.0`?  :-)  I'll try.

> If so, can you check if running a continuous ping against the target host makes the connection more stable?

Yes, it does.  If I ping continuously, the network doesn't go down at all.

**Comment by emanuele-f** [comment]
Version 2.1.0 is unknown to me, anyway the dev version from this repo should have a lot of improvements on the connection stability.

**Comment by praiskup** [comment]
Ok, thanks.  Closing for now.

**Comment by praiskup** [comment]
Hm, even update to v2.4 seems to help.  So FTR, I propose update of Fedora package:
https://src.fedoraproject.org/rpms/n2n/pull-request/1

**Comment by praiskup** [comment]
Ok, no.  It doesn't help - but the problems are much less frequent.  Are we really supposed to run software from `dev`, or from `2.4-stable` branch?

**Comment by emanuele-f** [comment]
dev branch has a lot of improvements over the stable yes. We will soon release a new stable version out of dev.

**Comment by praiskup** [comment]
Ok, I tried with `dev`, and still the same problem (both the `edge` binaries are updated, and `supernode` as well).  And the problem appears.

**Comment by praiskup** [comment]
Any idea how I could debug this?

**Comment by emanuele-f** [comment]
Could you post the edge and supernode logs with the `-v` option enabled?

**Comment by Logan007** [comment]
Closed due to inactivity, current version recommended to test. Please re-open if required.
