### ISSUE TITLE
Unable to quit

### ISSUE THREAD

**Issue by zjbdiy** [ntop/n2n#194]
I compiled windows with vs2017, unable to connect, exit, no error

https://s2.ax1x.com/2019/12/21/Qjn9sJ.jpg

**Comment by emanuele-f** [comment]
This is strange, as `_exit(0)` is called right after displaying the `Ok I am leaving now` message.
The connection to the local supernode seems established, what do you mean with "unable to connect"?

**Comment by Logan007** [comment]
Is this still an issue?

**Comment by zjbdiy** [comment]
I don't remember what happened at that time
The problem has been solved

**Comment by Logan007** [comment]
Thanks for reporting. If it happens again, let us know.
