### ISSUE TITLE
timeout? not output log when connect error

### ISSUE THREAD

**Issue by Hosigus** [ntop/n2n#197]
I'm using the latest n2n version from github, dev branch
I compiled Ubuntu and windows versions in Ubuntu environment and deployed to my ubuntu server
The port can communicate successfully(test with nc)
But when I run supernode in server and edge on my windows pc, it didn't output the log after "edge started"
no error or no success?
Minutes later,it shut it down automatically
It did output something like "Supernode not responding..." when I'm trying to connect to a wrong port.

It's that a bug?

**Comment by emanuele-f** [comment]
Hi, it seems like n2n is blocked in some call. Please ensure that TAP drivers are correctly installed as specified in https://github.com/ntop/n2n/blob/dev/doc/Windows.md . Does it show any message after it exists?

**Comment by Hosigus** [comment]
![D`BDT`C0URRTCA2{FITI3YX](https://user-images.githubusercontent.com/30467421/72738105-d378b000-3bdb-11ea-8972-f9d992b99e41.png)
It would show nothing after "edge started".
It would show "Shutting down..." and "OK,I'm leaving.." if I press "Ctrl+C".
![image](https://user-images.githubusercontent.com/30467421/72738387-6dd8f380-3bdc-11ea-9dce-98686e09a699.png)
It would show "Supernode not responding..." when I'm trying to connect to a wrong port.

**Comment by Hosigus** [comment]
And my TAP is fine
I can connect to other server successfully with low version like "v2.0.0"

**Comment by emanuele-f** [comment]
`WARNING: Supernode not reponding` -> this seems like a problem in the connection to the supernode

**Comment by Logan007** [comment]
Does it work with edge and supernode built from current _dev_?

**Comment by Logan007** [comment]
Considered answered as no news. Please re-open if required.
