### ISSUE TITLE
install  error on macos 10.13.6

### ISSUE THREAD

**Issue by Tonigt** [ntop/n2n#200]
sudo make install
[ 12%] Built target doc
[ 66%] Built target n2n
[ 75%] Built target n2n-benchmark
[ 83%] Built target supernode
[ 91%] Built target edge
[100%] Built target n2n-decode
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/sbin/edge
-- Installing: /usr/local/sbin/supernode
-- Installing: /usr/local/bin/n2n-decode
-- Installing: /usr/local/bin/n2n-benchmark
CMake Error at cmake_install.cmake:84 (file):
  file cannot create directory: /usr/share/man8.  Maybe need administrative
  privileges.

**Comment by emanuele-f** [comment]
Hi, does the directory `/usr/share` exist? What about `/usr/local/share/man`?

**Comment by emanuele-f** [comment]
Any news?
