### ISSUE TITLE
It is recommended to add a message about success

### ISSUE THREAD

**Issue by lucktu** [ntop/n2n#202]
When there is only one edge, or when all the connections are not P2P, it is difficult to know if the connection is successful.

Therefore, when the edge and supernode connection is successful, a message should be sent back to let us know that the connection is successful.

Thank you!

**Comment by Logan007** [comment]
> Therefore, when the edge and supernode connection is successful, a message should be sent back to let us know that the connection is successful.

Do you think that #335 solves this issue?

**Comment by Logan007** [comment]
Considered answered, please re-open if required.
