### ISSUE TITLE
Openwrt cross-compilation failed

### ISSUE THREAD

**Issue by woOzZ2** [ntop/n2n#203]
1. git clone https://github.com/ntop/n2n n2n
2. cp -r n2n/packages/openwrt package/n2n
3. make menuconfig # select Network -> VPN -> n2n-edge and n2n-supernode
4. make package/n2n/compile V=s

Step 3 will prompt you that there is no rule to make "menuconfig" stop

Hope to be able to give a short mipsel cross - compilation tutorial, thank you

**Comment by emanuele-f** [comment]
`menuconfig` is a standard make target for cross compilation environments. It seems like your cross compilation environment is not properly configured. I suggest you to first compile an image and install it on the device so that you know that your environment works.
