### ISSUE TITLE
How to get the status of edge connection?

### ISSUE THREAD

**Issue by 01BAI** [ntop/n2n#208]
I have created 2 edge, and they can PING each other. But how can i know whether they are P2P or forwarding by supernode？

**Comment by Logan007** [comment]
You could use `netcat` to connect to the management port: `netcat -u localhost 5644`

Sending another _line feed_ by pressing [Enter] should output the stats.

**Comment by 01BAI** [comment]
> You could use `netcat` to connect to the management port: `netcat -u localhost 5644`
> 
> Sending another _line feed_ by pressing [Enter] should output the stats.

 @Logan007  Thank you for your help and I got the stats, but how to understand these parameters？ 
![微信截图_20200316134510](https://user-images.githubusercontent.com/45509044/76726536-5fe2c180-678c-11ea-82d0-a62a6bcb969f.png)

**Comment by Logan007** [comment]
The line `paths  super:182,38 p2p:0,0` indicates that 
- `182` packets were sent via the supernode, 
- `38` packets were received via the supernode, 
- `0` packets were directly sent via p2p, and 
- `0` packets were directly received via p2p.
