### ISSUE TITLE
android wifi tether through VPN

### ISSUE THREAD

**Issue by ICFlying** [ntop/n2n#21]
Dear friend，Make the computer connected to the hot spot of the phone through the VPN channel，
I think it's very good

**Comment by lucaderi** [comment]
The Android app has been developed by contributors listed at https://github.com/ntop/n2n/tree/master/android/Hin2n

Can you please contact them about this matter and ask to send a pull request for changes?

**Comment by ICFlying** [comment]
thanks，I contacted with them ，he doing this job now.it will support this a few days later.

**Comment by lucaderi** [comment]
Thank you
