### ISSUE TITLE
AES: provide (better) hardware acceleration

### ISSUE THREAD

**Issue by Logan007** [ntop/n2n#214]
Reading some hints that openssl's `AES_encrypt_*` interface did not provide hardware acceleration, I dug into its code. Indeed, it seems that it employs a software based encryption only – I did not check the various ASMs for occurences of AES-NI though. However, that already was enough reason to start testing openssl's alternative `evp_*` which is [said](https://www.openssl.org/docs/man1.1.0/man3/EVP_EncryptInit.html) (Notes section) to guarantee the support of available hardware acceleration.

Please find the result in pull request #213 . ~~A tidied update will follow soon (remove one variable and anything else you might find).~~ _[done]_ Also, I have attached a [patch](https://github.com/ntop/n2n/files/4360880/patch.txt) as it might be easier to apply for some testing.

`tools/n2n-benchmark` reports __plus (!) 128 %__ better AES encryption-throughput (397.4 MB/s) on my i7-2860QM (compared to current dev: 174.6 MB/s) which might be an indicator for actual use of hardware acceleration. _[EDIT: data rates from new benchmark runs w/o other applications running in the background]_

Transmission (which also yielded higher throughput) was tested against an original edge built from current dev to ensure compatibility which seems to be flawless.

My guess is that openssl's `AES_encrypt_*` already is quite fast compared to n2n's Twofish as it might use platform-optimized code (pure ASM) if appropriately compiled but not the maybe available, dedicated AES-NI instructions yet.

~~A naturally next step would be to also use openssl's `evp_*` for the remaining IV related AES-ECB step.~~ Applying openssl's `evp_*` also to the one block IV is bogus to throughput (362.4 MB/s) and thus not implemented there. The hardware acceleration does not seem to pay off for a single block to encrypt due to the more complicated `evp_*` setup.

By the way, another significant encryption speed-up could be achieved by using AES in CTR-mode instead of CBC. But for security reasons, it would require to __sharply rethink__ the complete __IV handling__ – especially size, randomness, and its transmission. 

Any thoughts? How do your benchmarks compare?

**Comment by Logan007** [comment]
I got my hands on some other computers. Here is how `tools/n2n-benchmark`'s AES results compare (best of three):

CPU | AES Hw | `AES_encrypt_*` | `evp_*` | Gain
:--|:--:|--:|--:|--:
Core i5 M430 | ⁿ/ₐ | 104.0 MB/s | 170.1 MB/s | + 64 %¹
Celeron 3865U | ✓ | 111.2 MB/s | 313.9 MB/s | + 180 %
i7 2860QM | ✓ | 174.6 MB/s | 397.4 MB/s |  + 128 %
i7 4770T | ✓ | 209.2 MB/s | 492.9 MB/s | + 136 %
i7 5775C | ✓ | 217.0 MB/s | 496.0 MB/s | + 129 %
i7 7500U | ✓ | 213.6 MB/s | 650.9 MB/s | + 204 %
Cortex A53s | ⁿ/ₐ | 46.8 MB/s | 44.3 MB/s | - 5 %²

¹ Not every intel CPU supports AES-NI. Astonishingly, the M430 without AES-NI sees a gain just by using the probably more intel-optimized `evp_*` implementation (MMX, SSE?).

² The Raspberry Pi 3B's CPU does not come with any AES hardware acceleration which results in an expectable, light but observable drop due to the more complicated `evp_*` setup.

**Comment by Logan007** [comment]
By re-using the `EVP_CIPHER_CTX` (setup once – one each for encryption and decryption, reset after use – not freeing, re-use), I see another gain. For example, it comes to 666.6 MB/s (before: 650.9 MB/s) on that i7 7500U. But that's just gravy and shall not clutter the current PR.

**Comment by emanuele-f** [comment]
Can you check if reusing the `EVP_CIPHER_CTX` produces an improvement in the Cortex A53s performance?

**Comment by Logan007** [comment]
Indeed, reusing the context gives back some of the lost performance. I found the following (no compiler optimizations):

CPU | AES Hw | `AES_encrypt_*` | `evp_*` | reusing `CTX` | Gain
:--|:--:|--:|--:|--:|--:
Cortex A53s | ⁿ/ₐ | 46.8 MB/s | 44.3 MB/s | 45.2 MB/s | - ~~5.3~~ 3.6 %

Allowing for compiler optimizations `-O3` melts down the relative difference somewhat more:

CPU | AES Hw | `AES_encrypt_*` | `evp_*` | reusing `CTX` | Gain
:--|:--:|--:|--:|--:|--:
Cortex A53s | ⁿ/ₐ | 49.7 MB/s | 47.4 MB/s | 48.4 MB/s | - ~~4.6~~ 2.6 %

Given that relatively small performance loss, I would propose to also implement reusing the `EVP_CIPHER_CTX` anyway. And there is a good reason for it: The ARM Cortex A53s and others have the [ability](https://en.wikipedia.org/wiki/AES_instruction_set#Hardware_acceleration_in_other_architectures) to  come with hardware AES acceleration if the manufacturer licensed it. Unfortunately, neither Raspberry Pi 3B nor – to the best of my knowledge – the other Raspberry Pi models do not have it built in; probably a question related to price, anticipated purpose and value.

So, you might very well find a lot ARM devices that offer hardware acceleration, maybe even mobiles. A platform-dependent compile would not be able to safely discriminate between ARM with and without AES hardware acceleration. That's why I suggest to unconditionally use the `evp_*` version including reuse of `EVP_CIPHER_CTX`.

What do you think? Shall I push it into the pull request? Or make it a separate one that builds on the current one? Let me know.

_P. S._  Just for the sake of completeness, I have run the missing numbers for that i7 7500U CPU (without compiler optimizations):

CPU | AES Hw | `AES_encrypt_*` | `evp_*` | reusing `CTX` | Gain
:--|:--:|--:|--:|--:|--:
i7 7500U | ✓ | 213.6 MB/s | 650.9 MB/s | 666.6 MB/s | + ~~205~~ 212 %

Using `-O3`:
CPU | AES Hw | `AES_encrypt_*` | `evp_*` | reusing `CTX` | Gain
:--|:--:|--:|--:|--:|--:
i7 7500U | ✓ | 222.5 MB/s | 734.9 MB/s | 745.8 MB/s | + ~~230~~ 235 %

All platforms are 64-bit, measurements were taken using 64-bit Linux OS and a 64-bit compile – yes, also on Raspberry.

**Comment by emanuele-f** [comment]
Please add the context reuse to the PR in order to limit the impact on the ARM platform.

**Comment by Logan007** [comment]
Done. 

I have decided to better put the context setup in the init function than in the key setup because the context could even survive a key change.
