### ISSUE TITLE
Compiler Optimizations

### ISSUE THREAD

**Issue by Logan007** [ntop/n2n#216]
Is there a specific reason for which compiler optimizations are commented (and thus disabled) in the makefile even in the stable release?

I had some `tools/n2n-benchmark` run (best of three) and found that compiler optimizations proved to be quite useful. The `null` transform as well as `Twofish` relatively profit the most while `AES` shows a more flat slope as it basically depends on openssl's performance.

Evaluation of the following benchmark results suggests using `-O3`. Surprisingly, `-march=native` seems less helpful than expected. I will  bring up a corresponding pull request.

#### Cortex-A53 (Raspberry Pi 3B )

null | --- | -O1 | -O2 | -O3 | -Ofast
:--:|:--:|:--:|:--:|:--:|:--:
| --- | 479.1 MB/s | 709.8 MB/s | 887.5 MB/s | 1059.5 MB/s | 1058.8 MB/s
| -march=native | 479.1 MB/s | 698.3 MB/s | 886.9 MB/s | 1054.7 MB/s | 1059.0 MB/s

TF | --- | -O1 | -O2 | -O3 | -Ofast
:--:|:--:|:--:|:--:|:--:|:--:
| --- | 2.6 MB/s | 6.5 MB/s | 23.3 MB/s | 27.6 MB/s | 27.6 MB/s
| -march=native | 2.6 MB/s | 6.3 MB/s | 23.3 MB/s | 27.6 MB/s | 27.6 MB/s

AES¹ | --- | -O1 | -O2 | -O3 | -Ofast
:--:|:--:|:--:|:--:|:--:|:--:
| --- | 46.7 MB/s | 48.2 MB/s | 49.5 MB/s | 49.4 MB/s | 49.7 MB/s
| -march=native | 46.9 MB/s | 47.5 MB/s | 49.5 MB/s | 49.2 MB/s | 49.3 MB/s

#### i7 7500U

null | --- | -O1 | -O2 | -O3 | -Ofast
:--:|:--:|:--:|:--:|:--:|:--:
| --- | 3458.1 MB/s | 5499.4 MB/s | 6697.3 MB/s | 7960.4 MB/s | 7959.5 MB/s
| -march=native | 3169.0 MB/s | 5373.5 MB/s | 6877.9 MB/s | 7878.5 MB/s | 7459.9 MB/s

TF | --- | -O1 | -O2 | -O3 | -Ofast
:--:|:--:|:--:|:--:|:--:|:--:
| --- | 20.5 MB/s | 44.4 MB/s | 104.9 MB/s | 117.1 MB/s | 117.0 MB/s
| -march=native | 20.4 MB/s | 47.5 MB/s | 106.7 MB/s | 119.2 MB/s | 119.1 MB/s

AES¹ | --- | -O1 | -O2 | -O3 | -Ofast
:--:|:--:|:--:|:--:|:--:|:--:
| --- | 213.4 MB/s | 219.8 MB/s | 221.5 MB/s | 222.5 MB/s | 221.6 MB/s
| -march=native | 213.9 MB/s | 219.9 MB/s | 221.8 MB/s | 222.7 MB/s | 222.1 MB/s

¹ using `AES_encrypt_*` as in current `dev` branch.

**Comment by Logan007** [comment]
_P. S._ The `-O3` compiler optimization applied to the version that uses openssl's `evp_*` (#214) delivers **734.9 MB/s** AES throughput on i7 7500U CPU. I am extremely amazed about this potential – it is roughly **3.5 times** as fast!

**Comment by emanuele-f** [comment]
In general, adding optimizations reduces the ability to debug crashes and increases executable size. However, these are not issues with n2n so let's add the optimizations. Here are the results on my i3:

```
[null]
Run enc[transop_null] for 3s (512 bytes):   	    10703503 packets	  3567.8 Kpps	  1826.7 MB/s
Run enc[transop_twofish] for 3s (512 bytes):   	       57722 packets	    19.2 Kpps	     9.9 MB/s
Run enc[transop_aes] for 3s (512 bytes):   	      670142 packets	   223.4 Kpps	   114.4 MB/s
edge executable size: 404K

[-O2]
Run enc[transop_null] for 3s (512 bytes):   	    22187160 packets	  7395.7 Kpps	  3786.6 MB/s
Run enc[transop_twofish] for 3s (512 bytes):   	      349778 packets	   116.6 Kpps	    59.7 MB/s
Run enc[transop_aes] for 3s (512 bytes):   	      695034 packets	   231.7 Kpps	   118.6 MB/s
edge executable size: 588K

[-O3]
Run enc[transop_null] for 3s (512 bytes):   	    25614233 packets	  8538.1 Kpps	  4371.5 MB/s
Run enc[transop_twofish] for 3s (512 bytes):   	      366480 packets	   122.2 Kpps	    62.5 MB/s
Run enc[transop_aes] for 3s (512 bytes):   	      699392 packets	   233.1 Kpps	   119.4 MB/s
edge executable size: 672K
```
