### ISSUE TITLE
HighAvailability support?

### ISSUE THREAD

**Issue by chennqqi** [ntop/n2n#22]
When the single supernode down, the whole node for n2n would down.

**Comment by lucaderi** [comment]
Are you suggesting to use multiple supernodes perhaps?

**Comment by chennqqi** [comment]
yeah, multiple supernodes. And both of each sync infomation togather.

**Comment by dinopio** [comment]
n2n edge supports connecting to 2 superndes only
when i tested it does not share info from one supernode to the other

how do you connect 2 supernodes together in order have a fallback?

**Comment by chennqqi** [comment]
like master-slave mode?

**Comment by csheely** [comment]
Is this the same thing as the _federated supernodes_ feature described in the n2n man page?  I was just looking today to see if that feature has been implemented yet, but I guess it hasn't?

**Comment by Logan007** [comment]
Meanwhile, the federation feature has been implemented.
