### ISSUE TITLE
edge started but cant join community group

### ISSUE THREAD

**Issue by xctest** [ntop/n2n#221]
I compile the version V2.6-Stable successfully , but when i start the edge, the output log says : edge started and no more log . 
It seems the edge blocks in joining the community group . 
Other edge nodes can find me through nmap command, but they cant ping me .
I am on Windows 10 x64 .

So what's the problem, is something wrong ?

**Comment by emanuele-f** [comment]
Can you successfully ping other hosts from the windows host? Please try to temporary disable the windows firewall as it could block the ping requests. You can also specificy the `-v` option to increase the verbosity level.

**Comment by xctest** [comment]
@emanuele-f thank you, yes, I can ping other nodes successfully , and they can ping me after I close the firewall.
Does n2n can automatically find idle port and open it for communication, otherwise I had to close firewall on every user's machine.....

**Comment by emanuele-f** [comment]
You can just allow ICMP requests in the firewall via a specific rule without disabling it all together

**Comment by xctest** [comment]
@emanuele-f OK got it,  I will try , thanks a lot !
