### ISSUE TITLE
Cant compile n2n on Mac Catalina (10.15.4)

### ISSUE THREAD

**Issue by xctest** [ntop/n2n#222]
I download v2.6-stable on mac catalina, but when i use cmake to compile the source , I got the error :
"ld: cannot link directly with dylib/framework, your binary is not an allowed client of /usr/lib/libcrypto.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)"

I set the OPENSSL_ROOT_DIR to /usr/local/opt/openssl  but no use .

So Any help would be appreciate !

**Comment by emanuele-f** [comment]
On the web I've found https://forums.developer.apple.com/thread/124782 , maybe you need to install a different openssl build

**Comment by xctest** [comment]
@emanuele-f thank u very much, I will try it .
