### ISSUE TITLE
Can't the edge of n2n be placed in the bridge?

### ISSUE THREAD

**Issue by hxh616** [ntop/n2n#225]
I want the edge on both sides to make a two-layer tunnel, bridge to the br LAN, and let the br LANs on both sides form a big LAN. But it seems that the edge interface will hang when it is bridged. No matter how to restart the edge process, it is useless.

**Comment by lucaderi** [comment]
This is not currently supported at L2. n2n is a distributed architecture at L3. We could support L2 but it requires some work for adding bridge support
