### ISSUE TITLE
WARNING: Received packet with invalid community , WANING: Supernode not responding - moving to 0 of 1

### ISSUE THREAD

**Issue by MrCuiHao** [ntop/n2n#226]
hello , 
when I try to establish with the supernode in the windows10-professional version ,some machine will report the wrong infomation as follows:

_WARNING: Received packet with invalid community ,
WANING: Supernode not responding - moving to 0 of 1_

it can't ping with other edge node , but some other machine is ok, why ?

**Comment by emanuele-f** [comment]
It may depend on the n2n version, please ensure that you are using the same n2n version
