### ISSUE TITLE
Add embedded DHCP server

### ISSUE THREAD

**Issue by emanuele-f** [ntop/n2n#228]
It would be very practical if n2n had an embedded DHCP server which could be enabled via a cli option. In this way we don't have to bother configuring dnsmasq or similar

**Comment by Logan007** [comment]
Are you pondering a managed DHCP server which requires predefined MAC-IP assignments?

Or do you think more about configurationless IP assignments like APIPA oder zeroconf? In this case, an evaluation of the ARP table (IPv4) or neighborhood discovery (IPv6) could help the user to find the actual IPs assigned to the edge nodes.

**Comment by emanuele-f** [comment]
Here are the use cases:

- Using n2n to access a group of known machines (servers). In this case the known machines would need a fixed IP address whereas the volatile clients should not bother picking an unused IP address

- Using n2n to access the internet: in this case the gateway is usually the machine where the supernode is running (static IP). The volatile clients should get a dynamic IP.

So we need a simple DHCP server with the ability to specify some static IP addresses (e.g. via a simple text file to be put into the n2n options).

**Comment by emanuele-f** [comment]
This seems a good starting point: https://github.com/crossbowerbt/dhcpserver

**Comment by fengdaolong** [comment]
DHCP implementation ideas:
1. Add a command line parameter to sn to give the network segment and subnet of DHCP.
2. Each edge reports its virtual network card IP to sn, which is stored in the peer structure of sn.
3. If a DHCP function is enabled on an edge, it will ask sn to obtain an IP address, and then sn will find a non-existent IP in its peer table according to the subnet configuration and assign it to the edge.

**Comment by fengdaolong** [comment]
Regarding the content of DHCP, just add a message type.

**Comment by switch-st** [comment]
How about add DHCP feature to edge(may be a gateway edge)? This can take advantage of the DHCP function of the operating system.

**Comment by fengdaolong** [comment]
I recently used the weekend to implement this function, and I have completed the core code, and I will be able to pull requests soon.😎👏👏👏

**Comment by Logan007** [comment]
:muscle:

**Comment by lucaderi** [comment]
Implemented by https://github.com/ntop/n2n/pull/355
