### ISSUE TITLE
n2n 只支持udp吗

### ISSUE THREAD

**Issue by leezp** [ntop/n2n#234]
Does n2n only support UDP

**Comment by Logan007** [comment]
As of now, all traffic is encapsulated in UDP only – which of course can encapsulate all the other protocols and seems to support hole punching more easily.

In its previous version v1, n2n had optional http/tcp-encapsulation which seemed to be removed in v2. I am not sure about the reasons. However, ideas on bringing it back are discussed from time to time, see #144 and #131.

**Comment by leezp** [comment]
thanks

**Comment by lucaderi** [comment]
Implemented via pull request
