### ISSUE TITLE
more supernode  support

### ISSUE THREAD

**Issue by ICFlying** [ntop/n2n#24]
Dear friend ,    I hope n2n would be realized    cooperative work  among more supernode， that means different supernode will be distributed in different places to establish VPN connections across the optimized path router.

**Comment by lucaderi** [comment]
This would be a nice feature to have. You're right.

**Comment by ICFlying** [comment]
Dear friend ,Thank you for your reply. How should we plan this function?

**Comment by lucaderi** [comment]
I wish you have time to contribute with code and time to implement all this

**Comment by Logan007** [comment]
This would be a quite advanced feature. It would require a lot of prerequisites to be met and questions to be clarified beforehand:

- How do the supernodes get aware of each other? Do they get hints via file or cli at startup? Or should they get hints from the edgenodes that register to multiple supernodes and thus can forward their supernode list received and maintained so far? That should be the preferred way as it might make sure that information is legit.
- What entity should be able to generate and maintain the supernode list? Maybe not the supernodes but the edges would need to perform this additional task; supernodes should only forward the (continiously updated) information.
- This feature definitely requires the implementation of some routing protocol such as IS-IS as there is a need for a distributed list of edgenodes. Not an easy task...
- What would be the criteria for routing metric? Throughput? Ping? Reliability? Predefined? The supernodes (or the edgenodes that maintain and generate the supernode list) would need to map the n2n-network for it, another additional task that is not easy to implement.
- Is it safe to unencryptedly forward routing information between edgenodes and supernodes and also between supernodes? Shouldn't there be implemented a supernode authentication/verification first?

Of course, redundancy is good to have (also see Master-Slave-feature - routing with the right metric could take care of this). But with a view to the estimated pile of work, absolutely not coming to light so soon - just my 2 cents.

EDIT: Routing can be a bitch, especially if you need to take care of boundary conditions such as "one way directly, other way through a UDP stanced NAT hole. The B.A.T.M.A.N-adv project offers a nice scenario overview: https://www.open-mesh.org/projects/open-mesh/wiki/Routing_scenarios .

**Comment by bmullan** [comment]
Just found out about n2n while researching Mesh VPNs.

My Use-Case seems to be a good fit for a "multi-supernode" capability.
My project uses LXD Containers to create a multi-tenant, multi-node, multi-cloud/hybrid environment

LXD containers are "system" containers versus Docker containers which are "process" or application containers.

An LXD container runs a full linux distro and has an init, systemd etc.   Each LXD container just shares the Kernel of the LXD container's Host/Server.

This diagram I hope explains how I think a **Federated SuperNode** (ie Multi-SuperNode) capability could facilitate what I am doing.

So far I have a couple working options that implement this diagram:

- a different full-mesh VPN open-source tool
- a VXLAN/OVS/IPSec configuration

I saw where in N2N v2.x there is now something called Federated SuperNode's but I've yet to find any documentation about **how to configure** them or how the **_edge_** nodes use them?   

_**Is there any documentation somewhere on Federated SuperNodes?**_ 

But the following Diagram could be enabled by N2N and make the whole design quite a bit simpler.

**Click on the Diagram to enlarge it.**

![Overview Diagram - n2n w multiple supernode vpn](https://user-images.githubusercontent.com/1682855/69510048-3f56d900-0f09-11ea-8e0e-e7d69be6d926.png)

**Comment by emanuele-f** [comment]
Supernodes federation is not currently implemeted. However it should be equivalent to the current setup from the edge nodes point of view.

**Comment by bmullan** [comment]
Okay I'd already seen a comment to that effect more or less but what does
that actually mean in separate questions:

Example for say Two SuperNode's....

Does their */etc/n2n/supernode.conf* files need to container what new?

Something like the following?


> $ *more /etc/n2n/supernode.conf*
> #
> #        The configuration file is similar to the command line, with one
> option per line. An equal
> #        sign '=' should be used between key and value. Example: -l=7777
> or --local-port=7777
> #        This file contains a basic configuration example, please refer to
> the help (-h) for the full
> #        list of available options.
> #
> #       -l|--local-port
> #        Sets the UDP listening port.
> #
> *-l=7777*    # the default Port for single default SuperNode
> *-l=192.168.122.36:7777 <http://192.168.122.36:7777>*     # a 2nd entry
> with IP of the *"other" SuperNode* & its Port Number ??
>

then also

Starting the SuperNode do I still use *only* use:

$ *sudo systemctl start supernode*
>

or *do I have to add something like the start of the Edge Node's command
line also* like the
options:

*-c   -k  -a  -l *

*Or is there an example that someone can provide that shows:*

configuration file /etc/n2n/supernode.conf  for 2 SuperNodes
and
related CLI commands to start BOTH SuperNodes

thanks
Brian

**Comment by bmullan** [comment]
Okay I'd already seen a comment to that effect more or less but what does
that actually mean in separate questions:

Example for say Two SuperNode's....

Does their **/etc/n2n/supernode.conf** files need to contain anything new?

Something like the following?

> $ *more /etc/n2n/supernode.conf*
> \#
> \#        The configuration file is similar to the command line, with one
> option per line. An equal
> \#        sign '=' should be used between key and value. Example: -l=7777
> or --local-port=7777
> \#        This file contains a basic configuration example, please refer to
> the help (-h) for the full
> \#        list of available options.
> \#
> \#       -l|--local-port
> \#        Sets the UDP listening port.
> \#
> **-l=7777**         # the default Port for single default SuperNode
> **-l=192.168.122.36:7777**     # a 2nd entry
> with IP of the *other SuperNode* & its Port Number ??
>

then also

Starting the SuperNode do I still use **only** use:

$ **sudo systemctl start supernode**

or 
**do I have to add something like the start of the Edge Node's command line** that also adds some of the edge cli options:

*-c   -k  -a  -l*

**Or is there an example that someone can provide that shows:**

configuration file /etc/n2n/supernode.conf  for 2 SuperNodes
and
related CLI commands to start BOTH SuperNodes

thanks
Brian

**Comment by emanuele-f** [comment]
First of all, currently supernodes cannot talk to each other, so you cannot configure a supernode to connect to other supernodes in the configuration.

Currently starting multiple supernode systemd services on the same computer is not supported. If you need this functionality please open a separate issue. However you can start two different supernodes from the command line by running them on a different port:

```
# Terminal 1
supernode -l 1234

# Terminal 2
supernode -l 4567
```

You can then specify the supernode in the edges command line via the `-l` parameter, e.g. `-l 127.0.0.1:1234`. What you can currently do is to tell an edge node to connect to multiple supernodes. How it works right now is that if a supernode becomes unavailable, then the nedge node will try the next one round-robin. You can do this by specifying multiple `-l` parameters on the nedge command line, e.g. `-l 127.0.0.1:1234 -l 127.0.0.1:4567`

**Comment by bmullan** [comment]
@emanuele-f  

Regarding Federated SuperNodes...   I know now that they are not yet ready but from some of the comments of the N2N developers about the complexity of implementing it I thought perhaps it might be useful to look on GitHub at how other Mesh VPNs have done it.

Note... I am  not advocating any of these but just mentioning a couple I found so far to see if they might give N2N some ideas.

Some use DHT
Some use a distributed file system
Some use a distributed MySQL database of connection info
etc

One Mesh VPN uses **[IPFS](https://ipfs.io/#how)**.

I'd never heard of **IPFS** so I googled it and IPFS is really a cool technology:

In **that** Mesh VPN they say they use IPFS for:

>     It's used as:
>     Node discovery (using their DHT).
>     Fallback connector (when it's impossible to connect nodes directly).
>     STUN-replacement (tools to pass-trough a NAT).
>     Messenger (to send notification among nodes).

If you read about IPFS it seems a great fit for a Mesh VPN that could use an HA type of shared File for configuration information.

Another question ... does N2N operate at L3 only?

Brian

**Comment by emanuele-f** [comment]
Thank you for the links. Please note that n2n operates at the L2 level (ethernet), it uses standard linux TAP interfaces.

**Comment by yanggis** [comment]
@emanuele-f 
Hi one more supplement, AFAIK, n2n supports only supernodes; if you configure more two supernodes, for instance:
-l 1.1.1.1:1234 -l 2.2.2.2:4567 -l 3.3.3.3:5678
you will get a warning "too many supernodes".

In fact, two supernodes are not enough in reality; more improvements are required to support multiple supernodes.

**Comment by Akuna-Tarata** [comment]
What about the snm-project of "lukablurr" at
https://github.com/lukablurr/n2n_v2_fork
This was working with multiple supernodes. I used it 8 years bevore.
Maybee a talented coder can merged it into the actual code

**Comment by emanuele-f** [comment]
Extending the supernodes limitation from 2 to 8 is feasible but, currently, without practical use. As explained in #45, having more supernodes does not currently improve the network reliability. Also, supernodes do not talk to each other, this is something that should be fixed.

**Comment by Akuna-Tarata** [comment]
@emanuele-f

> having more supernodes does not currently improve the network reliability

Yes it does. 
And there is a load balancing between supernodes, too

> Also, supernodes do not talk to each other, this is something that should be fixed.

This was already fixed - Look at my link ;)
Costin Lupu explained everything in his paper.

**Comment by emanuele-f** [comment]
A link would be helpful in such case (https://github.com/lukablurr/n2n_v2_fork/blob/master/doc/multiple-supernodes.pdf). I'll check it.

**Comment by Logan007** [comment]
First look in the paper indicates an interesting apporach!

Yet I am a bit concerned about the possiblility of Denial of Service attacks due to unencrypted and unauthenticated communication between supernodes: A malicious supernode could just send out rubbish-advertisements for given and known communities.

Some (not too heavy) encryption of supernode-related parts of traffic could help. That would include the [header](https://github.com/ntop/n2n/issues/198) (so far, it is unencrypted because the supernode needs MACs and community for being able to forward) but also the registration, acknowledging, ... . Wouldn't the/a community name itself  make a feasible key as it is already known by the supernode? In a multi-community environment however, the supernode would have to check them all...

It might be better that the edges maintain the supernode list to forward them to their peer edge nodes. That way, new supernodes can only get into system and propagated via an already well known and trusted peer edge node (which shares the same key). Maybe less flexible but more trustful.

P. S. Why do the supernodes need to know about each other? Just for (public) advertisement? To narrow the view a bit, it's the _edges_ that need to know about the supernodes.

**Comment by emanuele-f** [comment]
I'd focus on the network availability problem, putting apart the optimized path problem for now. For more complex models we should totally rethink n2n as the distributed hash tables is probably the way to go (as suggested in the pdf above). In order to detect the slow/down supernodes we can send a "ping" n2n message to the supernodes, which would allow us also to measure the RTT so that we can choose the nearest supernode for sending a direct packet (this may not be the optimal path but is ok for now). For now we don't want supernodes to talk to each other as this would require auth and encryption as explained, let's focus on the edge nodes instead. For simplicity we can make all the edge nodes register to all the supernodes and assume that the edge nodes must be configured to have the same supernodes (`-l` option). It may happen that an edge node A can talk to supernode S1 but edge B cannot talk to S1. Edge node A should be able to ping edge node B and realize that it is only available through edge node S2. There are some choices to be made, e.g. if broadcast traffic (e.g. ARP requests) should be send only to the nearest supernode or to all the supernodes (this would generate a lot of traffic to the edge nodes).

**Comment by Logan007** [comment]
Meanwhile, the federation feature has been implemented.

**Comment by sweihub** [comment]
Hello,

What is the multiple-supernode status?
I cannot get the n2n v3 to work with two supernodes
1. I setup multiple edge nodes with two supernodes
2. After 24 hours, some of the edge nodes cannot connect to each other
3. I restart the edge nodes with single supernode, problem solved.

The multiple supernodes dose not improve the redundancy yet.
