### ISSUE TITLE
Compile error on Windows OS

### ISSUE THREAD

**Issue by skyformat99** [ntop/n2n#241]
error:
edge.c(751): error C2065: 'term_handler': undeclared identifier
sn.c(1023): error C2065: 'term_handler': undeclared identifier

The cause of the problem:

**#ifdef __linux__**
#ifdef WIN32
BOOL WINAPI term_handler(DWORD sig)
#else
static void term_handler(int sig)
#endif
{
 。。。。。。。。。。。
。。。。。。。。。。。
}
**#endif**

The bold text is superfluous.

**Comment by lucktu** [comment]
If you still haven't compiled it, you can download it here:
https://github.com/lucktu/n2n

**Comment by skyformat99** [comment]
this is bug

**Comment by emanuele-f** [comment]
Fixed in a014f5a68bf7243abd2cc95388ff036b127cd0e9 . Thank you for reporting.
