### ISSUE TITLE
Windows cannot compile

### ISSUE THREAD

**Issue by moshengrenzenme** [ntop/n2n#25]
I've tried a lot of ways, but I've failed.vs2008，vs2010，msys,msys2,cmake-gui,mingw32，"struct stat " error

**Comment by lucaderi** [comment]
Can you please report the exact error and how you compile it? Thanks

**Comment by moshengrenzenme** [comment]
In the 41 line of edge.c, the reason is that Windows has no <sys/stat.h> header, and cmake on windows is difficult to find OpenSSL, so I failed to use Visual Studio 2008 to compile

**Comment by littleplus** [comment]
* cmake 3.12.2
* Visual Studio 2017
* Windows 7 x64
* OpenSSL 1.0.2L

after use cmake 3.12 build the sln, I still could not compile it. Visual Studio 2017
```
cl : Command line error D8021: invalid numeric argument '/Wshadow'
```

Besides, Could I ask for a prebuilt n2n edge client?

**Comment by danrobbo** [comment]
> In the 41 line of edge.c, the reason is that Windows has no <sys/stat.h> header, and cmake on windows is difficult to find OpenSSL, so I failed to use Visual Studio 2008 to compile。
> cmake（msys64）：
> -- Configuring done
> CMake Error at win32/CMakeLists.txt:1 (add_library):
> Cannot find source file:
> 
> ```
> win32/getopt1.c
> win32/wintap.c
> ```
> win32/getopt.c
> Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
> .hxx .in .txx
> After removing win32, it will be wrong

This issue was resolved in https://github.com/ntop/n2n/pull/26

**Comment by emanuele-f** [comment]
Please also check out #66
