### ISSUE TITLE
[windows] compilation error in 2.7(latest) source code 

### ISSUE THREAD

**Issue by 244849530** [ntop/n2n#251]
When I compile using the latest version of the source code, I get the following error:

“C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\n2n-dev\build\edge.vcxproj”(Build target) (1) ->
“C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\n2n-dev\build\n2n.vcxproj”(default target) (3) ->
(ClCompile target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\n2n-dev\edge_utils.c(57,8): error C2065: “LZO1X_1_MEM_COMPRESS”: Undeclared identifier [C:\Program F
iles (x86)\Microsoft Visual Studio\2019\BuildTools\n2n-dev\build\n2n.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\n2n-dev\edge_utils.c(57,8): error C2057: Constant expression should be entered [C:\Program Files (x86)\Microsoft Vi
sual Studio\2019\BuildTools\n2n-dev\build\n2n.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\n2n-dev\edge_utils.c(57,8): error C2466: Cannot allocate an array of constant size 0 [C:\Program Files (x86)\Micro
soft Visual Studio\2019\BuildTools\n2n-dev\build\n2n.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\n2n-dev\edge_utils.c(57,48): error C2133: “wrkmem”: Unknown size [C:\Program Files (x86)\Micr
osoft Visual Studio\2019\BuildTools\n2n-dev\build\n2n.vcxproj]

System: Windows 10
Compile Tool:Visual Studio 2019 build tools (use Visual Studio 2017 will get the same error)

In the same enviroment,the stable release can be successfully compiled.

**Comment by Logan007** [comment]
Disclaimer: I am absolutely not a Windows expert... but you could try to add a `minilzo.c` entry to the `add_library( ...)` section of the `CMakeLists.txt` file, around line 55.

**Comment by 244849530** [comment]
> Disclaimer: I am absolutely not a Windows expert... but you could try to add a `minilzo.c` entry to the `add_library( ...)` section of the `CMakeLists.txt` file, around line 55.

thanks for your help,I try to inserted the minilzo.c entry in CMakeList addlibrary(...), but still get the same error.
It seems that edge_utils.c cannot get definition from minilzo.h.

**Comment by 244849530** [comment]
> Disclaimer: I am absolutely not a Windows expert... but you could try to add a `minilzo.c` entry to the `add_library( ...)` section of the `CMakeLists.txt` file, around line 55.

thanks for your help,I try to insert the minilzo.c entry in CMakeList addlibrary(...), but still get the same error.
It seems that edge_utils.c cannot get definition from minilzo.h.

**Comment by 244849530** [comment]
> Disclaimer: I am absolutely not a Windows expert... but you could try to add a `minilzo.c` entry to the `add_library( ...)` section of the `CMakeLists.txt` file, around line 55.

So I added #include<minilzo.h> in edge_utils.c, which can successfully compile the source code, and then run the edge program, showing the version is 2.5.1

**Comment by 244849530** [comment]
> Disclaimer: I am absolutely not a Windows expert... but you could try to add a `minilzo.c` entry to the `add_library( ...)` section of the `CMakeLists.txt` file, around line 55.

So I added `#include<minilzo.h>` in edge_utils.c, which can successfully compile the source code, and then run the edge program, showing the version is 2.5.1

**Comment by Logan007** [comment]
Great to hear that it works for you!

 I just wonder if you really have cloned the full current dev code base  as `edge_utils.c` already should include such a [line](https://github.com/ntop/n2n/blob/3d9d3a13f7f0e4ada2c5861807ed2dce990b6a49/edge_utils.c#L20).
