### ISSUE TITLE
Cross compilation failed

### ISSUE THREAD

**Issue by small-5** [ntop/n2n#260]
After [commit](https://github.com/ntop/n2n/commit/cd62591ade98d19e20c38c7492210a3d57b60f4b) , it cannot be compiled on openwrt and must be patched to succeed.

log:
speck.c:612: more undefined references to `htole64' follow
collect2: error: ld returned 1 exit status
Makefile:80: recipe for target 'edge' failed
make[3]: *** [edge] Error 1

**Comment by small-5** [comment]
After modifying Makefile.in to compile and generate binary file, it runs on the target machine, prompting illegal instruction.

**Comment by Logan007** [comment]
The `-march=native` directive makes the compiler find out the local architecture and can enable platform-specific features such as SSE or AVX. 

But on the other hand, it interferes with cross compiling. So, it was good that you removed it.

However, _illegal instruction_ sounds like the executable was compiled for another architecture/platform anyway. Did compilation finish smoothly after commenting/removing `-march=native`? Did it create the new, i.e. non-native, executable? You might also want to take a look into the `tools/Makefile`. Also, please do not forget to `make clean` (which often happens to me) after changes to the `Makefile` and before running `make` again.

And also, I would be interested in how did you fix the seemingly missing `htole64` for your target platform? Is it MIPS or ARM?

**Comment by small-5** [comment]
Thank you for your help.
I can only compile successfully after uncommenting - March = native. The problem of illegal instructions existed before the commit, which was normal in version 2.6. If I execute supernode without any parameters, I can see the help interface, but if I add -l <port>, I will be prompted for illegal instructions. I use openwrt-sdk-19.07.3-x86-64_gcc-7.5.0_musl for cross compilation.

**Comment by small-5** [comment]
Thank you for your help.
I can only compile successfully after uncommenting -march=native. The problem of illegal instruction existed before the commit, which was normal in version 2.6. If I execute supernode without any parameters, I can see the help interface, but if I add -l <port> , I will be prompted for illegal instruction. I use openwrt-sdk-19.07.3-x86-64_gcc-7.5.0_musl for cross compilation.

**Comment by Logan007** [comment]
> I can only compile successfully after _uncommenting_ -march=native. 

If you _uncomment_, i.e.`-march=native` gets used, it will compile a binary just for use on that specific _local_ computer. If this binary gets copied to any other hardware, it will most likely produce errors such as _illegal instruction_ when run (if not compatible hardware). But, you should be able to run it on the compiling computer – which is not your aim, I know.

Just for my clarification: If you remove the `march=native` part, it should allow cross-compilation. Is that the situation when you get the errors from your first post?

What hardware is it you run openwrt on?

**Comment by small-5** [comment]
I understand what you mean. If I cross-compile directly without commenting out -march=native, it will not compile successfully. The error reported is htole64. But if I uncomment it, the compiled binary cannot be used on the target machine. In this case, the htole64 error needs to be fixed. I am using X86_64 platform as a router to run OpenWrt, the CPU is N3710.

**Comment by small-5** [comment]
I understand what you mean. If I cross-compile directly and do not uncomment -march=native, it will not compile successfully. The error reported is htole64. But if I uncomment it, the binaries cannot be used on the target machine, so need to fix the htole64 error. I use the X86_64 platform as a router running on OpenWrt, CPU is N3710.

**Comment by small-5** [comment]
I can successfully compile after using this patch, no illegal instruction is reported when running on the target machine.

[001-Fix-Compile.zip](https://github.com/ntop/n2n/files/4757146/001-Fix-Compile.zip)

**Comment by small-5** [comment]
After a simple test, it can run normally and all edges can connect and communicate normally.

**Comment by emanuele-f** [comment]
I think we should exclude the speck transop compilation while on OpenWRT

**Comment by Logan007** [comment]
I plan to polish Speck implementation somewhen during the next days anyway, especially the key-setup. While doing so, I also will replace the `htole64` & company with network-byte-order code, i.e. `hotn` & friends which seem to be more compatible as they should be Standard C. I guess it will help.

@small-5 May I count on you for testing then?

**Comment by emanuele-f** [comment]
Ok, please note that the same issue occurred in android, I've temporary disabled speck on android in https://github.com/ntop/n2n/pull/259

**Comment by small-5** [comment]
@Logan007 Ok,with pleasure.

**Comment by Logan007** [comment]
@emanuele-f yeah, I saw that. Hope to fix it with the `ntohll`... or the above mentioned link to `portable_endian.h`.

**Comment by Logan007** [comment]
@small-5 I have just added pull request #262. Would you volunteer to test that code _without_ your patch applied? Thank you! Hope is that it will fix this issue.

**Comment by small-5** [comment]
@Logan007 Thank you. I'll test and give you feedback tomorrow

**Comment by small-5** [comment]
@Logan007 After testing, it can compile successfully and run normally on the target machine.Thank you.

**Comment by Logan007** [comment]
Thank you for testing
