### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by skyformat99** [ntop/n2n#264]
1. git clone  latest version
2. cmake .    
3. make  

error message:
CMakeFiles/n2n-benchmark.dir/tools/benchmark.c.o: In function `main':
benchmark.c:(.text+0x14f): undefined reference to `n2n_transop_speck_init'
libn2n.a(edge_utils.c.o): In function `edge_init':
edge_utils.c:(.text+0x47f): undefined reference to `n2n_transop_speck_init'
collect2: error: ld returned 1 exit status

**Comment by Logan007** [comment]
I made some additions to the `CMakefile.txt` file in #265 anyway, I guess it might help with this issue, too. Does it work out for you?
