### ISSUE TITLE
Suggestions for features and version updates

### ISSUE THREAD

**Issue by yingftf** [ntop/n2n#270]
1. Fix and publish unified communication protocol as soon as possible (including reserved or to be developed fields). The advantage of this is to avoid redeployment problems caused by version upgrade.
2. For the interconnection problem of supernode, corresponding communication standards should be formulated. Routing protocol can be added in three layers, similar to OSPF protocol (or directly integrated with the protocol). Simple DHCP service capability can be added in a single region, which can better support large-scale networking; support for IPv6 optimization, such as message translation, dual stack support, etc.
3. Edge adds IPv4 and IPv6 dual stack support; adds packet read and write interface (realizes pcap similar packet processing capability, facilitates secondary development or realizes routing, packet filtering and other functions); increases the open interface calling capability of runtime status indicator and node information.
4. Optimize the field information of Hash list, add query interface, so as to develop the application of platform management layer (it is better to realize the docking of database interface); add the support of network management protocol or the module integrating edge management function.
5. Simplify a version with only basic functions, adapt to the scene of low hardware configuration of Iot device or embedded device and little data flow.
I think N2N only realizes network construction and connection. Other non essential functions open interfaces for other organizations and individuals to develop and use. With the upgrading of the network, the support of N2N for IPv6 and Iot devices and the ability of large-scale network management should be strengthened.
My English level is limited, use translation software to translate this article; hope to understand.
Thank you for your hard work.

**Comment by skyformat99** [comment]
agree

**Comment by fengdaolong** [comment]
agree

**Comment by skyformat99** [comment]
But there is one thing more, Add the TCP mode from V1  to the new code.
https://github.com/meyerd/n2n/tree/master/n2n_v1

**Comment by Logan007** [comment]
Thank you for suggestions. Meahwhile, some of the have been picked up in other discussions (IPv6, TCP), has been worked on (interconnection --> federation), or is being worked on (routing).

Optimization in terms of speed to make nn2 run on smaller hardware are under continuous consideration and always welcome.
