### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by skyformat99** [ntop/n2n#274]
1. git clone latest version       #Added missing makefile dependency
2. cmake .

**error info:**

CMake Error at CMakeLists.txt:89 (add_executable):
  Cannot find source file:

    sn.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error at CMakeLists.txt:86 (add_executable):
  Cannot find source file:

    edge.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error at CMakeLists.txt:55 (add_library):
  Cannot find source file:

    n2n.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error at CMakeLists.txt:92 (add_executable):
  Cannot find source file:

    example_edge_embed_quick_edge_init.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error at CMakeLists.txt:95 (add_executable):
  Cannot find source file:

    example_edge_embed.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error at CMakeLists.txt:98 (add_executable):
  Cannot find source file:

    example_sn_embed.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: supernode
CMake Error: Cannot determine link language for target "supernode".
CMake Error: CMake can not determine linker language for target: edge
CMake Error: Cannot determine link language for target "edge".
CMake Error: Cannot determine link language for target "n2n".
CMake Error: CMake can not determine linker language for target: n2n
CMake Error: CMake can not determine linker language for target: example_edge_embed_quick_edge_init
CMake Error: Cannot determine link language for target "example_edge_embed_quick_edge_init".
CMake Error: CMake can not determine linker language for target: example_edge_embed
CMake Error: Cannot determine link language for target "example_edge_embed".
CMake Error: CMake can not determine linker language for target: example_sn_embed
CMake Error: Cannot determine link language for target "example_sn_embed".

**Comment by Logan007** [comment]
Does it work with all the recently  applied config-related changes?

**Comment by skyformat99** [comment]
The latest version is OK.
close it.
