### ISSUE TITLE
The following error occurred in static compilation use cmake

### ISSUE THREAD

**Issue by llfj** [ntop/n2n#277]
I used cmake to build n2n ,Dynamic was ok,But static was ERROR!
N2N VERSION  2.7.0 r377
![-47a728515192392](https://user-images.githubusercontent.com/39051487/85852935-38b47b00-b7e4-11ea-8bf4-6d0c589c7855.png)
Linking C executable edge
CMakeFiles/edge.dir/src/edge.c.o：在函数‘main’中：
edge.c:(.text+0x1167): 警告：Using 'getpwnam' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
libn2n.a(edge_utils.c.o)：在函数‘supernode2addr’中：
edge_utils.c:(.text+0xe1b): 警告：Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/root/openssl/linux_x64/a/lib/libcrypto.a(b_sock.o)：在函数‘BIO_gethostbyname’中：
b_sock.c:(.text+0x51): 警告：Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
libn2n.a(edge_utils.c.o)：在函数‘handle_PACKET’中：
edge_utils.c:(.text+0x4efa)：对‘ZSTD_decompress’未定义的引用
edge_utils.c:(.text+0x4f10)：对‘ZSTD_isError’未定义的引用
edge_utils.c:(.text+0x4f24)：对‘ZSTD_getErrorName’未定义的引用
libn2n.a(edge_utils.c.o)：在函数‘send_packet2net’中：
edge_utils.c:(.text+0x75e5)：对‘ZSTD_compress’未定义的引用
edge_utils.c:(.text+0x75fb)：对‘ZSTD_isError’未定义的引用
edge_utils.c:(.text+0x762b)：对‘ZSTD_getErrorName’未定义的引用
/root/openssl/linux_x64/a/lib/libcrypto.a(dso_dlfcn.o)：在函数‘dlfcn_globallookup’中：
dso_dlfcn.c:(.text+0x11)：对‘dlopen’未定义的引用
dso_dlfcn.c:(.text+0x24)：对‘dlsym’未定义的引用
dso_dlfcn.c:(.text+0x2f)：对‘dlclose’未定义的引用
/root/openssl/linux_x64/a/lib/libcrypto.a(dso_dlfcn.o)：在函数‘dlfcn_bind_func’中：
dso_dlfcn.c:(.text+0x334)：对‘dlsym’未定义的引用
dso_dlfcn.c:(.text+0x3f2)：对‘dlerror’未定义的引用
/root/openssl/linux_x64/a/lib/libcrypto.a(dso_dlfcn.o)：在函数‘dlfcn_load’ 中：
dso_dlfcn.c:(.text+0x461)：对‘dlopen’未定义的引用
dso_dlfcn.c:(.text+0x4d9)：对‘dlclose’未定义的引用
dso_dlfcn.c:(.text+0x512)：对‘dlerror’未定义的引用
/root/openssl/linux_x64/a/lib/libcrypto.a(dso_dlfcn.o)：在函数‘dlfcn_pathbyaddr’中：
dso_dlfcn.c:(.text+0x5b1)：对‘dladdr’未定义的引用
dso_dlfcn.c:(.text+0x611)：对‘dlerror’未定义的引用
/root/openssl/linux_x64/a/lib/libcrypto.a(dso_dlfcn.o)：在函数‘dlfcn_unload ’中：
dso_dlfcn.c:(.text+0x672)：对‘dlclose’未定义的引用
collect2: 错误：ld 返回 1
make[2]: *** [edge] 错误 1
make[1]: *** [CMakeFiles/edge.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by Logan007** [comment]
Does this issue persist?

**Comment by Logan007** [comment]
Closing as versioning has progressed since then.
