### ISSUE TITLE
macOS mojave v10.14.5 can not build

### ISSUE THREAD

**Issue by jonahzheng** [ntop/n2n#278]
gcc -g -O2 -I/usr/local/opt/openssl@1.1/include -I ./include      src/edge.c -L/usr/local/opt/openssl@1.1/lib/ libn2n.a  -o edge
src/edge.c:875:40: warning: implicit declaration of function 'OpenSSL_version'
      is invalid in C99 [-Wimplicit-function-declaration]
  traceEvent(TRACE_NORMAL, "Using %s", OpenSSL_version(0));
                                       ^
1 warning generated.
Undefined symbols for architecture x86_64:
  "_BIO_ctrl", referenced from:
      _openssl_err_as_string in libn2n.a(transform_cc20.o)
  "_BIO_free", referenced from:
      _openssl_err_as_string in libn2n.a(transform_cc20.o)
  "_BIO_new", referenced from:
      _openssl_err_as_string in libn2n.a(transform_cc20.o)
  "_BIO_s_mem", referenced from:
      _openssl_err_as_string in libn2n.a(transform_cc20.o)
  "_ERR_print_errors", referenced from:
      _openssl_err_as_string in libn2n.a(transform_cc20.o)
  "_EVP_CIPHER_CTX_free", referenced from:
      _transop_deinit_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_CIPHER_CTX_new", referenced from:
      _n2n_transop_cc20_init in libn2n.a(transform_cc20.o)
  "_EVP_CIPHER_CTX_reset", referenced from:
      _transop_encode_cc20 in libn2n.a(transform_cc20.o)
      _transop_decode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_CIPHER_CTX_set_padding", referenced from:
      _transop_encode_cc20 in libn2n.a(transform_cc20.o)
      _transop_decode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_DecryptFinal_ex", referenced from:
      _transop_decode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_DecryptInit_ex", referenced from:
      _transop_decode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_DecryptUpdate", referenced from:
      _transop_decode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_EncryptFinal_ex", referenced from:
      _transop_encode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_EncryptInit_ex", referenced from:
      _transop_encode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_EncryptUpdate", referenced from:
      _transop_encode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_chacha20", referenced from:
      _n2n_transop_cc20_init in libn2n.a(transform_cc20.o)
  "_OpenSSL_version", referenced from:
      _main in edge-909c46.o
  "_SHA256", referenced from:
      _n2n_transop_cc20_init in libn2n.a(transform_cc20.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [edge] Error 1

**Comment by lucaderi** [comment]
Can you post everything: configure and make logs please?

**Comment by jonahzheng** [comment]
$git clone https://github.com/ntop/n2n.git
$./autogen.sh
$./configure
$make
`gcc -g -O2 -I/usr/local/opt/openssl@1.1/include -I ./include      src/edge.c -L/usr/local/opt/openssl@1.1/lib/ libn2n.a  -o edge
src/edge.c:875:40: warning: implicit declaration of function 'OpenSSL_version' is invalid in C99
      [-Wimplicit-function-declaration]
  traceEvent(TRACE_NORMAL, "Using %s", OpenSSL_version(0));
                                       ^
1 warning generated.
Undefined symbols for architecture x86_64:
  "_BIO_ctrl", referenced from:
      _openssl_err_as_string in libn2n.a(transform_cc20.o)
  "_BIO_free", referenced from:
      _openssl_err_as_string in libn2n.a(transform_cc20.o)
  "_BIO_new", referenced from:
      _openssl_err_as_string in libn2n.a(transform_cc20.o)
  "_BIO_s_mem", referenced from:
      _openssl_err_as_string in libn2n.a(transform_cc20.o)
  "_ERR_print_errors", referenced from:
      _openssl_err_as_string in libn2n.a(transform_cc20.o)
  "_EVP_CIPHER_CTX_free", referenced from:
      _transop_deinit_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_CIPHER_CTX_new", referenced from:
      _n2n_transop_cc20_init in libn2n.a(transform_cc20.o)
  "_EVP_CIPHER_CTX_reset", referenced from:
      _transop_encode_cc20 in libn2n.a(transform_cc20.o)
      _transop_decode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_CIPHER_CTX_set_padding", referenced from:
      _transop_encode_cc20 in libn2n.a(transform_cc20.o)
      _transop_decode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_DecryptFinal_ex", referenced from:
      _transop_decode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_DecryptInit_ex", referenced from:
      _transop_decode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_DecryptUpdate", referenced from:
      _transop_decode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_EncryptFinal_ex", referenced from:
      _transop_encode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_EncryptInit_ex", referenced from:
      _transop_encode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_EncryptUpdate", referenced from:
      _transop_encode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_chacha20", referenced from:
      _n2n_transop_cc20_init in libn2n.a(transform_cc20.o)
  "_OpenSSL_version", referenced from:
      _main in edge-8a4430.o
  "_SHA256", referenced from:
      _n2n_transop_cc20_init in libn2n.a(transform_cc20.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [edge] Error 1`

**Comment by lucaderi** [comment]
Can you please check
$ ls -l /usr/local/opt/openssl@1.1
0 lrwxr-xr-x  1 deri  admin  28 Apr 24 00:04 /usr/local/opt/openssl@1.1@ -> ../Cellar/openssl@1.1/1.1.1g

and if you have an older version upgrade openssl 1.1 please?

**Comment by jonahzheng** [comment]
thank you, the same to you.

lvzx% ls -l /usr/local/opt/openssl@1.1
lrwxr-xr-x  1 lvzx  admin  28  6 29 16:52 /usr/local/opt/openssl@1.1 -> ../Cellar/openssl@1.1/1.1.1g
lvzx% ls -l /usr/local/opt/openssl    
lrwxr-xr-x  1 lvzx  admin  28  6 29 16:52 /usr/local/opt/openssl -> ../Cellar/openssl@1.1/1.1.1g
lvzx%

**Comment by yermulnik** [comment]
I'm having exactly the same issue on `macOS Catalina 10.15.5 19F101 x86_64` as @jonahzheng
```
> brew info openssl
openssl@1.1: stable 1.1.1g (bottled) [keg-only]
Cryptography and SSL/TLS Toolkit
https://openssl.org/
/usr/local/Cellar/openssl@1.1/1.1.1g (8,059 files, 18MB)
  Poured from bottle on 2020-07-03 at 23:46:37
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/openssl@1.1.rb
[…]
```
Any clue would be appreciated. Thanks in advance.

**Comment by yermulnik** [comment]
Here's the full output from `make`:
```
> make
gcc -g -O2 -I/usr/local/opt/openssl@1.1/include -I ./include -I/usr/local/Cellar/openssl@1.1/1.1.1g/include      -I/usr/local/opt/openssl@1.1/include  -c -o src/edge.o src/edge.c
src/edge.c:855:40: warning: implicit declaration of function 'OpenSSL_version' is invalid in C99
      [-Wimplicit-function-declaration]
  traceEvent(TRACE_NORMAL, "Using %s", OpenSSL_version(0));
                                       ^
1 warning generated.
gcc -g -O2 -I/usr/local/opt/openssl@1.1/include -I ./include -I/usr/local/Cellar/openssl@1.1/1.1.1g/include      -I/usr/local/opt/openssl@1.1/include  -c -o src/edge_utils.o src/edge_utils.c
gcc -g -O2 -I/usr/local/opt/openssl@1.1/include -I ./include -I/usr/local/Cellar/openssl@1.1/1.1.1g/include      -I/usr/local/opt/openssl@1.1/include  -c -o src/edge_utils_win32.o src/edge_utils_win32.c
gcc -g -O2 -I/usr/local/opt/openssl@1.1/include -I ./include -I/usr/local/Cellar/openssl@1.1/1.1.1g/include      -I/usr/local/opt/openssl@1.1/include  -c -o src/example_edge_embed.o src/example_edge_embed.c
gcc -g -O2 -I/usr/local/opt/openssl@1.1/include -I ./include -I/usr/local/Cellar/openssl@1.1/1.1.1g/include      -I/usr/local/opt/openssl@1.1/include  -c -o src/example_edge_embed_quick_edge_init.o src/example_edge_embed_quick_edge_init.c
gcc -g -O2 -I/usr/local/opt/openssl@1.1/include -I ./include -I/usr/local/Cellar/openssl@1.1/1.1.1g/include      -I/usr/local/opt/openssl@1.1/include  -c -o src/example_sn_embed.o src/example_sn_embed.c
gcc -g -O2 -I/usr/local/opt/openssl@1.1/include -I ./include -I/usr/local/Cellar/openssl@1.1/1.1.1g/include      -I/usr/local/opt/openssl@1.1/include  -c -o src/header_encryption.o src/header_encryption.c
gcc -g -O2 -I/usr/local/opt/openssl@1.1/include -I ./include -I/usr/local/Cellar/openssl@1.1/1.1.1g/include      -I/usr/local/opt/openssl@1.1/include  -c -o src/minilzo.o src/minilzo.c
gcc -g -O2 -I/usr/local/opt/openssl@1.1/include -I ./include -I/usr/local/Cellar/openssl@1.1/1.1.1g/include      -I/usr/local/opt/openssl@1.1/include  -c -o src/n2n.o src/n2n.c
gcc -g -O2 -I/usr/local/opt/openssl@1.1/include -I ./include -I/usr/local/Cellar/openssl@1.1/1.1.1g/include      -I/usr/local/opt/openssl@1.1/include  -c -o src/pearson.o src/pearson.c
gcc -g -O2 -I/usr/local/opt/openssl@1.1/include -I ./include -I/usr/local/Cellar/openssl@1.1/1.1.1g/include      -I/usr/local/opt/openssl@1.1/include  -c -o src/random_numbers.o src/random_numbers.c
gcc -g -O2 -I/usr/local/opt/openssl@1.1/include -I ./include -I/usr/local/Cellar/openssl@1.1/1.1.1g/include      -I/usr/local/opt/openssl@1.1/include  -c -o src/sn.o src/sn.c
gcc -g -O2 -I/usr/local/opt/openssl@1.1/include -I ./include -I/usr/local/Cellar/openssl@1.1/1.1.1g/include      -I/usr/local/opt/openssl@1.1/include  -c -o src/sn_utils.o src/sn_utils.c
gcc -g -O2 -I/usr/local/opt/openssl@1.1/include -I ./include -I/usr/local/Cellar/openssl@1.1/1.1.1g/include      -I/usr/local/opt/openssl@1.1/include  -c -o src/speck.o src/speck.c
gcc -g -O2 -I/usr/local/opt/openssl@1.1/include -I ./include -I/usr/local/Cellar/openssl@1.1/1.1.1g/include      -I/usr/local/opt/openssl@1.1/include  -c -o src/transform_aes.o src/transform_aes.c
gcc -g -O2 -I/usr/local/opt/openssl@1.1/include -I ./include -I/usr/local/Cellar/openssl@1.1/1.1.1g/include      -I/usr/local/opt/openssl@1.1/include  -c -o src/transform_cc20.o src/transform_cc20.c
gcc -g -O2 -I/usr/local/opt/openssl@1.1/include -I ./include -I/usr/local/Cellar/openssl@1.1/1.1.1g/include      -I/usr/local/opt/openssl@1.1/include  -c -o src/transform_null.o src/transform_null.c
gcc -g -O2 -I/usr/local/opt/openssl@1.1/include -I ./include -I/usr/local/Cellar/openssl@1.1/1.1.1g/include      -I/usr/local/opt/openssl@1.1/include  -c -o src/transform_speck.o src/transform_speck.c
gcc -g -O2 -I/usr/local/opt/openssl@1.1/include -I ./include -I/usr/local/Cellar/openssl@1.1/1.1.1g/include      -I/usr/local/opt/openssl@1.1/include  -c -o src/transform_tf.o src/transform_tf.c
gcc -g -O2 -I/usr/local/opt/openssl@1.1/include -I ./include -I/usr/local/Cellar/openssl@1.1/1.1.1g/include      -I/usr/local/opt/openssl@1.1/include  -c -o src/tuntap_freebsd.o src/tuntap_freebsd.c
gcc -g -O2 -I/usr/local/opt/openssl@1.1/include -I ./include -I/usr/local/Cellar/openssl@1.1/1.1.1g/include      -I/usr/local/opt/openssl@1.1/include  -c -o src/tuntap_linux.o src/tuntap_linux.c
gcc -g -O2 -I/usr/local/opt/openssl@1.1/include -I ./include -I/usr/local/Cellar/openssl@1.1/1.1.1g/include      -I/usr/local/opt/openssl@1.1/include  -c -o src/tuntap_netbsd.o src/tuntap_netbsd.c
gcc -g -O2 -I/usr/local/opt/openssl@1.1/include -I ./include -I/usr/local/Cellar/openssl@1.1/1.1.1g/include      -I/usr/local/opt/openssl@1.1/include  -c -o src/tuntap_osx.o src/tuntap_osx.c
gcc -g -O2 -I/usr/local/opt/openssl@1.1/include -I ./include -I/usr/local/Cellar/openssl@1.1/1.1.1g/include      -I/usr/local/opt/openssl@1.1/include  -c -o src/twofish.o src/twofish.c
gcc -g -O2 -I/usr/local/opt/openssl@1.1/include -I ./include -I/usr/local/Cellar/openssl@1.1/1.1.1g/include      -I/usr/local/opt/openssl@1.1/include  -c -o src/wire.o src/wire.c
ar rcs libn2n.a  src/edge.o  src/edge_utils.o  src/edge_utils_win32.o  src/example_edge_embed.o  src/example_edge_embed_quick_edge_init.o  src/example_sn_embed.o  src/header_encryption.o  src/minilzo.o  src/n2n.o  src/pearson.o  src/random_numbers.o  src/sn.o  src/sn_utils.o  src/speck.o  src/transform_aes.o  src/transform_cc20.o  src/transform_null.o  src/transform_speck.o  src/transform_tf.o  src/tuntap_freebsd.o  src/tuntap_linux.o  src/tuntap_netbsd.o  src/tuntap_osx.o  src/twofish.o  src/wire.o
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libn2n.a(edge_utils_win32.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libn2n.a(transform_aes.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libn2n.a(tuntap_freebsd.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libn2n.a(tuntap_linux.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libn2n.a(tuntap_netbsd.o) has no symbols
gcc -g -O2 -I/usr/local/opt/openssl@1.1/include -I ./include -I/usr/local/Cellar/openssl@1.1/1.1.1g/include      src/edge.c -L/usr/local/opt/openssl@1.1/lib/ libn2n.a  -o edge
src/edge.c:855:40: warning: implicit declaration of function 'OpenSSL_version' is invalid in C99
      [-Wimplicit-function-declaration]
  traceEvent(TRACE_NORMAL, "Using %s", OpenSSL_version(0));
                                       ^
1 warning generated.
Undefined symbols for architecture x86_64:
  "_BIO_ctrl", referenced from:
      _openssl_err_as_string in libn2n.a(transform_cc20.o)
  "_BIO_free", referenced from:
      _openssl_err_as_string in libn2n.a(transform_cc20.o)
  "_BIO_new", referenced from:
      _openssl_err_as_string in libn2n.a(transform_cc20.o)
  "_BIO_s_mem", referenced from:
      _openssl_err_as_string in libn2n.a(transform_cc20.o)
  "_ERR_print_errors", referenced from:
      _openssl_err_as_string in libn2n.a(transform_cc20.o)
  "_EVP_CIPHER_CTX_free", referenced from:
      _transop_deinit_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_CIPHER_CTX_new", referenced from:
      _n2n_transop_cc20_init in libn2n.a(transform_cc20.o)
  "_EVP_CIPHER_CTX_reset", referenced from:
      _transop_encode_cc20 in libn2n.a(transform_cc20.o)
      _transop_decode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_CIPHER_CTX_set_padding", referenced from:
      _transop_encode_cc20 in libn2n.a(transform_cc20.o)
      _transop_decode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_DecryptFinal_ex", referenced from:
      _transop_decode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_DecryptInit_ex", referenced from:
      _transop_decode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_DecryptUpdate", referenced from:
      _transop_decode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_EncryptFinal_ex", referenced from:
      _transop_encode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_EncryptInit_ex", referenced from:
      _transop_encode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_EncryptUpdate", referenced from:
      _transop_encode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_chacha20", referenced from:
      _n2n_transop_cc20_init in libn2n.a(transform_cc20.o)
  "_OpenSSL_version", referenced from:
      _main in edge-fd0a67.o
  "_SHA256", referenced from:
      _n2n_transop_cc20_init in libn2n.a(transform_cc20.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [edge] Error 1
```

**Comment by yermulnik** [comment]
JFYI: what I did to make `make` happy
1.  Came across this while was googling: https://github.com/petermax2/libelektra/commit/ade9dc2dddce58316b77aec8b5ec743842b36dc0 (where the main point is that `openssl` from `brew` and `macports` fails to provide those symbols)
2. git cloned https://www.openssl.org/source/gitrepo.html, ran `./Configure` and `make` (w/o installing it)
3. Amended `Makefile` and `tools/Makefile` in `n2n` cloned repo: `CFLAGS` to use `-I../openssl/include` and `LDFLAGS` to use `-L../openssl -lssl -lcrypto` (for `tools/Makefile` obviously I had to add extra `../` to paths)

Haven't yet tested whether compiled `n2n` is functional though (will update this thread when I get testing done)
Hope this helps

**Comment by yermulnik** [comment]
No luck yet =(
```
$ ./edge -c […] -k […] -l […]:443 -a 172.17.17.63 -s  255.255.255.252 -f
dyld: Library not loaded: /usr/local/lib/libssl.3.dylib
  Referenced from: /Users/[…]/work/src/CODE/n2n/./edge
  Reason: image not found
Abort trap: 6

$ sudo ln -s ~/work/src/CODE/openssl/libssl.3.dylib /usr/local/lib/
$ sudo ln -s ~/work/src/CODE/openssl/libcrypto.3.dylib /usr/local/lib/

$ ./edge -c […] -k […] -l […]:443 -a 172.17.17.63 -s  255.255.255.252 -f
13/Jul/2020 20:42:19 [edge_utils.c:2447] Adding supernode[0] = […]:443
13/Jul/2020 20:42:19 [edge.c:841] WARNING: Switching to Twofish as key was provided.
13/Jul/2020 20:42:19 [edge.c:852] Starting n2n edge 2.7.0 Jul 12 2020 23:08:15
Segmentation fault: 11
```
I'm starting to hate MacOS

**Comment by yermulnik** [comment]
So I installed openssl from repo (previously I went w/o installing it with `make install`), deleted and cloned `n2n` repo again and `./autogen.sh` → `./configure` → `make` worked as expected.
Now `edge` starts w/o errors (needs `sudo` to become `root`) but I'm not able to ping/connect supernode.
Will continue investigating...

**Comment by yermulnik** [comment]
Now I get port binding error despite using `-p` option:
```
[…]
13/Jul/2020 22:12:56 [edge_utils.c:2012] Binding to local port 1979
13/Jul/2020 22:12:56 [n2n.c:58] ERROR: Bind error on local port 1968 [Address already in use]
[…]
```

**Comment by yermulnik** [comment]
#219 seems to be related

**Comment by yermulnik** [comment]
Though nothing is using port 1968 but something does =( I hate MacOS
```
$ nc -vzu localhost 1968
Connection to localhost port 1968 [udp/lipsinc] succeeded!

$ sudo lsof -i udp:1968 | wc -l
       0
```

**Comment by SeptemberHX** [comment]
The same error here :(

**Comment by yermulnik** [comment]
The error goes away some time later (couldn't figure out what and why is that and when it goes away but it does even w/o reboot).
And eventually I was able to start `egde` node and connect to `supernode` and other `edge`s :partying_face:

**Comment by yermulnik** [comment]
So basically this is the working guide: https://github.com/ntop/n2n/issues/278#issuecomment-657718645
I think the issue can be closed now as the fix for the original issue was to install `openssl` from the repo but not from `brew`/`macports`.

> Now `edge` starts w/o errors (needs `sudo` to become `root`) but I'm not able to ping/connect supernode.

This was my fault using wrong subnet :man_facepalming:

**Comment by lucaderi** [comment]
n2n works for me on MacOS so I close this issue for the moment

**Comment by yermulnik** [comment]
> Now I get port binding error despite using `-p` option:
> 
> ```
> […]
> 13/Jul/2020 22:12:56 [edge_utils.c:2012] Binding to local port 1979
> 13/Jul/2020 22:12:56 [n2n.c:58] ERROR: Bind error on local port 1968 [Address already in use]
> […]
> ```

So basically here's what was missing in code to fix this issue:
```
diff --git a/src/n2n.c b/src/n2n.c
index 86d2dbe..e585cb8 100644
--- a/src/n2n.c
+++ b/src/n2n.c
@@ -48,6 +48,9 @@ SOCKET open_socket(int local_port, int bind_any) {

   sockopt = 1;
   setsockopt(sock_fd, SOL_SOCKET, SO_REUSEADDR, (char *)&sockopt, sizeof(sockopt));
+  #ifdef __APPLE__   // MacOS/X requires an additional call
+    setsockopt(sock_fd, SOL_SOCKET, SO_REUSEPORT, (char *)&sockopt, sizeof(sockopt));
+  #endif

   memset(&local_address, 0, sizeof(local_address));
   local_address.sin_family = AF_INET;
```

**Comment by SeptemberHX** [comment]
Well, I compiled it sucessfully once I switched to 2.6-stable branch instead of master branch.
Hope it helps for others.

**Comment by jonahzheng** [comment]
@SeptemberHX yes, 2.6-stable is ok on mac,but 2.8-stable build fail.
