### ISSUE TITLE
n2n edge connection times out

### ISSUE THREAD

**Issue by emanuele-f** [ntop/n2n#28]
I have noticed that n2n sometimes stalls when there are a lot of packet drops due to unreliable communication channel. Restarting n2n on both the edge nodes solves the issue, so I suspect some metadata n2n packets (e.g. registration) are dropped and not retransmitted. I will provide more information when I reproduce the problem again.

**Comment by dinopio** [comment]
When an edge is started and no traffic is sent (idle) it might lose the connection.
A way to keep the edge nodes up is to keep pinging the edge ip from a node on the network.
This is currently the only way I can keep the network up.

**Comment by ghostry** [comment]
[a temporary solution](https://blog.ghostry.cn/doc/docs/n2n/n2n-1b1am7b0njmbf)
