### ISSUE TITLE
Small & portable byte-aligned LZ77 compression

### ISSUE THREAD

**Issue by skyformat99** [ntop/n2n#298]
Small & portable byte-aligned LZ77 compression
https://ariya.github.io/FastLZ/

So you can think about replacing the existing compression algorithm with this one.
It is enough for the compression algorithm to select a suitable one, it does not need to contain so many algorithms, others can be deleted

**Comment by skyformat99** [comment]
another
https://github.com/coolbutuseless/lz4lite

**Comment by Logan007** [comment]
Do you know how it compares to the built-in LZO1X (`-z1` or `-z`) which is also LZ based?

**Comment by Logan007** [comment]
I found that [`lzbench`](https://github.com/inikep/lzbench) which I sometimes use to benchmark my (unfinished but to be advertised :smile:) [pucr](https://github.com/Logan007/pucr) also includes FastLZ. So, I have just had it run the numbers real quick:

```
Compressor name         Compress. Decompress. Compr. size  Ratio Filename
memcpy                  23635 MB/s 24976 MB/s       47105 100.00 ../ivanova.bin *** reference, all on i7 2860QM
lz4 1.9.2                 864 MB/s  3163 MB/s       14042  29.81 ../ivanova.bin *** not the lite version, though
fastlz 0.1 -1             404 MB/s  1049 MB/s       13712  29.11 ../ivanova.bin
lzo1x 2.10 -1             739 MB/s  1246 MB/s       13598  28.87 ../ivanova.bin *** offered in n2n
zstd 1.4.3 -1             328 MB/s   873 MB/s       10103  21.45 ../ivanova.bin
zstd 1.4.3 -7              87 MB/s   912 MB/s        9554  20.28 ../ivanova.bin *** offered in n2n
zstd 1.4.3 -22           2.41 MB/s   882 MB/s        8948  19.00 ../ivanova.bin
```

Actually, this is a wonderful opportunity to talk about the compression integrated in n2n and perform some comparison. Especially the columns _Compression (Speed)_, _Decompression (Speed)_, and _(Compression) Ratio_ are of most interest. While LZO1X and FastLZ are quite fast they do not squeeze as many bytes as ZSTD out of the original `ivanova.bin` file which I usually use for benchmarking. LZ4 is even faster but somewhat low on compression.

From looking at the numbers, it seems that FastLZ and LZO1X share the same league.

@skyformat99 Is there a specific reason you ask for FastLZ? Is FastLZ considered more lightweight (code, memory) than LZO1X?

By the way, [pucr](https://github.com/Logan007/pucr) cooks off nine more bytes. Also, she seems to compress better especially shorter files like ethernet packets… :innocent:

**Comment by Logan007** [comment]
One more point… The obvious difference between compression and decompression speed is the reason for the mantra 

_"Every node shall be able to decompress"_ :sunglasses:

…as it is something that can even be done smaller CPUs if required whereas compression of outgoing packets has to explicitly be enabled using the `-z` family of command line options for nodes running on stronger CPUs.

**Comment by skyformat99** [comment]
thanks.
The fastlz library is only 2 files, very lightweight, easy to use, and everything else is too big.

**Comment by Logan007** [comment]
LZO1x is LZ77 based, too. It also comprises two or three files only. And it already is implemented in n2n.

Even though FASTLZ and LZO1x share the same league, I read from the numbers above that LZO1x seems to be a bit faster and achieves better compression ratio.

So, with a view to the numbers, I actually do not see a need for change here…

**Comment by skyformat99** [comment]
thanks.
will close it.

**Comment by Logan007** [comment]
@skyformat99 Have you ever experienced the LZO1x-related bug described in #360? If you try to start up the edge using `-z` (several times), does it ever stop with an LZO init error?
