### ISSUE TITLE
how to seperate log and add log level

### ISSUE THREAD

**Issue by tlsalex** [ntop/n2n#310]
I am using centos7.

Currently, I use
 `journalctl -f -u supernode`
 `journalctl -f -u edge`
 `tail -f /var/log/messages`
to check log.

Is it possible to separate its log from /var/log/message to a specific file, like /var/log/supernode and /var/log/edge.
Is it possible to add log level to its config, like log level=1,2,3 which corresponding to -v -vv -vvv.

**Comment by Logan007** [comment]
If you want a numerical `$LOGLEVEL`, you could try something like `supernode <your options> -$(printf 'v%.0s' {1..$LOGLEVEL})`. Note that there is _no_ zero log level with this solution.

As the log seems to be output to `stdout`, you might have it diverted to `$LOGFILE` using the `supernode <your options> -$(printf 'v%.0s' {1..$LOGLEVEL}) >> $LOGFILE` syntax – given that `$LOGFILE`'s access rights allow the user who runs the supernode for write access.
