### ISSUE TITLE
Should the edge wait for REGISTER_SUPER_ACK before sending out packets?

### ISSUE THREAD

**Issue by Logan007** [ntop/n2n#311]
Observed one case in which edge sent out (broadcast) packets for distribution by supernode after _REGISTER_SUPER_ was sent but no _REGISTER_SUPER_ACK_ was received yet (which, in this case, was never sent out because of badly chosen community parameter). 

Probably, the supernode dropped the packets. But shouldn't an edge be quiet until it received _REGISTER_SUPER_ACK_? Shall we try to change this behaviour?

**Comment by fengdaolong** [comment]
I think we can try, but we must also ensure that there is a timeout retransmission mechanism.

**Comment by Logan007** [comment]
That retransmission mechanism is already in place, see [`update_supernode_reg()`](https://github.com/ntop/n2n/blob/bb64130c42bcf8f50cec965711f03724031fc818/src/edge_utils.c#L867).

I guess it would be about not allowing to send out (and maybe to accept) packets while a _REGISTER_SUPER_ACK_ has not been received yet, at least the very _first_ one. What gives me a bit of a headache here – also in conjunction with replay protection – is the "sessionless" behaviour of starting re-registering but still needing to accept packets that are on the line from that previous "session", a time before sending out _REGISTER_SUPER_. What if a "session" or a "link" really break for a while or programs get restarted?
