### ISSUE TITLE
so strange,the first ping package is much faster than later packages

### ISSUE THREAD

**Issue by tlsalex** [ntop/n2n#314]
My home network and office network using different ISP.
P2P connection is established successfully.
I noted that the first ping package is much faster than later packages ,always like that in these two days.
It is the ISP do something bad ,they don't like each other,they do that on purpose ?

```
root@home:~# ping tpfs -c2
PING tpfs (192.168.8.11) 56(84) bytes of data.
64 bytes from tpfs (192.168.8.11): icmp_seq=1 ttl=64 time=26.5 ms
64 bytes from tpfs (192.168.8.11): icmp_seq=2 ttl=64 time=51.6 ms
```

**Comment by Logan007** [comment]
It might depend on how your supernode is connected to the internet. The first packet(s) usually get distributed via the supernode until a REGISTER_ACK reaches the sender. For more details about the basic packet exchange mechanics, please have a look at the original [n2n paper](http://luca.ntop.org/n2n.pdf).

In some cases, connections via the supernode show less total delay than a p2p connection. I have experienced it myself as described [here](https://github.com/ntop/n2n/issues/291#issuecomment-665231045). It must be one of internet routing's X-Files…

**Comment by Logan007** [comment]
Do you require further information?
