### ISSUE TITLE
Run edge on windows as a service

### ISSUE THREAD

**Issue by tlsalex** [ntop/n2n#328]
When I run edge on windows,
I need to run cmd as administrator(can't assign IP address with run cmd as a normal user),
Then navigate to the folder that contain edge.exe
Then start edge.

It not quite convenient to in this way , I hope the edge or supernode can be run as a service on windows.

**Comment by Logan007** [comment]
Would a `.bat` file (on Desktop?) containing the complete command line do? It could possibly be _"Run as Administrator"_ with a right-click. In addition, If I remember correctly, file _"Properties"_ menu (right-click) might offer some always-run-as-administrator option on some tab.

Also, maybe [this](https://www.howtogeek.com/50786/using-srvstart-to-run-any-application-as-a-windows-service/) guide also applies to your Windows version. They say that there were _"several [RunAsService utilities] out there"_.

I hope these hints help. Let us know what you find!

**Comment by fengdaolong** [comment]
Another way is to use the windows task schedule that comes with the operating system to create a task and choose to run it when not logged in.

**Comment by skyformat99** [comment]
This feature is not required.

**Comment by tlsalex** [comment]
@Logan007 your idea is good for me ,thank you

**Comment by Logan007** [comment]
Which of the ideas was helpful to you? The `.bat` or the _RunAsService_? Let us know!

**Comment by tlsalex** [comment]
@Logan007 the bat is better for me. thank you

**Comment by 0x2a94b5** [comment]
I recommend using `NSSM` to run a .BAT or any .EXE file as a service.

[https://nssm.cc/usage](https://nssm.cc/usage) 

It is simpler, more stable and more functional than `SrvStart`.
