### ISSUE TITLE
may not be correct that register to  supernode in function update_supernode_reg.

### ISSUE THREAD

**Issue by switch-st** [ntop/n2n#341]
It's may not be correct that register to  supernode in function update_supernode_reg of line 934 to 944.

https://github.com/ntop/n2n/blob/2ea8dd53b7c5ed5390f3df42df3d92f43682c5c6/src/edge_utils.c#L934-L944

It will send register messages to both two supernodes. After that, `eee->supernode` will change to the last supernode address. Then edge will send messages to this address even if this address is not valid now. 

Also `send_register_super` function will change `eee->last_cookie`'s value every time. So call `send_register_super` function twice is not correct.

Just like this log:
![image](https://user-images.githubusercontent.com/7710981/88923204-eb746f00-d2a3-11ea-9eeb-96a2b7f82596.png)

test cmd: `./edge -a static:192.168.235.20  -c xxxx -k xxxx -l switchy.wang:10086 -l switchy.wang:9999 -f -A3 -vvv`

The second supernode `switchy.wang:9999` is invalid. Just first supernode `switchy.wang:10086` responded. But the cookie is not match with `eee->last_cookie` of edge.

I'm not sure about the purpose of why send register message to both supernode here. But i think that the logic here is incorrect.

**Comment by Logan007** [comment]
I think I see what you are talking about. I have no idea why the supernodes are iterated using that `for` loop. Especially as they already get _slowly_ iterated and retried over time along the `eee->*` fields `sup_attempts` and `conf.sn_idx`.

Would it help to
- comment / delete lines 909, 935 as well as 943 and
- replace `sn_idx` by `eee->conf.sn_idx` in lines 936 and 936?

I guess that is what you have had in mind, right? Good catch!

**Comment by skyformat99** [comment]
Every once in a while, the Edge sends a registration message to all the SuperNode nodes to maintain the Edge list.
An invalid SN node may become valid again at sometime in the future.
So It should send a registration message to all  SN nodes.

**Comment by skyformat99** [comment]
For cookies,  can put the  last_cookie  value to the structure of  n2n_edge_conf:
typedef struct n2n_edge_conf {
  n2n_sn_name_t       sn_ip_array[N2N_EDGE_NUM_SUPERNODES];
 ###  **n2n_cookie_t        last_cookie[N2N_EDGE_NUM_SUPERNODES];**            /**< Cookie sent in last REGISTER_SUPER. */
  n2n_route_t	      *routes;		      /**< Networks to route through n2n */
  n2n_community_t     community_name;         /**< The community. 16 full octets. */
  uint8_t	      header_encryption;      /**< Header encryption indicator. */
  he_context_t	      *header_encryption_ctx; /**< Header encryption cipher context. */
  he_context_t        *header_iv_ctx;	      /**< Header IV ecnryption cipher context, REMOVE as soon as seperte fileds for checksum and replay protection available */
  n2n_transform_t     transop_id;             /**< The transop to use. */
  uint16_t	      compression;	      /**< Compress outgoing data packets before encryption */
  uint16_t	      num_routes;	      /**< Number of routes in routes */
  uint8_t             dyn_ip_mode;            /**< Interface IP address is dynamically allocated, eg. DHCP. */
  uint8_t             allow_routing;          /**< Accept packet no to interface address. */
  uint8_t             drop_multicast;         /**< Multicast ethernet addresses. */
  uint8_t             disable_pmtu_discovery; /**< Disable the Path MTU discovery. */
  uint8_t             allow_p2p;              /**< Allow P2P connection */
  uint8_t             sn_num;                 /**< Number of supernode addresses defined. */
  uint8_t             tos;                    /** TOS for sent packets */
  char                *encrypt_key;
  int                 register_interval;      /**< Interval for supernode registration, also used for UDP NAT hole punching. */
  int                 register_ttl;           /**< TTL for registration packet when UDP NAT hole punching through supernode. */
  int                 local_port;
  int                 mgmt_port;
} n2n_edge_conf_t;


and , Deletes the last_cookie variable in the N2N_edge structure.

**Comment by skyformat99** [comment]
Sorry, the above method is too complicated and there are too many modifications.
There's a simple way to do it,
After sending a registration message to all SN nodes, update the last_cookie before sending the next one,
will fix it later.

**Comment by Logan007** [comment]
> Every once in a while, the Edge sends a registration message to all the SuperNode nodes to maintain the Edge list.
An invalid SN node may become valid again at sometime in the future.
So It should send a registration message to all SN nodes.

I don't think that this will change by the modifications proposed. The guarding `if` will still allow for those periodic (re-)REGISTER_SUPER after `conf.register_interval` seconds. The proposed changes will just will restore the probably original intended behaviour.

> For cookies, can put the last_cookie value to the structure of n2n_edge_conf:

That should already happen in `send_register_super()` if I am not mistaken.

Please also see line 1842 which will prevent that we cycle any further to the next supernode as soon as we got a valid response REGISTER_SUPER_ACK.

**Comment by switch-st** [comment]
> I think I see what you are talking about. I have no idea why the supernodes are iterated using that `for` loop. Especially as they already get _slowly_ iterated and retried over time along the `eee->*` fields `sup_attempts` and `conf.sn_idx`.
> 
> Would it help to
> 
> * comment / delete lines 909, 935 as well as 943 and
> * replace `sn_idx` by `eee->conf.sn_idx` in lines 936 and 936?
> 
> I guess that is what you have had in mind, right? Good catch!

This solution is simpler, clearer and works well. I also prefer this solution.

**Comment by switch-st** [comment]
This code was commited here https://github.com/ntop/n2n/commit/1c7b14995b8a899ec465af3cde8228b30ed437a7 by `lucaderi`. Maybe we can solve this problem in a better way while retaining this feature.
