### ISSUE TITLE
Twofish can't handle packets sized under 12 bytes properly

### ISSUE THREAD

**Issue by Logan007** [ntop/n2n#350]
Whenever packet size falls below 12 bytes, Twofish scheme decrypted packets will have 12 (16 byte block size _minus_ 4 byte nonce size) bytes in size (last unused bytes probably zeroed).

`twofish.c`'s handling of not fully filled one-block packets causes this. Longer packets that do not match block size do not see this problem as a CTS scheme is applied.

Every solution to this will break compatibility. I will think of something, maybe give Twofish a complete overhaul. But not for the upcoming release. For now, just be aware.

**Comment by fengdaolong** [comment]
I think that as the future version 3.0, there is no need to consider compatibility, so that n2n can be drastically improved. @lucaderi What do you think of this matter?

**Comment by Logan007** [comment]
…such short packets are rare though. Low-level programmer might encounter it.

As for version numbers, I did everything to preserve compatibility for the upcoming release **2.8**. Concerning a later **3.0**, I see too many changes upcoming that break compatibility anyway – I agree.

These days, I am getting into Twofish a little depper to see how we can improve it. But this will take weeks, nothing for **2.8** anyway.

Twofish has been the slowest cipher so far. So, are we riding a dead horse? I do not think so. I think that the variety of ciphers for the user to chose from is a strength.
