### ISSUE TITLE
ip route was gone after restart edge.service

### ISSUE THREAD

**Issue by tlsalex** [ntop/n2n#352]
I noted that the ip route was gone after I restart edge.service
I create a route with 
`ip route add 10.163.132.0/24 via 192.168.8.11 dev n2n0`
Then traffic was route as expected.
But after I restart edge.service. the route was gone.

1. Will it possible to add some feature as follow code , which is do something after start the service:
```
iface tap0 inet static
	pre-up ip tuntap add tap0 mode tap user root
	pre-up ip addr add 192.168.100.1/24 dev tap0
	up ip link set dev tap0 up
	post-up ip route add 192.168.100.0/24 dev tap0
```

2. Will it possible to create a persistent tap device by n2n. which I can initial that device on boot -- assign IP and route.

**Comment by Logan007** [comment]
> But after I restart edge.service. the route was gone.

That is expected as the device shuts down when n2n ends.

> Will it possible to add some feature as follow code , which is do something after start the service

I have read about the recently added `-n` option to create and remove routes by n2n itself as soon as it starts up or ends. You might want to try that. Let us know how it works.

Alternatively, you could use a script or `.bat` that not only contains the `edge` command but also embeds the `edge` command in the `ip route…` and other commands you might need – that is how I solved it before `-n` came up, still sticking to it as no need/time to change that yet.

> Will it possible to create a persistent tap device by n2n. which I can initial that device on boot -- assign IP and route.

I do not really know about that but I doubt it. I guess that the solution above would not make this necessarily a requirement.

**Comment by tlsalex** [comment]
Thank you , I will try the -n later.
Now I am using bellow way to fix it.
```

[Service]
Type=simple
ExecStartPre=
ExecStart=/usr/sbin/edge /etc/n2n/edge.conf -f
ExecStartPost=/sbin/ip route add 10.xx.xx.0/24 via 192.168.8.11 dev n2n0
Restart=on-abnormal
RestartSec=5
```

**Comment by Logan007** [comment]
> Will it possible to create a persistent tap device by n2n. which I can initial that device on boot -- assign IP and route.

While merging some documents, I found one of them (now: [TAP Configuration Guide](https://github.com/ntop/n2n/blob/dev/doc/TapConfiguration.md#ipv6)) pointing to `tunctl` of `uml-utilities` which made me remember your second question up there. I personally do not have any experience with these tools but hopefully, you find them helpful.

**Comment by Logan007** [comment]
So, is this still an issue to you?
