### ISSUE TITLE
About -H frame header encryption

### ISSUE THREAD

**Issue by skyformat99** [ntop/n2n#356]
In the case of the current -H encryption of the frame header, it is encrypted directly at the edge.
In fact, when edge starts sending the SN Register message for the first time, 
it's better to have SN encrypt it and then send it back.

When the encryption is generated, the flag field on the edge side sets a value tag.
In this way, -H encrypted edge and unencrypted Edge can also communicate normally.

What do you think?

**Comment by Logan007** [comment]
The community name is used to derive the header encryption key (pre-shared key). That is why the community name of encrypted communities must be kept secret. By sending it with a first unencrypted packet, it would get known to the public.

I absolutely do not recommend it.

**Comment by skyformat99** [comment]
In fact, we should design an approach similar to JWT that is both secure and easy to use.
https://jwt.io/

**Comment by Logan007** [comment]
Why should we? To be honest, I do not see that need.

As far as I see it, JWTs are mainly designed for **authentication** – header encryption is used for **privacy** against DPI and eavesdroppers – completely different discussions.

And, for the privacy, what could be easier than to use `-H` on cli?

**Comment by Logan007** [comment]
_P. S._ If you are aiming at strengthening authentication beyond the knowledge of the pre-shared key, the cookie-handling could be adopted, e.g. "sign" a cookie by encrypting or hash-crypt it before returning it to sender. Although, I do not believe that it would add more security to the current schemes as these already depend on the pre-shared key.
