### ISSUE TITLE
Invalid transop ID

### ISSUE THREAD

**Issue by lucaderi** [ntop/n2n#364]
I believe there is a bug

root@ubuntu18:/home/deri/n2n# edge -A4 -c XXXXXx -k KKKKKKKk -f -l supernode.ntop.org:7777  -z2
16/Aug/2020 11:42:25 [edge_utils.c:2599] Adding supernode[0] = supernode.ntop.org:7777
16/Aug/2020 11:42:25 [edge.c:851] Starting n2n edge 2.9.0 Aug 16 2020 03:41:38
16/Aug/2020 11:42:25 [edge.c:854] Using OpenSSL 1.1.1  11 Sep 2018
16/Aug/2020 11:42:25 [edge.c:857] Using compression: zstd.
16/Aug/2020 11:42:25 [edge.c:858] Using ChaCha20 cipher.
16/Aug/2020 11:42:25 [edge_utils.c:210] supernode 0 => supernode.ntop.org:7777
16/Aug/2020 11:42:25 [edge.c:887] Automatically assign IP address by supernode.
16/Aug/2020 11:42:25 [edge_utils.c:726] Successfully joined multicast group 224.0.0.68:1968
16/Aug/2020 11:42:25 [edge_utils.c:1808] [OK] Edge Peer <<< ================ >>> Super Node
16/Aug/2020 11:42:25 [edge.c:911] Local tuntap IP: 172.17.12.1, Mask: 255.255.255.0
16/Aug/2020 11:42:25 [edge.c:941] Dropping privileges to uid=65534, gid=65534
16/Aug/2020 11:42:25 [edge.c:965] edge started
16/Aug/2020 11:42:37 [edge_utils.c:1130] ERROR: invalid transop ID: expected ChaCha20(4), got invalid(772)
16/Aug/2020 11:43:07 [edge_utils.c:1130] ERROR: invalid transop ID: expected ChaCha20(4), got invalid(772)
16/Aug/2020 11:42:37 [edge_utils.c:1130] ERROR: invalid transop ID: expected ChaCha20(4), got invalid(772)
16/Aug/2020 11:43:07 [edge_utils.c:1130] ERROR: invalid transop ID: expected ChaCha20(4), got invalid(772)

**Comment by lucaderi** [comment]
Apparently this issue is due to some edge nodes that have not been updated. It would be nice to report the IP address (or anything else) for identifying such edges

**Comment by Logan007** [comment]
Will do, at least MAC. Pull request coming soon.
