### ISSUE TITLE
Windows compilation error "config.h: No such file or directory"

### ISSUE THREAD

**Issue by siskai** [ntop/n2n#366]
`Can you help me with this problem?`

D:\download\n2n-2.8>md build

D:\download\n2n-2.8>cd build

D:\download\n2n-2.8\build>cmake ..
-- Building for: Visual Studio 15 2017
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.16.27035.0
-- The CXX compiler identification is MSVC 19.16.27035.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: D:/download/n2n-2.8/build

D:\download\n2n-2.8\build>"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\amd64\MSBuild.exe" edge.vcxproj /t:Build /p:Configuration=Release
Microsoft (R) Build Engine verze 15.9.21+g9802d43bc3 pro .NET Framework
Copyright (C) Microsoft Corporation. Všechna práva vyhrazena.

Vytváření sestavení bylo zahájeno 16.8.2020 9:35:00.
Projekt D:\download\n2n-2.8\build\edge.vcxproj v uzlu 1 (počet cílů: Build).
Probíhá sestavení projektu D:\download\n2n-2.8\build\edge.vcxproj (1) - D:\download\n2n-2.8\build\ZERO_CHECK.vcxproj (2) v uzlu 1 (výchozí cíle).
PrepareForBuild:
  Probíhá vytváření adresáře Win32\Release\ZERO_CHECK\.
  Probíhá vytváření adresáře D:\download\n2n-2.8\build\Release\.
  Probíhá vytváření adresáře Win32\Release\ZERO_CHECK\ZERO_CHECK.tlog\.
InitializeBuildStatus:
  Probíhá vytváření souboru Win32\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild v důsledku zadání AlwaysCreate.
CustomBuild:
  Checking Build System
FinalizeBuildStatus:
  Probíhá odstraňování souboru Win32\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild.
  Probíhá aktualizace časového razítka pro Win32\Release\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate.
Sestavení projektu D:\download\n2n-2.8\build\ZERO_CHECK.vcxproj (s výchozími cíli) bylo dokončeno.

Probíhá sestavení projektu D:\download\n2n-2.8\build\edge.vcxproj (1) - D:\download\n2n-2.8\build\edge_utils_win32.vcxproj (3) v uzlu 1 (výchozí cíle).
PrepareForBuild:
  Probíhá vytváření adresáře edge_utils_win32.dir\Release\.
  Probíhá vytváření adresáře edge_utils_win32.dir\Release\edge_utils_win32.tlog\.
InitializeBuildStatus:
  Probíhá vytváření souboru edge_utils_win32.dir\Release\edge_utils_win32.tlog\unsuccessfulbuild v důsledku zadání AlwaysCreate.
CustomBuild:
  Building Custom Rule D:/download/n2n-2.8/CMakeLists.txt
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\CL.exe /c /I"C:\Program Files (x86)\OpenSSL-Win32\include" /I"D:\download\n2n-2.8\." /I"D:\download\n2n-2.8\include" /I"D:\download\n2n-2.8\win32" /W3 /WX- /diagnostics:classic /O2 /Ob2 /Oy- /D WIN32 /D _WINDOW
  S /D NDEBUG /D CMAKE_BUILD /D "GIT_RELEASE=\"\"" /D "PACKAGE_VERSION=\"2.7.0\"" /D "PACKAGE_OSNAME=\"Windows-10.0.18363\"" /D "N2N_VERSION=\"2.7.0\"" /D "N2N_OSNAME=\"Windows-10.0.18363\"" /D N2N_HAVE_AES /D "CMAKE_INTDIR=\"Release\"" /D _MBCS /Gm- /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"edge_
  utils_win32.dir\Release\\" /Fd"edge_utils_win32.dir\Release\edge_utils_win32.pdb" /Gd /TC /analyze- /errorReport:queue "D:\download\n2n-2.8\src\edge_utils_win32.c"
  Optimalizující kompilátor C/C++ společnosti Microsoft (R) verze 19.16.27035 pro procesory x86
  Copyright (C) Microsoft Corporation. Všechna práva vyhrazena.

  cl /c /I"C:\Program Files (x86)\OpenSSL-Win32\include" /I"D:\download\n2n-2.8\." /I"D:\download\n2n-2.8\include" /I"D:\download\n2n-2.8\win32" /W3 /WX- /diagnostics:classic /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D CMAKE_BUILD /D "GIT_RELEASE=\"\"" /D "PACKAGE_VERSION=\"2.7.0\"" /D "PACKAGE_OSNAME=\"Windows
  -10.0.18363\"" /D "N2N_VERSION=\"2.7.0\"" /D "N2N_OSNAME=\"Windows-10.0.18363\"" /D N2N_HAVE_AES /D "CMAKE_INTDIR=\"Release\"" /D _MBCS /Gm- /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"edge_utils_win32.dir\Release\\" /Fd"edge_utils_win32.dir\Release\edge_utils_win32.pdb" /Gd /TC /analyze- /errorRe
  port:queue "D:\download\n2n-2.8\src\edge_utils_win32.c"

  edge_utils_win32.c
D:\download\n2n-2.8\include\n2n.h(42): fatal error C1083: Nejde otevřít soubor zahrnout: config.h: No such file or directory [D:\download\n2n-2.8\build\edge_utils_win32.vcxproj]
Sestavení projektu D:\download\n2n-2.8\build\edge_utils_win32.vcxproj (s výchozími cíli) bylo dokončeno: CHYBA.

Probíhá sestavení projektu D:\download\n2n-2.8\build\edge.vcxproj (1) - D:\download\n2n-2.8\build\n2n.vcxproj (4) v uzlu 1 (výchozí cíle).
Probíhá sestavení projektu D:\download\n2n-2.8\build\n2n.vcxproj (4) - D:\download\n2n-2.8\build\win32\n2n_win32.vcxproj (5) v uzlu 1 (výchozí cíle).
PrepareForBuild:
  Probíhá vytváření adresáře n2n_win32.dir\Release\.
  Probíhá vytváření adresáře n2n_win32.dir\Release\n2n_win32.tlog\.
InitializeBuildStatus:
  Probíhá vytváření souboru n2n_win32.dir\Release\n2n_win32.tlog\unsuccessfulbuild v důsledku zadání AlwaysCreate.
CustomBuild:
  Building Custom Rule D:/download/n2n-2.8/win32/CMakeLists.txt
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\CL.exe /c /I"C:\Program Files (x86)\OpenSSL-Win32\include" /I"D:\download\n2n-2.8\." /I"D:\download\n2n-2.8\include" /I"D:\download\n2n-2.8\win32" /W3 /WX- /diagnostics:classic /O2 /Ob2 /Oy- /D WIN32 /D _WINDOW
  S /D NDEBUG /D CMAKE_BUILD /D "GIT_RELEASE=\"\"" /D "PACKAGE_VERSION=\"2.7.0\"" /D "PACKAGE_OSNAME=\"Windows-10.0.18363\"" /D "N2N_VERSION=\"2.7.0\"" /D "N2N_OSNAME=\"Windows-10.0.18363\"" /D N2N_HAVE_AES /D "CMAKE_INTDIR=\"Release\"" /D _MBCS /Gm- /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"n2n_w
  in32.dir\Release\\" /Fd"n2n_win32.dir\Release\n2n_win32.pdb" /Gd /TC /analyze- /errorReport:queue "D:\download\n2n-2.8\win32\getopt1.c" "D:\download\n2n-2.8\win32\getopt.c" "D:\download\n2n-2.8\win32\wintap.c"
  Optimalizující kompilátor C/C++ společnosti Microsoft (R) verze 19.16.27035 pro procesory x86
  Copyright (C) Microsoft Corporation. Všechna práva vyhrazena.

  getopt1.c
  cl /c /I"C:\Program Files (x86)\OpenSSL-Win32\include" /I"D:\download\n2n-2.8\." /I"D:\download\n2n-2.8\include" /I"D:\download\n2n-2.8\win32" /W3 /WX- /diagnostics:classic /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D CMAKE_BUILD /D "GIT_RELEASE=\"\"" /D "PACKAGE_VERSION=\"2.7.0\"" /D "PACKAGE_OSNAME=\"Windows
  -10.0.18363\"" /D "N2N_VERSION=\"2.7.0\"" /D "N2N_OSNAME=\"Windows-10.0.18363\"" /D N2N_HAVE_AES /D "CMAKE_INTDIR=\"Release\"" /D _MBCS /Gm- /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"n2n_win32.dir\Release\\" /Fd"n2n_win32.dir\Release\n2n_win32.pdb" /Gd /TC /analyze- /errorReport:queue "D:\downlo
  ad\n2n-2.8\win32\getopt1.c" "D:\download\n2n-2.8\win32\getopt.c" "D:\download\n2n-2.8\win32\wintap.c"

  getopt.c
  wintap.c
D:\download\n2n-2.8\include\n2n.h(42): fatal error C1083: Nejde otevřít soubor zahrnout: config.h: No such file or directory [D:\download\n2n-2.8\build\win32\n2n_win32.vcxproj]
  Generování kódu...
Sestavení projektu D:\download\n2n-2.8\build\win32\n2n_win32.vcxproj (s výchozími cíli) bylo dokončeno: CHYBA.

Sestavení projektu D:\download\n2n-2.8\build\n2n.vcxproj (s výchozími cíli) bylo dokončeno: CHYBA.

Sestavení projektu D:\download\n2n-2.8\build\edge.vcxproj (počet cílů: Build) bylo dokončeno: CHYBA.

Sestavení SE NEZDAŘILO.

"D:\download\n2n-2.8\build\edge.vcxproj" (Build cíl) (1) ->
"D:\download\n2n-2.8\build\edge_utils_win32.vcxproj" (výchozí cíl) (3) ->
(cíl ClCompile) ->
  D:\download\n2n-2.8\include\n2n.h(42): fatal error C1083: Nejde otevřít soubor zahrnout: config.h: No such file or directory [D:\download\n2n-2.8\build\edge_utils_win32.vcxproj]

"D:\download\n2n-2.8\build\edge.vcxproj" (Build cíl) (1) ->
"D:\download\n2n-2.8\build\n2n.vcxproj" (výchozí cíl) (4) ->
"D:\download\n2n-2.8\build\win32\n2n_win32.vcxproj" (výchozí cíl) (5) ->
  D:\download\n2n-2.8\include\n2n.h(42): fatal error C1083: Nejde otevřít soubor zahrnout: config.h: No such file or directory [D:\download\n2n-2.8\build\win32\n2n_win32.vcxproj]

    0 upozornění
    Počet chyb: 2

Uplynulý čas 00:00:02.27

**Comment by lucaderi** [comment]
You need to copy by hand a file generated on Unix

**Comment by siskai** [comment]
> 
> 
> You need to copy by hand a file generated on Unix

It helps. Thanks!

**Comment by includevsimport** [comment]
oh! Friend, can you give me a copy？

**Comment by siskai** [comment]
@includevsimport 

`1) Content of config.h`
/* include/config.h.  Generated from config.h.in by configure.  */
/* include/config.h.in.  Generated from configure.ac by autoheader.  */

/* GIT release */
#define GIT_RELEASE "2.8.0"

/* Support for linux capabilities */
/* #undef HAVE_LIBCAP */

/* Define to 1 if you have the `crypto' library (-lcrypto). */
#define HAVE_LIBCRYPTO 1

/* Define to 1 if you have the `zstd' library (-lzstd). */
/* #undef HAVE_LIBZSTD */

/* OpenSSL 1.1 is present */
#define HAVE_OPENSSL_1_1 /**/

/* Have pcap_immediate_mode */
/* #undef HAVE_PCAP_IMMEDIATE_MODE */

/* Have AES support */
#define N2N_HAVE_AES /**/

/* Have PCAP library */
/* #undef N2N_HAVE_PCAP */

/* Have ZSTD support */
/* #undef N2N_HAVE_ZSTD */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "edge"

/* OS name */
#define PACKAGE_OSNAME "Debian buster/sid"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "edge 2.8.0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "edge"

/* Define to the home page for this package. */
#define PACKAGE_URL ""

/* Define to the version of this package. */
#define PACKAGE_VERSION "2.8.0"

`2) Content of config.h.in`
/* include/config.h.in.  Generated from configure.ac by autoheader.  */

/* GIT release */
#undef GIT_RELEASE

/* Support for linux capabilities */
#undef HAVE_LIBCAP

/* Define to 1 if you have the `crypto' library (-lcrypto). */
#undef HAVE_LIBCRYPTO

/* Define to 1 if you have the `zstd' library (-lzstd). */
#undef HAVE_LIBZSTD

/* OpenSSL 1.1 is present */
#undef HAVE_OPENSSL_1_1

/* Have pcap_immediate_mode */
#undef HAVE_PCAP_IMMEDIATE_MODE

/* Have AES support */
#undef N2N_HAVE_AES

/* Have PCAP library */
#undef N2N_HAVE_PCAP

/* Have ZSTD support */
#undef N2N_HAVE_ZSTD

/* Define to the address where bug reports for this package should be sent. */
#undef PACKAGE_BUGREPORT

/* Define to the full name of this package. */
#undef PACKAGE_NAME

/* OS name */
#undef PACKAGE_OSNAME

/* Define to the full name and version of this package. */
#undef PACKAGE_STRING

/* Define to the one symbol short name of this package. */
#undef PACKAGE_TARNAME

/* Define to the home page for this package. */
#undef PACKAGE_URL

/* Define to the version of this package. */
#undef PACKAGE_VERSION

**Comment by includevsimport** [comment]
> @includevsimport
> 
> `1) Content of config.h`
> /* include/config.h. Generated from config.h.in by configure. _/ /_ include/config.h.in. Generated from configure.ac by autoheader. */
> 
> /* GIT release */
> #define GIT_RELEASE "2.8.0"
> 
> /* Support for linux capabilities _/ /_ #undef HAVE_LIBCAP */
> 
> /* Define to 1 if you have the `crypto' library (-lcrypto). */
> #define HAVE_LIBCRYPTO 1
> 
> /* Define to 1 if you have the `zstd' library (-lzstd). _/ /_ #undef HAVE_LIBZSTD */
> 
> /* OpenSSL 1.1 is present */
> #define HAVE_OPENSSL_1_1 /**/
> 
> /* Have pcap_immediate_mode _/ /_ #undef HAVE_PCAP_IMMEDIATE_MODE */
> 
> /* Have AES support */
> #define N2N_HAVE_AES /**/
> 
> /* Have PCAP library _/ /_ #undef N2N_HAVE_PCAP */
> 
> /* Have ZSTD support _/ /_ #undef N2N_HAVE_ZSTD */
> 
> /* Define to the address where bug reports for this package should be sent. */
> #define PACKAGE_BUGREPORT ""
> 
> /* Define to the full name of this package. */
> #define PACKAGE_NAME "edge"
> 
> /* OS name */
> #define PACKAGE_OSNAME "Debian buster/sid"
> 
> /* Define to the full name and version of this package. */
> #define PACKAGE_STRING "edge 2.8.0"
> 
> /* Define to the one symbol short name of this package. */
> #define PACKAGE_TARNAME "edge"
> 
> /* Define to the home page for this package. */
> #define PACKAGE_URL ""
> 
> /* Define to the version of this package. */
> #define PACKAGE_VERSION "2.8.0"
> 
> `2) Content of config.h.in`
> /* include/config.h.in. Generated from configure.ac by autoheader. */
> 
> /* GIT release */
> #undef GIT_RELEASE
> 
> /* Support for linux capabilities */
> #undef HAVE_LIBCAP
> 
> /* Define to 1 if you have the `crypto' library (-lcrypto). */
> #undef HAVE_LIBCRYPTO
> 
> /* Define to 1 if you have the `zstd' library (-lzstd). */
> #undef HAVE_LIBZSTD
> 
> /* OpenSSL 1.1 is present */
> #undef HAVE_OPENSSL_1_1
> 
> /* Have pcap_immediate_mode */
> #undef HAVE_PCAP_IMMEDIATE_MODE
> 
> /* Have AES support */
> #undef N2N_HAVE_AES
> 
> /* Have PCAP library */
> #undef N2N_HAVE_PCAP
> 
> /* Have ZSTD support */
> #undef N2N_HAVE_ZSTD
> 
> /* Define to the address where bug reports for this package should be sent. */
> #undef PACKAGE_BUGREPORT
> 
> /* Define to the full name of this package. */
> #undef PACKAGE_NAME
> 
> /* OS name */
> #undef PACKAGE_OSNAME
> 
> /* Define to the full name and version of this package. */
> #undef PACKAGE_STRING
> 
> /* Define to the one symbol short name of this package. */
> #undef PACKAGE_TARNAME
> 
> /* Define to the home page for this package. */
> #undef PACKAGE_URL
> 
> /* Define to the version of this package. */
> #undef PACKAGE_VERSION


After compiling in the linux environment, the config file is indeed generated. I am very grateful for the topic you started.

**Comment by VergLsm** [comment]
Same problem.
It's a bug rather than normal situation, should not be solved by copying files by hand.
Please reopen this issue.

**Comment by VergLsm** [comment]
@emanuele-f

**Comment by VergLsm** [comment]
When I applied this patch, the compilation passed.
```
--- a/include/n2n.h
+++ b/include/n2n.h
@@ -38,11 +38,7 @@
 #ifdef WIN32
 #include "win32/n2n_win32.h"
 
-#ifdef _MSC_VER
-#include "config.h" /* Visual C++ */
-#else
 #include "win32/winconfig.h"
-#endif
 #define N2N_CAN_NAME_IFACE 1
 #undef N2N_HAVE_DAEMON
 #undef N2N_HAVE_SETUID
```

**Comment by skyformat99** [comment]
> When I applied this patch, the compilation passed.
> 
> ```
> --- a/include/n2n.h
> +++ b/include/n2n.h
> @@ -38,11 +38,7 @@
>  #ifdef WIN32
>  #include "win32/n2n_win32.h"
>  
> -#ifdef _MSC_VER
> -#include "config.h" /* Visual C++ */
> -#else
>  #include "win32/winconfig.h"
> -#endif
>  #define N2N_CAN_NAME_IFACE 1
>  #undef N2N_HAVE_DAEMON
>  #undef N2N_HAVE_SETUID
> ```

you are right.
please take a PR.

**Comment by VergLsm** [comment]
@skyformat99 Sorry, I am not sure whether this commit violates the intention of other developers, but I think it is absolutely unreasonable. It seems that the new commit wants to use a new configuration file, which contains more configuration items and cannot be automatically generated in the Windows build. This can only be solved by an expert.

**Comment by skyformat99** [comment]
> @skyformat99 Sorry, I am not sure whether this commit violates the intention of other developers, but I think it is absolutely unreasonable. It seems that the new commit wants to use a new configuration file, which contains more configuration items and cannot be automatically generated in the Windows build. This can only be solved by an expert.

emmm， It seems you are a bit of an expert.
You can submit a PR first.

**Comment by emanuele-f** [comment]
Hope to clarify the things a bit. We need to distinguish between two build modes in Windows:

- `cmake` build: cmake does not use a config.h because it simply uses its own rules from CMakeLists.txt to set the proper defines (e.g. `N2N_HAVE_AES`)
- `manual` build (e.g. `Visual C++`): don't have much experience on this but I think you need to provide a custom config.h or similar file

I agree that this is a bug since the official instructions (written by me) reported in https://github.com/ntop/n2n/blob/dev/doc/Building.md#build-on-windows do not work anymore. This bug you are reporting was probably introduced in 96c05490e946a9782210257a042b66246d821a65 . In short, I think that the n2n project leader @lucaderi should decide which is the official method for building n2n in Windows and provide working instructions.

**Comment by lucaderi** [comment]
I personally use Microsoft Compilers and not cmake. the fix you are referring is inside _MSC_VER used by MS compilers.

IMHO n2n should build with both options, MS Compilers and cmake. However I do not use cmake, so feel free to patch the code as you want and send a PR for both documentation and code changes if necessary.

**Comment by VergLsm** [comment]
Conclusion: The key point of this bug is _MSC_VER is included in both build modes.
