### ISSUE TITLE
auto IP

### ISSUE THREAD

**Issue by Logan007** [ntop/n2n#367]
The freshly added auto IP feature (#355) can make the supernode assign IP addresses cross-community from the same sub-network's address range. That is an issue as different communities usually mean different sub-networks (sometimes even several edges on the very same computer).

Is it possible to modify this feature such that IP addresses are assigned on a per-community basis according to their very own (predefined?) sub-networks?

**Comment by fengdaolong** [comment]
If different communities use different subnets, there are two solutions:
1. The super node loads a configuration file. The content of the file is the correspondence between the complete community name and the IP subnet. When the community name exactly matches, the corresponding IP is automatically assigned;
2. Strengthen your recently implemented regular expression filtering community name function. Each community filtering condition corresponds to an IP subnet. When the community name meets the regular expression rules, the corresponding IP is automatically assigned.

For super nodes, it is impossible to determine the community name of the edge. I think the second solution is relatively better.

**Comment by Logan007** [comment]
> correspondence between the complete community name and the IP subnet

Perhaps, if we leave it un-determined for now, each (new) community can get its own new subnet range from which it draws the new IPs.

Extension to config-file reading could be done at some later point in time, e.g. some special syntax `<community name> <IP sub-network>` delimited by a blank (that would exclude blanks from community names).

> For super nodes, it is impossible to determine the community name of the edge. I think the second solution is relatively better.

The name is transmitted in the COMMON section of each packet, even the REGISTER_SUPER (if IP address proposal is sent back using REGISTER_SUPER_ACK). Even if not in the hash list yet (first edge registering), it should be readable from `cmn.community`.

> recently implemented regular expression filtering community name function

Yes, I guess that would be the place, somewhere during the processing of the REGISTER_SUPER. Alternatively,  the QUERY_PEER could be extended by some IP address field delivering a proposed IP address if asked about the very same peer (srcMac == queryMac)? The edge would need to query the supernode about itself (after registration) if it does not carry a fixed IP address.

**Comment by fengdaolong** [comment]
> Perhaps, if we leave it un-determined for now, each (new) community can get its own new subnet range from which it draws the new IPs.

A new community is created and new IPs can be extracted from it, but what if there are multiple different IP subnets in the community? For example, there are two edges, the IP is `192.168.5.7/24`, `172.16.88.99/24`, then which one should I choose?

>The name is transmitted in the COMMON section of each packet, even the REGISTER_SUPER (if IP address proposal is sent back using REGISTER_SUPER_ACK). Even if not in the hash list yet (first edge registering), it should be readable from cmn.community.

What I mean is that the super node cannot know which community name will be used by the edge, and therefore cannot select the IP subnet to be assigned based on the community name.
For example, the community subnet rules set by the super node:
`community01    192.168.66.0/24`
`community02    192.168.77.0/24`
`community03    192.168.88.0/24`
`community04    192.168.99.0/24`
However, a new edge is registered with the community name `logan007`. It is not in the community subnet rule list of the super node. How will it be assigned an IP address?
I think it is most appropriate to use regular expression rules for matching.

**Comment by Logan007** [comment]
> multiple different IP subnets in the community

That would be a special case which remains uncovered. Would a DHCP server be able to handle it? I would go with one community = one sub-network. That is a reasonable offer to users. Everything beyond that is probably something we are not able to manage.

> It is not in the community subnet rule list

If auto IP address feature is enabled, the supernode needs a pool of sub-networks each of which is a pool of IP addresses.

> a new edge is registered 

As soon as a `community.list` file is used, only communities that match or explicitly named can be accepted. For entries with IP sub-network, it is just the IP address pool representing that given IP sub-network. Lines without IP sub-network entry would draw a new sub-network from the sub-network pool (if it is the first edge in that community) and then offer an IP address from that.

Internally, each community structure would need a sub-network field and each node an IP address field. Assignment of new entities (sub-networks or IP addresses) must be carefully designed.

Also, I still am not too happy about using REGISTER_SUPER / REGISTER_SUPER_ACK because they recur. Shouldn't we use the QUERY_PEER / PEER_INFO messages which would need that additional IP address field as outlined in [this post](https://github.com/ntop/n2n/pull/363#issuecomment-674529919) of #363? The edge then can send it out "on demand" if it needs an IP address (after registration) or just not do it. Please take it as a suggestion, I do not want to interfere too much with your work here – which is really great! :muscle:

**Comment by fengdaolong** [comment]
>If auto IP address feature is enabled, the supernode needs a pool of sub-networks each of which is a pool of IP addresses.

If the super node has a subnet pool, then how to allocate the subnet pool to the newly registered community, there are only two options: either randomly allocate it, or allocate it after matching the subnet pool and community name.


>Lines without IP sub-network entry would draw a new sub-network from the sub-network pool (if it is the first edge in that community) and then offer an IP address from that.

In this case, it can only randomly assign a subnet from the subnet pool to the new community.

>use the QUERY_PEER / PEER_INFO messages

I agree with you! 
Our steps are to implement first and then improve. Using the REGISTER_SUPER / REGISTER_SUPER_ACK message body to report/allocate the IP is an implementation method with minimal changes to the old code. I fully agree that the QUERY_PEER / PEER_INFO message body carries IP information, because it is very reasonable, but the message content needs to be redesigned and modified.


My work is relatively busy, and I can only squeeze a little time to do these things on weekends, My progress is very slow. I think your thinking is very clear. If you have a lot of time, I support you to realize your ideas.

I support you in interfering with my implemented functions, because I believe you are great! 💪💪💪

**Comment by Logan007** [comment]
> If the super node has a subnet pool, then how to allocate the subnet pool to the newly registered community, there are only two options: either randomly allocate it, or allocate it after matching the subnet pool and community name.

> In this case, it can only randomly assign a subnet from the subnet pool to the new community.

Yes, exactly. If it is given with a community line (no matter of reg exp or fixed name), we use this sub-network. If no sub-network given with that line, we use a _random_ one. For now, we could use a pool of class C sub-networks e.g. 10.255.255.0/24 and then decrease (10.255.254.0/24, …). Those may not be used in other lines (we need to check while read the config line).

What do you think?

> If you have a lot of time, I support you to realize your ideas.

I feel humbled that you allow me to implement your ideas. Indeed, I have some time at hand these days. Even though I am not too deep in networking yet (I have to re-iterate… :smile:), I could give it a shot as it mainly is about parameters. I am just not sure where to start. Will take a deeper look at your two pull request's code tomorrow (#355 and #369)

**Comment by fengdaolong** [comment]
>What do you think?

I agree.

>Even though I am not too deep in networking yet

Believe in yourself, you can do it.😄

**Comment by Logan007** [comment]
I left a review on the original and meanwhile closed pull request #355. It contains some thoughts on how I understood things (or not yet) and what would need to be changed to move more towards the above sketched scheme. Let me know if you have thoughts on that.

**Comment by Logan007** [comment]
Okay, I got a little deeper into it. I think that I will **not** switch to QUERY_PEER / PEER_INFO. So, most changes will go to supernode logic to handle more sub-networks. Starting right away…

Do you know if new IP addresses / sub-networks (sent via the REGISTER_SUPER_ACK) will be effective immediately at the edge? Does the host instantly realize (setup routes etc.)? What happens if an already assigned IP address and sub-network change?

**Comment by fengdaolong** [comment]
>I think that I will not switch to QUERY_PEER / PEER_INFO.

Are you experiencing difficulties?🤣🤣🤣
If you decide to use QUERY_PEER / PEER_INFO to transmit IP information, it is recommended to modify it as soon as possible, because subsequent functions added may all rely on it to avoid code accumulation that is not easy to modify.


>Do you know if new IP addresses / sub-networks (sent via the REGISTER_SUPER_ACK) will be effective immediately at the edge?

This needs to modify all "tuntap_xxx.c".

>What happens if an already assigned IP address and sub-network change?

In the current code scheme, after the edge is started, it can only obtain the IP address after sending the REGISTER_SUPER / REGISTER_SUPER_ACK with the super node for the first time, and then save it in its own configuration. As long as the edge is not restarted, it will not change its IP address.

**Comment by Logan007** [comment]
> Are you experiencing difficulties?

Not so much difficulties (it would be as easy as moving the code from one switch case & data structure to another :wink:) but more thoughts on different scenarios. The more I think about it the more I become convinced that requesting / leasing the IP address is tied to the REGISTER_SUPER process – your original idea! 

I was thinking about an edge loosing connection for a while and finding itself alone in that community later-on which meanwhile was purged by the supernode.  It would continuously try to re-REGISTER with the SUPERnode (and not necessarily think of PEER_INFO). The supernode will re-open that community then. But probably with a new sub-network.

So, a new request should be re-triggered whenever an edge  loses connection to the supernode. Maybe as soon as we get the `Supernode not responding, now trying %s` error. How could a  new request for an IP address be triggered of which the response assigns a new address?

I will provide a pull request during the next days with changes to support the pool of sub-networks. The "re-request on connection failure" could be added later-on.

By the way, is there a standard way of describing a range of sub-networks? For example `10.128.0.0...10.255.255.0/24`? I would use it for the `-d` option as we now need network**s**. It only should just contain no white spaces.

**Comment by Logan007** [comment]
> But probably with a new sub-network.

I just got an idea on how to lower this probability: Hashing the community name shall help to decide which sub-network to assign (if not used yet).

**Comment by fengdaolong** [comment]
The super node is only a medium for N2N, which acts as a matchmaking bridge. The edge must not form a strong dependence on it. I think the ultimate goal of the edge is to get rid of the super node as much as possible.
For example, you and your girlfriend are two separate edges. The person who introduced the two of you is called the super node. When you two hold hands and have a sweet relationship, you no longer need a super node. Because you don't want to introduce people to interfere with your love, unless your relationship breaks down and you need an introducer to help reconcile you.🤣🤣🤣🤣🤣🤣🤣🤣🤣

**Comment by Logan007** [comment]
Aaawwww, this is such a sweetly depicted analogy! 

However, sometimes we might need help from the supernode. I will implement the outlined way of hashing the community name to assign an IP sub-network range. This might help to find the same network again (if not accidentally reserved by another community in the meantime). I lack creativity to imagine how this would translate into your allegory :wink:

**Comment by fengdaolong** [comment]
As long as our boss @lucaderi has no opinion, you can implement it according to your own ideas, and then slowly improve. 😉

**Comment by Logan007** [comment]
> I think the ultimate goal of the edge is to get rid of the super node as much as possible.

I agree. The auto IP feature however will give us some hardship decentralizing.

**Comment by fengdaolong** [comment]
Auto IP is only an auxiliary function of n2n, it is not the focus of n2n.
My vision for decentralized n2n is:
1. Merge edge and sn, and name them "n2n" for the time being. Let them have me in you and you in me, and become a hybrid. An "n2n" is both an edge and can provide super node services;
2. After multiple "n2n" are interconnected, one of the nodes is initially designated as a super node, and then they will vote to automatically elect one of the best nodes (for example, the environment with public IP, the fastest network speed) to other nodes Provide super node services, no longer need an independent super node;
3. Then, as for which node provides the function of automatic IP, it is also voted by them;

**Comment by Logan007** [comment]
We must share a similar vision…

I fully agree, supernode and edge share a lot of code and the packet format. So, somehow edge and supernode both are nodes. Those could be treated equally. Even supernodes could have a MAC address. IP address would only be required if the node has edge-character, i.e. requires an IP outlet on top of the underlying MAC-bases p2p-like structure. Some nodes have public (real world) IP addresses, not only the so-far supernodes. That is a special property that would mark these nodes as possible hole-punching helpers and packet-forwarders if required. Also, details about the network structure must be propagated or sent out on request.

Big question marks on routing and fail-over mechanisms. Also, some "anchor" nodes with public IP must be known upfront (like the supernodes now) to allow for easily joining the network. For keeping it resilient, maybe edges can memorize all the latest seen public nodes (just to find entrance again). Then, the voting or line evaluation mechanisms chose the best fitted punching helper / packet forwarder. Could different nodes of the same community employ different hole-punching helpers?

Phew, that sounds like a complete rework and overhaul.

This true p2p vision will require a lot of efforts to implement.

**Comment by fengdaolong** [comment]
Yes, that's what it means.
