### ISSUE TITLE
This is not v2 anymore!

### ISSUE THREAD

**Issue by lucktu** [ntop/n2n#375]
Because the latest edge is no longer compatible with the previous one

**Comment by yanggis** [comment]
Same problem here.
When I connect supernode (v.2.7.0) with latest edge (v.2.9.0), I got this error:
 n2n[13690]: ERROR: payload decompression failed: received packet indicating unsupported invalid compression.
Any info I should add to the config, so that edge (v.2.9.0) can be compatible with old supernode?

**Comment by lucktu** [comment]
My test looks fine (from edge), but I can't communicate。

If it's not compatible, why would you use it like that?

**Comment by yanggis** [comment]
No communication is fine?
As I have a lot of clients, upgradation for all of them together is a bit troublesome. I just tested the latest version to see if it is compatible with my supernode server; then decide if it is necessary to make the upgradation.

**Comment by lucktu** [comment]
If you want to strengthen management, but want to be compatible, can try the version before August 16, Or just use the latest supernode.

**Comment by yanggis** [comment]
OK, thanks for the info.

**Comment by Logan007** [comment]
The newly released, latest **stable 2.8** should be compatible to previous versions. Some efforts were taken to squeeze in the 2.8-features in a compatible way. Some features originally intended for 2.8 were even delayed for the sake of compatibility.

However, it is foreseeable that upcoming (not so soon) 3.0 will break compatibility due to new features.

_dev_ being called 2.9 develops further starting from 2.8 and towards 3.0. And _dev_ is as it says under development, I would even say heavy development these days. It is bleeding edge. This could include even daily changes. If you want to test it, please make sure to upgrade all edges and supernodes.

The internal packet format version in _dev_ will move from 2 to 3 soon so packets from older edges will be rejected. This will probably be done as soon as all major packet format changes are incorporated, there still are a few left. Until then, the edge keeps showing error messages about invalid transform IDs. This error message was extended to display (real world) IP and (n2n's edge) MAC addresses to help the user pointing to edges that still need to upgrade.

**Comment by lucktu** [comment]
> 
> 
> OK, thanks for the info.

It proves that August 8th is compatible

**Comment by lucktu** [comment]
@Logan007 , OK

**Comment by Logan007** [comment]
@lucktu I know about your strong efforts to provide compiled binaries. I appreciate them as a good way to make n2n more accessible to Windows users who might struggle to go all the way down the compile-it-yourself road.

Well, but _dev_ is _dev_ – even though it has a version number. From the action items I have left on my to-do list for now, two or three will definitely break compatibility to current _dev_ again as I plan to make a few changes to the cipher section. And other changes might come up, too. Shortly after the release, we have just started with all the changes.

Thank you for bringing it up. Maybe, we should state it more clearly in the README.md file. I will provide a suggestion as pull request.

**Comment by lucktu** [comment]
Thanks!

Maybe the dev shouldn't face all users, or should highlight the changes to its compatibility. To avoid any unnecessary panic.
 
In addition, I heard that v3.0 is coming, whether to give the blueprint for the future for everyone to discuss, It can also serve as a guide, so that all the program contributors do not get lost.

**Comment by Logan007** [comment]
> Maybe the dev shouldn't face all users

I would always prefer a public _dev_. Also, as users can test (they must be aware), it allows a valuable feedback to help the developers who in turn will bring new and maybe better code to _dev_ and so on. A self-reinforcing feedback circuit (or so)!

> highlight the changes to its compatibility

As vibrant as _dev_ is these days, features could even undergo changes. In my opinion, and I understand that there might be well founded other views, the release points are a good point in time to document the changes; but even with that, we could get better.

> To avoid any unnecessary panic.

I have drafted a note for the README.md as pull request. Do you think it is sufficent? If you see room for improvement, please feel free to provide a review on that pull request!

> I heard that v3.0 is coming, whether to give the blueprint for the future for everyone to discuss

As 2.8 has just been released, I think 3.0 is being drafted as we go, there is no central coordination. The ideas are publicly being discussed at several issues, pull requests and on [Discord](https://www.ntop.org/support/faq/howto-join-public-ntop-discussions/) – all the accessible places which interested users and developers might visit anyway. One thing I see more often these days are ideas to conceptually move even more towards p2p. 3.0 will probably depend on how much support each idea gets, on how it fits into the general concept, and also on who is able to bring it to code. We all ourselves are in the middle of creating it!

I held back myself to implement a few features I would have loved to see in n2n, but I did not want 2.8 to break compatibility. Those are coming now… :wink:

**Comment by lucktu** [comment]
"**A ship without a captain**"

Since it's v3, and it's not compatible, shouldn't some of the parameters be changed to default, like -e, -a, or something. without a master plan, how often will v3 run out of compatibility again? Without a major adjustment, why call it a v3?

I'm worried about the future.

**Comment by Logan007** [comment]
@lucktu I really enjoy our thoughts-exchanging conversations.

> shouldn't some of the parameters be changed to default, like -e, -a, or something

That would be a good thing to discuss! You should open an _Issue_ on that.

> "A ship without a captain"

Well, there is a captain namely Luca Deri. My impression is that he leaves all the midshipmen enough space to bring in their ideas and prove their talents. At the end of the day, it is him as maintainer who decides what is pulled in or not. Please keep in mind that all contributors are volunteers. They are not part of any chain of command. Also, I have to speak up for ntop: It is a company that needs to pay its bills. Even though n2n might be considered a wonderful piece of software promoting a quite unique concept, it most probably is not one of their cash cows and thus not enjoying highest priority.

> without a master plan

Everybody around brings ideas to the table. Let's discuss them. Eventually, somebody is able and willing to code them, some ideas might make it to a pull request, get peer reviewed, see changes, get accepted or rejected… 

> why call it a v3?

One the one hand, I guess that  is just the natural numbering avoiding a strange looking 2.10.

On the other hand, looking at how n2n evolved, there always will be a point in time up to which you can hold back the required changes. But at some point, you just have to apply the changes. Best thing would be to do it all at the same time. This is what happens now. I guess that 3.0 as a major change in numbering also is a good psychological point to apply these changes.

For example, just take a look at the compression feature. There just was no field to mark a packet as compressed. We achieved a compatible solution for 2.8 using some bit-twiddling in a very hacky way. Who will be able to maintain such a hacky solution in the long run? That is why compression now gets its very own data field and thus breaking compatibility. With a view to future features and versions, we will experience similar situations. Reworking the ciphers I find myself in a comparable setting – I just am not able to keep up compatibility while changing modes of operation for packet size and maybe speed.

> Without a major adjustment, 

I rarely cite myself but…

>> I held back myself to implement a few features I would have loved to see in n2n, but I did not want 2.8 to break compatibility. Those are coming now… 

It is my assumption that every contributor acts responsibly. Compatibility breaking changes are not supposed to happen every now and then. Those ideally happen accumulated and this is now! So, I expect to see even more changes to come for the 3.0 "overflow" release (not only from my part). Strolling through the _Issues_ and _Pull Requests_, I see a lot of ideas awaiting realization some of which having potential to massively impact compatibility: upnp, more p2p-character, distributed hash table approach, merge supernode and edge, tcp fall-back, multi-supernode support, IPv6… 

By the way, I guess it will take much longer until we see 3.0 being released; jumping from 2.6 to 2.8 was high-speed.

> I'm worried about the future.

Following the thoughts above, there is absolutely no need to be worried. I wish you could share my optimistic view on new features and more stability of n2n 3.0-spanned networks – which will last and remain compatible probably up to some 4.0 :wink:

**Comment by lucktu** [comment]
... guess ... guess ... guess ...  ^_^

Thank you for your efforts and sincerity!

**Comment by fengdaolong** [comment]
Our captain @lucaderi is too busy to process the code submitted by everyone in time, so that n2n cannot get fast iterative updates. 😏

**Comment by Logan007** [comment]
> …sincerity!

I promise that you will never get anything else.

**Comment by Logan007** [comment]
… anything else than my full sincerity! == "_I will always be true to you._"
