### ISSUE TITLE
Rework AES

### ISSUE THREAD

**Issue by Logan007** [ntop/n2n#378]
I took some time to review AES transform and plan for the following changes:

- With header encryption disguising internal MACs in place, I am way less concerned about payload's first plain text block. Thus, I would like to remove the AES's IV encryption. This saves the single AES-ECB step in IV generation and thus may speed things up a bit.

- ~~As I want to stick with flexible IV size and as it shall not be partly constant (the non-transmitted part will be constant as we skip the scrambling encryption step), I will revert to the _nonce_-like scheme already used in Twofish but using a 64 bit value by default.~~ I will implement full-size IV adding 8 more bytes to the packet.

- I will move the openSSL-related code into a new `aes.c` file to relieve the `transform_aes.c` from too specific code. This would allow to later eventually integrate some own AES code in `aes.c` more easily.

- I will replace the current key hashing with Pearson hashing for being independent from openSSL in this point. Also, this is a prerequisite for somewhen implementing own AES code.

- However, I would like to keep the general [scheme](https://github.com/ntop/n2n/issues/101#issuecomment-496020090) of password length-triggered key-length.

- Implement the [CTS](https://en.wikipedia.org/wiki/Ciphertext_stealing#CBC_implementation_notes) scheme. CTS will save between 1 and 16 bytes per packet as padding is not required anymore.

- The crypto-context shall be provided by `aes.c` to `transform_aes.c` allowing to flexibly handle it on transform-level while its internal structure depends on low level only.

On average, this will save 0.5 bytes per packet (added 8, saved (1+16)/2) and speed things up a bit. It will break compatibility to current dev for AES though – joining current disruptions.

Any thoughts or hints?

**Comment by lucktu** [comment]
Since it's for 3.0, not compatible, so let's go for it without scruples.

**Comment by skyformat99** [comment]
> I took some time to review AES transform and plan for the following changes:
> 
> * With header encryption disguising internal MACs in place, I am way less concerned about payload's first plain text block. Thus, I would like to remove the AES's IV encryption. This saves the single AES-ECB step in IV generation and thus may speed things up a bit.
> * ~As I want to stick with flexible IV size and as it shall not be partly constant (the non-transmitted part will be constant as we skip the scrambling encryption step), I will revert to the _nonce_-like scheme already used in Twofish but using a 64 bit value by default.~ I will implement full-size IV adding 8 more bytes to the packet.
> * I will move the openSSL-related code into a new `aes.c` file to relieve the `transform_aes.c` from too specific code. This would allow to later eventually integrate some own AES code in `aes.c` more easily.
> * I will replace the current key hashing with Pearson hashing for being independent from openSSL in this point. Also, this is a prerequisite for somewhen implementing own AES code.
> * However, I would like to keep the general [scheme](https://github.com/ntop/n2n/issues/101#issuecomment-496020090) of password length-triggered key-length.
> * Implement the [CTS](https://en.wikipedia.org/wiki/Ciphertext_stealing#CBC_implementation_notes) scheme. CTS will save between 1 and 16 bytes per packet as padding is not required anymore.
> * The crypto-context shall be provided by `aes.c` to `transform_aes.c` allowing to flexibly handle it on transform-level while its internal structure depends on low level only.
> 
> On average, this will save 0.5 bytes per packet (added 8, saved (1+16)/2) and speed things up a bit. It will break compatibility to current dev for AES though – joining current disruptions.
> 
> Any thoughts or hints?

very good。
support

**Comment by Logan007** [comment]
While reworking AES (please test #380 – be warned, it is not compatible), I thought of maybe (optionally) getting independent from openSSL, so we can have a basic AES support (plain C, additionally x86 AES-NI) even if not compiled with openSSL but still revert to openSSL if compiled with it.

Main advantage would be to not have to statically include openSSL for AES support (still required for ChaCha20 though). @lucktu, do you remember the rough difference in executable size?

Disadvantage: Probably slower on non-AES-NI platforms if not compiled with openSSL support (but available after all).

What do you think? Would it make sense?
