### ISSUE TITLE
[feature request] password for supernode

### ISSUE THREAD

**Issue by HuJK** [ntop/n2n#382]
I want to setup a supernode that only I can use.

So I request a feature that I can set a password for supernode, edge node have to give password to join the supernode, thanks a lot!

**Comment by Logan007** [comment]
I am glad to say that we already have that! :wink:

Please think of the community-name as password and start the supernode with the `-c <community file>` parameter where the `<community file>` would be the path to a simple text file containing a single line with the name of your community. It will be the only community allowed. Only nodes from that community can join (`-c <community name>` at the edge).

If you want to encrypt that access and prevent open transmission of the community name via the network, **all** edges should additionally use `-H` command line option for header encryption.

Also, please see the `community.list` file for advanced use of that file.

**Comment by Logan007** [comment]
_P. S._ In addition to this access barrier, if you use payload encryption `-A_` at the edges, only the edges can decipher the traffic. So even if anyone would be able to break that access barrier, the payload remains protected by the payload crypto (see [this document](https://github.com/ntop/n2n/blob/dev/doc/Crypto.md) for details).

**Comment by Logan007** [comment]
_Another P. S_ This is a good question! I will make it the first one to go into a FAQ doc I am drafting.

**Comment by HuJK** [comment]
Thank you a lot!
