### ISSUE TITLE
[Bug report] edge can't read config file properly.

### ISSUE THREAD

**Issue by HuJK** [ntop/n2n#384]
```
OS: Ubuntu 20.04 / Centos 7.4
Version: v.2.8.0.r533.56ccbbb
```

The default service file are not work. While I tried to run it manually, it throws error:
```bash
root@PC # /usr/sbin/edge /etc/n2n/edge.conf -f
fish: “/usr/sbin/edge /etc/n2n/edge.co…” terminated by signal SIGSEGV (Address boundary error)
```

It seems that it can't read config file properly.

I have to update the service file to this to make it work:
```service
[Unit]
Description=n2n edge process
After=network-online.target syslog.target nfw.target
Wants=network-online.target

[Service]
Type=simple
ExecStartPre=
ExecStart=/bin/sh -c '/usr/sbin/edge $(cat /etc/n2n/edge.conf | grep  -e \^[^\#]) -f'
Restart=on-abnormal
RestartSec=5

[Install]
WantedBy=multi-user.target
Alias=
```

Basically I print the config file, filter out lines start with ```#```, and fill it to command lines.
```
/usr/sbin/edge $(cat /etc/n2n/edge.conf | grep  -e \^[^\#]) -f
```

**Comment by Logan007** [comment]
I tried to start an edge with the default config file and it works properly here (Arch Linux).

First, I was thinking that maybe the additional `-f` in your command line was causing the trouble (usually, the syntax is indicated as `edge <edge.conf file>` only, without any additions) but even that worked out here.

Has anybody else experienced such an error so far?

**Comment by Logan007** [comment]
Does it work if you put the `-f` inside your `.conf` file and use the pure `edge <edge.conf file>` syntax?

**Comment by HuJK** [comment]
It works now... Did you do any update on it?
