### ISSUE TITLE
[Feature request] Show connected client and their NAT type.

### ISSUE THREAD

**Issue by HuJK** [ntop/n2n#386]
Can I list connected edge node and their community, source IP, and NAT type from supernode?

**Comment by Logan007** [comment]
The edges as well as the supernode provide basic information via their respective localhost udp management port. They default to 5644 and 5645.

You can request that information by just sending a new line (press [ENTER] key) running the following command (localhost only):

`netcat -u  localhost 5644` (edge) or
`netcat -u  localhost 5645`(supernode).

The edge even understands some simple commands, try `help`.

**Comment by skyformat99** [comment]
> The edges as well as the supernode provide basic information via their respective localhost udp management port. They default to 5644 and 5645.
> 
> You can request that information by just sending a new line (press [ENTER] key) running the following command (localhost only):
> 
> `netcat -u localhost 5644` (edge) or
> `netcat -u localhost 5645`(supernode).
> 
> The edge even understands some simple commands, try `help`.

can add it to faq？

**Comment by Logan007** [comment]
Done – #388

**Comment by skyformat99** [comment]
> Done – #388

thanks O(∩_∩)O

**Comment by HuJK** [comment]
I am using Centos 7, and I can't get any response from port 5644 and 5645...

Is there any misconfigured?

![image](https://user-images.githubusercontent.com/15907444/91629133-c8e78a00-e9f8-11ea-8aa7-37da95de234b.png)

**Comment by HuJK** [comment]
Thanks a lot. 

It would be better if I can know edge nodes uses supernode's traffic or not(Symmetric NAT or not).

**Comment by Logan007** [comment]
From the **edge** management port output you can read the nodes connected listed as _peers_ are peer-to-peer, the nodes listed as _pending peers_ use supernode forwarding.

In my opinion, it would be a bit difficult to have the **supernode** keep track of this: A supernode does not know about packets that are exchanged peer-to-peer and not forwarded via itself. So, even a packet counter at the supernode would not be a reliable indicator.

Also, please keep in mind that some connections to between edges can be peer-o-peer while others are forwarded via the supernode. Only the edge knows about how it connected to the others. It is a property not specific to one edge but specific to each pairwise connection between edges making it an _n²_ status output.
