### ISSUE TITLE
Drop openSSL 1.0 support & other library handling

### ISSUE THREAD

**Issue by Logan007** [ntop/n2n#402]
With the latest changes that offer integrated implementations for all ciphers, we might not need openSSL **1.0** support anymore.

openSSL **1.0** is only used for AES in case openSSL **1.1** is not available. In my limited test environment, the now included software AES (plain C) beats openSSL **1.0**'s AES on every computer (several Intel CPUs, Raspberry Pi 3B+).

If nobody experiences any different results, I want to drop the openSSL **1.0** support – defaulting to the built-in AES implementation instead. Please share your experience!

Optional openSSL **1.1** support remains untouched. Without any manual intervention, it gets used if found during compilation. Is this a behavior we should change? Should openSSL be completely optional and only be enabled if explicitly configured? That would require changes to the configuration process of which maybe somebody understands more than I do. Any thoughts?

**Comment by skyformat99** [comment]
support.
Use cmake or other, the user can set their own, default not to use openSSL.

**Comment by Logan007** [comment]
I think I can manage to have the openSSL support required to explicitly be enabled during the configuration process. If it works out, it will be like `./configure --with-openssl` to have the configure script check for openSSL. It will remain unchecked for and unused otherwise (defaulting to the built-in ciphers). See #410.

What about zstd compression? To use it or not to use it by default? If present, of course…

**Comment by skyformat99** [comment]
> I think I can manage to have the openSSL support required to explicitly be enabled during the configuration process. If it works out, it will be like `./configure --with-openssl` to have the configure script check for openSSL. It will remain unchecked for and unused otherwise (defaulting to the built-in ciphers). See #410.
> 
> What about zstd compression? To use it or not to use it by default? If present, of course…

thanks.
set it not to use this by default.
But allow the user to choose.  
Because in a cross-compiled environment, relying on automatic search is not feasible.

**Comment by Logan007** [comment]
> set it not to use this by default.

Thank you for your statement! I am fine with any default. As it got the most votes so far and resembles the newly proposed `--with-openssl` behavior, I will add it to the same pull request.

> Because in a cross-compiled environment, relying on automatic search is not feasible.

That, indeed, is a very good point. It made me check if _zstd_ can easily be integrated and found that it probably is not too hard to do but the number of required source code files to pull in is very likely to exceed the number of n2n's own files.

**Comment by skyformat99** [comment]
> That, indeed, is a very good point. It made me check if _zstd_ can easily be integrated and found that it probably is not too hard to do but the number of required source code files to pull in is very likely to exceed the number of n2n's own files.

Because the ZSTD is so large, it is not appropriate to integrate it into n2n.
It's best to keep the N2N small, light and compact.
