### ISSUE TITLE
compile error on Visual Studio 2015

### ISSUE THREAD

**Issue by skyformat99** [ntop/n2n#415]
![image](https://user-images.githubusercontent.com/10938976/92849693-32ff2680-f41e-11ea-9f66-35b2a4fc4020.png)

**Comment by skyformat99** [comment]
It seems to be a problem with the function speck_ctr( )  in file speck.c.

**Comment by Logan007** [comment]
I do not see such an error on Linux. Maybe it is related to the includes and header files. I will try to find something during the weekend but cannot test on Windows.

**Comment by Logan007** [comment]
@skyformat99 Does it help to remove the `inline` keyword from line 667 of the `src/speck.c` file?

**Comment by skyformat99** [comment]
> @skyformat99 Does it help to remove the `inline` keyword from line 667 of the `src/speck.c` file?

yes, you are right.
Delete the inline and  can compile.

**Comment by Logan007** [comment]
Okay, thank you for the feedback. I will provide a pull request.

**Comment by skyformat99** [comment]
thanks
