### ISSUE TITLE
Big problem between windows and jetson nano ubuntu 

### ISSUE THREAD

**Issue by MrCuiHao** [ntop/n2n#416]
hello friend, I have a big problem, when I using jetson nano device with ubuntu 18.04 LTS arm system to ping another jetson nano device，ping is ok，but when I use windows 10 ping jetson nano device , ping is blocked.  Magically, when I using jetson nano 1 keep ping jetson nano 2 until ping is ok，windows 10 can ping jetson nano 2，sorry about my English，you can also have a look at the pictures below 
![image](https://user-images.githubusercontent.com/37323877/92854598-ea4a6c00-f423-11ea-8c66-989360e4f8b9.png)
![image](https://user-images.githubusercontent.com/37323877/92854069-2df0a600-f423-11ea-9648-c50de9efa446.png)

**Comment by MrCuiHao** [comment]
this changed picture is same as the above
![image](https://user-images.githubusercontent.com/37323877/92856385-f7685a80-f425-11ea-8179-fbd460020220.png)

**Comment by Logan007** [comment]
It looks a bit related to the Windows computer. Just guessing:

- Maybe the firewall? You could try to use `-p 5555` option with Windows edge. It will make n2n edge listen on local port 5555. Then, you could allow the Windows firewall to open this UDP port 5555 to n2n edge.

- Or is it maybe the ISP NAT? You could also try to use the Windows edge with `-S` command line option. This will always connect the Windows edge to the supernode (not p2p). Maybe it is more reliable in your case.

- Is Windows n2n version exactly the same version as Linux n2n? (A lot of changes during the last weeks).

**Comment by MrCuiHao** [comment]
thanks for your reply. I used same version, but not the newest version. ActuaIly，the network is ok between windows and ubuntu,   but when I added more ubuntu and windows edge node, windows edge node can't access the other ubuntu edge node, the network between ubuntu edge node is not good, I just test your answer, it can only access for a while，  about 1 second，then the network is blocked, but when I changed the port of supernode from 53 to 54,  the windows can access the ubuntu , everything is ok, it's so strangely

**Comment by MrCuiHao** [comment]
> It looks a bit related to the Windows computer. Just guessing:
> 
> * Maybe the firewall? You could try to use `-p 5555` option with Windows edge. It will make n2n edge listen on local port 5555. Then, you could allow the Windows firewall to open this UDP port 5555 to n2n edge.
> * Or is it maybe the ISP NAT? You could also try to use the Windows edge with `-S` command line option. This will always connect the Windows edge to the supernode (not p2p). Maybe it is more reliable in your case.
> * Is Windows n2n version exactly the same version as Linux n2n? (A lot of changes during the last weeks).

thanks for your reply. I used same version, but not the newest version. ActuaIly，before the network was ok between windows and ubuntu, but when I added more ubuntu and windows edge node, windows edge node can't access the other ubuntu edge node, the network between ubuntu edge node is not good, I just test your answer, it can only access for a while， about 1 second，then the network is blocked, but when I changed the port of supernode from 53 to 54, the windows can access the ubuntu , everything is ok, it's so strangely

**Comment by Logan007** [comment]
> changed the port of supernode from 53 to 54, the windows can access the ubuntu , everything is ok, it's so strangely

I am glad to hear that everything works fine on supernode port 54.

Maybe, port 53 (original DNS?) just gets filtered for well formed packets by Windows or some other firewall on their way?
