### ISSUE TITLE
support multiple supernodes

### ISSUE THREAD

**Issue by lovitus** [ntop/n2n#421]
Will it support multiple supernodes?
I want n2n vpn to get more tolerant such as one of the supernodes is down.

**Comment by Logan007** [comment]
Indeed, this has been discussed from time to time. Please see #45, #24, and #22 as well as parts of #292. 

As of now, several supernodes are supported. It just had to be known to the edges beforehand (simply by an additional `-l` at the edge). This happens in a backup-fashion: A reserve-supernode can be started if one fails. Actively using them in parallel will have your network partitioned (some edges connected to one supernode, some to another).

Considering these known limitations, current discussions however seem to move more towards a fully p2p-approach which then would require no supernode at all, every node might be equal highly increasing network resilience.

**Comment by lovitus** [comment]
> Indeed, this has been discussed from time to time. Please see #45, #24, and #22 as well as parts of #292.
> 
> As of now, several supernodes are supported. It just had to be known to the edges beforehand (simply by an additional `-l` at the edge). This happens in a backup-fashion: A reserve-supernode can be started if one fails. Actively using them in parallel will have your network partitioned (some edges connected to one supernode, some to another).
> 
> Considering these known limitations, current discussions however seem to move more towards a fully p2p-approach which then would require no supernode at all, every node might be equal highly increasing network resilience.

I'm sorry to open this issue without search related info before.
thanks for your reply and your post written in there [https://github.com/ntop/n2n/issues/24#issuecomment-459502556](https://github.com/ntop/n2n/issues/24#issuecomment-459502556)

**Comment by Logan007** [comment]
No worries… perhaps we should add this to the FAQ document.
