### ISSUE TITLE
Setting MAC address on edge under windows

### ISSUE THREAD

**Issue by danrobbo** [ntop/n2n#43]
Hi, 

Has anyone been able to set the MAC address of the tap interface using the -m parameter under windows? As far as I can tell this hasn't been implemented in Win32.

`edge.exe -c mynetwork -a 1.2.3.4 -l 10.0.0.5:1234 -m 00:FF:34:BD:A7:A1`

**Comment by ghost** [comment]
Confirm that mac assignment under Windows 2019 is not working:

![BigMac](https://user-images.githubusercontent.com/10000402/55290566-a0ef9380-53cc-11e9-8d04-96ab16ed6657.png)
