### ISSUE TITLE
Supernodes need to keep list of peers 

### ISSUE THREAD

**Issue by fcarli3** [ntop/n2n#432]
The idea is to create a "federation" of supernodes where each one knows the others. The federation can be an additional community, maybe with a special flag, where only supernodes allowed in. So, the federation can be handled as a regular community throughout the entire code, using the `sn_community` structure.
That way, a supernode needs a new field in its structure: a list of `peer_info` which every item contains informations about a known supernode.

**Comment by Logan007** [comment]
> a supernode needs a new field in its structure: a list of peer_info which every item contains informations about a known supernode

It might be sufficient to add a new field to the `sn_community` (**not** to `peer_info`) structure indicating if this community is a/the federation or not (a regular community then), e.g. `is_federation`.

**Comment by fcarli3** [comment]
Yes, but in `n2n_sn_t` structure how can we represent the list of other supernodes?

**Comment by Logan007** [comment]
> how can we represent the list of other supernodes?

It is already in the `sn_community` structure, just use the list of peers/nodes, supernodes in this case:

```C
  struct peer_info *edges; 		      /* Link list of registered edges. */
```

That will allow to treat the other supernodes as nodes, just like the edges, mostly no special treatment required, not even in the code.

Find the list (if ever required) by ITERating through the list of communities, checking for `is_federation`. A link to this special community might not be required. Most of the times (if not always), access to the federation will happen in the context of accessing other community as well, e.g. for purging, so there might be no need to have a special pointer.

Also (but I am not sure about that), I do not know how sorting of the communities (that happens from time to time for optimizing header decryption) would affect this pointer.

**Comment by fcarli3** [comment]
Yes, it seems better than my original idea. So we only have to do #433
