### ISSUE TITLE
Supernodes must handle registrations requests from other supernodes

### ISSUE THREAD

**Issue by fcarli3** [ntop/n2n#434]
The concept uses the `from_supernode` flag, the community name (or federation name) and relies on REGISTER_SUPER packets (and the corresponding REGISTER_SUPER_ACK) exchanged between supernodes. A supernode handles a REGISTER_SUPER packet in `process_udp` and it checks the origin of the received packet. It would not know if a packet comes from another federation and interpret it as regular community. Only, that the packet has the "from_supernode" flag set, which would make it discard the packet. 

That way, we only need an additional compare to make sure that the `from_supernode` value corresponds to our internal federation marking of that community. A comparison like `if (from_supernode != comm.is_federation) return;` in the specific `case` of `process_udp` could work.

It only continues if is a regular community (`from_supernode` unset because from edge and `comm.is_federation` unset) or if it is a legit packet from another federated supernode: those will be the same (`from_supernode` set as from supernode and `comm.is_federation` set because it is our well-known federation)

**Comment by fcarli3** [comment]
@Logan007 I'm trying to solve this issue but I have a doubt.
My understanding is that after a supernode handles a REGISTER_SUPER, it builds REGISTER_SUPER_ACK message. In this message there are two interesting fields:
- `num_sn`: it provides the number of additional supernodes
- `sn_bak`: for each additional supernode there is its socket 

So my idea is to take the length of the supernodes list and save it in `num_sn`. Then, for each `peer` of this list, I could take the `peer.sock` and copy it in `sn_bak`. 
However, looking at the REGISTER_SUPER_ACK structure, it seems `sn_bak` can store only one socket, but maybe I'm wrong.
This is an example of what I would like to do, but I don't know if I can with `sn_bak`.
```C
HASH_FIND_COMMUNITY(sss->communities, &sss->federation, fed);
if(fed){
	ack.num_sn = (int)HASH_COUNT(fed->edges); /* number of supernodes in the federation */
	if(ack.num_sn > 0){
		HASH_ITER(hh,fed->edges,scan,tmp_peer){
			memcpy(ack.sn_bak, &(scan->sock), sizeof(n2n_sock_t));
		}
	}
```

**Comment by Logan007** [comment]
Basically, this understanding is correct and the code should work (+/- details).

You are right, as of now, it only puts sockets in there. But it does not mean that you could not put any other additional structures in there (MACs) – the memory is yours! Encode and decode should match, of course.

Another thing: You might want to limit the number of other nodes' data you send with the packets. Make sure that the packet buffer does not overflow and we remain in reasonable limits, maybe below MTU to stay safe. Also, you need to make a selection anyway, as you only want to copy the recently active ones (having a timestamp younger than the 20 second limit) as discussed elsewhere (purging?). A general approach could be to pick random ones from the community (how many? (MTU - REGISTER_SUPER_ACK intro size) / (MAC size + socket size) ... or so) which fulfill the 20 second criterion. Looks like another sub-routine…

**Comment by fcarli3** [comment]
Ok, so I could add a new field, e.g. `mac_addr`, in REGISTER_SUPER_ACK structure. That way, if `num_sn > 0`, each supernode has its socket `sn_bak` and its MAC address `mac_addr`. I guess `HASH_ITER` function iterates over the various supernode and avoid phenomena such as overwriting of nodes' data.
After this, as you said, if I'll need to limit the number of nodes' data, I'll have to do a selection basing on the timestamp (we discuss about this also in re-registration and purge process). Is it right?

**Comment by Logan007** [comment]
> I guess HASH_ITER function iterates over the various supernode and avoid phenomena such as overwriting of nodes' data.

HASH_ITER is the comfortable `for` replacement for any hashable structure. It will make sure that it iterates through the whole hash list (and even is delete-safe – you can delete the current item from the hash list using HASH_DEL and the iteration will continue anyway).

> I'll need to limit the number of nodes' data

Yes.

> I'll have to do a selection basing on the timestamp

Yes.

> Is it right?

Yes.

The available space determines the number of nodes' data you can send. This max number can be determined upfront (before iteration), maybe even as macro. Easiest for now would be add each eligible node (`if(now-timestamp < RE_REGISTRATION_LIMIT)...` or so) and to count them up to that max number (`break` the iteration then).

Advanced scheme could pre-select the eligible ones first whilst counting them. From this sub-set, the predefined max number of nodes can get randomly selected. There are several ways to do that, an algorithmic question. Forget about this paragraph for now.

**Comment by fcarli3** [comment]
So, if I understand well, you suggest to check the number of supernodes in the federation (`HASH_COUNT` function) and the available space in the sending buffer (is there a function or some to do this?). After that I would check eligible nodes and copy their informations in REGISTER_SUPER_ACK until the sending buffer will be full. 
To check the eligible nodes, I see some interesting fields in `peer_info` structure but I don't know the differences between them: `last_seen` and `last_valid_time_stamp`. Which is the best or the most correct to use?

**Comment by Logan007** [comment]
Thinking in pseudo-code, very pseudo… :

```
number = 0
ITER (comm)
    if ((now - comm.last_seen) >= ALLOWED_TIME) 
       continue; /* skip the long-time-not-seen ones */
    if ((++number) * ENTRY_SIZE) > MAX_AVAILABLE_SPACE_FOR_ENTRIES
        break; /* done early if no more space availble */
   copy field information

copy number to sn_num
```

We do not need the max number HASH_COUNT (as HASH_ITER iterates thorugh the whole set, only MAX_AVAILABLE_SPACE calculated as depicted above (+/- 1) is required).

Please use `last_seen` (`last_valid_time_stamp` is a micro second counter used for time stamps in header encryption).

**Comment by fcarli3** [comment]
Would `ENTRY_SIZE` be the size of the informations of each supernode (e.g., `sizeof(n2n_sock_t)+sizeof(n2n_mac_t)`). 

Then, `MAX_AVAILABLE_SPACE_FOR_ENTRIES` is the same as `N2N_SN_PKTBUF_SIZE` ? Because I really don't understand if I have to compute it or it is already present in the code

**Comment by Logan007** [comment]
> Would ENTRY_SIZE be the size of the informations of each supernode (e.g., sizeof(n2n_sock_t)+sizeof(n2n_mac_t)).

Yes.

> Then, MAX_AVAILABLE_SPACE_FOR_ENTRIES is the same as N2N_SN_PKTBUF_SIZE ?

No.

Well, this is the point to think about packet sizes. `N2N_SN_PKTBUF_SIZE` is just the internal max buffer size for packet handling (`2048` bytes if I remember correctly). Packets to be transmitted usually are much smaller (also see the MTU section of the TAP Configuration document). Internet allows for roughly 1500 byte-sized packets. The non-PACKET¹ packets include the n2n specific additions, the actual available net size thus is smaller. That is why net payload of PACKETs is allowed with an MTU size of 1290 bytes only. As the non-PACKETs do not have the ethernet frame payload, we might have some more space available, but I would no count on it. So, to stay safe, we better assume that we only have MTU-size bytes available (MTU either defaults to DEFAULT_MTU or is set by command line at **edge**, we here (at **supernode**) could use the default or just half or even third of it, to stay _very_ safe (I have seen public networks allowing only MTU of 600 bytes) – to be discussed with a network expert). From this max packet size we need to deduct the fixed parts of the REG_SUPER_ACK packet (common section with MACs and community, flags, sn_num, … please see the encode/decode functions in `wire.c` to get a notion of the single fields' sizes) to calculate the `MAX_AVAILABLE_SPACE_FOR_ENTRIES`.

> Because I really don't understand if I have to compute it or it is already present in the code

It is no present yet. As this seems pretty much constant, you do not want to re-calculate it all over and over again. If I implemented it, I would put it (as calculation expressed with constants) in a macro. But that is a debatable style-related question.

____________
¹ all packets have a header including a common section with the MACs, community name, … data PACKETs even more such as compression indicator, encryption indicator, IV for encryption… and the payload is encapsulated in ethernet frame which adds an ethernet header

**Comment by fcarli3** [comment]
I've seen `encode/decode` functions of REGISTER_SUPER_ACK and I think we have to compute the amount of space occuped by common section, cookie, MAC address, net_addr, net_bitlen, lifetime, socket and num_sn. I've also seen how `encode/decode` functions works for `uint8_t`, `uint16_t`, `uint32_t` and `uint64_t`, and I've read that I can't use `sizeof()` with these last data types due to compilers and architectures. So I've tried to write a macro:

```C
#define MAX_AVAILABLE_SPACE_FOR_ENTRIES \
             DEFAULT_MTU - \(1+1+2+sizeof(n2n_common_t)+sizeof(n2n_cookie_t)+sizeof(n2n_mac_t)+1+2+4+1+sizeof(n2n_sock_t)+1); \
```
Could it work?

**Comment by Logan007** [comment]
I would do it that way. But that does not mean that it meets the project's coding style :wink:

Do not forget to add a comment explaining where you got the sizes from, not for every byte but refer to "field sizes of REGISTER_SUPER_ACK as used in wire.c" or so.

I am not able to tell if it does exactly what you want. To find out, you might create your own _"dirty debuggin' branch"_, add this line somewhere (where it definitely gets seen), and temporarily use `fprintf`s to `stdout` (or so) to find out (as you might not have REGISTER_SUPER_ACKs to be handled yet or do not want to setup edges as well, you might want to add the `fprintf` at another place, maybe `main()` or `sn_init()`). I admit that there possibly are more elegant ways to debug, I am not your best advisor on that.
