### ISSUE TITLE
process_udp dropped a packet with seemingly encrypted header for which no matching community which uses encrypted headers was found.

### ISSUE THREAD

**Issue by VikramAIS** [ntop/n2n#444]
Hi,

When I am trying to edge on my VM, I am getting the message "process_udp dropped a packet with seemingly encrypted header for which no matching community which uses encrypted headers was found." on supernode and "Warning: Server not responding" on edge.

Thanks,
Vikram

**Comment by Logan007** [comment]
Hello,

Please make sure that edge and supernode have the exact same built version, e.g. both from current dev. We creently have had a lot of changes to packet format so it is important to have all participants (edges **and** supernode) being built from the same source code of the exact same version.

**Comment by VikramAIS** [comment]
Thank you...Logan. I can able to establish connection now. Any script to test the multicast working properly?

**Comment by Logan007** [comment]
I am glad that it works for you. Thanks for bringing up the question. We might add it to the FAQ.

Are you referring to general ethernet broadcast? That one should work (nearly) out of the box, just give `-E` to edge's command line options. I found it working just by using broadcasting apps such a minidlna which flawlessly works between n2n edges.

Or, are you talking about the local ethernet edge detection? That should work out of the box (not on Windows). The debug output (`-vvvvv`) will show `[P2P] Rx REGISTER from <socket>`. Not sure as I have not tested it, but you might see a local IP address here if it originates from a local peer.

**Comment by VikramAIS** [comment]
What is the multicast ip address EDGE uses to send messages and its default portnumber?

**Comment by Logan007** [comment]
Are you looking for [this](https://github.com/ntop/n2n/blob/3f8d32fa77f64e81268a9d68b6576ecc518cb723/include/n2n_wire.h#L36)?

**Comment by VikramAIS** [comment]
Yes, thank you verymuch

**Comment by Logan007** [comment]
You are most welcome.
