### ISSUE TITLE
Handle REGISTER_SUPER_ACK payload 

### ISSUE THREAD

**Issue by fcarli3** [ntop/n2n#449]
An edge has to analyze REGISTER_SUPER_ACK payload in order to find out which supernodes are available. After the edge decodes the message, it could use the existing code in `re_register_and_purge_supernodes()` (`src/sn_utils.c`) to check alive supernodes and add them in a specific data structure.

**Comment by Logan007** [comment]
I think that packet handling will much resemble the part you did for the supernode. You could also switch to the same data structure, i.e. a hash list of `peer_info_t`. That might require a few changes in the remaining edge code (whenever the supernodes get handled in their array, we need to switch to hash list – I do not expect too many places; however, we need to point to the current supernode or mark it with a flag such as `is_current`).

**Comment by fcarli3** [comment]
>  (whenever the supernodes get handled in their array, we need to switch to hash list – I do not expect too many places; however, we need to point to the current supernode or mark it with a flag such as is_current)

Sorry, but I didn't understand very well this last part. Could you give a deeper explaination, please? Thank you!

**Comment by Logan007** [comment]
As far as I remember, the edge keeps the supernodes in an array (`sn_ip_array[]`). That would need to be replaced with a hash list of `peer_into_t`.

As a consequence, a few changes to the code are required, for example the registration process iterates through this array (over time), see the repeatedly called (from main loop) `update_supernode_reg()` in `edge_utils`. And to any other place that deals with this array.

If we have a hash list, we need to keep track of the supernode to which the edge currently is registered. That could be a pointer into the hash_list (not sure if it works – does sorting change the position in memory or only the pointer chains in hash list?) or a flag like `is_current` to the peer_info (would require search to find current supernode, maybe not so good).

**Comment by fcarli3** [comment]
> If we have a hash list, we need to keep track of the supernode to which the edge currently is registered. That could be a pointer into the hash_list (not sure if it works – does sorting change the position in memory or only the pointer chains in hash list?) or a flag like is_current to the peer_info (would require search to find current supernode, maybe not so good).

Maybe the second option is better because even if it has a little cost assures us to find the current supernode if it's in the list. I don't know if a pointer could work because I don't know well how sorting works

**Comment by Logan007** [comment]
Found [it](https://troydhanson.github.io/uthash/userguide.html#_your_structure)! So, we could use a pointer. Could it ever happen that the current supernode gets purged and thus getting a zombie*?

**Comment by fcarli3** [comment]
> So, we could use a pointer.

Could we add directly in `n2n_edge` structure ?

> Could it ever happen that the current supernode gets purged and thus getting a zombie*?

Could we handle that and send REGISTER_SUPER to another supernode ?

**Comment by Logan007** [comment]
> Could we add directly in n2n_edge structure ?

Yes, and that would replace at least `sn_idx`.

>> Could it ever happen that the current supernode gets purged and thus getting a `zombie*`?

> Could we handle that and send REGISTER_SUPER to another supernode ?

We just need to make sure that we do not delete a node from the list which is pointed to by the newly added `pointer_to_current_supernode`. That will probably require some precautions during the **purge** (`if(…)`). But can a current supernode ever be purged? After re-registration time-out (20 sec), the pointer probably remains set to the formerly current supernode (and re-registration process be initiated) until successfull re-registration will have happened. But what happens if we do not succeed in re-registration before the item eventually gets deleted after 90 sec?
