### ISSUE TITLE
Multiple supernodes do not increase network availability

### ISSUE THREAD

**Issue by dinopio** [ntop/n2n#45]
Hi I was wondering if a supernode is ok to be a client also.

Here is my setup

4 machines running edge, 2 of which have supernodes on them
all 4 machines subscribes to all supernodes

when i kill a supernode the network dies and does not use the other supernode.
Any ideas?

**Comment by lucaderi** [comment]
Please report how you have started the edge/supernode

**Comment by emanuele-f** [comment]
This is also related: https://github.com/ntop/n2n/issues/24

**Comment by Logan007** [comment]
Meanwhile, the federation feature has been implemented.
