### ISSUE TITLE
Define a supernode selection strategy 

### ISSUE THREAD

**Issue by fcarli3** [ntop/n2n#450]
After an edge finds out alive supernodes, it should choose one to connect with, maybe the best one according to a specific strategy. We could develop a strategy based on latency for now, then we could combine with other criteria (e.g. workload of a supernode).
We could use a function called by a function pointer so we can change it in the future if necessary

**Comment by Logan007** [comment]
How to get the latency?

A timestamp of REGISTER_SUPER's sending time could be compared to current time upon arrival of REGISTER_SUPER_ACK. But then, we already are registered. So, how to get a complete picture of the latencies?

Maybe, we do not need that complete picture. A somewhat lazy approach would be to send out REGISTER_SUPER to all known supernodes at the same time and accept every REGISTER_SUPER_ACK but only register with the first one (this implicitly is the one with the lowest return-time) while evaluating the others (extract their supernode list payload). That would require something like a global status of `needs_registration` (don't we have that already?) or a function that can always check for it. The status must change from _unregistered_ to _registered_ with the actual registration on first answer.

Following this strategy will make it hard to easily switch selection strategy later which might require a (somewhat) full picture on the selection criterion.

**Comment by Logan007** [comment]
Another recent thought I want to share:

If the supernodes are kept in a hash_list structure at the edge, registration could just try one after another in that list. This list just needs to get sorted by the selection criterion which could be anything you want. 

For example, see `sn_utils.c` how communities get sorted by amount of traffic. Of course, the list of supernodes would need other criterions to be sorted by. But implementing it this way (sorting), the scheme could easily be adopted later-on just by changing the criterion (ping, number of edges served by that supernode which would need to be polled, …).
