### ISSUE TITLE
LAN discovery

### ISSUE THREAD

**Issue by aman448** [ntop/n2n#452]
It's seem that I/we can't get working services LAN discovery,
There may be a configuration problem? or is it currently not possible?

**Comment by Logan007** [comment]
LAN discovery via multicast is disabled on Windows because there were too many issues, see #65.

Concerning other operating systems, we have not heard of any problems recently.

Please note that in case you use `-S` on edge's command line, all connections will be made through the supernode – also those to locally neighboring peers. Other than that, the feature is not configurable.

**Comment by aman448** [comment]
Thanks for the quick reply, yes it happened to my friend which is on Windows 10, while I myself on Linux.

**Comment by Logan007** [comment]
If you are able to compile yourself for Windows, you might want to re-enable it by commenting line 31 of the `include/edge_utils_win32.h` file and experiment with the findings of #65: some blame a driver version.

**Comment by aman448** [comment]
I can't figure out it, there may problem on **my end**,
I tried torrenting and got nothing via "Local Peer discovery" with a friend who is using Windows 10.
later I tested some video games that were hosted on VPS (Quake 3, Jedi Knight), searching LAN network for games
and got nothing again.
Here the configuration:
Me (Linux):
``./edge -S -A3 -r -E -D -z2 -c *** -k *** -a 192.168.254.1 -p 50001 -l ***:***``
Edge runs on the same machine that runs supernode (VPS) (Linux):
``./edge -S -A3 -r -E -D -z2 -c *** -k *** -a 192.168.254.2 -p 50001 -l ***:***``

**Comment by Logan007** [comment]
> Please note that in case you use `-S` on edge's command line, all connections will be made through the supernode – **also those to locally neighboring peers.** 

That is, there will be no multicast peer registration (because everything runs through the supernode).

Please try to **omit** `-S`.

**Comment by Logan007** [comment]
_P. S._ Are we talking about the same thing? Is your friend physically in the same LAN than you? Or are you talking about trasmitting general broad/multocasts through n2n?

**Comment by aman448** [comment]
> _P. S._ Are we talking about the same thing? Is your friend physically in the same LAN as you are? Or are you talking about transmitting general broad/multicasts through n2n?

Not physically, and about generally transmitting multicasts. In text above I mention that I tried running some video games servres on VPS machine for testing purpose.

I removed all options beside `-c`, `-k`, `-a`, `-p`, `-l` i.e
`sudo ./edge -c *** -k *** -a 192.168.254.* -p 50001 -l ***` for both machines
I still won't get expected behavior

**Comment by Logan007** [comment]
Oh, I see.

The last hint I could give is to enable ip forwarding on your linux machines (also VPS) using the `sudo sysctl -w net.ipv4.ip_forward=0` command as seen in the [Routing](https://github.com/ntop/n2n/blob/dev/doc/Routing.md) documentation.

**Comment by aman448** [comment]
I got it working, thanks for helping and sorry for wasting time.

**Comment by Logan007** [comment]
You are welcome!

So, what was the issue? (Please share your finding so others might benefit.)

**Comment by aman448** [comment]
Enabling IPv4 forward and configuring  `-n` get what I wanted to, I simply overlooked docs and fell into pit of ignorance.

**Comment by xiahuaijia** [comment]
n2n-2.8
I was testing the minecraft LAN and found that the server was not found.  It is normal to use ip connection.

I also want to enable LAN discovery. I tried to enable IPv4 forwarding and configure routing but it didn't work
Use `-n` edge to stop running

Do I need to modify `include/edge_utils_win32.h #define SKIP_MULTICAST_PEERS DISCOVERY` and recompile to solve it

'edge.exe -c=GTFO -A3  -D -E -r -v -k=*** -l=**** -d="OpenVPN TAP-Windows6" -a=192.168.100.123'

**Comment by Logan007** [comment]
@xiahuaijia I am not fully aware of your exact setup and what you want to achieve. Could you provide some more information? Is the Minecraft server on the same computer than the other edge? Are the two edges in the same local area network?

You probably do not need to re-compile.

Also, please be aware that `-n` is for adding other/additional routes, it requires some additional information (a route, maybe `-n 0.0.0.0/0:10.0.0.1`), it does not work alone. Have you seen our [Routing](https://github.com/ntop/n2n/blob/dev/doc/Routing.md) document? It contains some helpful hints.

@aman448 Could you give some more hints on how you configured routes in your setup?

**Comment by xiahuaijia** [comment]
Minecraft is not running as a server. There is an open to lan option in singleplayer

Use two computers in the physical LAN to run minecraft. Run singleplayer on one of the computers and open to LAN. The other computer can search for LAN games among multiplayer players.
https://youtu.be/0a3YkQN1tCI
![S.png](https://i.loli.net/2020/12/22/RodVTc2i9SMXGe3.png)


When using edge:
Run edge on two computers with the same parameters, I want all data to pass through `supernode` so use `-S`
A ip: 192.168.100.100
B ip: 192.168.100.101
`edge.exe -c=GTFO -A3 -D -E -r -v -k=*** -l=**** -d="OpenVPN TAP-Windows6" -a=192.168.100.123 -S -n=192.168.100.0/24:172.17.73.208`

I set the TAP network card metric of the two computers to 10

```
>netsh interface ipv4 show interfaces
Idx     Met         MTU          State                Name
---  ----------  ----------  ------------  ---------------------------
  1          75  4294967295  connected     Loopback Pseudo-Interface 1
  9          10        1290  connected     OpenVPN TAP-Windows6
 10          25        1500  connected     Ethernet
```

Now open LAN in Minecraft singleplayer, unable to search LAN server

![Sng](https://i.loli.net/2020/12/22/XaLCdNv3eQl7Bm4.png)


Server ifconfig
![Snip.png](https://i.loli.net/2020/12/22/cxVA5CIznygS8JN.png)


```
# sysctl -p
vm.swappiness = 0
kernel.sysrq = 1
net.ipv4.neigh.default.gc_stale_time = 120
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.default.rp_filter = 0
net.ipv4.conf.default.arp_announce = 2
net.ipv4.conf.lo.arp_announce = 2
net.ipv4.conf.all.arp_announce = 2
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 1024
net.ipv4.tcp_synack_retries = 2
net.ipv4.ip_forward = 1
```

**Comment by Logan007** [comment]
Do I understand correctly that it works well if you give the other computer's IP address as server IP (192.168.100.100 or 192.168.100.101) directly? And the two edges probably can ping each other, right?

~~If so, it seems to be a Minecraft multicast issue as described [here](http://blog.zencoffee.org/2016/12/minecraft-local-server-discovery-cant-find-lan-games/). I could imagine that Minecraft does not bind to the virtual network adapter but to the real one in the first place.~~ _I saw that you already lowered the metric._

For what exact reason have you added the route `-n …`? If you only want to connect two edge nodes (via the supernode), you probably do not need the `-r` and `-n ...` option.

So far, I have not heard of n2n itself having known issues with exchanging multi cast packets between its virtual adapters as long as `-E` is set (which you did) on both edges. You could check if multicast packets get transmitted by making the edges and the supernode more verbose by using `-vvvvvvv` command line option and then ` | grep multicast`  (` | findstr` on Windows?). It should show some multicast activity then. Should one edge or the supernode show less activity than the other edge, we might need to further debug it.

Now that I better understand your issue, I think that you definitely do **not** need to re-compile. The "peer discovery" helps local n2n edge nodes to find themselves much faster if in the same LAN. They create their own multicast group. This is independent from multicast packets of other applications being forwarded/transmitted via n2n.

**Comment by Logan007** [comment]
P. S. `netsh interface ip show joins` should show to which interface Minecraft binds (224.0.2.60). Does it bind to the correct interface?

**Comment by xiahuaijia** [comment]
I checked the interface binding but the same as before. I added the parameter -v to see the multicast information, but the server is still not searched

```
>netsh interface ip show joins

Interface 1: Loopback Pseudo-Interface 1

Scope       References  Last  Address
----------  ----------  ----  ---------------------------------
0                    4  Yes   239.255.255.250

Interface 9: OpenVPN TAP-Windows6

Scope       References  Last  Address
----------  ----------  ----  ---------------------------------
0                    0  Yes   224.0.0.1
0                    4  Yes   224.0.0.251
0                    1  Yes   224.0.0.252
0                    5  Yes   239.255.255.250

Interface 10: Ethernet 7

Scope       References  Last  Address
----------  ----------  ----  ---------------------------------
0                    0  Yes   224.0.0.1
0                    5  Yes   224.0.0.251
0                    1  Yes   224.0.0.252
0                    5  Yes   239.255.255.250
```

I need zstd compression but forgot to add it before. I re-statically compiled the edge with openssl-1.1.1 and zstd (Before using shared library) , re-tested minecraft LAN search of work. There are too many variables and I don’t know what caused the problem but now the LAN search is working. Thank you for your help

![Snip](https://user-images.githubusercontent.com/8602553/102920419-b4f2f700-44c5-11eb-940a-fd7680f552fd.png)

**Comment by xiahuaijia** [comment]
I found out where the problem is. If minecraft has been started before setting the network adapter metric, it will bind to the wrong network adapter until the computer is restarted. Restarting the game will not change the binding network adapter

**Comment by Logan007** [comment]
Thank you for reporting back your finding!
