### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by small-5** [ntop/n2n#453]
After Commit [277b8ba4f46bb1f872ed614dc735602466fbd989](https://github.com/ntop/n2n/commit/277b8ba4f46bb1f872ed614dc735602466fbd989), if supernode uses -c community.list, it will prompt Segmentation fault. It should be related to the recent changes of supernode. The operating platform is Openwrt X86_64 compiled with the latest source code.
![1](https://user-images.githubusercontent.com/61473216/95014477-bc022a00-0679-11eb-9f81-c597ca4d4bd3.jpg)

**Comment by Logan007** [comment]
I do not see this error out here on x86, using the original `community.list` file though. And it does not happen on your platform if you omit `-c`?!

**Comment by Logan007** [comment]
How many characters has your community name in the list-file? All regular ASCII characters (asking for maybe unicode incluencing length)?

**Comment by Logan007** [comment]
@small-5 Could you please try one thing: Move the `    comm_init(s,cmn_str);` of line 94 in the `src/sn.c` file two lines further down, as first instruction inside  the following ` if(s != NULL) {`-block and try again? Thank you!

**Comment by Logan007** [comment]
... and same for `comm_init(comm,(char *)cmn.community);` of line 984 in the `src/sn_utils.c` file?

**Comment by small-5** [comment]
The community name has a total of 7 characters. The same name in the previous version can be started normally.
I will test it later and tell you the result, thank you!

**Comment by small-5** [comment]
I modified these two files in the way you said, but the same error still occurs.
https://github.com/small-5/n2n/commit/e9cc288ba5b56fe0c2b9216f980f49ffb28fe06a

**Comment by small-5** [comment]
I modified these two files in the way you said, but the same error still occurs.
Maybe my previous statement is wrong. The supernode compiled with Commit 277b8ba4f46bb1f872ed614dc735602466fbd989 can be used normally on Openwrt. I mean it can’t be used normally after this version.
![1](https://user-images.githubusercontent.com/61473216/95018733-23c56e80-0694-11eb-9e7f-02f00226d87c.jpg)
![2](https://user-images.githubusercontent.com/61473216/95018735-2627c880-0694-11eb-8bb0-22a92f2939a4.jpg)

**Comment by Logan007** [comment]
Thanks for reporting and especially testing! Let's have a look at the following commits then.

**Comment by Logan007** [comment]
I think I nailed it down to the REGISTER_SUPER handling in line 1140 of `src/sn_utils.c` file. After the `HASH_FIND_PEER(fed->edges, reg.edgeMac, p);` the following block should be guarded by a `if (p) {` which needs to end with an additional closing braced bracket `}` in line 1153/1154.

We will fix that along with the other items mentioned above. For now, I hope it helps.

**Comment by small-5** [comment]
Hope this problem can be fixed, thank you!

**Comment by small-5** [comment]
> Hope this problem can be fixed, thank you!
Cross compilation failed
![1](https://user-images.githubusercontent.com/61473216/95147934-bd843d00-07b4-11eb-8ff5-ed95d69b6c26.jpg)

**Comment by small-5** [comment]
@fcarli3 Cross compilation failed
![1](https://user-images.githubusercontent.com/61473216/95147979-dbea3880-07b4-11eb-9f6e-cde54f6967f3.jpg)

**Comment by fcarli3** [comment]
It should be fixed now

**Comment by small-5** [comment]
Compiled successfully and can be used normally,Thank you!
