### ISSUE TITLE
n2n v.2.9.0 on Pi3 cant connect to demo supernode

### ISSUE THREAD

**Issue by frenchfaso** [ntop/n2n#456]
I´ve just upgraded n2n to latest version (2.9.0.r729.c3805ed) on a Pi3 and now it cant connect to the demo supernode anymore.
It keeps logging this error:

> WARNING: Supernode not responding, now trying supernode.ntop.org:7777

In contrast, on my x86 laptop, the latest version seems to be 2.8, which does work fine indeed.
Am I missing something?

PS: I´ve tried with firewall enabled and disabled (UFW), same warning

Thanks for your help!

**Comment by Logan007** [comment]
Please be aware that 2.8 is the latest stable release, so the demo supernode also is 2.8.

However, 2.9 is actually synonymous to current _dev_ branch. It prepares the somewhen upcoming 3.0 which will be a major release bringing major (not compatible) changes. On that route, current _dev_ has seen a lot of heavy changes so far and probably will see some more. So, it is not backwards compatible anymore (#375).

If you want to test current _dev_ [anyway](https://github.com/ntop/n2n#manual-compilation), you need all edges **and** the supernode being of the same version – in case of _dev_ we recommend even from the same source version (commit counter).

**Comment by frenchfaso** [comment]
Thanks for the quick reply!
I've done a simple "sudo apt install n2n" on the Pi3, after having added the repo following this page:

> https://packages.ntop.org/

An "apt policy n2n" shows 2.9 is the only version available. Is this intended?

**Comment by Logan007** [comment]
I am not sure if the packages page is intended to have stable or nightly builds. Thanks for notifying, we will check.

**Comment by frenchfaso** [comment]
Thanks!
I'll stay tuned.
In the meanwhile I compiled from source on the Pi3 (not without issues #457 )

**Comment by lucaderi** [comment]
For PI we do not have a stable repository, just dev

**Comment by frenchfaso** [comment]
> For PI we do not have a stable repository, just dev

Ok, thanks
