### ISSUE TITLE
I want to be faster. What parameters should be used to run n2n

### ISSUE THREAD

**Issue by huddhudd** [ntop/n2n#467]
I want to be faster. What parameters should be used to run n2n

**Comment by Logan007** [comment]
Maybe you want to have a look at our [Building](https://github.com/ntop/n2n/blob/dev/doc/Building.md) documentation which contains hints on how to build making use of compiler optimizations and hardware features.

Also, the `tools/n2n-benchmark` utility (not on Windows) gives hints which of the ciphers are the fastest ones. You could run it after having compiled with or without optimizations for comparison and switch to a cipher which is faster on your platform.
