### ISSUE TITLE
command line help text

### ISSUE THREAD

**Issue by Logan007** [ntop/n2n#469]
What about displaying a short help text containing the mandatory options in an _usage_ style only (without further explanation) and additionally hinting that `--help` would give more detailed information (showing the full help text with all options then)?

In my opinion, especially `edge` would benefit.

**Comment by fengdaolong** [comment]
When there are more and more parameters for n2n, it is necessary to find a way to fold the parameters to make the command line more concise.

**Comment by fengdaolong** [comment]
This is how git command parameters do, can you refer to the source code of [git](https://github.com/git/git) to see how it is implemented?

**Comment by Logan007** [comment]
Actually, I was inspired by iperf… :wink:

**Comment by Logan007** [comment]
Git is a good example for how well options could be sorted.

**Comment by Logan007** [comment]
Solved by #604.
