### ISSUE TITLE
Edges Identification in One Community

### ISSUE THREAD

**Issue by wlt-cortex** [ntop/n2n#473]
Hello everyone:

I am a new one to the n2n project just approaching yesterday. And I want to know that how can I identify the edge node in some specific community. Here is my case:

Suppose I have two machines named `dev-sever` and `office` in different places and networks. The two are connected with `n2n` in community name: `labs` using DHCP, and then I wonder to know if there are some parameters in the startup of edge node to register human-readable name into supernode so that I can find which name is the right one when listing the accessible peers in edge node or supernode.

> Another proposed problem is that the query command: `nc -u localhost 5644` is out-dated sometimes. I don't know this situation is normal or maybe refresh manually or just wait some time.

some notes:
    
+ I don't find early issues describing the same question.
+ I find some out-dated scripts and `n2n` v1 seems to have the `-d` parameter indicating that edge device name? And now the parameter has been removed yet.

```shell
# On supernode
dnf install dhcp-server dhcp-client n2n -y
systemctl disable dhcpd --now
supernode -f -l 9090 -v

# On supernode/one edge
edge -f -d edge0 -r -a 192.168.1.0 -c foo -k bar -l localhost:9090 -v -A
cat > /etc/dhcp/dhcpd.conf <<EOF
subnet 192.168.1.0 netmask 255.255.255.0 {
        range 192.168.1.10 192.168.1.100;
}
EOF
dhcpd -f edge0

# On all other edges
dnf install dhcp-client n2n -y
edge -f -d edge0 -r -a dhcp:0.0.0.0 -c foo -k bar -l 116.203.50.42:9090 -v -A -m $(echo $(hostname)|md5sum|sed 's/^\(..\)\(..\)\(..\)\(..\)\(..\).*$/02:\1:\2:\3:\4:\5/') # To get the same MAC address and thus the same IP address every time
pkill -9 dhclient; dhclient edge0
```
referenced by [here](https://gitlab.com/snippets/1895685).

+ I know the `static IP` can solve the problem but it's awkward I thought, I need to manually set the static IP and try to avoid the IP conflicting. I have set lots of duplicated IPs when testing early and seems that the supernode will accept this request!!! strange.

So could you tell me how can I do?

**Comment by Logan007** [comment]
Would the MAC address (`-m`) be helpful? Hex-only but readable. However, you still have to avoid conflicts then.

An internal edge-name is not available (yet).

`-d <device name>` is the internal Linux device name (try `ip link`) and defaults to `edge0` if not provided. It only is visible on the local system where it is used for system's device handling purposes.

**Comment by wlt-cortex** [comment]
> Would the MAC address (`-m`) be helpful? Hex-only but readable. However, you still have to avoid conflicts then.
> 
> An internal edge-name is not available (yet).
> 
> `-d <device name>` is the internal Linux device name (try `ip link`) and defaults to `edge0` if not provided. It only is visible on the local system where it is used for system's device handling purposes.

Ok, got it. The DHCP seems to be in conflict with the community structure. Once a person joined a new community, what he sees is pure of numeric values like MAC, edge IP, ...etc. But all of these do little support to him since he won't know the machine function with dynamic IP. Even more, it's hard to correlate the dynamic IP and real machine, although all the supernode and edge nodes may be started by himself.

So I think why not add some hint field(device description) in the source code and expose it in the manager mode? Can this be a new feature to be implemented? Maybe I can help with this, but you should leave enough time for me since I am newer to the project.

**Comment by Logan007** [comment]
> Once a person joined a new community, what he sees is pure of numeric values like MAC, edge IP, ...etc. 

Yes. In this respect, n2n does not offer more than a regular network interface. DHCP server might assign IP addresses (based on fixed MAC addresses) and name resolution can be provided. As far as I can see, DHCP and name resolution are out of n2n's scope as there are many other products that serve these purposes very well.

If you refer to n2n's auto-IP feature, please be aware that this is not intended to provide full DHCP functionality. If required, identification between the edges must happen either based on fixed MAC addresses or on a higher protocol level.

> The DHCP seems to be in conflict with the community structure.

I would not agree with that. In my view, a community is somewhat equivalent to a network in which one can use a DHCP server of course. Note that those usually need fixed MAC addresses.

> So I think why not add some hint field(device description) in the source code and expose it in the manager mode? 

That is an interesting idea. A kind of meta-description only exposed to humans, e.g. via the management port?

> Can this be a new feature to be implemented?

In fact, it would not be too hard to do. However, it is none of my current priorities.

> Maybe I can help with this, but you should leave enough time for me since I am newer to the project.

My experience is that every contribution to the project is very welcome. Please take your time and feel free to submit any code. If you need hints where exactly in the code to look for implementing this feature, just ask. Perhaps on the [Discord](https://www.ntop.org/community/) server?

**Comment by fengdaolong** [comment]
Currently, any edge does not have a unique identifier. Once an edge restarts, the edge's MAC, IP, Socket, etc. information will change, and other edges and super nodes will consider it a new edge.Unless the edge assigns a fixed MAC address to the tutap adapter through the "-m" parameter at startup, this MAC address can be used as the unique identifier of the edge for the time being, but in most cases, no one will specify the MAC address to run the edge.

@Logan007  I have an idea: when the edge is started, it will calculate a MAC address to tuntap by default through some physical hardware ID of the computer (for example, the MAC of the physical network adapter), then this MAC will be the unique identifier of the edge. In the future, regardless of restarting the program, restarting the operating system, or even reinstalling the operating system, the MAC of the edge will not be changed unless specified by the "-m" parameter. Then, N2N adds a function, the super node or any edge can make notes and descriptions on the edge list with its own preference.

**Comment by Logan007** [comment]
> but in most cases, no one will specify the MAC address to run the edge.

And why would anyone specify another identifier then? :wink:

> it will calculate a MAC address to tuntap by default through some physical hardware ID of the computer (for example, the MAC of the physical network adapter)

Sounds good! What about a hash of the lowest MAC found? I just fear that this might become very platform dependent code.

One question, though: What would happen if several edges are started for different networks on the same computer? I have no idea if the OS can handle several adapters with the same MAC even if they belong to different IP networks.

**Comment by betabeauty** [comment]
> My experience is that every contribution to the project is very welcome. Please take your time and feel free to submit any code. If you need hints where exactly in the code to look for implementing this feature, just ask. Perhaps on the Discord server?

Ok, I will join and ask if necessary.

**Comment by fengdaolong** [comment]
>What would happen if several edges are started for different networks on the same computer? 

The operating system does not allow multiple network adapters to use the same MAC address. If the same computer starts multiple edges, let the MAC address of tuntap increment.

**Comment by Logan007** [comment]
That would render the MACs dependant on their order of starting and not so definitely unique (as per network) anymore.

**Comment by fengdaolong** [comment]
This is true, but there will always be ways.
If multiple edges are running on a computer at the same time, their startup parameters must not be the same. In this case, things are easy to handle. You can use the edge operating parameter values ​​(such as: -d) as the calculation condition for the MAC address.  😉😉😉

**Comment by Logan007** [comment]
Of course, the `-d` provided device name! That is **extremely** clever as it defaults (only once) to a certain value (`edge0`) and additional  ones require a different device name anyway. I like that.

So, you suggest to calculate an ID/MAC like `hash(lowest non-n2n available MAC) XOR hash (device name)`?

Umm, but what about Windows systems? As far as I know, they do not have named devices.

**Comment by fengdaolong** [comment]
Cross-platform is a headache, it does increase the complexity of program portability. However, I have another way, that is, the MAC randomly generated when the edge is run for the first time is saved as a file, and then the MAC file stored locally is first checked each time the edge is run, and automatically loaded if it exists, this file can be the edge configuration file "edge.conf".

**Comment by betabeauty** [comment]
Most people do not add a description field when running an edge, and if the number of online edges is large, the description field may be repeated a lot, and finally have to be distinguished by a unique MAC address. I think the description field cannot be reported by the peer edge actively, but is filled in by the users of the currently running edge according to their own preferences, and only the users of the current edge know it.
We need to fully discuss #473, @Logan007  what do you think?

_Originally posted by @fengdaolong in https://github.com/ntop/n2n/pull/475#issuecomment-714917337_

Suppose the two possible situations that choose the n2n project:

### Known Resources Usage

just my case :)

This community to set up is for available resources access, such as person/company serves a lot of servers for friends, staff. A person that joins this community would know what they actually want. For the available resources server, we could supply total (num of characters) ** 16 >> 26 * 16 >> 100000  numbers of the unique names in theory, and it's enough for most of the cases. 

### Resouces Share

Applications like libtorrent or DHT?

A person that wants to acquire some available resources joins the public community. In this view, he would try to find interest resources. And I think the name hint does a little help for him to select different IPs at least, the repeated names is also useful.

We can classify two edge categories generally: server edge and client edge. I think the server side is more important to expose the name hint in the peers' information and the client may not be necessary to set the name hint.

Some ideas about the existed edge startup logic (add query setup):

Edge node will start with some setting query in the command line in the first setup, like if expose name hint to peers/supernode. I think this logic can be implemented easier with a configuration file. Conf file's existence and specific environment variable will control the setup trigger. 

> Cross-platform is a headache, it does increase the complexity of program portability. However, I have another way, that is, the MAC randomly generated when the edge is run for the first time is saved as a file, and then the MAC file stored locally is first checked each time the edge is run, and automatically loaded if it exists, this file can be the edge configuration file "edge.conf".

A combination with the above MAC generation idea, maybe a good start.

**Comment by fengdaolong** [comment]
Okay, I am not against your idea, after all, this is just an optional parameter.
I think the next step should be to let the edge have a unique identity, which will be very useful for subsequent full peer-to-peer communications.
