### ISSUE TITLE
how to tunnel all traffic from one edge to another

### ISSUE THREAD

**Issue by tlsalex** [ntop/n2n#476]
Please see bellow screenshot as my network diagram:
HomePC run edge as a client. 
OfficePC run edge as a client. 
An internet server run supernode as Server.

Home local network: 10.0.0.0/24 gateway 10.0.0.1
Office local network:172.16.0.0/24 gateway 172.16.0.1

N2N network is 192.168.1.0/24
Home edge 192.168.1.33
Office edge 192.168.1.22

P2P connection is established without problem between these two nodes.

I want to tunnel all my homepc traffic to officepc , which is I will access the internet via officepc, rather than from local network.
What route item do I need to add to my homepc ?
Something like this: ip route add 0.0.0.0/0 via 192.168.1.22  dev  n2n0 ? 
But it will not work ,as the default rule should point to the gateway of local network.
![network](https://user-images.githubusercontent.com/36788337/97006154-00def980-1572-11eb-90a1-70ac0cf5afaa.PNG)

**Comment by Logan007** [comment]
If I am not mistaken here, n2n's [`doc/Routing.md`](https://github.com/ntop/n2n/blob/dev/doc/Routing.md) might contain helpful hints as it describes the [exact same scenario](https://github.com/ntop/n2n/blob/dev/doc/Routing.md#route-all-internet-traffic-from-n2n-node-at-home-through-office-network).

**Comment by tlsalex** [comment]
thanks , it works well by this way in linux " In order to tunnel all the internet traffic, use -n 0.0.0.0/0:10.0.0.1" while it does not work in Windows.
