### ISSUE TITLE
install and configure a supernode on an Ubuntu VPS

### ISSUE THREAD

**Issue by frenchfaso** [ntop/n2n#477]
Hy there,
I'm trying to configure a supernode on a little VPS with Ubuntu Server 20.04 lts.
I successfully configured, compiled and installed a 2.8 supernode doing the following:
- ./autogen.sh
- ./configure CFLAGS="-O3 -march=native"
- sudo make install supernode
- copied ./packages/etc/n2n/supernode.conf.sample to /etc/n2n/supernode.conf
- copied ./packages/etc/systemd/system/supernode.service.in to /etc/systemd/system/supernode.service

What user and group should I configure in the supernode.service file?
Should I create a new "n2n" user and a new "n2n" group?

Thanks for the help!

**Comment by Logan007** [comment]
The supernode requires privileges to be started and usually drops privileges to the nobody user (or `-u` and `-g`) shortly after start. Most users might find this to be sufficient.

However, I think I remember a more common recommendation to let every service run as a different user for isolation purposes such that not all services are by the same nobody user. Just in case one service gets hacked, it does not allow for further access.

At the end of the day, it depends on your security needs.

**Comment by frenchfaso** [comment]
Thanks @Logan007 !
For the time being I've added a new user "n2n" with
`sudo adduser --system --group --no-create-home n2n`
which seems to recreate the same situation as if you would install n2n via ntop repositories (system user, login disabled, no home dir)
