### ISSUE TITLE
Windows port is not running successfully

### ISSUE THREAD

**Issue by dirend** [ntop/n2n#49]
Have to change something to compile with VS2017. After running supernode and edge on same machine , they are waiting like these. 

t:\SHARED>edge -a 10.1.2.2 -c mynetwork -k encryptme -l 10.150.17.217:12345
03/Oct/2018 11:13:33 [edge.c:606] Starting n2n edge 2.0.0 Oct  3 2018 10:32:05
03/Oct/2018 11:13:33 [edge.c:609] supernode 0 => 10.150.17.217:12345
03/Oct/2018 11:13:33 [edge.c:649] ip_mode='static'
Open device [name={B3A4C17F-ABD0-4FDF-9B7A-58D79D31C7CA}][ip=10.1.2.2][ifName=Ethernet 2][MTU=1400][mac=00:FF:B3:A4:C1:7F]
Setting Ethernet 2 device address...

Device Ethernet 2 set to 10.1.2.2/255.255.255.0
03/Oct/2018 11:13:33 [edge.c:694] edge started
03/Oct/2018 11:13:33 [edge_utils.c:672] Chose new tx_transop_idx=1
03/Oct/2018 11:13:33 [edge_utils.c:1371] Rx REGISTER_SUPER_ACK myMAC=00:FF:B3:A4:C1:7F [10.150.17.217:12345] (external 10.150.17.217:58198). Attempts 2

t:\SHARED>supernode -v -l 12345
03/Oct/2018 11:13:23 [sn.c:836] supernode is listening on UDP 12345 (main)
03/Oct/2018 11:13:23 [sn.c:847] supernode is listening on UDP 5645 (management)
03/Oct/2018 11:13:23 [sn.c:850] supernode started
03/Oct/2018 11:13:33 [n2n.c:317] Purging old registrations
03/Oct/2018 11:13:33 [n2n.c:322] Remove 0 registrations
03/Oct/2018 11:13:33 [sn.c:148] update_edge created   00:FF:B3:A4:C1:7F ==> 10.150.17.217:58198
03/Oct/2018 11:14:37 [n2n.c:317] Purging old registrations
03/Oct/2018 11:14:37 [n2n.c:322] Remove 0 registrations

**Comment by emanuele-f** [comment]
I can successfully run both supernode and edge node in windows now. This issue is quite old and some fixes has been merged since it was opened, so I'm closing it. Please check the updated instructions on building/running on windows https://github.com/ntop/n2n/blob/dev/doc/Windows.md . If you still experience this with the new version, please open a new issue.
