### ISSUE TITLE
Version is't the same

### ISSUE THREAD

**Issue by lucktu** [ntop/n2n#50]
2018-10-11, The version of n2n for windows is 2.0.0, for ubuntu is 2.5.0, and for padavan is 2.3.0.
Pay attention please, Thank you!

**Comment by emanuele-f** [comment]
Thank you. Windows version fixed in d7b3b2c06b431fad9a60820ef0a58a8c1bebe3ab . Other fixes: 327a847681e35c37d55a4d0aaec419e2fde9634f . If you find other mismatches please open a new issue (or better, provide a pull request)
