### ISSUE TITLE
n2n package for Ubuntu 20.10 (Groovy Gorilla)

### ISSUE THREAD

**Issue by tlsalex** [ntop/n2n#504]
I run Ubuntu 20.10 (Groovy Gorilla) on my laptop. Then tried to install n2n follow the instruction from https://packages.ntop.org/apt-stable/

But currently it's for v20.04. If I run those code on v20.10. I can't get the correct version which should be n2n v2.8 

I would appreciate if someone build n2n package for V20.10

**Comment by tlsalex** [comment]
I compile it from source,
I got bellow warning when I ran it , will it be a problem ?
`[edge.c:918] WARNING: n2n has not been compiled with libcap-dev. Some commands may fail.`

**Comment by yanggis** [comment]
apt install libcap-dev
then try again.

**Comment by tlsalex** [comment]
thanks man @yanggis , install libcap-dev and recompile , then it works well now.
