### ISSUE TITLE
Question: any username/password like protection on supernode(server)?

### ISSUE THREAD

**Issue by fei4xu** [ntop/n2n#514]
Hi,

I'd like to check if I can use some security method like username/password or anything else so that I can protect my supernode/server from being connected by any one?

On the edge side ,the **-k** seems nothing to related to server side, am I right?

**Comment by Logan007** [comment]
Hello,

> I'd like to check if I can use some security method like username/password or anything else so that I can protect my supernode/server from being connected by any one?

May I refer you to our [`doc/Faq.md`](https://github.com/ntop/n2n/blob/dev/doc/Faq.md#i-want-to-setup-a-supernode-that-only-i-can-use-perhaps-even-password-protected) document?

> On the edge side ,the **-k** seems nothing to related to server side, am I right?

Right. `-k` specifies the key for the payload encryption that is the data being exchanged between the edges peer-to-peer or sometimes forwarded via the supernode. The supernode is not able to decrypt the payload data – there also is no need for the supernode to decipher the payload for forwarding. So, the supernode does not require that `-k` parameter.

**Comment by fei4xu** [comment]
Thanks for pointing it out!
