### ISSUE TITLE
ERROR: Failed to decode common section in N2N_UDP

### ISSUE THREAD

**Issue by fei4xu** [ntop/n2n#516]
Hi,

I'm running n2n dev branch (latest commit, you can check the commit in messages below), but the edge can't connect to supernode. 
The error message is like this:

>19/Nov/2020 17:05:16 [edge_utils.c:2961] Adding supernode = 52.52.52.52:8282
19/Nov/2020 17:05:16 [edge.c:813] WARNING: Switching to Twofish as key was provided.
19/Nov/2020 17:05:16 [edge.c:824] Starting n2n edge 2.9.0.r782.e66f913 Nov 19 2020 08:51:48
19/Nov/2020 17:05:16 [edge.c:830] Using compression: none.
19/Nov/2020 17:05:16 [edge.c:831] Using Twofish cipher.
19/Nov/2020 17:05:16 [edge_utils.c:220] Number of supernodes in the list: 1
19/Nov/2020 17:05:16 [edge_utils.c:222] supernode 0 => 52.52.52.52:8282
19/Nov/2020 17:05:16 [edge.c:854] Use manually set IP address.
19/Nov/2020 17:05:16 [edge.c:884] Local tap IP: 192.168.100.102, Mask: 255.255.255.0
19/Nov/2020 17:05:16 [edge.c:909] WARNING: n2n has not been compiled with libcap-dev. Some commands may fai                         l.
19/Nov/2020 17:05:16 [edge.c:914] Dropping privileges to uid=65534, gid=65534
19/Nov/2020 17:05:16 [edge.c:938] edge started
19/Nov/2020 17:05:16 [edge_utils.c:697] Successfully joined multicast group 224.0.0.68:1968
19/Nov/2020 17:05:20 [edge_utils.c:1897] ERROR: Failed to decode common section in N2N_UDP
19/Nov/2020 17:05:20 [edge_utils.c:1897] ERROR: Failed to decode common section in N2N_UDP

There are 2 **ERROR**s in it.

I also tested _2.8-stable_, it runs ok with my supernode.

**Comment by skyformat99** [comment]
Because the version is not compatible

**Comment by Logan007** [comment]
> `[edge_utils.c:1897] ERROR: Failed to decode common section in N2N_UDP`

This error message usually indicates that there are header-encrypted packets coming in that cannot be decrypted. **If** (and I am guessing here) you have other additional edges run with `-H` in local your network, those will send out encrypted (according to their community) multicast REGISTERs (to find local peers faster) causing this error message then. In this case, it is unrelated to the non-connecting issue.

> I also tested 2.8-stable, it runs ok with my supernode.

Please be aware that 2.9 is considered _dev_ and packet format has changed from time to time and will further change until we reach 3.0. Latest stable indeed is 2.8. So, the 2.9 edge is not guaranteed to connect to a 2.8 supernode – in fact, it does not. Please also see that one note in our [`Readme`](https://github.com/ntop/n2n#manual-compilation) file.

**Comment by fei4xu** [comment]
oh, I didn't realize the versions between supernode and edge should be compatible.

As far as I have tested, v2.6 seems to be compatible to v2.8.

**Comment by Logan007** [comment]
> As far as I have tested, v2.6 seems to be compatible to v2.8.

Yes, we try to delay required packet format changes until major version jumps, in this case 3.0 and hopefully are able to keep it compatible up to some 4.0 release then…

Again, 2.9 can be considered the _dev_ preparing 3.0.
