### ISSUE TITLE
Packets periodically stuck in n2n

### ISSUE THREAD

**Issue by lucaderi** [ntop/n2n#519]
There is a problem somewhre in n2n (need to be investigated) that causes packet to be stuck somewhere. This is a edge-to-edge (no via supernode) communication with a stable network link. Pinging the same hosts outside of n2n does not show this behaviour. As there is no packet loss, I believe the edge process is sometime doing some housekeeping activity that prevents the system to work properly.

$ ping 192.168.2.222
PING devel (192.168.2.222): 56 data bytes
64 bytes from 192.168.2.222: icmp_seq=0 ttl=63 time=73.398 ms
64 bytes from 192.168.2.222: icmp_seq=1 ttl=63 time=9.510 ms
64 bytes from 192.168.2.222: icmp_seq=2 ttl=63 time=7.828 ms
64 bytes from 192.168.2.222: icmp_seq=3 ttl=63 time=8.293 ms
64 bytes from 192.168.2.222: icmp_seq=4 ttl=63 time=8.316 ms
64 bytes from 192.168.2.222: icmp_seq=5 ttl=63 time=8.386 ms
Request timeout for icmp_seq 6
Request timeout for icmp_seq 7
Request timeout for icmp_seq 8
Request timeout for icmp_seq 9
Request timeout for icmp_seq 10
64 bytes from 192.168.2.222: icmp_seq=6 ttl=63 time=5050.881 ms
64 bytes from 192.168.2.222: icmp_seq=7 ttl=63 time=4069.765 ms
64 bytes from 192.168.2.222: icmp_seq=8 ttl=63 time=3065.479 ms
64 bytes from 192.168.2.222: icmp_seq=9 ttl=63 time=2060.576 ms
64 bytes from 192.168.2.222: icmp_seq=10 ttl=63 time=1057.787 ms
64 bytes from 192.168.2.222: icmp_seq=11 ttl=63 time=53.567 ms
64 bytes from 192.168.2.222: icmp_seq=12 ttl=63 time=9.022 ms
64 bytes from 192.168.2.222: icmp_seq=13 ttl=63 time=8.142 ms
64 bytes from 192.168.2.222: icmp_seq=14 ttl=63 time=8.701 ms
64 bytes from 192.168.2.222: icmp_seq=15 ttl=63 time=8.819 ms
64 bytes from 192.168.2.222: icmp_seq=16 ttl=63 time=8.245 ms
64 bytes from 192.168.2.222: icmp_seq=17 ttl=63 time=8.985 ms
64 bytes from 192.168.2.222: icmp_seq=18 ttl=63 time=8.499 ms
64 bytes from 192.168.2.222: icmp_seq=19 ttl=63 time=8.795 ms
64 bytes from 192.168.2.222: icmp_seq=20 ttl=63 time=8.610 ms
64 bytes from 192.168.2.222: icmp_seq=21 ttl=63 time=8.668 ms
64 bytes from 192.168.2.222: icmp_seq=22 ttl=63 time=8.056 ms
64 bytes from 192.168.2.222: icmp_seq=23 ttl=63 time=8.585 ms
64 bytes from 192.168.2.222: icmp_seq=24 ttl=63 time=8.067 ms
64 bytes from 192.168.2.222: icmp_seq=25 ttl=63 time=8.778 ms
64 bytes from 192.168.2.222: icmp_seq=26 ttl=63 time=11.464 ms
64 bytes from 192.168.2.222: icmp_seq=27 ttl=63 time=8.310 ms
^C
--- devel ping statistics ---
28 packets transmitted, 28 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 7.828/557.626/5050.881/1311.212 ms

**Comment by Logan007** [comment]
As never observed in my setup, I am just guessing here from what I have read in the code: Maybe the [supernode resolution](https://github.com/ntop/n2n/blob/e66f913e8177e113794cb87be95d35d38f1e1a71/src/n2n.c#L229)?

**Comment by Logan007** [comment]
Are you able to reproduce this issue? If so, it would be helpful to verify or falsify the suspicion that it is about  the supernode resolution by maybe adding simple traceEvents (they output the time, e.g. `traceEvent(TRACE_ERROR, "!!! entering supernode2sock");` upon entering **and** leaving `supernode2sock()` in `n2n.c` at line 232.

**If** time between entering and leaving proves to be too long (causing this issue), we might need to switch to a threaded approach for the recurring DNS resolution (not the initial lookup) and protect the corresponding fields with a mutex.
