### ISSUE TITLE
add specific DNS when I tunnel all traffic to other edge.

### ISSUE THREAD

**Issue by tlsalex** [ntop/n2n#520]
I am not sure whether I am right for this scenario, maybe someone can explain this，

In my home network ,we use 2 DNS provided by ISP.  if we use these 2 DNS to resolve some websites ,it will return the incorrect record , maybe this situation is call "DNS Spoofing and Poisoning" .

But in my company network, we always can get the correct record by using company DNS.

If I tunnel all my traffic from home edge to company edge. will it possible to make the OS to use my company's DNS automatically.
just like add a parameter to edge.

In Ubuntu 20.10, I check the current DNS  via "systemd-resolve --status" ,and bellow is my result, I don't know what is the difference between link-wide DNS and system-wide DNS , when to use link's DNS  , when to use  system's DNS

```
Link 2 (wlp3s0)
      Current Scopes: DNS            
DefaultRoute setting: yes            
       LLMNR setting: yes            
MulticastDNS setting: no             
  DNSOverTLS setting: no             
      DNSSEC setting: no             
    DNSSEC supported: no             
  Current DNS Server: 119.119.119.119
         DNS Servers: 199.199.0.200  
                      119.119.119.119
          DNS Domain: ~. 
```

**Comment by Logan007** [comment]
If you use resolved, you might want to consider a manual approach by trying to change the `/etc/resolv.conf` file to just one line `nameserver <yourCompany'sInternalDnsIpAddress>` (delete or comment the original lines), and restore `/etc/resolv.conf` original content when done.

In case you consider a bash script, the following lines might come in handy:

```bash
# store /etc/resolv.conf file content into RES variable
RES=$(</etc/resolv.conf)

# replace /etc/resolv.conf file content with the one following line
echo "nameserver 192.168.8.1" > /etc/resolv.conf

# restore variable RES' content to /etc/resolv.conf file
echo "$RES" > /etc/resolv.conf
```

**Comment by tlsalex** [comment]
From this link -- [https://fedoramagazine.org/systemd-resolved-introduction-to-split-dns/](url) and under bellow scenario:
 
In my laptop ,the wireless network card interface is assigned a DNS (216.216.216.216) provided by my router.

Edge will create a tap devices ,in my case is edge0.If edge0 is assign a DNS 8.8.8.8 , and configure its routing domains and search domains to: google.com. If my browser request the IP of  www.google.com ,  systemd-resolved will use 8.8.8.8 to resolve www.google.com, rather than use 216.216.x.x

I seems to be a good solution for my issue

But the problem is how do assign DNS and  routing & search domains to edge0 interface
I want to use a script to add these info to edge0 interface, but seems the ip command does not has the ability to do that task.

Any one can help ?

**Comment by tlsalex** [comment]
I almost find my way home, but I still have a small problem, I start my edge via script as bellow

```
root@alexpc ~]# cat /home/alex/exec/edge.sh 
#!/bin/bash
ip route add xx.79.144.xx via 192.168.100.1 dev wlp3s0
ip route add xx.91.158.xx via 192.168.100.1 dev wlp3s0
/usr/sbin/edge /etc/n2n/edge.conf -r -f &  -- run it in background in order to run later instructions
/usr/bin/resolvectl dns edge0 8.8.8.8 8.8.4.4
/usr/bin/resolvectl domain edge0 ~.
/usr/bin/resolvectl flush-caches
/usr/bin/fg  -- at here, I want to bring it back to foreground 
```
In last instruction , I want to bring it back to foreground as I want to see what is happening.
But the fact is , it will quit the child shell open for edge.sh 

@Logan007 could you help me please , thanks in advance.

**Comment by Logan007** [comment]
Okay, so this is about job control...

As far as I know, `fg` is **not** a file/command in `/bin` but a shell built-in which can only be called from interactive shells such as the terminal. The script execution is considered a non-interactive shell environment. You could force it to be interactive by adding the `-i` option to the shebang. Also, just use `fg`.

Finally, you may find it useful to add some sleep after starting the edge to allow the edge to fully start up before the following commands get executed; they might require access to the `edge0` device which gets created in during edge start-up. I added some `echo`es to demonstrate it – watch the output if run with `sleep` as compared to if run without `sleep`.

```bash
#!/bin/bash -i

…

echo BEFORE EDGE
/usr/sbin/edge /etc/n2n/edge.conf -r -f &
sleep 3
echo AFTER EDGE

…

echo AFTER DNS
fg
```

To use `-i` in shell scripts is something usually not recommended to do. In this case, however, it might help you to achieve your goal.

By the way, I wonder why you do not put the `-r` and `-f` options into the `.conf` file.

**Comment by tlsalex** [comment]
At the beginning , it did not work , and then I found I should use `fg rather than /usr/bin/fg` in my script , I don't why I got /usr/bin/fg in my fedora, anyway , it work now .
Thanks, my hero!
