### ISSUE TITLE
Logs show P2P connection ,but it's not. 

### ISSUE THREAD

**Issue by tlsalex** [ntop/n2n#521]
Home wlp3s0: 192.168.100.100 edge:192.168.8.33
Office eth0: 10.183.132.4 edge: 192.168.8.22

At the very beginning I use the simplest way to tunnel all my traffic to home edge node to office node. with `-n=0.0.0.0/0:192.168.8.22`
But the connection is PsP (from the logs).

Then I follow the guide from https://github.com/ntop/n2n/blob/dev/doc/Routing.md , try to make it to be  P2P
Similar to this case: Route All Internet Traffic from n2n Node at Home through Office Network

At the office edge node ,
Enable IP masquerade with:
`firewall-cmd --zone=public --add-masquerade --permanent`
And add a route 
`192.168.100.100 via 192.168.8.33 dev n2n0 src 10.183.132.4 -- I wonder ,do I need 'src 10.183.132.4' in this route ?`

At home edge node,
Before add routes , I start edge successfully and it's real P2P connection, the speed is so fast.
Then I add bellow route:
```
ip route del default  --- ERROR: sendto failed (101) Network is unreachable
ip route add default via 192.168.8.22 dev edge0 src 192.168.100.100  -- WARNING: Supernode not responding, now trying x.x.x.x
ip route add 1xx.xx.xx.xx via 192.168.100.1 dev wlp3s0 src 192.168.100.100 -- P2P] Rx REGISTER from x.x.x.x :30022
```

Now the logs show me it's P2P connection ,but it's connection is very slow , I can see a lot of TX or RX Supernode Supernode pkts.
I am so confuse, any one can help ?

**Comment by Logan007** [comment]
I start wondering if the changed default route prevents your n2n home edge from contacting the UDP ports exposed by your office computer directly.

Supernode's and newer edge's management port output provide information on the real IP address of the other edge (your office edge or your office's firewall or the IP address assigned by your office's ISP). You might want to add that address/address range as another exceptional route (not only to your supernode `ip route add 1xx.xx.xx.xx via 192.168.100.1 dev wlp3s0 src 192.168.100.100 `) to your home computer.

P. S.   I like your new github profile picture.

**Comment by tlsalex** [comment]
I have to say thank you again, it does work after adding exception route for the public IP address of my office's edge.
Now I just use -n=0.0.0.0/0:192.168.8.22 , then P2P is good to go.

```
[root@alex exec]# cat edge.sh 
#!/bin/bash
ip route add xx.xx.xx.9 via 192.168.100.1 dev wlp3s0 1>/dev/null 2>&1  -- for supernode
ip route add xx.xx.xx.8 via 192.168.100.1 dev wlp3s0 1>/dev/null 2>&1  -- for office's edge
/usr/sbin/edge /etc/n2n/edge.conf -r -f   --for me
```
Thank you again!!
