### ISSUE TITLE
hole punching does not work in some cases  

### ISSUE THREAD

**Issue by zadrakar** [ntop/n2n#523]
In some cases, v1 works and v2 does not while maintaining the same conditions.  In #168 @emanuele-f  suggest me create new issue

I don't know much about NAT types and which ones are suitable for P2P. Not even how to find out exactly their type. Neither is under my control but ISPs does. I determine NAT the type from STUN server like this:
`$ pystun3 -H stun.voip.aebc.com`
If you have a better solution, let me know. 

I ran both n2n v1 and v2 on each machine.  My setup is:
- A - PC behind "Symmetric NAT"     
- B - PC  behind "Symmetric NAT" too 
- C1 - LTE cell phone behind "Full Cone" NAT  (hin2n v0.6.0)
- C2 - the same cell phone (as C1), behind same "Symmetric NAT" as B in the same local network (as B)
- C3 - the same cell phone (as C1), behind same "Symmetric NAT" as A in the same local network (as A)
- supernode - far remote location, high latency, perfect for testing

And results:
- A <-> C1  -   n2n v1 communicating directly, v2 always  throught supernode
- A <-> C3  -   both versions communicate through supernode
- B <-> C1  -   n2n v1 communicating directly, v2 always indirectly throught supernode
- B <-> C2  -   n2n v1 communicating  trough  supernode, v2 directly in local subnet
- A <-> B   -  n2n v1 and v2 using supernode

Direct/indirect communications can be seen at first glance from the latency of the ping. I also verified it with Wireshark. (Yes, I know there is an easier way.) If more data needs to be added, I will try it

Conclusion: p2p communication "Symmetric NAT" <-->  "Full Cone" is possible, but n2n v2.8 does not work in this case.

Update 2020-11-30: edge A problem was caused by firewall settings

**Comment by Logan007** [comment]
Considered answered, please re-open if required.
