### ISSUE TITLE
librt on macOS

### ISSUE THREAD

**Issue by JackChen0910** [ntop/n2n#535]
Librt does not exist on OS X, please fix it

**Comment by Logan007** [comment]
Thank you for reporting, I will think of something – actually, we need to link librt only if glibc is present and older than version 2.17.

**Comment by Logan007** [comment]
Does it work for you if you remove the `-lrt` from lines 51 and 52 of Makefile.in and re-run `./autogen.sh` afterwards?

**Comment by JackChen0910** [comment]
yep, I did so, and it worked
