### ISSUE TITLE
n2n sporadically does not work when both edges are into the same network

### ISSUE THREAD

**Issue by emanuele-f** [ntop/n2n#54]
This happens during n2n start. Sometimes the two hosts ping each other successfully, sometimes only the first ping request and reply are delivered and subsequent packets dropped. More testing is needed to understand the issue

**Comment by dinopio** [comment]
(re-posting, my reply didnt get submitted)
Im Using 2.5 (occurs on 2.4 also) I cannot get the network to stay up
Edges cant talk to each other after some inactivity, or sometimes right after a restart.
the only way to keep them up is to constantly ping them all from a node in the network.

**Comment by emanuele-f** [comment]
Issue has been fixed in 5f4dfdc6838ed742a8faf7c874277073c62f34a9
