### ISSUE TITLE
Ubuntu 16.04 Compile Error

### ISSUE THREAD

**Issue by wsyccc** [ntop/n2n#55]
fatal error: config.h: No such file or directory
compilation terminated.
CMakeFiles/n2n.dir/build.make:62: recipe for target 'CMakeFiles/n2n.dir/n2n.c.o' failed
make[2]: *** [CMakeFiles/n2n.dir/n2n.c.o] Error 1
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/n2n.dir/all' failed
make[1]: *** [CMakeFiles/n2n.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by emanuele-f** [comment]
Usually you should run `./autogen.sh` then `make`

**Comment by wsyccc** [comment]
Oh, got it thank you
