### ISSUE TITLE
Invalid link in documentation

### ISSUE THREAD

**Issue by swilkey** [ntop/n2n#553]
On https://github.com/ntop/n2n/blob/dev/doc/Advanced.md page there is a link to "details about Communities" which has an incorrect url https://github.com/ntop/n2n/blob/dev/doc/doc/Communities.md

The url should go to:
https://github.com/ntop/n2n/blob/dev/doc/Communities.md

Can this be corrected please?

I also just discovered other invalid URLs on the page too:
"Routing document" should go to https://github.com/ntop/n2n/blob/dev/doc/Routing.md
"Traffic Restrictions" should go to https://github.com/ntop/n2n/blob/dev/doc/TrafficRestrictions.md

**Comment by Logan007** [comment]
Thanks for reporting, I will create a pull request to fix it.

**Comment by swilkey** [comment]
Thank you, I had no idea how to do that.

------ Original Message ------
