### ISSUE TITLE
Memory leak occurred in the latest version of openwrt (19.07.5)

### ISSUE THREAD

**Issue by VergLsm** [ntop/n2n#559]
I have several routers, all of which have installed openwrt and n2n and have been running well.
A few days ago, the latest openwrt (19.07.5) was updated.
I found that the memory usage of n2n kept increasing until it crashed.
These routers are roughly the same, the greater the throughput, the faster the crash.

My configuration file is as follows:
```
-d=n2n0
-c=xxxxxxxx
-k=xxxxxxxx
-m=xx:xx:xx:xx:xx:xx
-a=192.168.xx.xx
-l=xxx.xxx.xxx:10086
-r
-A5
-z
```

![6E15731D-39EF-4A17-8A99-A52D809684A4](https://user-images.githubusercontent.com/13448810/102871673-ab43a200-4479-11eb-8410-6d4b7190cdbc.jpeg)
![9D73EFB9-2D8E-4EC6-B791-A096F801804A](https://user-images.githubusercontent.com/13448810/102871699-b0085600-4479-11eb-8b0c-2ba0d1d6dba1.jpeg)

**Comment by Logan007** [comment]
What n2n version do you use / is included in openWRT? If you have an opportunity to call n2n's `edge` from command line on that openWRT, it usually outputs the exact version in the very first line.

It might be related to compression which was fixed in #390. Does it work better without `-z`?

**Comment by VergLsm** [comment]
Sorry, my n2n version is 2.8, and the source code is from 472a9878f72299466ddbce2a232ea9e081159fa9. I will try to remove -z and reply with the result.

**Comment by Logan007** [comment]
472a9878f72299466ddbce2a232ea9e081159fa9 does not seem to include the fix of #390 yet. In addition to omitting `-z`, do you want to try to build from 99e56e9f3c34c49eeb297971d41150b433489120? 

`-z` is supposed to be working then.

**Comment by VergLsm** [comment]
Yes, you’re right.

**Comment by VergLsm** [comment]
It works fine after removing ```-z```. 
Next I will test whether 99e56e9f3c34c49eeb297971d41150b433489120 fixed the issue.
![微信截图_20201223182622](https://user-images.githubusercontent.com/13448810/102986837-689eca00-454c-11eb-8c84-a365cbe0144d.png)

**Comment by VergLsm** [comment]
99e56e9 works great!
![微信截图_20201224121239](https://user-images.githubusercontent.com/13448810/103059997-b9143700-45e1-11eb-86be-003e221b53b5.png)

The ipk from #560

**Comment by Logan007** [comment]
I am glad that it works!
