### ISSUE TITLE
Register succeed but two edge can't communicate in newest version,but a old version works..

### ISSUE THREAD

**Issue by cchit** [ntop/n2n#56]
Hi:
     I used to setup a supernode in my server and run an edge in the same server and my personal workstation. They works well. I downloaded the newest version yesterday and sh ./autogen.sh 
make PREFIX=some path install in both server and my workstation, and then I setup the supernode and edge in server, only edge in my workstation,they register succeed but they can not ping eachother through the n2n ip addr.

**Comment by cchit** [comment]
try several times, it works now. It seems some kind of unstable, I'll try to do more test.

**Comment by emanuele-f** [comment]
This is probably fixed with #71 . Closing this for now, if you have other clues with the new version, please open a separate ticket.
