### ISSUE TITLE
is there a easy way to get the edge status on supernode?

### ISSUE THREAD

**Issue by cholley** [ntop/n2n#566]
Here is the use case:
I have a lot of edges running under the same supernode, then I want to check the edge list to show their status to monitor those devices and build a proxy platform to manage them on the web.
Of course, we can check it manually like this:
![image](https://user-images.githubusercontent.com/10412149/103220627-adb36980-495b-11eb-8c51-a1c73c185659.png)

But it is not friendly to check specific edges with filters, for example, based on mac, get the IP, and generate a proxy path to access them. If the supernode can provide a way to search a specific edge and show the edge like the picture above that will be very great. 
I think there might be  3 methods to reach the goal:
1. The supernode will output the edge list with status realtime to a cache file, it can be a text file with JSON format, just like the community.list.
2.  Send a query by cli or HTTP  with filter parameters, then supernode can reply a result with JSON or other format;
3. The real-time edge status will be stored in the lightweight database, sqlite or redis?

Maybe there are other better ideas to meet the needs, please let me know, thanks very much!

**Comment by Logan007** [comment]
As there is no http server integrated in n2n yet (and also no database), your best chance for now is to query the management port using `netcat`. You may find the following script useful to get the IP address for any given MAC address

```
#!/bin/bash

MAC=$1

IP=$(echo | timeout -s 1 1 netcat -u localhost 5645 | grep --line-buffered "$MAC" | tr -s [:blank:] | cut -d ' ' -f 3 | grep -oE "[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}")

echo $IP
```

by calling it with the MAC address as parameter, e.g. `./script 10:20:30:40:50:60`. I assume you wanted the virtual *tun_tap* IP address, otherwise you need to replace the `-f 3` by `-f 5`. You can even redirect the script's output into a file if that better suits your needs: `./script 10:20:30:40:50:60 > filename.txt`.

**Comment by cholley** [comment]
> As there is no http server integrated in n2n yet (and also no database), your best chance for now is to query the management port using `netcat`. You may find the following script useful to get the IP address for any given MAC address
> 
> ```
> #!/bin/bash
> 
> MAC=$1
> 
> IP=$(echo | timeout -s 1 1 netcat -u localhost 5645 | grep --line-buffered "$MAC" | tr -s [:blank:] | cut -d ' ' -f 3 | grep -oE "[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}")
> 
> echo $IP
> ```
> 
> by calling it with the MAC address as parameter, e.g. `./script 10:20:30:40:50:60`. I assume you wanted the virtual _tun_tap_ IP address, otherwise you need to replace the `-f 3` by `-f 5`. You can even redirect the script's output into a file if that better suits your needs: `./script 10:20:30:40:50:60 > filename.txt`.

Thanks @Logan007 
It should work! I will write  a script to update the status of edge list every second and redirect it to a cache file,  then the app can parse the file to get the expect result. thanks again!
