### ISSUE TITLE
Does n2n support NAT Crossing of stun mode?

### ISSUE THREAD

**Issue by akevy** [ntop/n2n#57]
Learned the documentation, support relay penetration nat,does n2n support NAT Crossing of stun mode? Thank you very much

**Comment by emanuele-f** [comment]
Sorry for the late reply, n2n indeed employs some mechanisms to cross NAT devices, but not STUN. In the cases where direct communication between the nodes is not possible, the supernode is used to make the nodes communicate. This happens transparently to the nodes.
