### ISSUE TITLE
there is a bug in config file supernode.conf

### ISSUE THREAD

**Issue by cholley** [ntop/n2n#581]
Check this:
![image](https://user-images.githubusercontent.com/10412149/104316089-edab4c80-5516-11eb-8249-170d9fc97650.png)

The parameter `-p=27654` was detected as 7654, the `2` is missed. 
btw, tested with the latest dev source.

**Comment by Logan007** [comment]
Thanks for reporting, I will have a look.

**Comment by cholley** [comment]
> Thanks for reporting, I will have a look.

And this one is weird, too.

![image](https://user-images.githubusercontent.com/10412149/104316682-cd2fc200-5517-11eb-8bbf-6fa2b39b134a.png)

Should the `-c=community.list` be placed in the end of the config file? it is not mentioned any where, and it is unreasonable.

**Comment by Logan007** [comment]
I think I see what went wrong: If you want to start with `.conf` file, do not give the `-c` parameter, just a bare `./supernode supernode.conf`. Your command line given above shows a `-c` which needs to go into the config-file only as it indicates the path to the community file – not to the config file.

`7654` is the default port and is, by coincidence, very similar to your choice of port.

**Comment by cholley** [comment]
> I think I see what went wrong: If you want to start with `.conf` file, do not give the `-c` parameter, just a bare `./supernode supernode.conf`. Your command line given above shows a `-c` which needs to go into the config-file only as it indicates the path to the community file – not to the config file.
> 
> `7654` is the default port and is, by coincidence, very similar to your choice of port.

you are right, it is my fault! Sorry for the carelessness! please close it. Thank you!

**Comment by Logan007** [comment]
No problem. I am just glad that it works for you and I do not need to fix the code…  :relieved:

**Comment by Logan007** [comment]
P. S. As author of an issue, you should have access to the  "Close" button, too.

**Comment by cholley** [comment]
ok, noticed.
