### ISSUE TITLE
The latest version of edge and supernode  removed daemon mode? 

### ISSUE THREAD

**Issue by cholley** [ntop/n2n#585]
I notice that I can not run edge and supernode in daemon mode, they are working as foreground mode as default without any parameters, even `-f`. How to make it work as daemon mode?

**Comment by Logan007** [comment]
What platform are you running them on?

I can confirm that daemon and foreground both work very well on (current Arch) Linux.

Alternatively, on Linux, you could try to setup a systemd-service. There are some [unit files](https://github.com/ntop/n2n/tree/dev/packages/etc/systemd/system) available in the repository.

On Windows, n2n does not support daemonized mode, i.e. running in the background. So, providing or omitting `-f` would not make any difference. #458  / #328 contain hints to run as service if required.

**Comment by cholley** [comment]
it is a mistake
