### ISSUE TITLE
20 character community name

### ISSUE THREAD

**Issue by Logan007** [ntop/n2n#588]
Optional header encryption was squeezed into the existing packet format using the existing 16 byte community name field to not break packet compatibility when introduced during version 2.x.

Now, that we are preparing for 3.0 and already have seen some compatibility breaking changes, I would like to add yet another one:

I would like to extend the community name from 16 to 20 characters (well, 19 plus zero termination). It's not because I like longer community names but I would recommend a longer IV (and longer IV components) for the header encryption making it more secure:

We can make the hash more significant  – as of now, roughly half of it vanishes into the XOR with lower time stamp which has no decisive influence if jitter is allowed (it is by default, for the comfort of not losing mixed-order UDP packets).

The downside is that packets add up 4 more bytes to their length. Nothing comes for free...

Any thoughts?

**Comment by skyformat99** [comment]
thanks.
If there is no impact on transmission efficiency and performance, I agree

**Comment by Logan007** [comment]
I have just finished the coding and I have not been able to see any difference in performance (`scp`).

The impact the 4 additional rounds (32 for 128-bit block size instead of 28 for 96-bit block size – on one block, namely the iv, only) might have surely is (over-)compensated for by simpler round functions (48/96-bit width required additional rectifying shifts, not anymore with 64-bit width) as well as by simpler IV construction (no fixed part required anymore, can operate directly on the packet, less `memcpy`).
