### ISSUE TITLE
Where are the official?

### ISSUE THREAD

**Issue by lucktu** [ntop/n2n#59]
Since June 6, 2018, no big progress. We were a little disappointed.

**Comment by emanuele-f** [comment]
Hi, we are active with the support and we have added new features like the local network peers discovery. The things we want to fix soon are the SSL libraries integration and some bugs like #54  . Since this is a community driven project, if you have suggestions or pull requests, please discuss them with us and other users too.

**Comment by lucktu** [comment]
It's very nice to meet you!

Yes, I see. but the probability of p2p, zerotier > meyerd's n2n > n2n_v2. and rsync can't use in n2n_v2.
Even in p2p state, the traffic through supernode is relatively large.

In addition, Some people say that n2n security is poor, and anyone who knows the main parameters can join the network. Is it possible to select one of the edges as the manager, and only after its confirmation can new edge enter?

I do not understand programming, some requirements may be unreasonable, forgive me please!

**Comment by emanuele-f** [comment]
> It's very nice to meet you!
> 
> Yes, I see. but the probability of p2p, zerotier > meyerd's n2n > n2n_v2. and rsync can't use in n2n_v2.
> Even in p2p state, the traffic through supernode is relatively large.

Some of these software are not maintained anymore. Regarding the techniques they use to enstablish a p2p vpn, I think they are basically the same as n2n (UDP holepunching). But with some kind of NAT devices very is not much to do, so the supernode is essential.

> In addition, Some people say that n2n security is poor, and anyone who knows the main parameters can join the network.

This is something we want to improve. A security expert in this field to review it would help a lot.

> Is it possible to select one of the edges as the manager, and only after its confirmation can new edge enter?

There are mechanisms to verify the identity of the peers by the means of certificates. What makes n2n great right now is the ability to quickly create networks, so maybe this could be an optional feature.

> I do not understand programming, some requirements may be unreasonable, forgive me please!

Thank you, users feedback is essential to improve a software

**Comment by lucktu** [comment]
I agree with your evaluation! Thank you!

**Comment by emanuele-f** [comment]
Thank you for the feedback, please feel free to open/comment new feature requests.
