### ISSUE TITLE
n2n-2.8 Stable seems to have a memory leak (Windows x64)

### ISSUE THREAD

**Issue by xiahuaijia** [ntop/n2n#601]
n2n version: 2.8 Stable Release
OpenSSL-1.1.1i
zstd-1.4.8
TAP-Windows Provider V9 - 9.24.6.601

When using n2n to transfer data, the memory keeps increasing
The memory is constantly increasing on all edges that use this build

![n2n_RAM](https://user-images.githubusercontent.com/8602553/105821433-cf088380-5ff5-11eb-86b2-e6703239ef11.png)

edge.conf

```
-c=GTFO
-A3
-k=....
-z2
-E
-l=xxx...
-d=OpenVPN TAP-Windows6
-a=static:192.168.x.x

-S
```

**Comment by Logan007** [comment]
As you use compression, I guess that it is the same bug as reported in #559. It was solved by #390 and #391 – even for 2.8 in an aftermath.

Can you please confirm that your build already includes that fix?

**Comment by xiahuaijia** [comment]
The 472a987 build used before.  Now 99e56e9 is work.

![Snipaste](https://user-images.githubusercontent.com/8602553/105840338-db003f80-600d-11eb-9e6a-11bd99db2db3.png)

**Comment by Logan007** [comment]
I am glad that it works for you!
