### ISSUE TITLE
questions when I read the source code..

### ISSUE THREAD

**Issue by randomize00** [ntop/n2n#603]
Hello, I've been reading the source code for a while.
I have two little questions.
First, in src/sn_util.c:1488 :

`if((from_supernode == 0) != (comm->is_federation == IS_NO_FEDERATION)) {`

this checking seems odd, Can REGISTER_SUPER_ACK be sent by an edge ?

Second.
I find a macro, N2N_FLAGS_SOCKET, since there is no comment, I don't know what does it mean. it looks like it always appears with the macro N2N_FLAGS_FROM_SUPERNODE.

any  helpful reply will be appreciated, thank you.

**Comment by Logan007** [comment]
> Can REGISTER_SUPER_ACK be sent by an edge ?

No, it can't. 

`if((from_supernode == 0) != (comm->is_federation == IS_NO_FEDERATION))` makes sure that packets that claim to be from a supernode (`from_supernode` flag in the header) really are from (super)nodes of the corresponding supernode community. In other words, flag and community must correspond. If not, there is an error or some manipulation we want to detect and avoid. Thus, we perform the check with the following error message.

> I find a macro, N2N_FLAGS_SOCKET ... it always appears with the macro N2N_FLAGS_FROM_SUPERNODE.

Those are flag masks defined in `include/n2n_typedefs.h:259`. They define the (currently two) flags used in the common section of each packet. FROM_SUPERNODE indicates that this is a packet sent from or through a supernode which is important to know in case we need to decide if to forward again or not, etc. The SOCKET flag indicates that some previous (super-)node added the socket of the original sender to the packet, so the the final recipient can use that one to directly send data back. The flags are not necessarily equal.

**Comment by randomize00** [comment]
Thank you very much.
About the checking,  I have a new question - Do you mean, if an edge (not in federation commutity), or a supernode ( in federation community ) manipulate a REGISTER_SUPER_ACK and send to us, then it can pass this checking ? How to guarantee that those nodes won't try to manipulate a packet to attack us ?

**Comment by Logan007** [comment]
> Do you mean, if an edge (not in federation commutity), or a supernode ( in federation community ) manipulate a REGISTER_SUPER_ACK and send to us, then it can pass this checking ?

No. What I mean is that those manipulations are detected by performing this check.

> How to guarantee that those nodes won't try to manipulate a packet to attack us ?

That is exactly what this check does. This check makes sure that no manipulated packet gets through, only valid packets. Another way to read it: If _(no supernode flag set)_ does not correpsond to _(this packet is from a regular community)_, then the error is thrown.

And the condition also works the other way 'round:  If _(supernode flag set)_ does not correpsond to _(this packet is from the federation)_, then the error is thrown.

Please keep in mind that `(from_supernode == 0)` and `(comm->is_federation == IS_NO_FEDERATION)` result in boolean values which finally get compared by `!=`. Flag check and federation check need to give the same result in order to continue, the error is thrown otherwise.

**Comment by Logan007** [comment]
> How to guarantee that those nodes won't try to manipulate a packet to attack us ?

As a post script, please note that federation packets are protected by header encryption, so no edge is able to manipulate or spoof this kind of packets without knowing the secret federation name which is only shared among the supernodes (`-F <federation name>` on the supernode).

To better protect your peer-to-peer connections as well as edge-supernode connections, I recommend to use header encryption `-H`, please have a look into the advanced documentation in the `/doc`folder for details.

**Comment by randomize00** [comment]
OK. This is very what I needed. Thanks.

**Comment by randomize00** [comment]
Since @Logan007 said that REGISTER_SUPER_ACK cannot be sent by an edge, maybe you can simply wrtie the checking like this ?
```
if(  from_supernode == 0 || comm->is_federation == IS_NO_FEDERATION)  )
{
       exception handle code ...
}
```

**Comment by Logan007** [comment]
Thank you for your proposal. If I compare the two different conditions, I get the following table:

from_supernode packet flag | federation community | randomize00 result | current result
-----|-----|-----|-----
0    |  0  |    |
0    |  1  | Error   | Error
1    |  0  |    | Error
1    |  1  |    | 

The condition is a "kick-out" condition. It only lets pass properly formed packets.

> Since @Logan007 said that REGISTER_SUPER_ACK cannot be sent by an edge

Let me add that a **regular** edge will (better: should) never send such a packet. What about malicious nodes? Or nodes just gone crazy? External attackers? Or just a coding error? 

So, this original check also is a packet format sanity check: Imagine a community with unencrypted headers, following your idea, everyone could spoof such a packet and set this flag in a packet with regular community (not the federation one) and thus inject additional supernodes (REGISTER_SUPER_ACK payload) that do not belong in there. 

This thought basically also is the reason for do not letting edges bring new supernodes to the federation, that is a privilege of supernodes who will propagate and distribute their knowledge among themselves and to all the edges.

**Comment by randomize00** [comment]
Emm..

```
if(  from_supernode == 0 || comm->is_federation == IS_NO_FEDERATION)  )
{
       exception handle code ...
}
```

Since I use OR operator, I  think the table may be like this :
from_supernode packet flag | federation community | randomize00 result | current result
------------ | ------------- | ------------- | -------------
0 | 0 | Error | 
0 | 1 | Error | Error
1 | 0 | Error | Error
1 | 1 | |

**Comment by Logan007** [comment]
Oh my, **and** vs. **or**! I wish I could read better... :facepalm: back to school!

You are right! Your solution would make REGISTER_SUPER_ACK checking much safer. Do you want to provide a corresponding pull request?

**Comment by randomize00** [comment]
Sorry. I am a rookie of github and still don't know even how to folk and maintain my code repository.
because it only changes a line, maybe you can add it yourself.
