### ISSUE TITLE
Auto-IP does not work when specified from commandline

### ISSUE THREAD

**Issue by franzflasch** [ntop/n2n#607]
It seems, that the auto-ip feature only works when specified from a conf file.

Test with commandline parameters:

Supernode:
```
~# supernode -c community -p <super-node-port> -a 192.168.123.0-192.168.123.0/24 -f
28/Jan/2021 07:53:55 [sn.c:161] Loaded 1 fixed-name communities from community
28/Jan/2021 07:53:55 [sn.c:164] Loaded 0 regular expressions for community name matching from community
28/Jan/2021 07:53:55 [sn.c:391] The network range for community ip address service is '192.168.123.0...192.168.123.0/24'.
28/Jan/2021 07:53:55 [sn.c:699] supernode is listening on UDP <super-node-port> (main)
28/Jan/2021 07:53:55 [sn.c:707] supernode is listening on UDP 5645 (management)
28/Jan/2021 07:53:55 [sn.c:716] Dropping privileges to uid=65534, gid=65534
28/Jan/2021 07:53:55 [sn.c:732] supernode started
```

Edge:
```
~# edge -f -d tap15 -c network -l <super-node-ip>:<super-node-port>
28/Jan/2021 07:54:02 [edge_utils.c:3027] Adding supernode = <super-node-ip>:<super-node-port>
28/Jan/2021 07:54:02 [edge.c:885] Starting n2n edge 2.9.0.r846.f352c99 Jan 28 2021 07:05:46
28/Jan/2021 07:54:02 [edge.c:891] Using compression: none.
28/Jan/2021 07:54:02 [edge.c:892] Using null cipher.
28/Jan/2021 07:54:02 [edge_utils.c:227] Number of supernodes in the list: 1
28/Jan/2021 07:54:02 [edge_utils.c:229] supernode 0 => <super-node-ip>:<super-node-port>
28/Jan/2021 07:54:02 [edge_utils.c:267] WARNING: Encryption is disabled in edge
28/Jan/2021 07:54:02 [edge.c:921] Automatically assign IP address by supernode.
28/Jan/2021 07:54:02 [edge.c:990] Send REGISTER_SUPER to supernode [<super-node-ip>:<super-node-port>] asking for IP address.
28/Jan/2021 07:54:02 [edge.c:1001] Received REGISTER_SUPER_ACK from supernode for IP address asignment.
28/Jan/2021 07:54:02 [edge.c:1023] Created local tap device IP: 10.231.156.73, Mask: 255.255.255.0, MAC: 92:DC:5D:AC:B9:72
28/Jan/2021 07:54:02 [edge.c:1071] WARNING: n2n has not been compiled with libcap-dev. Some commands may fail.
28/Jan/2021 07:54:02 [edge.c:1076] Dropping privileges to uid=65534, gid=65534
28/Jan/2021 07:54:02 [edge.c:1100] edge started
28/Jan/2021 07:54:02 [edge_utils.c:753] Successfully joined multicast group 224.0.0.68:1968
28/Jan/2021 07:54:02 [edge_utils.c:2176] [OK] Edge Peer <<< ================ >>> Super Node
```
It obviously uses the predefined Network Address 10.x.x.x instead of the specified one (192.168.123.0)

Test with config from a conf-file:
```
-p=<super-node-port>
-a=192.168.123.0-192.168.123.0/24
-c=community
-f
```
 It seems to work as expected:
```
~# supernode supernode.conf
28/Jan/2021 07:52:55 [sn.c:391] The network range for community ip address service is '192.168.123.0...192.168.123.0/24'.
28/Jan/2021 07:52:55 [sn.c:161] Loaded 1 fixed-name communities from community
28/Jan/2021 07:52:55 [sn.c:164] Loaded 0 regular expressions for community name matching from community
28/Jan/2021 07:52:55 [sn.c:699] supernode is listening on UDP <super-node-port> (main)
28/Jan/2021 07:52:55 [sn.c:707] supernode is listening on UDP 5645 (management)
28/Jan/2021 07:52:55 [sn.c:716] Dropping privileges to uid=65534, gid=65534
28/Jan/2021 07:52:55 [sn.c:732] supernode started
```

```
~# edge -f -d tap15 -c network -l <super-node-ip>:<super-node-port>
28/Jan/2021 07:53:10 [edge_utils.c:3027] Adding supernode = <super-node-ip>:<super-node-port>
28/Jan/2021 07:53:10 [edge.c:885] Starting n2n edge 2.9.0.r846.f352c99 Jan 28 2021 07:05:46
28/Jan/2021 07:53:10 [edge.c:891] Using compression: none.
28/Jan/2021 07:53:10 [edge.c:892] Using null cipher.
28/Jan/2021 07:53:10 [edge_utils.c:227] Number of supernodes in the list: 1
28/Jan/2021 07:53:10 [edge_utils.c:229] supernode 0 => <super-node-ip>:<super-node-port>
28/Jan/2021 07:53:10 [edge_utils.c:267] WARNING: Encryption is disabled in edge
28/Jan/2021 07:53:10 [edge.c:921] Automatically assign IP address by supernode.
28/Jan/2021 07:53:10 [edge.c:990] Send REGISTER_SUPER to supernode [<super-node-ip>:<super-node-port>] asking for IP address.
28/Jan/2021 07:53:10 [edge.c:1001] Received REGISTER_SUPER_ACK from supernode for IP address asignment.
28/Jan/2021 07:53:10 [edge.c:1023] Created local tap device IP: 192.168.123.73, Mask: 255.255.255.0, MAC: 76:C4:5A:F7:60:32
28/Jan/2021 07:53:10 [edge.c:1071] WARNING: n2n has not been compiled with libcap-dev. Some commands may fail.
28/Jan/2021 07:53:10 [edge.c:1076] Dropping privileges to uid=65534, gid=65534
28/Jan/2021 07:53:10 [edge.c:1100] edge started
28/Jan/2021 07:53:10 [edge_utils.c:753] Successfully joined multicast group 224.0.0.68:1968
28/Jan/2021 07:53:10 [edge_utils.c:2176] [OK] Edge Peer <<< ================ >>> Super Node
```

**Comment by Logan007** [comment]
I will have a closer look. Thanks for reporting!

**Comment by Logan007** [comment]
I tried it here from command line using the original `community.list` file. Apart from having only one subnet available as your `-a` only allows one (message: `No assignable sub-network left for community 'netleo')`, an edge connecting to `mynetwork` community (not the `netleo`), draws an IP address from the specified range.

Even if I create a `community` file with only one entry `community` in it, the address gets drawn from the specified range.

So, I have to ask what is the exact content of your `community` file? Only the community name (no space, no special characters, only ASCII)?

**Comment by franzflasch** [comment]
It only has one entry with a community name, nothing else:
```
~# cat community 
network
```
Is it mandatory to specify other things in the community file?

**Comment by Logan007** [comment]
> Is it mandatory to specify other things in the community file?

No, it is not. Optionally, you could specify the network in there, seperated by a space character, such as

`network 192.168.123.0/24` (see comments in original `community.list` file)

but that is, again, optional. It should work the way you originally tried and I am still on the hunt to re-produce this unexpected behavior over here.

**Comment by Logan007** [comment]
And there is no withespace after `network`?

**Comment by franzflasch** [comment]
No. However now I tried to insert a whitespace and also a newline. It does not change anything.

Maybe I should add, that the supernode is running on an OpenWrt Router with a Mipsel CPU.

```
root@OpenWrt:~# cat /proc/cpuinfo 
system type             : MediaTek MT7628AN ver:1 eco:2
machine                 : TP-Link TL-WR902AC v3
processor               : 0
cpu model               : MIPS 24KEc V5.5
BogoMIPS                : 385.84
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa                     : mips1 mips2 mips32r1 mips32r2
ASEs implemented        : mips16 dsp
Options implemented     : tlb 4kex 4k_cache prefetch mcheck ejtag llsc pindexed_dcache userlocal vint perf_cntr_intr_bit nan_legacy nan_2008 perf
shadow register sets    : 1
kscratch registers      : 0
package                 : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available
```

**Comment by franzflasch** [comment]
The strange thing is, that the supernode actually prints the correct network range, regardless of how it was specified:

`The network range for community ip address service is '192.168.123.0...192.168.123.0/24'.`

But only when I specify it via commandline the edge node gets the default Network Address (10.x.x.x)

**Comment by Logan007** [comment]
> Maybe I should add, that the supernode is running on an OpenWrt Router with a Mipsel CPU.

That should not affect the network assignment. I am still on it.

> The strange thing is, that the supernode actually prints the correct network range, regardless of how it was specified

That is just the result of command line paramter evaluation if I remember correctly, so there must be some reason somewhere in the code for this strange behavior. It definitely is not the intended behavior. Let me do further checks, need to re-produce it first.

By the way, since you have an interesting CPU in that router, could you share your `tools/benchmark` output?

**Comment by franzflasch** [comment]
> By the way, since you have an interesting CPU in that router, could you share your tools/benchmark output?

Yes, will do.

**Comment by Logan007** [comment]
Now, this is getting really strange. I am able to re-produce this behavior with the supernode being on a remote server, but it works as expected with supernode on localhost... both the exact same software version. Will keep you posted while getting deeper into it!

**Comment by franzflasch** [comment]
I am running the server also on a remote location. I've never tested it locally.

**Comment by Logan007** [comment]
Turns out to be some logic error... fixed. I hope.
