### ISSUE TITLE
compile fails，please help me

### ISSUE THREAD

**Issue by a512154224** [ntop/n2n#62]
[root@tlx build]# make
[ 14%] Built target doc
[ 19%] Building C object CMakeFiles/n2n.dir/version.c.o
/root/n2n/version.c:1:20: error: config.h: No such file or directory
/root/n2n/version.c:3: error: ‘PACKAGE_VERSION’ undeclared here (not in a function)
/root/n2n/version.c:4: error: ‘PACKAGE_OSNAME’ undeclared here (not in a function)
make[2]: *** [CMakeFiles/n2n.dir/version.c.o] Error 1
make[1]: *** [CMakeFiles/n2n.dir/all] Error 2
make: *** [all] Error 2

**Comment by a512154224** [comment]
[ 61%] Building C object CMakeFiles/n2n.dir/tuntap_freebsd.c.o
[ 66%] Building C object CMakeFiles/n2n.dir/tuntap_netbsd.c.o
[ 71%] Building C object CMakeFiles/n2n.dir/tuntap_linux.c.o
[ 76%] Building C object CMakeFiles/n2n.dir/tuntap_osx.c.o
[ 80%] Building C object CMakeFiles/n2n.dir/version.c.o
/root/n2n/version.c:3: error: ‘PACKAGE_VERSION’ undeclared here (not in a function)
/root/n2n/version.c:4: error: ‘PACKAGE_OSNAME’ undeclared here (not in a function)
make[2]: *** [CMakeFiles/n2n.dir/version.c.o] Error 1
make[1]: *** [CMakeFiles/n2n.dir/all] Error 2
make: *** [all] Error 2

**Comment by emanuele-f** [comment]
Please run `./autogen.sh` then `./configure` and then `make`

**Comment by a512154224** [comment]
Thank you very much, it has been compiled successfully.

**Comment by emanuele-f** [comment]
You are welcome!
