### ISSUE TITLE
Hello，Windows cannot compile，Please help me

### ISSUE THREAD

**Issue by a512154224** [ntop/n2n#63]
[root@lstcml win32]# mkdir build
[root@lstcml win32]# cd build/
[root@lstcml build]# cmake ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /root/n2n/win32/build
[root@lstcml build]# make
Scanning dependencies of target n2n_win32
[ 33%] Building C object CMakeFiles/n2n_win32.dir/getopt1.c.o
[ 66%] Building C object CMakeFiles/n2n_win32.dir/getopt.c.o
[100%] Building C object CMakeFiles/n2n_win32.dir/wintap.c.o
In file included from /root/n2n/win32/wintap.c:6:0:
/root/n2n/win32/n2n_win32.h:20:22: fatal error: winsock2.h: No such file or directory
 #include <winsock2.h>
                      ^
compilation terminated.
make[2]: *** [CMakeFiles/n2n_win32.dir/wintap.c.o] Error 1
make[1]: *** [CMakeFiles/n2n_win32.dir/all] Error 2
make: *** [all] Error 2

**Comment by ghostry** [comment]
I also encountered such a problem.
Which kind person can give me a 2.4 version of the Windows finished file.

**Comment by emanuele-f** [comment]
I never compiled it on windows, so I cannot help sorry. Maybe #66 can help?

**Comment by emanuele-f** [comment]
Addessed in #66. I've added some instructions in 5742ef978f264cb9692c0f8d830515c3200b20be
