### ISSUE TITLE
send log of edge/supernode to a file specified in the configuration

### ISSUE THREAD

**Issue by tlsalex** [ntop/n2n#639]
I run edge/supernode in daemon mode.
I would like their log will be sent to a file specified in the configuration.
I tried to achieve this via ` ./edge ./edge.conf > edge.log`
but it doesn't work.

```
[root@n2n01 n2n-0218]# /root/n2n/n2n-0218/edge /root/n2n/n2n-0218/tusedge.conf > /root/n2n/n2n-0218/edge.log
[root@n2n01 n2n-0218]# ps -ef | grep edge
nobody     33346       1  0 09:33 ?        00:00:00 /root/n2n/n2n-0218/edge /root/n2n/n2n-0218/tusedge.conf  -- the > not exist anymore
root       33375   32651  0 09:33 pts/1    00:00:00 grep --color=auto edge
```
I already add -vv in the edge.conf , if I make a ping , edge will generate lots of log . but I tail -f edge.log , nothing happen . which may means it is not working in this way.

**Comment by Logan007** [comment]
If you have systemd running, have you tried to run it as a systemd service?

I have my edges and supernodes run as a systemd-service (with `-f` in the `.service` file command line) so they seemingly run in the background. The system logs all the output and the log for this service can be read by `journalctl -u edge.service` (replace your exact service name). Alternatively, you could try to add the `StandardOutput=file:/path/to/your/log.file` line to the `.service` file.

**Comment by Logan007** [comment]
Any news?

By the way, does the `.conf` file contains `-f`?

**Comment by Logan007** [comment]
Closed due to inactivity. Please re-open if not solved yet.
