### ISSUE TITLE
Cannot cross compile

### ISSUE THREAD

**Issue by small-5** [ntop/n2n#644]
After 85894715bd2af342b7682f3dcc12bf4a7ac75855, it cannot be cross-compiled on openwrt, and an error will be reported: checking whether the C compiler works... no. After removing the newly added part of configure.seed, it will be normal, please fix.Thank you!

**Comment by Logan007** [comment]
I saw some similar issues compiling for local platform after some recent pull/fetch and figured out that starting a fresh build off from the `./autogen.sh` step helped me.

**Comment by small-5** [comment]
Today there is a new problem. After the source code of openwrt is updated, it cannot be compiled, and there will be:
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
Upstream replaced autoconf with autoconf-lean.After re-using autoconf,can compile normally.
https://github.com/openwrt/openwrt/commit/32c664ff02910bf39a3fbd5a5a4a8bff3191dd03

**Comment by small-5** [comment]
Check config.log and found that no parameters were passed in ./configure, I can compile normally after applying a patch
![1](https://user-images.githubusercontent.com/61473216/109547929-f7a8ff00-7b06-11eb-8033-66de315243ae.png)

**Comment by Logan007** [comment]
Thank you very much. Could you please provide a very short explanation on what this change exactly does, and why it does not affect the regular build? I just am not too deep into build tool chains...

**Comment by small-5** [comment]
Follow the steps of https://github.com/ntop/n2n#manual-compilation, execute ./autogen.sh and execute it again in the future./configure or ./configure CFLAGS="-O3 -march=native", so This will not affect local compilation. But after openwrt uses autoconf-lean, it must be executed by the toolchain./configure and additional parameters, otherwise it will report configure: error: cannot run C compiled programs.

After deleting the ./configure in autogen.sh, the parameters of config.log are as follows:
![1](https://user-images.githubusercontent.com/61473216/109968249-6c5d8280-7d2d-11eb-9fcd-f214a6bc10b6.png)

After keeping the ./configure in autogen.sh, the ./configure in config.log does not have any parameters, which will cause only the values ​​of AR and CC to be passed to the Makefile, and other FLAGS are missing.
![2](https://user-images.githubusercontent.com/61473216/109968228-6667a180-7d2d-11eb-901c-0d8ab43b8641.png)

**Comment by small-5** [comment]
Follow the steps of https://github.com/ntop/n2n#manual-compilation, execute ./autogen.sh and execute it again in the future./configure or ./configure CFLAGS="-O3 -march=native", so This will not affect local compilation. But after openwrt uses autoconf-lean, it must be executed by the toolchain./configure and additional parameters, otherwise it will report configure: error: cannot run C compiled programs.

Deleting the ./configure in autogen.sh, the parameters of config.log are as follows:
![1](https://user-images.githubusercontent.com/61473216/109968806-1f2de080-7d2e-11eb-81c4-c8cd9d0fbf6e.png)

Keeping the ./configure in autogen.sh, the ./configure in config.log does not have any parameters, which will cause only the values ​​of AR and CC to be passed to the Makefile, and other FLAGS are missing.
![2](https://user-images.githubusercontent.com/61473216/109968919-41276300-7d2e-11eb-9dc9-541e330859d8.png)

**Comment by Logan007** [comment]
Thank you for explanation! @lucaderi is more involved in building and packaging and we therefore should wait for review.

**Comment by small-5** [comment]
In addition, the 13 lines of .travis.yml also need to be supplemented with a separate ./configure

**Comment by SvenRoederer** [comment]
Just a sidenote: I'm using cmake to build in OpenWrrt-SDK (tested so far for 18.06 and 19.07) and had no trouble to build dcd3801df52b9371445909a6148bfc3e41008d6c

**Comment by lucaderi** [comment]
I consider this ./configure an optional step but if you believe it is necessary I will accept the PR you make and close this ticket
