### ISSUE TITLE
ERROR: Failed to bind to local multicast group 224.0.0.68:1968

### ISSUE THREAD

**Issue by Menci** [ntop/n2n#65]
On Windows 10, with patch below so I compiled it successfully.

```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 3e351df..cacbb77 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -29,7 +29,6 @@ endif(NOT DEFINED CMAKE_BUILD_TYPE)
 #set(CMAKE_BUILD_TYPE Debug)
 #set(CMAKE_BUILD_TYPE Release)

-if (DEFINED UNIX)
 # None
 set(CMAKE_C_FLAGS "-Wall -Wshadow -Wpointer-arith -Wmissing-declarations -Wnested-externs")
 set(CMAKE_CXX_FLAGS "-Wall -Wshadow -Wpointer-arith -Wmissing-declarations -Wnested-externs")
@@ -39,7 +38,8 @@ set(CMAKE_CXX_FLAGS_DEBUG "-g")
 # Release
 set(CMAKE_C_FLAGS_RELEASE "-O2 -DNDEBUG")
 set(CMAKE_CXX_FLAGS_RELEASE "-O2 -DNDEBUG")
-endif()
+
+set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -I/usr/include -Wl,-LC:\\\\MinGW\\\\lib -Wl,-LC:\\\\MinGW\\\\msys\\\\1.0\\\\lib")

 ## DEBUG FOR CMAKE
 #message(${N2N_VERSION})
diff --git a/edge.c b/edge.c
index d92472c..3028722 100644
--- a/edge.c
+++ b/edge.c
@@ -730,7 +730,15 @@ int main(int argc, char* argv[]) {

     /* allow multiple sockets to use the same PORT number */
     setsockopt(eee.udp_multicast_sock, SOL_SOCKET, SO_REUSEADDR, &enable_reuse, sizeof(enable_reuse));
+#ifndef WIN32
+    /*
+     * From https://stackoverflow.com/questions/17212789/multiple-processes-listening-on-the-same-port
+     * Windows only knows the SO_REUSEADDR option, there is no SO_REUSEPORT.
+     * Setting SO_REUSEADDR on a socket in Windows behaves like setting
+     * SO_REUSEPORT and SO_REUSEADDR on a socket in BSD...
+     */
     setsockopt(eee.udp_multicast_sock, SOL_SOCKET, SO_REUSEPORT, &enable_reuse, sizeof(enable_reuse));
+#endif

     mreq.imr_multiaddr.s_addr = inet_addr(N2N_MULTICAST_GROUP);
     mreq.imr_interface.s_addr = htonl(INADDR_ANY);
diff --git a/edge_utils.c b/edge_utils.c
old mode 100644
new mode 100755
index 13bb7c9..01f34bb
--- a/edge_utils.c
+++ b/edge_utils.c
@@ -1743,7 +1743,16 @@ int quick_edge_init(char *device_name, char *community_name,

     /* allow multiple sockets to use the same PORT number */
     setsockopt(eee.udp_multicast_sock, SOL_SOCKET, SO_REUSEADDR, &enable_reuse, sizeof(enable_reuse));
+
+#ifndef WIN32
+    /*
+     * From https://stackoverflow.com/questions/17212789/multiple-processes-listening-on-the-same-port
+     * Windows only knows the SO_REUSEADDR option, there is no SO_REUSEPORT.
+     * Setting SO_REUSEADDR on a socket in Windows behaves like setting
+     * SO_REUSEPORT and SO_REUSEADDR on a socket in BSD...
+     */
     setsockopt(eee.udp_multicast_sock, SOL_SOCKET, SO_REUSEPORT, &enable_reuse, sizeof(enable_reuse));
+#endif

     mreq.imr_multiaddr.s_addr = inet_addr(N2N_MULTICAST_GROUP);
     mreq.imr_interface.s_addr = htonl(INADDR_ANY);
```

When I start edge with

```
edge.exe -a static:<ip here> -c somename -k password -l domain:port -b
```

It failed with:

```
ERROR: Failed to bind to local multicast group 224.0.0.68:1968
```

**Comment by littleplus** [comment]
I could completely successfully compile it now in Windows 7 x64, however, I meet the same error.

**Comment by Menci** [comment]
@littleplus How did you compile it? Did you patch the code?

**Comment by littleplus** [comment]
@Menci No, I compile it straight after I clone it by using cmake and vs2017 to compile the whole sln file.

**Comment by Menci** [comment]
@littleplus I don't have VS, so I used cmake with MSYS make.

**Comment by emanuele-f** [comment]
@Menci please note that the windows build has been fixed with https://github.com/ntop/n2n/pull/66 . You should not need anymore the patch above to compile it. Here are some updated instructions for compilation https://github.com/ntop/n2n/blob/dev/doc/Windows.md

**Comment by emanuele-f** [comment]
@Menci @littleplus in f5b2d00b065dfdf72b7be65d673b2a77f08c3730 I've added the `WSAGetLastError()` error log, please retry with the new version and report the error code you get. Are you running the program as administrator right?

**Comment by littleplus** [comment]
@emanuele-f Of course,
Error Code:
```
28/Mar/2019 13:21:04 [edge.c:744] ERROR: WSAGetLastError(): 10065
```

**Comment by Menci** [comment]
Now I don't have MSVC toolchain. Can I compile it with MSYS?

**Comment by emanuele-f** [comment]
I'm not very familiar with windows toolchains, it should be fine as long as it compiles fine. 10065 is WSAEHOSTUNREACH, I have to figure out why it returns such error

**Comment by ghost** [comment]
Same here:

Device Ethernet 4 set to 10.0.25.3/255.255.255.0
29/Mar/2019 04:44:32 [transform_aes.c:428] transop_addspec_aes sa_id=0, 128 bits data=encryptme.
29/Mar/2019 04:44:32 [edge.c:740] ERROR: Failed to bind to local multicast group 224.0.0.68:1968 [errno 0]
29/Mar/2019 04:44:32 [edge.c:744] ERROR: WSAGetLastError(): 10065

Network Setup
Supernode runs on a Windows VPS in a cloud with both UDP ports open in the Windows firewall. 

Edge client 1
One Windows edge client runs within VMware on my notebook and connected to the supernode :)

Edge client 2
The error above is from my Windows notebook itself, which hosts Vmware workstation :(

Code compiled with VS2017 and ICC19U3 from unchanged master. Plenty of Winsock deprecated warnings. 
TAP driver 9.22.1

Seems to be an issue with TAP driver and a physical network adapter, as on both virtual OS environments it seems to work fine.

**Comment by emanuele-f** [comment]
The multicast group uses the actual local network not the virtual one, so the tap driver should not be a problem here.

**Comment by ghost** [comment]
Think I found a solution or workaround after one of my vm's worked fine with n2n, but then stopped with the multicast error after a reboot which is odd:

My installation path of n2n was:
- Download https://swupdate.openvpn.org/community/releases/openvpn-install-2.4.7-I603.exe
- Extract exe with 7z to obtain tap-windows.exe
- Install tap driver using tap-windows.exe
- then dl this: http://build.openvpn.net/downloads/releases/tap-windows-9.22.1.zip
- extract and install new tap driver version using rightclick-on-inf file
- go to device manager and manually update TAP network device to 9.22.1
- reboot (just in case)

Now multicast error comes. To fix it I manually selected back the 9.21.x tab driver version in device manager.

So to manually install and update 9.22.1 messes up things. I don't know how to install 9.22.1 using command line. So for know I recommend to only use tap-windows.exe.

I tested this with Windows 2019 machines only, but should be very similar to Windows 10.

**Comment by ghost** [comment]
Quote: "Yes. 9.22.1 is broken and we know it. "

https://github.com/OpenVPN/tap-windows6/issues/49

The only "good" version for all Windows is 9.21.2 for now.

**Comment by Teteros** [comment]
Does anyone affected by this have still have it on the latest [9.23.3](http://build.openvpn.net/downloads/releases/tap-windows-9.23.3-I601.exe) ?

They fixed the signatures (as long as you got the certs from the installer version, weird!) and I don't have this issue on my VM so far.

If you don't want to deal with the installer to install/remove TAPs I attached x32/x64 scripts I usually use that might be of use for you. (just double click the .cmd file to use because default powershell policy prevents executing 3rd party scripts)
[tap-windows-9.23.3_with_scripts.zip](https://github.com/ntop/n2n/files/3278996/tap-windows-9.23.3_with_scripts.zip)

**Comment by emanuele-f** [comment]
@Teteros there is a reason why powershell is disabled by default, many people just run commands without even reading so it's better to direct users towards the official repositories instead of custom scripts

**Comment by lennondotw** [comment]
Has this problem been solved? I successfully compiled it, but I also encountered the same problem. I installed TAP-Windows Adapter V9 version 9.23.3.601, and I am using Windows 10.
```
Setting TAP device address...
Device TAP set to 192.168.100.2/255.255.255.0
21/Jun/2019 22:30:56 [edge_utils.c:182] supernode 0 => supernode.ntop.org:7777
21/Jun/2019 22:30:58 [edge_utils.c:1753] ERROR: Failed to bind to local multicast group 224.0.0.68:1968 [errno 0]
21/Jun/2019 22:30:58 [edge_utils.c:1757] ERROR: WSAGetLastError(): 10065
21/Jun/2019 22:30:58 [edge_utils.c:210] ERROR: Error: socket setup failed
21/Jun/2019 22:30:58 [edge.c:653] ERROR: Failed in edge_init
```

**Comment by Teteros** [comment]
@ReekyStive Yeah it's strange, I don't have the issue on 10 build 1809, while my friend on 1903 does.

Try [9.21.2](http://build.openvpn.net/downloads/releases/tap-windows-9.21.2.exe) which seems to not have this issue.

@emanuele-f I was wondering why edge needs to bind on port 1968 when multicast is off by default? Shouldn't it only bind if `-r -E` is passed?

**Comment by emanuele-f** [comment]
n2n requires multicast to discover local peers. `-r` will allow n2n to route the packets to other hosts, so this is not related. The `-E` option only affects the packets for the virtual n2n0 interface, whereas local peers multicast discovery happens on the physical interfaces (e.g. eth0).

**Comment by emanuele-f** [comment]
Multicast discovery now disabled in windows with https://github.com/ntop/n2n/commit/41bff29df6f682bf0713512da308fcb5e7c17202 , @ReekyStive please confirm that n2n now works fine for you

**Comment by lennondotw** [comment]
> Multicast discovery now disabled in windows with [41bff29](https://github.com/ntop/n2n/commit/41bff29df6f682bf0713512da308fcb5e7c17202) , @ReekyStive please confirm that n2n now works fine for you

I have succeeded! Thank you for your help!

**Comment by lennondotw** [comment]
> Multicast discovery now disabled in windows with [41bff29](https://github.com/ntop/n2n/commit/41bff29df6f682bf0713512da308fcb5e7c17202) , @ReekyStive please confirm that n2n now works fine for you

But I found a new problem. I did it on my Ubuntu server by following the README file:
```
reekystive@ReekyServer:/etc/n2n$ sudo systemctl start supernode
Failed to start supernode.service: Unit supernode.service not found.
reekystive@ReekyServer:/etc/n2n$ sudo systemctl enable supernode
Failed to enable unit: Unit file supernode.service does not exist.
```
Maybe I did something wrong?

**Comment by emanuele-f** [comment]
Have you installed the `n2n` package from http://packages.ntop.org ? You can also build the package manually from github, but I have to add the instructions

**Comment by lennondotw** [comment]
I built and installed them manually. I edited rc.local, so the supernode can now boot automatically.

**Comment by lennondotw** [comment]
I am currently playing Minecraft with my friends via n2n. They said it was very laggy. I monitored to make sure that network traffic did not pass through the server, and the latency between us and the supernode server was low. I pinged them through n2n and found that the latency was also low. But they are really laggy.
I am still looking for the reason, but I have not found the reason for the time being.

**Comment by emanuele-f** [comment]
I only tried once to play with an RTS strategy game and it worked very well, but maybe for more realtime gaming there is something to improve. Interesting!

**Comment by Teteros** [comment]
Friend with this issue on 9.23.3 drivers reported it's also fixed on latest `dev`.
Though that's expected since the windows version doesn't even bind on multicast port 1968 anymore.

Wouldn't it suit this to be made an argument passed to `edge` rather than a compile time only option though? Not all users need local-peer discovery regardless of playform.

**Comment by emanuele-f** [comment]
On windows I would keep it disabled to avoid headaches for the users. On other platform is usually desirable  to have it active as it will avoid unnecessary internet bandwidth usage. Also the discovery message is not sent too often. Anyway, if you are concerned about this and want to disable it all together then please open a separate issue.

**Comment by fengdaolong** [comment]
@emanuele-f 

The reasons for this problem are as follows:
When there are multiple network cards in the system, including physical network cards or VMware Network Adapter, etc. When setsockopt set the IP_ADD_MEMBERSHIP action, if specified as INADDR_ANY `mreq.imr_interface.s_addr = htonl(INADDR_ANY);`, the operating system will randomly add the IP address of a network adapter. If the IP is not the egress network card of the default route, the binding fails. Socket error code is 10065 (No route to host).

The solution that can be thought of:
Find out the IP address of the network card according to the default route, and replace INADDR_ANY with a specific IP address.
