### ISSUE TITLE
Run error on WIN10

### ISSUE THREAD

**Issue by small-5** [ntop/n2n#652]
Use VS2019 to compile commit 20133f599c22c88eb160b9c53c52894772cb71af,and an error will be reported when running, as shown in the figure, please fix!
![1](https://user-images.githubusercontent.com/61473216/109568585-149efb80-7b22-11eb-94b5-84d1eab534a6.png)

**Comment by Logan007** [comment]
Thanks for reporting!

This is no real "ERROR" as indicated, just a result of slighlty changed logic for TCP implementation. I will fix it sometime soon.

**Comment by Logan007** [comment]
Do you want to try #653?

**Comment by small-5** [comment]
Now the error is WARNING: Supernode not responding
supernode has also been recompiled
![image_2021-03-02_19-25-06](https://user-images.githubusercontent.com/61473216/109642043-76487f80-7b8d-11eb-8552-66345e85fe95.png)

**Comment by Logan007** [comment]
Oh, I see, you have been talking about the "not responding" and not so much about the "ERROR" message...

The new commit 1ef2f8f to the pull request should fix it. It took a while to find the unsuspected datatype behaving strangely... if anyone could explain, I would be interested.

**Comment by small-5** [comment]
Thank you! https://github.com/ntop/n2n/commit/1ef2f8f2307c939491bb22021adc7b6e907de22e has solved this problem.
