### ISSUE TITLE
Packet Format Changes - Final Call for 3.x!

### ISSUE THREAD

**Issue by Logan007** [ntop/n2n#656]
I would like to add some final packet format changes. They shall be final in terms of that they ensure compatibility throughout the whole 3.x series.

I would like to
- add a `srcMac` field to REGISTER_SUPER_ACK to deliver `-l`-provided supernode's MAC back to the edge
- ~~enlarge auth token size to 64 or 128 to ensure seamless integeration of future auth schemes~~

and open a corresponding pull request soon.

Are there any more ideas of what we should consider? Should we integrate a "reserved" field of say 64 bytes into each message type for later re-dedication if required?

**Comment by skyformat99** [comment]
> Are there any more ideas of what we should consider? Should we integrate a "reserved" field of say 64 bytes into each message type for later re-dedication if required?

It would be wasteful to have 64 bytes per message.It is recommended that there be two types of message frames.
64 bytes are added when supernode requires auth.

**Comment by Logan007** [comment]
@skyformat99, you are absolutely right! 64 unconditionally empty bytes per REGISTER_SUPER would sum up to roughly a quarter megabyte per day. Thank you very much for pointing it out.

I took a deep look into the code (`wire.c`) and found that auth tokens already are encoded flexible size. So, the 64 or 128 are just internal maximum sizes of which only those that are really needed get encoded into the packet. With that already present flexibility being available, we can scratch that bullet from the list.

**Comment by skyformat99** [comment]
> @skyformat99, you are absolutely right! 64 unconditionally empty bytes per REGISTER_SUPER would sum up to roughly a quarter megabyte per day. Thank you very much for pointing it out.
> 
> I took a deep look into the code (`wire.c`) and found that auth tokens already are encoded flexible size. So, the 64 or 128 are just internal maximum sizes of which only those that are really needed get encoded into the packet. With that already present flexibility being available, we can scratch that bullet from the list.

thanks, very good!

**Comment by Logan007** [comment]
Additionally, I want to add a field to REGISTER_SUPER_ACK's payload: supernode_load.

Edges which are connected through supernode only do not have an opportunity to send out ping to other supernodes. Therefore, they do not have any idea of other supernode's load and are not able to dynamically switch to another one.

If the load values were transmitted inside the REGISTER_SUPER_ACK payload, those edges would benefit as well. I do not want to implement this mechanism yet but reserve this field in the packet's data structure for later addition during 3.x series without breaking compatibility then.
