### ISSUE TITLE
supernode.conf bug？

### ISSUE THREAD

**Issue by zhengbucuo** [ntop/n2n#661]
![image](https://user-images.githubusercontent.com/31462232/110591510-1ddc3800-81b4-11eb-90ac-78ef46e4e74d.png)

I have a similar problem
#581

**Comment by Logan007** [comment]
~~Could you please share your supernode's `.conf` file content?~~ Sorry, I have not seen  it in the first place.

**Comment by Logan007** [comment]
What version do you use?

In case you use 2.8, please note that the port parameter changed from `-l` to `-p` during development of 2.9/3.0. So, for 2.8 it still would be `-l=1109`.

I see that you use the executable from the `/usr/sbin/` folder and not the local directory `./supernode` one. Have you made sure that it is current _dev_ in `/usr/sbin`?

I have just tried your exact configuration with current _dev_ (2.9) and it works well over here.

**Comment by zhengbucuo** [comment]
- version info
```
root@n2n:/etc/n2n# supernode
Welcome to n2n v.2.8.0.r540.53afd3c for Debian bullseye/sid
Built on Mar 10 2021 21:19:07
Copyright 2007-2020 - ntop.org and contributors
```
btw...
After re installation, it is normal.
It could be a small probability event？
3Q~

**Comment by Logan007** [comment]
Okay, if it is 2.8, you definitely need to use `-l=...` instead of `-p=...`.

**Comment by Logan007** [comment]
Okay, if it is 2.8, you definitely need to use `-l=...` instead of `-p=...`.

**Comment by Logan007** [comment]
So, shall we close this? Please re-open if required.
