### ISSUE TITLE
mipsel and mipsel can not  communicate or ping

### ISSUE THREAD

**Issue by llfj** [ntop/n2n#681]
n2n v.2.9.0.r902.35dc670 

Mingw cross-compiled windows and linux do not use -k to communicate and ping. If you use -k, you can communicate but you can't ping. There should be a problem with encryption and decryption after compilation. But windows and windows can communicate with or without -k, and can also ping. Windows compiled with the VS compiler can communicate with Linux normally and can also ping.

But use buildroot tool to cross compile mipsel edge (such as CPU: mtk7621, openwrt), they can register to the supernode correctly, but the mipsel edge and mipsel edge or any edge cannot communicate or ping, no matter whether -k is used or not.

[192.168.100.1.txt](https://github.com/ntop/n2n/files/6259005/192.168.100.1.txt)
[192.168.100.2.txt](https://github.com/ntop/n2n/files/6259006/192.168.100.2.txt)
[supernode3.txt](https://github.com/ntop/n2n/files/6259007/supernode3.txt)

[n2n_v2_linux_mipsel.zip](https://github.com/ntop/n2n/files/6259011/n2n_v2_linux_mipsel.zip)

**Comment by Logan007** [comment]
> **Mingw** cross-compiled windows and linux ...

I hope we get it solved with #642.

> use **buildroot** tool to cross compile mipsel edge ...

Is #571 related?

Overall, all kinds of **cross**-compiling seem to cause difficulties. And frankly, I have no idea about the causes yet. Anyone?

**Comment by llfj** [comment]
#571 ARM
Cross-compiled to ARM edge, can communicate with other platforms.

**Comment by Logan007** [comment]
@llfj On the one hand, this is great news! Could you give some hints to @kingvonlei in #571 on how you achieved it?

On the other hand, it is quite confusing that cross-compilation works for some platforms and not for others. Strange things ...

**Comment by llfj** [comment]
Errors of #571 occurs during compilation, but I was successful
I do not use autogen.sh
I use CMAE, so there is no errors like #571

**Comment by llfj** [comment]
v.2.9.0.r946.ecedcdc 
mipsel and mipsel  can communicate normally，ping test can pass.

**Comment by Logan007** [comment]
> v.2.9.0.r946.ecedcdc
> mipsel and mipsel can communicate normally，ping test can pass.

So, is this issue resolved then? Did you use special settings?

**Comment by llfj** [comment]
resolved，didn't to use any special settings

**Comment by Logan007** [comment]
Good news!
