### ISSUE TITLE
openwrt Compilation failed

### ISSUE THREAD

**Issue by dwj0** [ntop/n2n#686]
configure: WARNING: unrecognized options: --disable-nls
configure: loading site script /mnt/sdb1/hc5962/include/site/mipsel
checking for mipsel-openwrt-linux-gcc... gcc
checking whether the C compiler works... no
configure: error: in `/mnt/sdb1/hc5962/build_dir/target-mipsel_24kc_musl/n2n-2.9.0_dev_git667b7df0836f95b77e7e6301438e9ab9e65883ee':
configure: error: C compiler cannot create executables
See `config.log' for more details

**Comment by Logan007** [comment]
Does #712 solve it for you?

**Comment by Logan007** [comment]
Any news?

**Comment by Logan007** [comment]
Considered solved. Please re-open if required.
