### ISSUE TITLE
Hello, a company has applied for an invention patent with similar functions as yours

### ISSUE THREAD

**Issue by wnark** [ntop/n2n#688]
[一种基于端口复用和TCP加密技术的内网穿透方法_周正军_段春明.zip](https://github.com/ntop/n2n/files/6374664/TCP._._.zip)

**Comment by wnark** [comment]
Please pay attention to protect your ideas. Thank you
[一种内网穿透系统_何少军_邱镇_毕艳冰_崔迎宝_魏_省略_丰_黄晓光_李檀_刘园园_费长顺.zip](https://github.com/ntop/n2n/files/6374670/_._._._._._._._._._._.zip)

**Comment by tlsalex** [comment]
Please pay attention to protect your ideas. Thank you

**Comment by orangeagain** [comment]
水论文的吧

**Comment by skyformat99** [comment]
无关话题
close it
