### ISSUE TITLE
WARNING: Failed to resolve supernode host

### ISSUE THREAD

**Issue by felix-git-hub** [ntop/n2n#689]
n2n 2.8 built with the static option on Debian x64, it worked all right on the debian platform, however when on  OpenWrt 19.07.4 x86 platform, the edge failed to resolve the supernode, while ping the host url works well.

[edge_utils.c:370] WARNING: Failed to resolve supernode host

**Comment by felix-git-hub** [comment]
./edge -c mynetwork -k mysecretpass -a 192.168.100.1 -f -l super
node.ntop.org:7777
27/Apr/2021 14:59:10 [edge_utils.c:2575] Adding supernode[0] = supernode.ntop.org:7777
27/Apr/2021 14:59:10 [edge.c:841] WARNING: Switching to Twofish as key was provided.
27/Apr/2021 14:59:10 [edge.c:852] Starting n2n edge 2.8.0 Apr 25 2021 20:29:00
27/Apr/2021 14:59:10 [edge.c:858] Using compression: none.
27/Apr/2021 14:59:10 [edge.c:859] Using twofish cipher.
27/Apr/2021 14:59:10 [edge.c:869] ip_mode='static'
27/Apr/2021 14:59:10 [edge_utils.c:211] supernode 0 => supernode.ntop.org:7777
27/Apr/2021 14:59:10 [edge_utils.c:370] WARNING: Failed to resolve supernode host supernode.ntop.org
27/Apr/2021 14:59:10 [edge.c:935] WARNING: Running as root is discouraged, check out the -u/-g options
27/Apr/2021 14:59:10 [edge.c:947] edge started
27/Apr/2021 14:59:10 [edge_utils.c:727] Successfully joined multicast group 224.0.0.68:1968
27/Apr/2021 14:59:10 [edge_utils.c:370] WARNING: Failed to resolve supernode host supernode.ntop.org
27/Apr/2021 14:59:13 [edge_utils.c:370] WARNING: Failed to resolve supernode host supernode.ntop.org
27/Apr/2021 14:59:23 [edge_utils.c:370] WARNING: Failed to resolve supernode host supernode.ntop.org
27/Apr/2021 14:59:33 [edge_utils.c:927] WARNING: Supernode not responding, now trying supernode.ntop.org:7777
27/Apr/2021 14:59:33 [edge_utils.c:370] WARNING: Failed to resolve supernode host supernode.ntop.org
27/Apr/2021 14:59:43 [edge_utils.c:370] WARNING: Failed to resolve supernode host supernode.ntop.org
^C27/Apr/2021 14:59:45 [edge.c:775] Shutting down...

**Comment by felix-git-hub** [comment]
ping supernode.ntop.org
PING supernode.ntop.org (151.11.50.180): 56 data bytes
64 bytes from 151.11.50.180: seq=0 ttl=48 time=288.196 ms
64 bytes from 151.11.50.180: seq=1 ttl=48 time=291.076 ms
64 bytes from 151.11.50.180: seq=2 ttl=48 time=290.972 ms
^C
--- supernode.ntop.org ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 288.196/290.081/291.076 ms

**Comment by lucktu** [comment]
"supernode.ntop.org:7777" is for n2n_v2.9 (It's actually v3, which isn't compatible with v2), isn't for v2.

**Comment by felix-git-hub** [comment]
built with -static option,  it seems that glibc is missing in the openwrt
edge_utils.c:(.text+0xf75): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
