### ISSUE TITLE
connection fail when using hotspot

### ISSUE THREAD

**Issue by tlsalex** [ntop/n2n#692]
I can not use Wi-Fi today, but I can connect to a hotspot provided from my phone on my laptop.

Unfortunately， edgenode can not connect to supernode , I though it was MTU problem , then I add -D to edge config. but it's still not working , keep showing bellow errors: 

However , I can see the traffic from edge to supernode by using tcpdump on my server. what should I do in order to fix it?

```
04/May/2021 17:59:07 [edge_utils.c:1320] WARNING: Supernode not responding, now trying xx.xx.xx.xx:8080
04/May/2021 17:59:07 [edge_utils.c:208] Binding to local port 0
04/May/2021 17:59:07 [edge_utils.c:208] Binding to local port 0
04/May/2021 17:59:13 [edge_utils.c:1320] WARNING: Supernode not responding, now trying xx.xx.xx:8080
04/May/2021 17:59:13 [edge_utils.c:208] Binding to local port 0
04/May/2021 17:59:13 [edge_utils.c:208] Binding to local port 0
```
PS:  run in TCP mode

**Comment by Logan007** [comment]
I am not exactly sure what is going on there. I would suspect NAT but it should not be at all problem with TCP connection. Does it work in UDP mode then?

**Comment by Logan007** [comment]
Strange enough, I encountered the same issue on one certain computer (only that one) a few days ago. And it is persistent. Only reboot helps it, but only for roughly 30 minutes. I am not sure about the specifics, maybe it is some system update I did. This definitely needs further investigation.

**Comment by Logan007** [comment]
In my case, I found the issue by running the supernode with `-vvvvv` option and investigating the log. Turns out that the clocks were not in sync while using header encryption `-H` ... :facepalm: 

So, at least for me, that was easily fixed :wink:

Did you check your system clocks?

**Comment by Logan007** [comment]
> hotspot provided from my phone

Maybe mobile provider filtering things such as the unusual port 8080 (well, unusual for some...)? Would it work with supernode on port 80 or 443?

**Comment by Logan007** [comment]
Still an issue?

**Comment by Logan007** [comment]
> on Jul 21
> Still an issue?

Considered deprecated, please re-open if required.
