### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by guojiazhuxi** [ntop/n2n#696]
this is the configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for pcap_open_live in -lpcap... yes
checking for pcap_set_immediate_mode in -lpcap... yes
checking for cap_get_proc in -lcap... no
configure: creating ./config.status

Make failed
gcc -O3 -march=native -DSN_SELECTION_RTT  -I ./include        src/edge.c  libn2n.a  -o edge
libn2n.a(random_numbers.o): In function `n2n_seed':
random_numbers.c:(.text+0x214): undefined reference to `_rdseed64_step'
collect2: error: ld returned 1 exit status
make: *** [edge] Error 1

Please，What should I do？

**Comment by Logan007** [comment]
First, please make sure that you have run `./autogen.sh`, `./configure CFLAGS="<your flags>"` and `make clean` before running make again. Believe me, I have seen the strangest things myself especially after **not** running `make clean`... :wink:

It seems that the compiler assumes `__RD_SEED__` (hardware random number generator, used in `src/random_numbers.c:144` for initialization) to be defined. The compiler sets this macro if it assumes proper hardware support. What does  `echo | gcc -dM -E - -march=native | grep SEED` show?

To find out if the CPU supports rdseed, please run `lscpu | grep --color rdseed`. Does it show up? What CPU do you use?

If you find that the `__RDSEED__` macro is set but the CPU does not support it, you could manually turn it off, just add `-U__RDSEED__` to your flags, e.g. `./configure CFLAGS="-O3 -march=native -DSN_SELECTION_RTT -U__RDSEED__"`.

**Comment by guojiazhuxi** [comment]
thank you!
My system is centos7
echo | gcc -dM -E - -march=native | grep SEED  :  #define __RDSEED__ 1
lscpu | grep --color rdseed : Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq **rdseed** adx smap avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 arat avx512_vnni

I ran make clean, but I still get the above error .
The configuration I am running is：./configure CFLAGS="-O3 -march=native -DSN_SELECTION_RTT -std=gnu99"


now  run ./configure CFLAGS="-O3 -march=native -DSN_SELECTION_RTT -U__RDSEED__ -std=gnu99" is ok

**Comment by Logan007** [comment]
> ... is ok

I am glad to hear!

Does it work if you do not adhere to gnustd99, i.e. omitting `-std=gnu99`?

**Comment by guojiazhuxi** [comment]
This will not work, it will show the following error：
src/aes.c: In function ‘aes_internal_key_setup’:
src/aes.c:300:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for(int i = 1; i < ctx->Nr; ++i) {
     ^
src/aes.c:300:5: note: use option -std=c99 or -std=gnu99 to compile your code
make: *** [src/aes.o] Error 1

**Comment by Logan007** [comment]
Oh, I see. Then, the `-U...` is your best choice.

**Comment by guojiazhuxi** [comment]
If I use -std=c99, it also does not work：

src/transform_aes.c: In function ‘n2n_transop_aes_init’:
src/transform_aes.c:226:5: error: unknown type name ‘u_char’
     const u_char *encrypt_key = (const u_char *)conf->encrypt_key;
     ^
src/transform_aes.c:226:5: error: unknown type name ‘u_char’
src/transform_aes.c:245:5: warning: passing argument 2 of ‘setup_aes_key’ from incompatible pointer type [enabled by default]
     return setup_aes_key(priv, encrypt_key, encrypt_key_len);
     ^
src/transform_aes.c:178:12: note: expected ‘const uint8_t *’ but argument is of type ‘const int *’
 static int setup_aes_key (transop_aes_t *priv, const uint8_t *password, ssize_t password_len) {

**Comment by Logan007** [comment]
Yes, the code does not adhere to the strict standards everywhere... And some (older version?) compiler might require the `-std=gnu99` to compile well. However ,it apparently does not include the `rdseed`, so we need to undef it manually.

**Comment by guojiazhuxi** [comment]
I have three computers, all of which are installed with centos7 system, and all of them have the same error. I think this may not be an example.

**Comment by guojiazhuxi** [comment]
Thank you very much, the software you developed has helped me a lot, and your open source spirit has also greatly influenced me!

**Comment by Logan007** [comment]
Could you please check your compiler version `gcc --version` for me?

I just got aware that the `rdseed` instrinsics are supported by gcc starting from version 4.6 or 4.8.

**Comment by guojiazhuxi** [comment]
> Could you please check your compiler version `gcc --version` for me?
> 
> I just got aware that the `rdseed` instrinsics are supported by gcc starting from version 4.6 or 4.8.

I can, how can I do it?

**Comment by guojiazhuxi** [comment]
the gcc version:
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by Logan007** [comment]
I think if you get a chance to upgrade to a newer version of `gcc`, the `-U...` will not be required anymore.

However, I will guard the `rdseed` section with some `GNUC > 4` version checking. It might exclude some other legit compilers from compiling this instruction as well, but it is as sharp as I can get to it now.

Everybody, please feel free to fine-tune.

**Comment by guojiazhuxi** [comment]
thank you

**Comment by introspection3** [comment]
@Logan007 it's a problem,you can use c99,but when we use highest version,it's also a bug ,so this is code excpetion.

**Comment by introspection3** [comment]
@Logan007 gcc lastest

**Comment by Logan007** [comment]
Perhaps it is better to temporarily disable this code section...

Does this only happen on CentOS?

Have you tried `clang` instead of `gcc`?

**Comment by introspection3** [comment]
@Logan007 not yet,sir,so we do as you said c99

**Comment by Logan007** [comment]
What CPU?

**Comment by introspection3** [comment]
vps 
: Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz
centos

**Comment by Logan007** [comment]
The CPU should support RDSEED instruction. I guess that `lscpu` show it as well. Also, `echo | gcc -dM -E - -march=native | grep SEED` presumably shows the RDSEED define...

Not sure what happens here. Maybe, it is `gcc` or it is virtualization-related. Thinking of how to solve it... :thinking:

**Comment by Logan007** [comment]
> Oh, I see. Then, the -U... is your best choice.

I haven't been able to come up with a better solution. As I do not see the nedd to glabally disable this part of the code, I will add a hint to the `doc/Building.md` document.

**Comment by Logan007** [comment]
Added a hint to Building doc, considered "solved". Please re-open if a better solution is found.
