### ISSUE TITLE
communication via spuernode<->supernode fail

### ISSUE THREAD

**Issue by fghlw** [ntop/n2n#698]
edge A connected to node A; edge B connected to node B, node B set -l xxxx:xxxx connect to node A; 
node A with internet IP, node B be in internal network but can access internet communicate to node A.
But edge A can't communicate to edge B

**Comment by Logan007** [comment]
Do you want to check out current _dev_? I have a strong feeling that #707 might also have fixed this issue.

**Comment by fghlw** [comment]
thank you. I will try it.

**Comment by fghlw** [comment]
a question, if need rebuild "edge"? I remember I replaced some function(about get/set IP?) to make it work under "xp", but I forgot which one...

**Comment by Logan007** [comment]
I am not all too deep into Windows, but you are maybe talking about `inet_ntop()`?

**Comment by fghlw** [comment]
Yes, looks like this function not available in xp?

**Comment by Logan007** [comment]
I can't say for sure, never tried XP. But I saw @etherealvisage having implemented a [corresponding wrapper function](https://github.com/elphasecure/n2n/commit/7cc7624a48798550ad6f4b5f26df4b3518125327).

If this turns out to be the missing piece to get the software running on Windows XP, hope is that someone back-ports it to our _dev_ in a way which does not affect compatibility with more recent Windows versions.

**Comment by etherealvisage** [comment]
The backport should be pretty simple. Add the relevant source files and conditionally compile them in if on XP/if asked to during configuration. Not sure if that's all that's needed for XP support, but certainly this piece isn't hard :-)

**Comment by Logan007** [comment]
@etherealvisage Do you want to provide a pull request?

**Comment by fghlw** [comment]
the newest "autogen.sh" seems miss "./configure"? it can't work

**Comment by Logan007** [comment]
As far as I remember, `./configure` always needs to be manually invoked after `./autogen.sh`. I have never seen anything else in this project.

**Comment by fghlw** [comment]
> As far as I remember, `./configure` always needs to be manually invoked after `./autogen.sh`. I have never seen anything else in this project.

the code I downloaded on March include this line, so I thought it included

**Comment by Logan007** [comment]
I am not sure what has happened there. Especially as we always [advertise](https://github.com/ntop/n2n#manual-compilation) to use the `./autogen.sh`-`./configure`-`make`trinity.

Apart from this, does it work for you with a manual `./configure`?

**Comment by fghlw** [comment]
it works, but if included in "./autogen.sh" more "auto"..   :)

I use the newest code but in "first node" run "nc -u 127.0.0.1 xxxx"
I got " 1 | 192.168.100.4/0 "  the mask is "0"?

**Comment by Logan007** [comment]
> I use the newest code but in "first node" run "nc -u 127.0.0.1 xxxx"

you run this at the supernode, right?

> I got " 1 | 192.168.100.4/0 " the mask is "0"?

A `/0` mask indeed is very unusual. Default should be `/24` (auto IP as well as manually assigned).

How does the corresponding edge gets its IP address? `-a ....` or does it draw auto IP address from the supernode? Does it only affect the first edge? Do the other edges show up with the correct mask?

**Comment by fghlw** [comment]
> > I use the newest code but in "first node" run "nc -u 127.0.0.1 xxxx"
> 
> you run this at the supernode, right?
> 
> > I got " 1 | 192.168.100.4/0 " the mask is "0"?
> 
> A `/0` mask indeed is very unusual. Default should be `/24` (auto IP as well as manually assigned).
> 
> How does the corresponding edge gets its IP address? `-a ....` or does it draw auto IP address from the supernode? Does it only affect the first edge? Do the other edges show up with the correct mask?

in this machine "-a" is not work, I set IP manually.  Now this supernode only connect this edge.  And this supernode connected to another supernode which with internet IP.  On "another supernode" "nc" command not read the correct IP of "192.168.100.4"

**Comment by fghlw** [comment]
What my setting is wrong?

**Comment by Logan007** [comment]
> I set IP manually

So, just to clarify, you set the edge's TAP IP address by an `ip link ...` command? And you do not give the `-a <IP-address>` at the edge command? Does the other supernode show a TAP address from the `10.xx.xx.xx` range? What OS do you run that edge on?

**Comment by fghlw** [comment]
> > I set IP manually
> 
> So, just to clarify, you set the edge's TAP IP address by an `ip link ...` command? And you do not give the `-a <IP-address>` at the edge command? Does the other supernode show a TAP address from the `10.xx.xx.xx` range? What OS do you run that edge on?

I run edge on win10 set IP via GUI not command. Not shown `10.xx.xx.xx` on another supernode(but not confirm that, I can check later).

**Comment by fghlw** [comment]
I checked no "10.xx.xx.xx" on another supernode. just "COMMUNITY xxxx" but below that is blank

**Comment by fghlw** [comment]
I start the egde by "srvany" to avoid show a shell window on desktop.  seems this not work fine.  But I still can't find connections on "node A".

**Comment by Logan007** [comment]
Interestingly, during one of my rare expeditions to a Windows VM, I also saw the IP address and especially the subnet not being set properly – for some so far  unknown reason. I was able to get it work using `-a 10.99.99.99/24` (note the added CIDR subnet `/24`) at the edge. I hope it might help you as well.

**Comment by Logan007** [comment]
Did it help?

**Comment by Logan007** [comment]
Considered deprecated, please re-open if required.

**Comment by fghlw** [comment]
Thank you, just notice that, I can try, but all my network are set 10.xx.xx.xx, so normally I don't use these IPs. But Still can try that.

**Comment by Logan007** [comment]
... or any other CIDR subnet matching your needs. The point is more about explicitly _specifying_ the subnet.
