### ISSUE TITLE
How much traffic and edgenodes can a supernode support ？

### ISSUE THREAD

**Issue by MaoPann** [ntop/n2n#699]

**Comment by Logan007** [comment]
Basically, your hardware determines the limit.

To get an idea of what your hardware is capable to do, you could run the`tools/n2n-benchmark` utility which determines some encryption, decryption and compression speed figures. I usually recommend to [build](https://github.com/ntop/n2n/blob/dev/doc/Building.md) using the `-O3` as well as the `-march=native` compiler flags.

`edge` and `supernode` need to process incoming packets which does not only include encryption but also additional internal packet handling.

**Comment by MaoPann** [comment]
If the performance of the hardware is enough, how much can it reach? Can you give us a specific number for reference? In addition, do we need to pay for a license to use n2n

**Comment by Logan007** [comment]
> If the performance of the hardware is enough, how much can it reach?

There is no limit in the code concerning the number of max edge nodes.

Traffic-wise, it depends a little bit on if p2p is possible: If p2p is possible, the supernode does not need to forward the data traffic (only broadcasts, multicasts and some registration traffic).

> Can you give us a specific number for reference?

I have [heard](https://github.com/ntop/n2n/issues/412#issue-694901085) that above 5,000 edge nodes, one supernode at a 1000 Mbps line was saturated handling the background broadcast traffic only. However, this scenario should be mitigated by the meanwhile added federation feature which interconnects several supernodes to share the load.

> In addition, do we need to pay for a license to use n2n

n2n is [licensed](https://github.com/ntop/n2n/blob/dev/LICENSE) under GNU GPL 3.0. So, you do not have to pay for just using it but you always need to stick to the license conditions.

However, if you **want** to pay for using it, there are ways to support the development.

**Comment by MaoPann** [comment]
thanks!!!
