### ISSUE TITLE
Revamp CBC: Initialization Vector, Message Authentication

### ISSUE THREAD

**Issue by Logan007** [ntop/n2n#70]
As far as I realized, for now, the initialization vector (IV) for CBC mode is set to zero - instead, a 32 bit random value is inserted in front of the packet used. As it is generated randomly on one end and not evaluated on the other end of the communication line (which would require further communication steps), I am not able to see how the current implementation of the nonce helps to prevent replay attacks. 

Given AES's block size of 128 bit and that ethernet packets (we are talking iso/osi level 2) have a well known constant preamble, the first block might only have a variety of 2 ^ 32 = 4G possibilites. I am not saying that this weakens the system, but it could help known-plaintext attacks. Attack complexity even lowers as the key seems to be ASCII coded input.

I would recommend to use full block sized IV in the following way:

- Get rid of the encrypted nonce.

- Initialize a complete block sized 128 bit random value as IV for the packet data encryption.

- If neccessary, a few (!) of those bits could be used to encode part of a universal time stamp or some counter. For example, some part of a unix time stamp and also a packet counter would allow to detect replay attacks. This idea of a feature needs more evaluation as the receiver must handle this properly but somewhat tolerant towards packet loss and diverging clocks, details might be subject to another issue to be created later.

- Encrypt IV seperately as a single block (another key **could** be used, e.g. the second half of the SHA512ed input key, see [#68](https://github.com/ntop/n2n/issues/68)) and prepend it to the encrypted packet. Of course, the receiver needs to decrypt the IV before it can decrypt the packet. This is necessary to stop an attacker from fiddling with the IV (prevents a possible attack on the first block) and also because of maybe some somewhat predictable parts of the IV (timestamp or counter, see above). This also allows to use the same random IV for message authentication, see below - random IV for message authentication would be insecure otherwise.

And as the packet gets a new format anyway, some space for message authentication (ECBC-MAC) could be reserved as follows:

- Before encrypting the packet, add a 16 bit field for the packet length in front of it. 16 bit should suffice for ethernet frames. This is necessary for the security of the following message authentication method. The length should share the first data block, no separate block. The receiver is to verify packet length.

- Encrypt the last, already encrypted message block (another key **must** be used, e.g. the second half the the SHA512ed input key, see [#68](https://github.com/ntop/n2n/issues/68)) again and prepend it to the encrypted packet. It does not matter if it is in the first place or between the encrypted IV and the encrypted packet content. This method takes advantage of the already chained content in CBC mode, so it only works in CBC mode. It requires one additional encryption step only - it should not affect performance much, given that AES could be hardware accelerated now. The receiver must verify this message authentication code by reencrypting the decrypted data and redoing the additional encryption step. Unfortunately, this de-/encryption step only followed by a comparison to the last data block are **not** sufficient, because this way, changes of data in the middle of the package could not be detected due to parallel decryption in CBC mode.

- In a "strict mode", packets that do not match length (round up to block size where appropriate) or fail authentication must be discarded.

With all this implemented, it would be a huge step forward in terms of security. Maybe TF should switch to CBC mode, too? 

Packets would look like as follows:

```
*  [V|SSSS|MMMMMMMMMMMMMMMM|IIIIIIIIIIIIIIII|LLDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD]
*         |< encrypted K2 >|< encrypted K2 >|<------- encrypted K1 --------->|
```

where
V = the AES version, if required,
S = a 32-bit SA number in clear text,
M = the 128 bit Message authentication code (last encrypted data block encrypted again using K2),
I = the separately encrypted IV (using K1 or preferably K2),
L = length of the following data (encrypted using K1), 
D =  data (encrypted using K1),
K1 = key1 and
K2 = key2.

[EDITed - _lifting some confusive wording_]

**Comment by emanuele-f** [comment]
You are right, this is broken, not only the IV is set to 0 on startup but also before sending a packet (see https://github.com/ntop/n2n/blob/dev/transform_aes.c#L184), this is suspect too.

To summarize the outlined problems:
- The CBC IV is not random, it's set to 0
- The CBC IV is reset to 0 before sending every packet
- The replay nonce is useless as it's never checked (this also applies to twofish)

Before digging in a complete rework, some thoughts and questions:
 - Is there a quick fix to properly initialize and use the IV without/with minimal packet modifications?
 - Is CBC appropriate for this task in n2n? If yes, can we drop the key-schedule mode of n2n (`-K` option) to simplify things and perform fixes without worrying about compatibility?
 - Regarding replay prevention, can we find a general solution that works with both aes and twofish without binding it to the actual encryption method used?

**Comment by emanuele-f** [comment]
More information:
 - The IV *can* be sent in cleartext. Reusing the same IV, however, is *insecure* and does not provide confidentiality (the current implementation is bugged and must be fixed)
 - Due to the way CBC encryption works, using a wrong IV in the decryption is fine. This will only invalidate the first block decryption, the following blocks will be decrypted successfully. "Explicit Initialization Vectors" use this property to avoid sending the IV and instead providing a dummy block just for the initial synchronization.

Source: https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Initialization_vector_(IV)

As far as I understand, a quick fix would be to randomize the encryption IV vector without further modifications. We would lose the first block of data (this can be fixed later on) but confidentiality would be fixed

**Comment by Logan007** [comment]
I would not consider this a _bug_ as impact on security is not too heavy, but below 2 ^ 160 due the preamble and zeroed IV. For now, users should just be aware of it. It could be seen more as an _enhancement_ to security.

Generally, the IV could be sent in clear text. But **if** it is used for message authentication as suggested **or** contains predictable parts (like non-disclosed counter values as suggested) **or** shall be applied to some predictable block, it needs to be encrypted for transmission to keep up security. I would also recommend to do it because the first plain text data block is somewhat predictable.

CBC is very suitable, same holds true for ECBC-MAC (big advantage: only a few steps to add). It just is essential to use another key K2 on the last block, that already is encrypted with K1, and of course to encrypt IV (see above) as well as to add packet lentgh in the first place of the encrypted packet.

As TF also is a block cipher even with the same block size, nothing should keep it away from CBC.

[EDITed multiple times - just love to edit]

**Comment by Logan007** [comment]
PS: Can't promise anything, but with enough time, I might be able to apply the necessary changes to the AES code... Last coding experience is more than a while ago.

**Comment by emanuele-f** [comment]
Thank you for your feedback! I'm not very practical with the crypto stuff, so I cannot fully review the proposal above, there are still points not clear to me. I'd wait other reviews before going to implement anything. Please keep in mind that authentication is not a priority right now whereas fixing (or greatly improving) confidentiality is (#68 is in fact important too). Avoiding packet replays should also be implemented. A simple solution will easily fit the current requirements better than a complex one.

**Comment by Logan007** [comment]
Please find attached a [patch](https://github.com/ntop/n2n/files/2923141/revampCBC.txt) that implements nearly all of the above mentioned. The only thing missing is the verification of the message authentication code as we shall prioritize confidentiality. But it already is calculated and put into the enhanced packet format. AES version is increased by one.

IV is random and encrypted (because first plain text block is quite foreseeable). IV does not contain any replay protection yet.

The changes proposed by [#68](https://github.com/ntop/n2n/issues/68) and [#75](https://github.com/ntop/n2n/issues/75) are also included.

To keep the patch as short as possible and changes to the code as small as possible, I did not put any comments or updated the existing ones. Cleanup could follow in a later patch. UPDATE: ... in pull request #76.

**Comment by emanuele-f** [comment]
Closing this issue as the specific parts have been split in separate issues and pull request above.
