### ISSUE TITLE
Keep getting this error

### ISSUE THREAD

**Issue by guojiazhuxi** [ntop/n2n#704]
[sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
 [sn_utils.c:720] authentication failed

excuse me, can you tell me the reason？

**Comment by guojiazhuxi** [comment]
[sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
[sn_utils.c:720] authentication failed

excuse me, can you tell me the reason？

**Comment by guojiazhuxi** [comment]
The above IP address is not set or owned by me

**Comment by Logan007** [comment]
> `[sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.`

This is not an error, just an information. If you did not provide your edge the `-a <some IP address>` parameter, it would use this one. It gets chosen automatically. Details about this _auto-IP_ feature can be found in the [doc](https://github.com/ntop/n2n/blob/dev/doc/TapConfiguration.md#ip-address) folder.

> `[sn_utils.c:720] authentication failed`

I am not sure about this one. Just guessing, do you use manually assigned MAC addresses and IP addresses? If yes, please make sure that they do not collide by accident (same address on two nodes, e.g. by copy-pasting command lines).

**Comment by guojiazhuxi** [comment]
I tried, if a federation is formed, such problems will occur。

**Comment by Logan007** [comment]
That is a very valuable hint. I will check and get back to you. However, I have got a few questions for you:;

- What exact version do you use?

- Did you see that with any version before (in case you tried it before)?

- Do you use `-J` at the the edges?

- Do you use `-P` at the edges?

- Does your supernode use `-F` for its own federation name?

- Are you sure that all edges have distinct MAC addresses and IP addresses?

- Do these two messages appear at the same time?

- Do you see any of your edges quit due to an authentication error?

**Comment by guojiazhuxi** [comment]
1.version Welcome to n2n v.2.9.0.r918.75ab1fc for x86_64-unknown-linux-gnu
2.I haven't seen it before, and it was only today that I used the-v option to find this problem.
3.At the edge, I didn't use the-P and-J options
4.I used the -F option 
5.I set the ip address and can be sure that they are different ，and 
6.The MAC address is automatically set by the program
7.These two messages appear in pairs, and the same problem occurs in each of my supernodes. And the ip addresses are all 58.218.10.48/0，This ip address is a public network address.
8.There is no marginal exit.
9.thanks！

**Comment by guojiazhuxi** [comment]
-d=n2n0
-c=thenetwork
-k=tangkk
-a=192.168.101.3
-p=33578
-l=127.0.0.1:47777
This is the edge of my supernode computer.

**Comment by guojiazhuxi** [comment]
-d=n2n0
-c=thenetwork
-k=sdflllkk
-a=192.168.101.3
-p=33578
-l=127.0.0.1:47777
This is the edge of my supernode computer.

**Comment by guojiazhuxi** [comment]
-p=47777
-c=/etc/n2n/community.list
-F=thenetwork
-l=xxxxx:xxxx
-l=xxx.xxxx
this is my supernode config

**Comment by guojiazhuxi** [comment]
Jun 07 21:59:19 centos supernode[18975]: 07/Jun/2021 21:59:19 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 07 21:59:19 centos supernode[18975]: 07/Jun/2021 21:59:19 [sn_utils.c:720] authentication failed
Jun 07 21:59:22 centos supernode[18975]: 07/Jun/2021 21:59:22 [sn_utils.c:1916] Rx REGISTER_SUPER_NAK from BE:8A:06:A8:8F:98 [159.75
Jun 07 21:59:29 centos supernode[18975]: 07/Jun/2021 21:59:29 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 07 21:59:29 centos supernode[18975]: 07/Jun/2021 21:59:29 [sn_utils.c:720] authentication failed
Jun 07 21:59:32 centos supernode[18975]: 07/Jun/2021 21:59:32 [n2n.c:288] supernode2sock successfully resolves supernode IPv4 address for 119.9
Jun 07 21:59:32 centos supernode[18975]: 07/Jun/2021 21:59:32 [n2n.c:288] supernode2sock successfully resolves supernode IPv4 address for 159.7
Jun 07 21:59:32 centos supernode[18975]: 07/Jun/2021 21:59:32 [sn_utils.c:1916] Rx REGISTER_SUPER_NAK from BE:8A:06:A8:8F:98 [159.7
Jun 07 21:59:39 centos supernode[18975]: 07/Jun/2021 21:59:39 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 07 21:59:39 centos supernode[18975]: 07/Jun/2021 21:59:39 [sn_utils.c:720] authentication failed
Jun 07 21:59:42 centos supernode[18975]: 07/Jun/2021 21:59:42 [sn_utils.c:1916] Rx REGISTER_SUPER_NAK from BE:8A:06:A8:8F:98 [159.75
Jun 07 21:59:49 centos supernode[18975]: 07/Jun/2021 21:59:49 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 07 21:59:49 centos supernode[18975]: 07/Jun/2021 21:59:49 [sn_utils.c:720] authentication failed
Jun 07 21:59:52 centos supernode[18975]: 07/Jun/2021 21:59:52 [sn_utils.c:1916] Rx REGISTER_SUPER_NAK from BE:8A:06:A8:8F:98 [159.75
Jun 07 21:59:59 centos supernode[18975]: 07/Jun/2021 21:59:59 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 07 21:59:59 centos supernode[18975]: 07/Jun/2021 21:59:59 [sn_utils.c:720] authentication failed
Jun 07 22:00:02 centos supernode[18975]: 07/Jun/2021 22:00:02 [sn_utils.c:1916] Rx REGISTER_SUPER_NAK from BE:8A:06:A8:8F:98 [159.75
Jun 07 22:00:09 centos supernode[18975]: 07/Jun/2021 22:00:09 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 07 22:00:09 centos supernode[18975]: 07/Jun/2021 22:00:09 [sn_utils.c:720] authentication failed
Jun 07 22:00:12 centos supernode[18975]: 07/Jun/2021 22:00:12 [sn_utils.c:1916] Rx REGISTER_SUPER_NAK from BE:8A:06:A8:8F:98 [159.75
Jun 07 22:00:19 centos supernode[18975]: 07/Jun/2021 22:00:19 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 07 22:00:19 centos supernode[18975]: 07/Jun/2021 22:00:19 [sn_utils.c:720] authentication failed
Jun 07 22:00:22 centos supernode[18975]: 07/Jun/2021 22:00:22 [sn_utils.c:1916] Rx REGISTER_SUPER_NAK from BE:8A:06:A8:8F:98 [159.75
Jun 07 22:00:29 centos supernode[18975]: 07/Jun/2021 22:00:29 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 07 22:00:29 centos supernode[18975]: 07/Jun/2021 22:00:29 [sn_utils.c:720] authentication failed
Jun 07 22:00:32 centos supernode[18975]: 07/Jun/2021 22:00:32 [sn_utils.c:1916] Rx REGISTER_SUPER_NAK from BE:8A:06:A8:8F:98 [159.75
Jun 07 22:00:39 centos supernode[18975]: 07/Jun/2021 22:00:39 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 07 22:00:39 centos supernode[18975]: 07/Jun/2021 22:00:39 [sn_utils.c:720] authentication failed
Jun 07 22:00:42 centos supernode[18975]: 07/Jun/2021 22:00:42 [sn_utils.c:1916] Rx REGISTER_SUPER_NAK from BE:8A:06:A8:8F:98 [159.75
Jun 07 22:00:49 centos supernode[18975]: 07/Jun/2021 22:00:49 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 07 22:00:49 centos supernode[18975]: 07/Jun/2021 22:00:49 [sn_utils.c:720] authentication failed

**Comment by Logan007** [comment]
Thank you very much for reporting!!

I hope #707 fixes it, please re-open if not.

**Comment by guojiazhuxi** [comment]
authentication failed
The authentication failed has disappeared，but it always appear Assign IP 58.218.10.48/0 to tap adapter of edge.
In the document, the system can only assign A class An address to the edge, but it is not. All my ip are fixed and do not repeat.

**Comment by guojiazhuxi** [comment]
The authentication failed has disappeared，but it always appear Assign IP 58.218.10.48/0 to tap adapter of edge.
In the document, the system can only assign A class An address to the edge, but it is not. All my ip are fixed and do not repeat.

**Comment by Logan007** [comment]
Ah, I think it can be ignored in this case as no supernode assigns addresses to other supernodes (and no supernode accepts addresses from other supernodes, they have no TAP interface to assign it to). I understand that it might be confusing. Let me see if I can disable this message.

**Comment by guojiazhuxi** [comment]
Jun 08 00:51:31 centos supernode[8593]: 08/Jun/2021 00:51:31 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:51:41 centos supernode[8593]: 08/Jun/2021 00:51:41 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:51:52 centos supernode[8593]: 08/Jun/2021 00:51:52 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:52:02 centos supernode[8593]: 08/Jun/2021 00:52:02 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:52:13 centos supernode[8593]: 08/Jun/2021 00:52:13 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:52:23 centos supernode[8593]: 08/Jun/2021 00:52:23 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:52:44 centos supernode[8593]: 08/Jun/2021 00:52:44 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:52:44 centos supernode[8593]: 08/Jun/2021 00:52:44 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:53:08 centos supernode[8593]: 08/Jun/2021 00:53:08 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:53:08 centos supernode[8593]: 08/Jun/2021 00:53:08 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:53:32 centos supernode[8593]: 08/Jun/2021 00:53:32 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:53:33 centos supernode[8593]: 08/Jun/2021 00:53:33 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:53:53 centos supernode[8593]: 08/Jun/2021 00:53:53 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:54:04 centos supernode[8593]: 08/Jun/2021 00:54:04 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:54:14 centos supernode[8593]: 08/Jun/2021 00:54:14 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:54:35 centos supernode[8593]: 08/Jun/2021 00:54:35 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:54:35 centos supernode[8593]: 08/Jun/2021 00:54:35 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:54:57 centos supernode[8593]: 08/Jun/2021 00:54:57 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:54:57 centos supernode[8593]: 08/Jun/2021 00:54:57 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:55:21 centos supernode[8593]: 08/Jun/2021 00:55:21 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:55:21 centos supernode[8593]: 08/Jun/2021 00:55:21 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:55:43 centos supernode[8593]: 08/Jun/2021 00:55:43 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:55:43 centos supernode[8593]: 08/Jun/2021 00:55:43 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:56:13 centos supernode[8593]: 08/Jun/2021 00:56:13 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:56:13 centos supernode[8593]: 08/Jun/2021 00:56:13 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:56:44 centos supernode[8593]: 08/Jun/2021 00:56:44 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:56:44 centos supernode[8593]: 08/Jun/2021 00:56:44 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:57:06 centos supernode[8593]: 08/Jun/2021 00:57:06 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:57:27 centos supernode[8593]: 08/Jun/2021 00:57:27 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:57:27 centos supernode[8593]: 08/Jun/2021 00:57:27 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:57:48 centos supernode[8593]: 08/Jun/2021 00:57:48 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:57:48 centos supernode[8593]: 08/Jun/2021 00:57:48 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:58:09 centos supernode[8593]: 08/Jun/2021 00:58:09 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:58:09 centos supernode[8593]: 08/Jun/2021 00:58:09 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:58:30 centos supernode[8593]: 08/Jun/2021 00:58:30 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:58:30 centos supernode[8593]: 08/Jun/2021 00:58:30 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:58:51 centos supernode[8593]: 08/Jun/2021 00:58:51 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:58:51 centos supernode[8593]: 08/Jun/2021 00:58:51 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:59:12 centos supernode[8593]: 08/Jun/2021 00:59:12 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.
Jun 08 00:59:12 centos supernode[8593]: 08/Jun/2021 00:59:12 [sn_utils.c:805] Assign IP 58.218.10.48/0 to tap adapter of edge.



Yes, I'm a little confused, but more importantly, these useless mistakes take up a lot of my memory. 😃

**Comment by Logan007** [comment]
Only log-wise... not in the running program. I am about to push the fixed version.

**Comment by guojiazhuxi** [comment]
thanks! In recent use, I think federation is very useful! I find that using federation can effectively improve the efficiency of P2P.

**Comment by Logan007** [comment]
I have just fixed it, current _dev_ should be okay now :wink:

Again, thank you for reporting!

Concerning the federation, I fully agree that the addition of this feature was a very useful one. @fcarli3 has built it as part of his thesis.

It allows for way better scalability, helps spanning networks all over the world with local nests (if [built](https://github.com/ntop/n2n/blob/dev/doc/Building.md#federation--supernode-selection-by-round-trip-time) with RTT supernode selection) and finally, it covers fall-back / backup scenarios very well as the one supernode is not the single point of failure anymore.

**Comment by guojiazhuxi** [comment]
Yes, thank you again for your selfless dedication, your software is very helpful to my work and study, thank you very much! 👍
