### ISSUE TITLE
how to configure a specified IF for -n <cidr:gateway) parameter via my perfered Iface but not default gw?

### ISSUE THREAD

**Issue by galaxyskyknight** [ntop/n2n#709]
I found if I configure the -n <cidr:gateway> with edge spaw up, it will automatically attached to a local IF which have default route(0.0.0.0) but not what I wanted IF( e.g n2n) this will cause the cidr not route to proper 'gateway' directly but route to default gw attached IF. so is there any tricky that I can change this or likely I could use '-n <cidr:gateway:IFname(or IFidx)> to specify the subnet route to my perferred network adapter?

**Comment by galaxyskyknight** [comment]
I guess this feature is not implemented yet, so please consider if it could work on 2.8 branches? for now, I am good with 2.8 except this above feature. becoz it will cause the netx hop unreachable if the cidr net route to default (0.0.0.0) gateway attached IF as it is wrong(it should bind to n2n tap/tun device). the 3.0 version feature looks good such like supernode interconnection(federation)  and supernode/edge authentication but not necessary for me now. I am only looking for a stable version with above feature. If it is already done, please let me know. thanks

**Comment by Logan007** [comment]
> I guess this feature is not implemented yet, so please consider if it could work on 2.8 branches?

> If it is already done, please let me know. 

We certainly are open for enhancement if this is a required feature and somebody wants to implement it. Any volunteers?

> it will cause the netx hop unreachable if the cidr net route to default (0.0.0.0) gateway attached IF as it is wrong(it should bind to n2n tap/tun device)

I do not know much of the routing in-depth details, so just a short question: Shouldn't the OS automatically chose the interface by the gateways IP address (and the standard route for the gateways IP network)? For example, if _n2n_ device has `10.99.99.0/24` network, shouldn't any gateway IP address from the `10.99.99.xxx` range automatically go through the _n2n_ network interface?

Maybe, I just got something wrong here. Could you please provide an example situation for which the interface designation would be required?

**Comment by galaxyskyknight** [comment]
I tested again, this looks like only happedn on Windows build
say the top like this, 
1)I have two edges &one supernode, two edges in physical are openwrt routers run edge binanry, those n2n interfaces assigned n2n interface IP ,one is 10.0.0.1(router 1) and another 10.0.0.2(router 2) and they are connected to supernode(which has public IP address, let's assume 1.2.3.4), and the openwrt router 's LAN interface IP address is 192.168.1.1 (router1 LAN 192.168.1.0/24) and  router 2 is 192.168.2.1(router 2 LAN 192.168.2.0/24), 
2) so now, if I'd like to connect two router's LAN, (say I will access 192.168.2.x to 192.168.1.x) If I not use the -n paramteres, the alternative way is that I have to manually configure the static route like  the following on both routers:
route add 192.168.1.0 mask 255.255.255.0 10.0.0.1 metric 1000 IF 12  --> here 12 is the IFIndex on windows for TAP device
route add 192.168.2.0 mask 255.255.255.0 10.0.0.2 metric 1000 IF 12

pls note here I manually specified the interface to make it distinguish. This will perfectly make the following data link work through using p2p method:
192.168.1.0/24(LAN)<->10.0.0.1(n2n)<->0.0.0.0 default gw on router1<->WAN<->0.0.0.0 default gw on router2<->10.0.0.2(n2n)<->192.168.2.0/24(LAN)

**However the problem is the -n <cidr:gateway> parameter's behavior is not automatically bind it to n2n TAP IF but to local physical network interface where is the 0.0.0.0/default gw attached.**

say I configure -n <192.168.1.0/24:10.0.0.1> -n <192.168.2.0/24:10.0.0.2> for above case, the route table printed shows that on windows the route to LAN is attached to WAN interface(0.0.0.0/0 gw, mostly is the phsyical network adapter 0)  but not to the TAP device.  That will definitely break the data link path above.

Please advise. thanks.

**Comment by Logan007** [comment]
> I tested again, this looks like only happedn on Windows build

I took a look at the code.

If I read it correctly, of which I am not sure, it is intended that `-n` provided routes bind to the TAP interface (on Linux, `src/edge_utils.c:3377`).

On Windows (different code path), a `route add ...` command is manually assembled, see `/src/edge_utils.c:3407`. The assembled command should be output to the log. Could you please verify that the printed command is meaningful, especially if the gateway is correct (`10.0.0.2` and not `0.0.0.0`)? I only have limited access to Windows.

Finally, if it really were required, I think there maybe could be a way to get an interface name from command line `-n cidr:gw%if` calling `if_nametoindex()` –  on Linux, not sure about Windows. But I still think that the route should automatically guide packets through the TAP device if the gateway's IP address is in the TAP's sub-network address range...

**Comment by galaxyskyknight** [comment]
hi the route CMD on windows should be like the following: (you can try on windows by print 'route' and refer to its help.

```
 route ADD 157.0.0.0 MASK 255.0.0.0  157.55.80.1 METRIC 3 IF 2
      destination^      ^mask          ^gateway   metric^   ^
                                                    Interface^
```

it is fine for MASK part could be 157.0.0.0/24 format but if you not explicite specify the IF parameter, the command will try to find the BEST interface to match its subnet , somehow this 'BEST' final binded from system perspective is the default 0.0.0.0 not the n2n interface, that is the problem, I also look into the code, it didn't do the that IF assignment on windows.
 
the following route add commond only specified the 'c_net_addr, route->net_bitlen, c_gateway' for the 'route add' command's parameters,so....as mentioned above. I am not sure its match logical is related to the metric between defaut gw IF and n2n IF, just guess if I promote the metric for n2n IF, shall it works? didn't have time to test yet. but if we have the mechanism to explicite specify it, it will work anyway.

````
static int edge_init_routes_win (n2n_edge_t *eee, n2n_route_t *routes, uint16_t num_routes) {
#ifdef WIN32
    int i;
    struct in_addr net_addr, gateway;
    char c_net_add````r[32];
    char c_gateway[32];
    char cmd[256];

    for(i = 0; i < num_routes; i++) {
        n2n_route_t *route = &routes[i];
        if((route->net_addr == 0) && (route->net_bitlen == 0)) {
            traceEvent(TRACE_NORMAL, "Warning: The 0.0.0.0/0 route settings are not supported on Windows");
            return(-1);
        } else {
            /* ip route add net via n2n_gateway */
            memcpy(&net_addr, &(route->net_addr), sizeof(net_addr));
            memcpy(&gateway, &(route->gateway), sizeof(gateway));
            _snprintf(c_net_addr, sizeof(c_net_addr), inet_ntoa(net_addr));
            _snprintf(c_gateway, sizeof(c_gateway), inet_ntoa(gateway));
            _snprintf(cmd, sizeof(cmd), "route add %s/%d %s > nul", c_net_addr, route->net_bitlen, c_gateway);
            traceEvent(TRACE_NORMAL, "ROUTE CMD = '%s'\n", cmd);**
            system(cmd);
        }
    }

#endif // WIN32

**Comment by Logan007** [comment]
> just guess if I promote the metric for n2n IF, shall it works? 

You could try using `-x 1` at the edge. It will give higher interface metric than the default interface (but does not reset after the edge quits, so it stays with that low interface metric meaning high priority).

> but if we have the mechanism to explicite specify it, it will work anyway.

I assume you are talking about the interface index (to specify). If you take a look at the Linux way of setting the route, you can see that it relies on the interface index `if_idx` of the TAP device (`edge_init_routes_linux()`, e.g. at around `src/edge_utils.c:3365`). It is retrieved during TAP initialization during `tuntap_open()`  at `src/tuntap_linux:236` and stored into `eee->device.if_idx`.

The Windows code does neither retrieve nor set the interface index during `open_wintap()` at `win32/wintap.c:296`. That is presumably the reason for the Windows route code you cited above does not use `eee->device.if_idx`.

According to web documentation, there should be a [way](https://docs.microsoft.com/en-us/windows/win32/api/netioapi/nf-netioapi-if_nametoindex) to retrieve Windows interface index similar to the Linux call (and then could be used in the `route add ...` command). However, they say it will only work on Visa and above and therefore not on XP which still seems to be a [requirement](https://github.com/ntop/n2n/issues/698#issuecomment-856739133).

**Comment by galaxyskyknight** [comment]
OK, thanks for the reply. I think we are aligned with the issue and solution, the problem is whether we still need to have compatibility support for such a 'retired' system like XP or not in win code. Or even we have better way that to define some Macro and WINAPI to tell the code run on XP system or VISA and above so that we could use the different call method for open_wintap()?

**Comment by galaxyskyknight** [comment]
update: use -x  doesnt help on windows.

**Comment by galaxyskyknight** [comment]
I believe this is the same to #528 @Logan007

**Comment by Logan007** [comment]
Yes, it looks similar.

**Comment by Logan007** [comment]
@galaxyskyknight 
@leonardospeca
@ChenJun-github-lab

Please try #717 and let me know.

**Comment by galaxyskyknight** [comment]
@Logan007 thanks for the effort, please see my comments on the change.
