### ISSUE TITLE
Cannot compile the latest branch on Openwrt X86 toolchain!

### ISSUE THREAD

**Issue by galaxyskyknight** [ntop/n2n#710]
when configure, it prompts the gcc cannot create excutable error, please see the log below, the stable release (v2.8) can compile well,  I don't know what happened , may related the 2.9.0 code change some parameter usage for gcc? To compile this code on different openwrt platform is very important to me, please kindly help. thanks @ntop @Logan007 

This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by edge configure 2.9.0, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure --target=x86_64-openwrt-linux --host=x86_64-openwrt-linux --build=x86_64-pc-linux-gnu --program-prefix= --program-suffix= --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls

## --------- ##

hostname = 
uname -m = x86_64
uname -r = 4.15.0-142-generic
uname -s = Linux
uname -v = #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /root/OpenWRT/openwrt-sdk-21.02.0-rc2-x86-64_gcc-8.4.0_musl.Linux-x86_64/staging_dir/target-x86_64_musl/host/bin
PATH: /root/OpenWRT/openwrt-sdk-21.02.0-rc2-x86-64_gcc-8.4.0_musl.Linux-x86_64/staging_dir/hostpkg/bin
PATH: /root/OpenWRT/openwrt-sdk-21.02.0-rc2-x86-64_gcc-8.4.0_musl.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/bin
PATH: /root/OpenWRT/openwrt-sdk-21.02.0-rc2-x86-64_gcc-8.4.0_musl.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/bin
PATH: /root/OpenWRT/openwrt-sdk-21.02.0-rc2-x86-64_gcc-8.4.0_musl.Linux-x86_64/staging_dir/host/bin
PATH: /root/OpenWRT/openwrt-sdk-21.02.0-rc2-x86-64_gcc-8.4.0_musl.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/bin
PATH: /root/OpenWRT/openwrt-sdk-21.02.0-rc2-x86-64_gcc-8.4.0_musl.Linux-x86_64/staging_dir/host/bin
PATH: /root/OpenWRT/openwrt-sdk-21.02.0-rc2-x86-64_gcc-8.4.0_musl.Linux-x86_64/staging_dir/host/bin
PATH: /root/OpenWRT/openwrt-sdk-21.02.0-rc2-x86-64_gcc-8.4.0_musl.Linux-x86_64/staging_dir/host/bin
PATH: /usr/local/sbin
PATH: /usr/local/bin
PATH: /sbin
PATH: /bin
PATH: /usr/sbin
PATH: /usr/bin

## ----------- ##

configure:1697: loading site script /root/OpenWRT/openwrt-sdk-21.02.0-rc2-x86-64_gcc-8.4.0_musl.Linux-x86_64/include/site/x86_64
| #!/bin/sh
| . $TOPDIR/include/site/linux
| ac_cv_c_littleendian=${ac_cv_c_littleendian=yes}
| ac_cv_c_bigendian=${ac_cv_c_bigendian=no}
| 
| ac_cv_sizeof___int64=0
| ac_cv_sizeof_char=1
| ac_cv_sizeof_int=4
| ac_cv_sizeof_int16_t=2
| ac_cv_sizeof_int32_t=4
| ac_cv_sizeof_int64_t=8
| ac_cv_sizeof_long_int=8
| ac_cv_sizeof_long_long=8
| ac_cv_sizeof_long=8
| ac_cv_sizeof_off_t=8
| ac_cv_sizeof_short_int=2
| ac_cv_sizeof_short=2
| ac_cv_sizeof_size_t=8
| ac_cv_sizeof_ssize_t=8
| ac_cv_sizeof_u_int16_t=2
| ac_cv_sizeof_u_int32_t=4
| ac_cv_sizeof_u_int64_t=8
| ac_cv_sizeof_uint16_t=2
| ac_cv_sizeof_uint32_t=4
| ac_cv_sizeof_uint64_t=8
| ac_cv_sizeof_unsigned_int=4
| ac_cv_sizeof_unsigned_long=8
| ac_cv_sizeof_unsigned_long_long=8
| ac_cv_sizeof_unsigned_short=2
| ac_cv_sizeof_void_p=8
configure:1817: checking for x86_64-openwrt-linux-gcc
configure:1844: result: gcc
configure:2113: checking for C compiler version
configure:2122: gcc --version >&5
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:2133: $? = 0
configure:2122: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
configure:2133: $? = 0
configure:2122: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:2133: $? = 1
configure:2122: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'; did you mean '--version'?
gcc: fatal error: no input files
compilation terminated.
**configure:2133: $? = 1
configure:2153: checking whether the C compiler works**
configure:2175: gcc -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -ffile-prefix-map=/root/OpenWRT/openwrt-sdk-21.02.0-rc2-x86-64_gcc-8.4.0_musl.Linux-x86_64/build_dir/target-x86_64_musl/n2n-2.9.0_dev_git53e930db105df0e1103d8b6de9d5cb223c744d49=n2n-2.9.0_dev_git53e930db105df0e1103d8b6de9d5cb223c744d49 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/root/OpenWRT/openwrt-sdk-21.02.0-rc2-x86-64_gcc-8.4.0_musl.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/include -I/root/OpenWRT/openwrt-sdk-21.02.0-rc2-x86-64_gcc-8.4.0_musl.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include/fortify -I/root/OpenWRT/openwrt-sdk-21.02.0-rc2-x86-64_gcc-8.4.0_musl.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include  -L/root/OpenWRT/openwrt-sdk-21.02.0-rc2-x86-64_gcc-8.4.0_musl.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/lib -L/root/OpenWRT/openwrt-sdk-21.02.0-rc2-x86-64_gcc-8.4.0_musl.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib -znow -zrelro  conftest.c  >&5
**gcc: error: unrecognized command line option '-fhonour-copts'; did you mean '-fhonor-std'?
gcc: error: unrecognized command line option '-ffile-prefix-map=/root/OpenWRT/openwrt-sdk-21.02.0-rc2-x86-64_gcc-8.4.0_musl.Linux-x86_64/build_dir/target-x86_64_musl/n2n-2.9.0_dev_git53e930db105df0e1103d8b6de9d5cb223c744d49=n2n-2.9.0_dev_git53e930db105df0e1103d8b6de9d5cb223c744d49'**
configure:2179: $? = 1
configure:2217: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "edge"
| #define PACKAGE_TARNAME "edge"
| #define PACKAGE_VERSION "2.9.0"
| #define PACKAGE_STRING "edge 2.9.0"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:2222: error: in `/root/OpenWRT/openwrt-sdk-21.02.0-rc2-x86-64_gcc-8.4.0_musl.Linux-x86_64/build_dir/target-x86_64_musl/n2n-2.9.0_dev_git53e930db105df0e1103d8b6de9d5cb223c744d49':
configure:2224: error: C compiler cannot create executables
See `config.log' for more details

## ---------------- ##

ac_cv_c_bigendian=no
ac_cv_c_gettext_without_libintl=yes
ac_cv_c_littleendian=yes
ac_cv_c_long_double=no
ac_cv_conv_longlong_to_float=yes
ac_cv_env_CC_set=set
ac_cv_env_CC_value=x86_64-openwrt-linux-musl-gcc
ac_cv_env_CFLAGS_set=set
ac_cv_env_CFLAGS_value='-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -ffile-prefix-map=/root/OpenWRT/openwrt-sdk-21.02.0-rc2-x86-64_gcc-8.4.0_musl.Linux-x86_64/build_dir/target-x86_64_musl/n2n-2.9.0_dev_git53e930db105df0e1103d8b6de9d5cb223c744d49=n2n-2.9.0_dev_git53e930db105df0e1103d8b6de9d5cb223c744d49 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro '
ac_cv_env_CPPFLAGS_set=set
ac_cv_env_CPPFLAGS_value='-I/root/OpenWRT/openwrt-sdk-21.02.0-rc2-x86-64_gcc-8.4.0_musl.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/include -I/root/OpenWRT/openwrt-sdk-21.02.0-rc2-x86-64_gcc-8.4.0_musl.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include/fortify -I/root/OpenWRT/openwrt-sdk-21.02.0-rc2-x86-64_gcc-8.4.0_musl.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include '
ac_cv_env_LDFLAGS_set=set
ac_cv_env_LDFLAGS_value='-L/root/OpenWRT/openwrt-sdk-21.02.0-rc2-x86-64_gcc-8.4.0_musl.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/lib -L/root/OpenWRT/openwrt-sdk-21.02.0-rc2-x86-64_gcc-8.4.0_musl.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib -znow -zrelro '
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_build_alias_set=set
ac_cv_env_build_alias_value=x86_64-pc-linux-gnu
ac_cv_env_host_alias_set=set
ac_cv_env_host_alias_value=x86_64-openwrt-linux
ac_cv_env_target_alias_set=set
ac_cv_env_target_alias_value=x86_64-openwrt-linux
ac_cv_file__dev_zero=yes
ac_cv_func___adjtimex=yes
ac_cv_func___va_copy=no
ac_cv_func__exit=yes
ac_cv_func_bcmp=yes
ac_cv_func_bcopy=yes
ac_cv_func_bzero=yes
ac_cv_func_cimag=yes
ac_cv_func_creal=yes
ac_cv_func_fchmod=yes
ac_cv_func_getaddrinfo=yes
ac_cv_func_getcwd=yes
ac_cv_func_getdomainname=yes
ac_cv_func_getpgrp_void=yes
ac_cv_func_getpwuid_r=yes
ac_cv_func_gettimeofday=yes
ac_cv_func_index=yes
ac_cv_func_lstat=yes
ac_cv_func_lstat_dereferences_slashed_symlink=yes
ac_cv_func_lstat_empty_string_bug=no
ac_cv_func_malloc_0_nonnull=yes
ac_cv_func_malloc_works=yes
ac_cv_func_memcmp_clean=yes
ac_cv_func_memcmp_working=yes
ac_cv_func_posix_getgrgid_r=yes
ac_cv_func_posix_getpwuid_r=yes
ac_cv_func_psignal=yes
ac_cv_func_pthread_key_delete=yes
ac_cv_func_realloc_0_nonnull=yes
ac_cv_func_realloc_works=yes
ac_cv_func_rename=yes
ac_cv_func_rindex=yes
ac_cv_func_setgrent_void=yes
ac_cv_func_setlocale=yes
ac_cv_func_setpgrp_void=yes
ac_cv_func_setresuid=no
ac_cv_func_setvbuf_reversed=no
ac_cv_func_stat_empty_string_bug=no
ac_cv_func_stat_ignores_trailing_slash=no
ac_cv_func_strerror=yes
ac_cv_func_strftime=yes
ac_cv_func_utimes=yes
ac_cv_func_va_copy=no
ac_cv_func_vsnprintf=yes
ac_cv_have_accrights_in_msghdr=no
ac_cv_have_broken_snprintf=no
ac_cv_have_control_in_msghdr=yes
ac_cv_have_decl_sys_siglist=no
ac_cv_have_openpty_ctty_bug=yes
ac_cv_have_space_d_name_in_struct_dirent=yes
ac_cv_header_netinet_sctp_h=no
ac_cv_header_netinet_sctp_uio_h=no
ac_cv_int64_t=yes
ac_cv_lbl_unaligned_fail=no
ac_cv_linux_kernel_pppoe=yes
ac_cv_linux_vers=2
ac_cv_pack_bitfields_reversed=yes
ac_cv_path_LDCONFIG=
ac_cv_prog_CC=gcc
ac_cv_regexec_segfault_emptystr=no
ac_cv_sctp=no
ac_cv_sizeof___int64=0
ac_cv_sizeof_char=1
ac_cv_sizeof_int16_t=2
ac_cv_sizeof_int32_t=4
ac_cv_sizeof_int64_t=8
ac_cv_sizeof_int=4
ac_cv_sizeof_long=8
ac_cv_sizeof_long_int=8
ac_cv_sizeof_long_long=8
ac_cv_sizeof_off_t=8
ac_cv_sizeof_short=2
ac_cv_sizeof_short_int=2
ac_cv_sizeof_size_t=8
ac_cv_sizeof_ssize_t=8
ac_cv_sizeof_u_int16_t=2
ac_cv_sizeof_u_int32_t=4
ac_cv_sizeof_u_int64_t=8
ac_cv_sizeof_uint16_t=2
ac_cv_sizeof_uint32_t=4
ac_cv_sizeof_uint64_t=8
ac_cv_sizeof_unsigned_int=4
ac_cv_sizeof_unsigned_long=8
ac_cv_sizeof_unsigned_long_long=8
ac_cv_sizeof_unsigned_short=2
ac_cv_sizeof_void_p=8
ac_cv_sys_restartable_syscalls=yes
ac_cv_time_r_type=POSIX
ac_cv_type_suseconds_t=yes
ac_cv_uchar=no
ac_cv_uint64_t=yes
ac_cv_uint=yes
ac_cv_ulong=yes
ac_cv_ushort=yes
ac_cv_va_copy=C99
ac_cv_va_val_copy=yes
as_cv_unaligned_access=yes

## ----------------- ##

ADDITIONAL_TOOLS=''
AR='ar'
CC='gcc'
CFLAGS='-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -ffile-prefix-map=/root/OpenWRT/openwrt-sdk-21.02.0-rc2-x86-64_gcc-8.4.0_musl.Linux-x86_64/build_dir/target-x86_64_musl/n2n-2.9.0_dev_git53e930db105df0e1103d8b6de9d5cb223c744d49=n2n-2.9.0_dev_git53e930db105df0e1103d8b6de9d5cb223c744d49 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro '
CPPFLAGS='-I/root/OpenWRT/openwrt-sdk-21.02.0-rc2-x86-64_gcc-8.4.0_musl.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/include -I/root/OpenWRT/openwrt-sdk-21.02.0-rc2-x86-64_gcc-8.4.0_musl.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include/fortify -I/root/OpenWRT/openwrt-sdk-21.02.0-rc2-x86-64_gcc-8.4.0_musl.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include '
DEFS=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EXEEXT=''
GIT_COMMITS=''
GIT_RELEASE='2.9.0'
GIT_REVISION=''
LDFLAGS='-L/root/OpenWRT/openwrt-sdk-21.02.0-rc2-x86-64_gcc-8.4.0_musl.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/lib -L/root/OpenWRT/openwrt-sdk-21.02.0-rc2-x86-64_gcc-8.4.0_musl.Linux-x86_64/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib -znow -zrelro '
LIBOBJS=''
LIBS=''
LTLIBOBJS=''
N2N_DEFINES=''
N2N_LIBS=''
N2N_MAJOR=''
N2N_MINOR=''
N2N_PATCH=''
N2N_VERSION_SHORT='2.9.0'
OBJEXT=''
PACKAGE_BUGREPORT=''
PACKAGE_NAME='edge'
PACKAGE_STRING='edge 2.9.0'
PACKAGE_TARNAME='edge'
PACKAGE_URL=''
PACKAGE_VERSION='2.9.0'
PATH_SEPARATOR=':'
SHELL='/bin/bash'
ac_ct_CC=''
bindir='/usr/bin'
build_alias='x86_64-pc-linux-gnu'
datadir='/usr/share'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='/usr'
host_alias='x86_64-openwrt-linux'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='/usr/info'
libdir='${exec_prefix}/lib'
libexecdir='/usr/lib'
localedir='${datarootdir}/locale'
localstatedir='/var'
mandir='/usr/man'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/usr'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='/usr/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='/etc'
target_alias='x86_64-openwrt-linux'

## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "edge"
#define PACKAGE_TARNAME "edge"
#define PACKAGE_VERSION "2.9.0"
#define PACKAGE_STRING "edge 2.9.0"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""

configure: exit 77

**Comment by Logan007** [comment]
> may related the 2.9.0 code change some parameter usage for gcc?

None that I am aware of.

> please kindly help. thanks @ntop @Logan007

Did you run `./autogen.sh` and / or `make clean`? Sorry for only general advice. Building is just not my specialty.

But I know that other [users](https://github.com/ntop/n2n/search?q=openWrt&type=issues) build for openWRT.

Anyone?

**Comment by small-5** [comment]
Need to delete lines 16 and 17 of configure.seed.
CC and AR need to be passed by toolchain.

**Comment by galaxyskyknight** [comment]
has been resolved, thanks!

**Comment by galaxyskyknight** [comment]
thanks ! That's wonderful
