### ISSUE TITLE
User/Password Authentication not supported in Federation & High CPU Load on Supernode (TCP)

### ISSUE THREAD

**Issue by galaxyskyknight** [ntop/n2n#711]
My test senario is like this

**precondition:** Two supernodes on different VPS service provide and connected with federation configuration, and works fine.
**senario 1:** configure edge using authentication mode(means add the username/password/sn public key on those config, for edge that is using -I -J -P 3 parameters)
**senario 2:** configure edge using non-authentication mode (means not using above)

I have five edges and the supernode NOT compile with closet. however I found the following test result :
1. when testing senario 2, the edge registration is random, obey to the loadbalance, 2 of 5 registered on sn 1 and 3 of 5 regiested on sn2,  and failover works fine (means I mannually shutdown one sn).
2. when testing snario 1, the edge registration is fixed to one sn, no any more to be random..... and that's so weired, and the failover is still works fine(I shut down the sn where all edge attached, in serveral seconds they all failover to another sn).

So I guess the loadbalance doesn't work on Federation + Authentication mode? see my attached pic. Please help to check.

![无标题](https://user-images.githubusercontent.com/66289873/121828167-5e86a880-ccf1-11eb-8101-8d6ca123e186.jpg)

**Comment by galaxyskyknight** [comment]
by the way SN1 and SN2 both have public IPv4 address. each edge using a seperate username and password as shown in above picture in 'HINT'  also I configure two SN in same sequence in edge.conf e.g -l <sn1:port> -l <sn2:port>.

**Comment by galaxyskyknight** [comment]
weired thing is this issue is not 100% reproduce, it can be migrated to other node when the time moving on. but when start up it could be there. however, there is a second issue： only those edge on same node could be reachd each other(by ping), but the edge between nodes cannot be ping. I enabled the ipv4_forwad and all the edges are in the same subnet 10.0.0.0/24.

**Comment by galaxyskyknight** [comment]
so I am really wondering how the federation works, the edge registered only on the master supernode or regiested on all arch nodes? is it shown up on all supernode by <nc -u localhost 5645> or only shown up on the real physical registed node but pass by to other arch nodes? if only registed one node, how the edge choose which one when it initial start up to register if I specified more than one node in its configure file like -l <sn1:port> -l <sn2,port>?

Per my observation from nc -u localhost 5645 command on both nodes , if some edge registered on node 1 and some other registered on node 2, the two side edge cannot be reached each other inter-supernode but only reach range is inside one supernode it belongs to. I checked with arp and route, the route is fine as they are all in same subnet for edge and n2n interface (10.0.0.0/24) but the arp doesn't. the edge's arp entry on peer's supernode's is imcomplete on local supernode. so the layer forward is obviously is unreachable. I don't know how to resolve this.

**Comment by galaxyskyknight** [comment]
Finally I managed to make a 5 edge registered between 2 supernode situation, see the 10.0.0.4 now is unreachable for both supernodes, the diag snapshot below, please help to see what happend
Diag on supernode 1:
![1](https://user-images.githubusercontent.com/66289873/121848950-55133580-cd1d-11eb-8f5f-49eb37403a37.jpg)

Diag on supernode 2:

![2](https://user-images.githubusercontent.com/66289873/121848964-593f5300-cd1d-11eb-9022-5780250b727b.jpg)

**Comment by galaxyskyknight** [comment]
I also found there is high cpu issue(100%) for 'supernode' process while after failover scenario, not sure what is the trigger point.

**Comment by galaxyskyknight** [comment]
tests further found:  if disable -I -J -P in same fedreation (means using basic ID auth),  the edges registerd among different supernods could be inter-communicated, but if enable usr:password auth, the edge could only reach those who registered in the same node. does this match its original design or a bug?

**Comment by Logan007** [comment]
> if enable usr:password auth, the edge could only reach those who registered in the same node. does this match its original design or a bug?

Currently, user-password authentication is supported with **one** supernode only. As mentioned [here](https://github.com/ntop/n2n/pull/673#issuecomment-850970591), multi-supernode support would follow at a later point in time. It is possible to implement but would require some additional efforts outlined in the [draft](https://github.com/ntop/n2n/issues/670#issuecomment-802119568).

> so I am really wondering how the federation works, the edge registered only on the master supernode or regiested on all arch nodes?

General federation information is available in the `/doc/Federation.md` document. Basically, the supernodes form their own community with supernode members only. Edges register with one supernode only. They chose the supernode based on the local selection strategy (RTT based or load based – edges learn about the load from the PING/PONG packet paylaod).

Packets from edges which have to be forwarded in case of failing p2p, but also REGISTER_SUPERs etc., are forwarded to the other supernodes. Per those forwarded REGISTER_SUPERs, supernodes know about the other edges and the supernode they are registered to. That way, they can route packets destined to a certain edge to the corresponding supernode only (not flooding the whole supernode-federation).

> I also found there is high cpu issue(100%) for 'supernode' process while after failover scenario, not sure what is the trigger point.

That is interesting and would probably be an own issue. Have you found more information on triggering this?

**Comment by galaxyskyknight** [comment]
> > if enable usr:password auth, the edge could only reach those who registered in the same node. does this match its original design or a bug?
> 
> Currently, user-password authentication is supported with **one** supernode only. As mentioned [here]>>>(https://github.com/ntop/n2n/pull/673#issuecomment-850970591), multi-supernode support would follow at a later point in time. It is possible to implement but would require some additional efforts outlined in the [draft](https://github.com/ntop/n2n/issues/670#issuecomment-802119568).

Yes, I believe this is a very important feature for the federation, the supernodes in same federation should be transparent to any edge using the valid user:password among those supernodes in same federation. then the failover could be free among any of supernode under the SAME federation. so currently I have to disable this user:password based edge auth till this feature implemented.
> 
> > so I am really wondering how the federation works, the edge registered only on the master supernode or regiested on all arch nodes?
> 
> General federation information is available in the `/doc/Federation.md` document. Basically, the supernodes form their own community with supernode members only. Edges register with one supernode only. They chose the supernode based on the local selection strategy (RTT based or load based – edges learn about the load from the PING/PONG packet paylaod).
> 
> Packets from edges which have to be forwarded in case of failing p2p, but also REGISTER_SUPERs etc., are forwarded to the other supernodes. Per those forwarded REGISTER_SUPERs, supernodes know about the other edges and the supernode they are registered to. That way, they can route packets destined to a certain edge to the corresponding supernode only (not flooding the whole supernode-federation).
> 
> > I also found there is high cpu issue(100%) for 'supernode' process while after failover scenario, not sure what is the trigger point.
> 
> That is interesting and would probably be an own issue. Have you found more information on triggering this?

Nope yet, havn't check the syslog, it is happend just by trigger serveral failover on two supernodes, then I could see both of nodes got supernode process 100%) I just guess there is a dead loop somewhere or perhaps run into a heavy CHACHA cipher calculation load on those packets decode, just guess...

**Comment by Logan007** [comment]
> I just guess there is a dead loop somewhere or perhaps run into a heavy CHACHA cipher calculation load on those packets decode, just guess...

As long as the supernode still performs its work, e.g. forwarding etc., an endless dead loop is very unlikely. 100 percent CPU load could also result from a fully loaded line, i.e. it is just very busy to do its job.

But we definitely should keep an eye on it!

By the way, the supernode does not decrypt the payload (Twofish, AES, ChaCha, SPECK) as it does not know the key. It eventually performs header encryption (SPECK) if community is header encrypted (`-H` at the edges).

**Comment by galaxyskyknight** [comment]
> > I just guess there is a dead loop somewhere or perhaps run into a heavy CHACHA cipher calculation load on those packets decode, just guess...
> 
> As long as the supernode still performs its work, e.g. forwarding etc., an endless dead loop is very unlikely. 100 percent CPU load could also result from a fully loaded line, i.e. it is just very busy to do its job.
> 
> But we definitely should keep an eye on it!
> 
> By the way, the supernode does not decrypt the payload (Twofish, AES, ChaCha, SPECK) as it does not know the key. It eventually performs header encryption (SPECK) if community is header encrypted (`-H` at the edges).

Yes, if enable user:password authentication, I see from document say that it would automatically enable the header encryption per design.  the high cpu is gone after restart the supernode on both nodes(restart one will not affect another one's high CPU). Will attach the log if this happen next time.

**Comment by galaxyskyknight** [comment]
fortunately, the high cpu issue reproduced there on one supernode, no logs(I dont' know how to make the supernode dump the log to syslog-_-!) but I use the strace <strace -T -tt -e trace=all -p pid>to see it seems stuck in a infinite recvfrom() and select() loop, but I used tcpdump to capture the supernode listen port(both tcp,udp) the traffic is very slow and there is no flooding attack at all, I obersved another normal supernode, the log also attached for comparision.  plze help to check.  I will keep high cpu node there and see if what kind of information you need please update here, thank you @Logan007 

High CPU node: 
13:49:02.235209 recvfrom(7, "", 751, 0, 0x7ffcefd95160, [16->0]) = 0 <0.000003>
13:49:02.235249 select(8, [4 5 6 7], NULL, NULL, {tv_sec=10, tv_usec=0}) = 1 (in [7], left {tv_sec=9, tv_usec=999999}) <0.000004>
13:49:02.235301 recvfrom(7, "", 751, 0, 0x7ffcefd95160, [16->0]) = 0 <0.000004>
13:49:02.235342 select(8, [4 5 6 7], NULL, NULL, {tv_sec=10, tv_usec=0}) = 1 (in [7], left {tv_sec=9, tv_usec=999999}) <0.000005>
13:49:02.235381 recvfrom(7, "", 751, 0, 0x7ffcefd95160, [16->0]) = 0 <0.000004>
13:49:02.235438 select(8, [4 5 6 7], NULL, NULL, {tv_sec=10, tv_usec=0}) = 1 (in [7], left {tv_sec=9, tv_usec=999999}) <0.000007>
13:49:02.235593 recvfrom(7, "", 751, 0, 0x7ffcefd95160, [16->0]) = 0 <0.000005>
13:49:02.235669 select(8, [4 5 6 7], NULL, NULL, {tv_sec=10, tv_usec=0}) = 1 (in [7], left {tv_sec=9, tv_usec=999999}) <0.000004>
13:49:02.235725 recvfrom(7, "", 751, 0, 0x7ffcefd95160, [16->0]) = 0 <0.000017>
13:49:02.235765 select(8, [4 5 6 7], NULL, NULL, {tv_sec=10, tv_usec=0}) = 1 (in [7], left {tv_sec=9, tv_usec=999999}) <0.000004>
13:49:02.235819 recvfrom(7, "", 751, 0, 0x7ffcefd95160, [16->0]) = 0 <0.000003>
13:49:02.235861 select(8, [4 5 6 7], NULL, NULL, {tv_sec=10, tv_usec=0}) = 1 (in [7], left {tv_sec=9, tv_usec=999999}) <0.000004>
13:49:02.235901 recvfrom(7, "", 751, 0, 0x7ffcefd95160, [16->0]) = 0 <0.000004>
13:49:02.235955 select(8, [4 5 6 7], NULL, NULL, {tv_sec=10, tv_usec=0}) = 1 (in [7], left {tv_sec=9, tv_usec=999999}) <0.000005>
13:49:02.236009 recvfrom(7, ^C"", 751, 0, 0x7ffcefd95160, [16->0]) = 0 <0.000028>
strace: Process 9322 detached

Normal node:
13:47:17.499767 recvfrom(4, "\3\1\0cMyHomeN2N\0\0\0\0\0\0\0\0\0\0\0\0\220\20\0\0\3\0\220"..., 2048, 0, {sa_family=AF_INET, sin_port=htons(60086), sin_addr=inet_addr("x.x.x.x")}, [16]) = 104 <0.000021>
13:47:17.499841 sendto(4, "\3\1\0cMyHomeN2N\0\0\0\0\0\0\0\0\0\0\0\0\220\20\0\0\3\0\220"..., 104, 0, {sa_family=AF_INET, sin_port=htons(46117), sin_addr=inet_addr("x.x.x.x")}, 16) = 104 <0.000028>
13:47:17.499917 select(7, [4 5 6], NULL, NULL, {tv_sec=10, tv_usec=0}) = 1 (in [4], left {tv_sec=9, tv_usec=998509}) <0.001533>
13:47:17.501528 recvfrom(4, "\3\2\0\3MyHomeN2N\0\0\0\0\0\0\0\0\0\0\0\0\220\20\0\0\5\0\220"..., 2048, 0, {sa_family=AF_INET, sin_port=htons(2529), sin_addr=inet_addr("x.x.x.x")}, [16]) = 96 <0.000022>
13:47:17.501666 sendto(4, "\3\1\0cMyHomeN2N\0\0\0\0\0\0\0\0\0\0\0\0\220\20\0\0\5\0\220"..., 104, 0, {sa_family=AF_INET, sin_port=htons(46117), sin_addr=inet_addr("x.x.x.x")}, 16) = 104 <0.000033>
13:47:17.501784 select(7, [4 5 6], NULL, NULL, {tv_sec=10, tv_usec=0}^Cstrace: Process 29702 detached
 <detached ...>

**Comment by galaxyskyknight** [comment]
seems the high cpu node is trying infintely read from FD=7, I checked with the following and found the fd 7 mapping to a tcp 60086 port(my node listen port is 60086, I don't know why supernode listen both on tcp and udp? shoud it be listen only on UDP?  so I open the incoming rule for both tcp and udp for 60086),  however even I remove the rule for access tcp 60086, the high cpu not fade out but still there, looks like if not restart the node, it will not be fixed. Also I am not sure what makes it stuck there and only the tv_sec & tv_usec looks abnormal.

![3](https://user-images.githubusercontent.com/66289873/122001965-ba315e80-cde3-11eb-8c02-cca6f90fde57.jpg)

**Comment by Logan007** [comment]
Thank you, that is very helpful.

To me, it looks TCP related. I guess you are using one edge connected via TCP, right?

If I am not mistaken here, the TCP connection triggers and wakes up on 'select()'ing the `7` filedescriptor over and over again without having new data available as rcvgfrom()` returning zero. Need to find out the reason.

>  I don't know why supernode listen both on tcp and udp?

We have recently added TCP support. It listens on the same port.

> tv_sec & tv_usec looks abnormal

10 seconds default, seem to be triggered immediately (remaining time is extremely close to 10).

**Comment by galaxyskyknight** [comment]
I spawn one edge on the same VPS where node runs, looks like it use both tcp/udp  and unix domain DGRAM as well. see below, it weired that there is a CLOSE_WAIT stuck connection there with a outside IP address (89.248.165.93) and not sure how it be there. this is for tcp.
See edge side, there is an Edge using unix domain stream type socket connected? but supernode side no unix domain stream type socket on listening? why? not familiar with unix domain socket programming.
![1](https://user-images.githubusercontent.com/66289873/122007442-83ab1200-cdea-11eb-98c7-e9434d1e811d.jpg)

**Comment by Logan007** [comment]
> with a outside IP address (89.248.165.93) and not sure how it be there

`whois 89.248.165.93` indicates in some remarks that they indeed are scanning the internet. Not sure what they are doing to the port.

Socket-wise, I am not sure yet how to judge the CLOSE_WAIT status.

**Comment by Logan007** [comment]
I took a look at the code and found a possible issue at `src/edge_utils.c:2268`.

We might want to replace that line `if((bread <= 0) && (errno)) {` by `if(bread <= 0) {`. You could try that one if you dare, I haven't had the time for trials yet.

I suspect that `select()` is triggered by a the connection being closed (from that scanning address) which is why `rcvfrom()` returns 0 (orderly closed connection, no bytes to read). As this is no error, `err` is not set.

**Comment by galaxyskyknight** [comment]
sounds reasonable. you could check in it and I will try if I have chance to build and deploy. thanks

**Comment by Logan007** [comment]
I think #713 fixes the high CPU load.

As the original mentioned issue is a "feature still to be implemented" which we actually and already [plan](https://github.com/ntop/n2n/pull/673#issuecomment-850970591) for, I will have this issue closed by the pull request.

I renamed this issue to also reflect the 100 % CPU problem hopefully solved now.
