### ISSUE TITLE
option to supernode to turn off the function of mac authentication

### ISSUE THREAD

**Issue by skyformat99** [ntop/n2n#714]
In addition,could you please add an option to supernode to turn off the function of mac authentication?Because in some cases, it is not necessary to start MAC anti spoofing.Thank you!

from  DDNS Bug #703   (This issue also discusses this point)

In fact, in embedded devices, it operates unattended.Most of the time, often power off to restart, or network instability and other reasons disconnected.
It would be a lot easier if you added an option.

**Comment by Logan007** [comment]
To be honest, I was reluctant with this in the first place as it would turn off a security feature.

> In fact, in embedded devices, it operates unattended.Most of the time, often power off to restart, or network instability and other reasons disconnected.

While I understand that the unattended reboot scenario is an issue, let me add that it does not necessarily require to turn off MAC/IP spoofing protection. I know that the alternative~~s~~ (~~`-m` and `-a` at the edge; or:~~`-I` and `-J` for user-password authentication, federation support still to implemented) ask for more user effort in terms of edge configuration.

However, given the demand, I consider adding such an option to the supernode along with a WARNING message sometime soon.

**Comment by Logan007** [comment]
Please test #716 and let me know.

**Comment by skyformat99** [comment]
I tested it and it seems to have some problems.

1) start  supernode ，But the -M option is not used：
  ./supernode -p 10088 -f

2) start edge
   ./edge -d aaa -c myn -k mysecretpass -a 192.168.100.2  -l 127.0.0.1:10088
  it is ok.
then,   kill it
    kill -9   (edge pid)

then,  start  edge again:
     ./edge -d aaa -c myn -k mysecretpass -a 192.168.100.2  -l 127.0.0.1:10088
  use   ps aux | grep  edge  to  check,

but edge is not started.   But there is no warning message.  
The old version should have a warning message?

 
Note:   that   supernode when the -M option is used,   edge is perfectly OK.
 ./supernode -p 10088 -f   -M

**Comment by skyformat99** [comment]
> I tested it and it seems to have some problems.
> 
> 1. start  supernode ，But the -M option is not used：
>    ./supernode -p 10088 -f
> 2. start edge
>    ./edge -d aaa -c myn -k mysecretpass -a 192.168.100.2  -l 127.0.0.1:10088
>    it is ok.
>    then,   kill it
>    kill -9   (edge pid)
> 
> then, start edge again:
> ./edge -d aaa -c myn -k mysecretpass -a 192.168.100.2 -l 127.0.0.1:10088
> use ps aux | grep edge to check,
> 
> but edge is not started. But there is no warning message.
> The old version should have a warning message?
> 
> Note: that supernode when the -M option is used, edge is perfectly OK.
> ./supernode -p 10088 -f -M


Sorry,  I have confirmed again. It's totally OK.
will close it.
