### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by small-5** [ntop/n2n#719]
Use the latest source code to cross compile, segfault appears on OpenWRT
Some core files are generated in the /tmp/
Please Fix it,Thanks!
[log.txt](https://github.com/ntop/n2n/files/6721486/log.txt)

**Comment by small-5** [comment]
This problem arises when the supernode cannot connect.
This segfault will not appear if i don't use boot auto start and wait for the network to connect and start manually.

**Comment by skyformat99** [comment]
> This problem arises when the supernode cannot connect.
> This segfault will not appear if i don't use boot auto start and wait for the network to connect and start manually.

![image](https://user-images.githubusercontent.com/10938976/123588361-37b09200-d81a-11eb-953e-f4a60afdbac8.png)

The problem is this function.
Actually, this shouldn't be a bug.

**Comment by skyformat99** [comment]
Is it possible to consider adding an automatic reconnect option, when there is a problem, automatic cycle reconnect.

**Comment by small-5** [comment]
I feel that this problem appeared after 1586ae62a77542becd6eb846060e9de799d4e272, but there was no before. I will use the version before 1586ae62a77542becd6eb846060e9de799d4e272 to compile and test.

**Comment by small-5** [comment]
Yes, the problem is indeed caused by 3c6ab56d3fdbc6464803cca61fe814f8b8fbbd6f, I used c55e3e32463d9821b7459c9c86108e6f364a1529 to compile it is normal.

**Comment by small-5** [comment]
The problem is indeed caused by 3c6ab56, I used c55e3e3 to compile it is normal.
