### ISSUE TITLE
TCP option `-S2` didn't work on Windows

### ISSUE THREAD

**Issue by DestroyPhoenix** [ntop/n2n#721]
supernode server: ubuntu 20.04 server
edge clients: 2 Windows 10 PCs
All binary is compiled with the latest dev branch by myself.

run supernode: `supernode -p 12345`
use `netstat -lntup` can see the supernode bind the port 12345 both udp and tcp.

run edge1: `edge -c test -k test -l server:port -S2`
run edge2: `edge -c test -k test -l server:port -S2`

but it still use udp... :(

**Comment by Logan007** [comment]
I have [not  been able](https://github.com/ntop/n2n/pull/627#issuecomment-782093706) to make TCP work on Windows edges yet so it is [disabled](https://github.com/ntop/n2n/pull/627#issuecomment-783353970). Any help is appreciated.

**Comment by DestroyPhoenix** [comment]
Thanks. I will try some other tools cooperate with edge, hope has some solution on Windows.

**Comment by Logan007** [comment]
Maybe [those tools](https://github.com/ntop/n2n/issues/353#issuecomment-670848709) might help in the meanwhile... not sure if available on Windows though.

**Comment by DestroyPhoenix** [comment]
Thanks.

**Comment by DestroyPhoenix** [comment]
[udp2raw-tunnel](https://github.com/wangyu-/udp2raw-tunnel) is a nice tool for help udp over tcp both on Windows.
`edge<-->udp2raw client<-->udp2raw server<-->supernode`
I tested it work well, but the delay has doubled or even more, it's from 4ms increase to over than 15ms.

**Comment by DestroyPhoenix** [comment]
I tested n2n+[udp2raw-tunnel](https://github.com/wangyu-/udp2raw-tunnel) with a game, it's work, n2n version is [v2.8](https://github.com/ntop/n2n/releases/tag/2.8).
supernode port: 9999
udp2raw server port: 10000
udp2raw client udp port: 9999
`edge<--udp: 127.0.0.1:9999-->udp2raw client<--tcp: supernode_ip:10000-->udp2raw server<--udp: 127.0.0.1:9999-->supernode`

supernode:
`./supernode -l  9999`

udp2raw server:
`./udp2raw_amd64 -s -l 0.0.0.0:10000 -r 127.0.0.1:9999  -a -k "n2n" --raw-mode faketcp`

udp2raw client:
`udp2raw_mp.exe -c -l 0.0.0.0:9999 -r supernode_ip:10000 --raw-mode faketcp -k "n2n" --enable-color`

edge:
`edge.exe -c n2n -k n2n -l 127.0.0.1:9999 -r -a dhcp:10.0.0.1`

**Comment by Logan007** [comment]
Thanks for sharing as it might help others for the time being!
