### ISSUE TITLE
Supernode identify requirred.

### ISSUE THREAD

**Issue by laikee99** [ntop/n2n#723]
Hi,
I want to know how to secure the super node? We are in a unstable network environment, and can not directly connect to the nodes, must relay on the supernode, but I actually don't want someone just connect the supernode without the permission, how can I achieve that? Thanks.

**Comment by Logan007** [comment]
First of all, you should use `-c <community.list file name>` at the supernode. The plain text file contains all [allowed community names](https://github.com/ntop/n2n/blob/dev/doc/Communities.md#restrict-supernode-access). Only listed communties will be allowed to connect then, so keep the name secret. A sample `community.list` file (including more detailed information also about advanced features) should come with n2n.

As the community name is transmitted in plain text by default, sniffing would reveal it. That is why you should enable [header encryption](https://github.com/ntop/n2n/blob/dev/doc/Crypto.md#header) (`-H`) at **all** the edges. Header encryption is a per-community setting; all edges of one community need to either have it enabled or disabled.

Going with this configuration, only edges knowing the right community name (`-c <community.list file name>`) will be able to register to the supernode and join the community.

You might find our [FAQ](https://github.com/ntop/n2n/blob/dev/doc/Faq.md#i-want-to-setup-a-supernode-that-only-i-can-use-perhaps-even-password-protected) helpful. :wink:

____

If you need more detailed access control, you could try the [user-password authentication](https://github.com/ntop/n2n/blob/dev/doc/Authentication.md#user--password-based-authentication) scheme which we have recently [added](https://github.com/ntop/n2n/pull/673) to the _dev_ branch (currently working with **one** supernode only, no federation support yet).

**Comment by laikee99** [comment]
> First of all, you should use `-c <community.list file name>` at the supernode. The plain text file contains all [allowed community names](https://github.com/ntop/n2n/blob/dev/doc/Communities.md#restrict-supernode-access). Only listed communties will be allowed to connect then, so keep the name secret. A sample `community.list` file (including more detailed information also about advanced features) should come with n2n.
> 
> As the community name is transmitted in plain text by default, sniffing would reveal it. That is why you should enable [header encryption](https://github.com/ntop/n2n/blob/dev/doc/Crypto.md#header) (`-H`) at **all** the edges. Header encryption is a per-community setting; all edges of one community need to either have it enabled or disabled.
> 
> Going with this configuration, only edges knowing the right community name (`-c <community.list file name>`) will be able to register to the supernode and join the community.
> 
> You might find our [FAQ](https://github.com/ntop/n2n/blob/dev/doc/Faq.md#i-want-to-setup-a-supernode-that-only-i-can-use-perhaps-even-password-protected) helpful. 😉
> 
> If you need more detailed access control, you could try the [user-password authentication](https://github.com/ntop/n2n/blob/dev/doc/Authentication.md#user--password-based-authentication) scheme which we have recently [added](https://github.com/ntop/n2n/pull/673) to the _dev_ branch (currently working with **one** supernode only, no federation support yet).

Thank you so much, I did learn a lot from this. This is a very useful experience and guide that how we use N2N securely.
:)
