### ISSUE TITLE
Question: Is there any plan for the federation feature to support supernode sync up while using -I -J encryption?

### ISSUE THREAD

**Issue by galaxyskyknight** [ntop/n2n#726]
currently for the federation feature, if between supernodes only specify the same federation, the edge info could be sync up and all edge nodes cound be inter-communicated, however, if using -I -J for supernodes, those edges registered on different supernodes could not be inter-communicated any more but limited to registered supernode ONLY. That seems if using federation encryption mode ,the edges info will not sync up if they attache to different supernode, there are different behavior for encryption/non-encryption in federation feature, I am more preffered that the edges should be synced up for those registered in the same federation zone among supernodes.

I mentioned above before in another issue, and seems is it WIP?  any plans?:)

**Comment by Logan007** [comment]
> and seems is it WIP? any plans?:)

According to [this](https://github.com/ntop/n2n/blob/dev/doc/Authentication.md#possible-extensions), the multi-supernode support for user-password authentication would follow later with a different pull request. It indeed is work in progress at a very early stage – [planned](https://github.com/ntop/n2n/issues/670#issuecomment-802119568) but [not begun](https://github.com/ntop/n2n/pull/673#issuecomment-850970591) yet. One of my open action items to tackle sometime soon. I just am a bit short of time these days.

Once done, it will allow seamless communication among the password-authenticated edges no matter to which of the federated supernodes they register.

> I am more preffered that the edges should be synced up for those registered in the same federation zone among supernodes.

This feature however will require the administrator to manually or automatically, e.g. by support of some tools such as`syncthing`, keep the `community.list` files for each supernode in sync.

> I mentioned above before in another issue

Yes, I remember #711.

**Comment by galaxyskyknight** [comment]
Got, thank you. looking forward to this feature implementation.

**Comment by Logan007** [comment]
Do you want to test #741?
