### ISSUE TITLE
Option -K <keyfile> not available

### ISSUE THREAD

**Issue by atorrente75** [ntop/n2n#727]
I installed the n2n v.2.9.0.r926.39aa50b from the official Development Builds repository (ubuntu 20.04).
In the man pages the option -K is listed but not on the `edge --help` . Anyway i cannot use it because it's not recognized.

What can I do to have this option enabled?

**Comment by Logan007** [comment]
The keyfile support is long gone. It was a feature of 2.4 or 2.6, I cannot really remember. The man pages do not reflect current changes and still neeed to be polished for 3.0, see [4th task over at #562](https://github.com/ntop/n2n/issues/562#issue-774467229).

**Comment by atorrente75** [comment]
Thank you for your quick replay. So, the only available encryption options are (and will be?) the key ascii and the N2N_KEY environment variable ?

**Comment by Logan007** [comment]
> So, the only available encryption options are [...] the key ascii and the N2N_KEY environment variable ?

Additionally, you could also use a [`.conf` file](https://github.com/ntop/n2n/blob/dev/doc/ConfigurationFiles.md#configuration-files) which can have the key parameter `-k ...` inside. Just make sure to restrict file access properly.

Other alternatives to provide the key require a script-driven way, e.g. `N2N_KEY=$(...some command to read/generate key from BIOS, keyfile, or decrypt keyfile with BIOS UUID, ...) edge <your parameters>`.

Direct provision of the key through `-k ...` at the command line might reveal the key when taking a closer look on the processes through `ps -Af` or so. It is considered more secure to use the `N2N_KEY` environment variable or the `.conf` file.

The payload is encrypted with the pre-shared key (PSK). There are different ciphers (`-A_` command line option) with different [properties](https://github.com/ntop/n2n/blob/dev/doc/Crypto.md#overview). For example, depending on your needs, you could use [AES](https://github.com/ntop/n2n/blob/dev/doc/Crypto.md#aes) which triggers different key sizes (AES-128, AES-192, AES-256) depending on the length of the provided ASCII key. The ASCII input gets hashed before fed as key to the cipher. 

The recently added [user-password authentication](https://github.com/ntop/n2n/blob/dev/doc/Authentication.md#user--password-based-authentication) scheme adds some more security as the payload encryption IV is additionally encrypted by a dynamic key. But so far, only the stream ciphers ChaCha20 (`-A4`) and SPECK (`-A5`) can benefit from it.

> and will be?

Plans are to also have the block ciphers Twofish (`-A2`) and AES (`-A3`) work with the user-password authentication scheme sometime soon for additional protection by the dynamic key.

With a view to the **4.x** series (note, that we now are preparing the **3.x** series) we might go full public-private key.

**Comment by Logan007** [comment]
Does it answer your question?

**Comment by Logan007** [comment]
Closing as considered answered. Please re-open if required.

As a post script, let me add the following...

> ... script-driven way

I have seen the following for use with a BIOS-UUID encrypted key working on that specific machine only – hopefully still after BIOS update :wink:

```bash
k=$(aescrypt -d -p $(dmidecode | grep -w UUID | sed "s/^.UUID\: //g") -o - /<some path>/keyfile | cat)
N2N_KEY=$k /usr/bin/edge -H -A5 -f -c secretCommunity -a 10.xx.xx.xx -E -r -l xx.xx.xx.xx:xxxxx
```

where  the (one) key containing `keyfile` would be generated by the following command

```bash
echo -n "secretKey" | aescrypt -e -p $(sudo dmidecode | grep -w UUID | sed "s/^.UUID\: //g")  - > /<some path>/keyfile
```

driven by the AES Crypt tool which is available as source code from the download section of developers' [home page](https://www.aescrypt.com/), others might suit corresponding needs as well (ssh?).
