### ISSUE TITLE
can not use brctl addif br-lan edge0 

### ISSUE THREAD

**Issue by styfstr** [ntop/n2n#732]
n2n version: 2.8
My openwrt device (edge IP ```10.0.0.1```) and my windows PC (edge IP ```10.0.0.2```) can ping each other. After windows executes the command ```route add 192.168.10.0 mask 255.255.0 10.0.0.1```, windows can ping openwrt's intranet ```192.168.10. X```.
Now I want to set up a LAN in another way (this way can be successful with OpenVPN)

1.  Set two IP addresses for windows edge network card (```10.0.0.2``` and ```192.168.10.33```)

2.  Openwrt uses ```brctl addif br-lan edge0``` to bind ```edge0``` and ```eth0``` together.

Now, when I use ```brctl addif br-lan edge0``` to bind edge0 and eth0 together under openwrt.  my openwrt device and PC will can't communicate. Below is the log of my openwrt device

![image](https://user-images.githubusercontent.com/44523785/126469755-1d602520-d35b-49d2-b398-a3686268df46.png)

my openwrt device config:

![image](https://user-images.githubusercontent.com/44523785/126470813-93c17129-9182-4795-a67f-b032c46dba8a.png)

Why can't eth0 and edge0 be bound together？

**Comment by Logan007** [comment]
> ... eth0 and edge0 be bound together ...

Bridge support has been a still pending issue up to now, please see #302 and #204.

> Why ...

I am not sure about the reasons, not too deep into bridging. Any help is appreciated.

**Comment by styfstr** [comment]
Thanks.
Is there any plan to solve it, because bridging is much more convenient than routing table.

**Comment by Logan007** [comment]
>  bridging is much more convenient than routing table.

I know...

> Is there any plan to solve it

#302 is flagged with _Help Wanted_. We still are looking for someone to sustainably solve it. Any help with it is appreciated.

**Comment by styfstr** [comment]
I will continue to pay attention to this issue, and I will submit any findings to Issues in time.

**Comment by zonghao-xie** [comment]
Is this issue solved now?

**Comment by Logan007** [comment]
I think the status is still "open". While @maxleaf created the pull request #977, it was closed very soon after before any chance to review.

**Comment by Logan007** [comment]
Great news, I hope you will share your results with that pull request again.

**Comment by thankeyes** [comment]
> > I think the status is still "open". After @maxleaf had created the pull request #977, it was closed very soon then, even before we had any chance to review.
> > Is there anyone who has an environment available for testing it?
> 
> Yes，I'm working on this issuse. And the patch should work. But since Shanghai's lockdown, there is no test environment on my hand. If someone can help test it, it would be greatly appreciated.

I tried on my openwrt router,the outside device can connect to my router with the bridge mode (the LAN ip:192.168.1.1),
but all the other devices in the LAN are out of connection.
btw: here the things I found that you have to do so that you can run in the bridge mode.
edge  -d zf100 -a **192.168.1.1**   -c n100 -k n100 -p 10100 -M 1400 -l superser:superport -A -t 20260   -m **aa:bb:cc:dd:ee:ff**
1.it has to use 192.168.1.1 instead of dhcp:0.0.0.0
2.mac address:aa:bb:cc:dd:ee:ff, it has to use the same mac address with the br-lan

**Comment by styfstr** [comment]
Sorry, I just saw the message.
If you haven't tested yet, I can help.

**Comment by reinhard1** [comment]
I have tried to add an edge device to a bridge.
When i try this, i lose the previous working connection to the other edge device.
I am testing this with the git head code.

**Comment by hamishcoleman** [comment]
Hi @reinhard1 - there are some patches that add this feature referenced in the comments above, but none of them have been merged as yet, so it is known not to work

**Comment by reinhard1** [comment]
Yes, i have seen the patch and the merge request, but, as i understand, this merge request is rejected.
Will this feature added in the near future?

**Comment by hamishcoleman** [comment]
The merge request was not rejected, the original author closed it while he continued to work on the patch

**Comment by maxleaf** [comment]
> superser:superport -A -t 20260 -m **aa:bb:cc:dd:ee:ff**



> edge -d zf100 -a **192.168.1.1** -c n100 -k n100 -p 10100 -M 1400 -l



> > > I think the status is still "open". After @maxleaf had created the pull request #977, it was closed very soon then, even before we had any chance to review.
> > > Is there anyone who has an environment available for testing it?
> > 
> > 
> > Yes，I'm working on this issuse. And the patch should work. But since Shanghai's lockdown, there is no test environment on my hand. If someone can help test it, it would be greatly appreciated.
> 
> I tried on my openwrt router,the outside device can connect to my router with the bridge mode (the LAN ip:192.168.1.1), but all the other devices in the LAN are out of connection. btw: here the things I found that you have to do so that you can run in the bridge mode. edge -d zf100 -a **192.168.1.1** -c n100 -k n100 -p 10100 -M 1400 -l superser:superport -A -t 20260 -m **aa:bb:cc:dd:ee:ff** 1.it has to use 192.168.1.1 instead of dhcp:0.0.0.0 2.mac address:aa:bb:cc:dd:ee:ff, it has to use the same mac address with the br-lan

for edge node, -r option is needed
