### ISSUE TITLE
the edge doesn't work properly in latest code for win build

### ISSUE THREAD

**Issue by galaxyskyknight** [ntop/n2n#733]
hello

I use the latest code compiled win build by VS2019 on win 10 platform and it could shown up from supernode side by using 'nc -u localhost 5645' however, it is unreachable from other edge via ping, fortunately I kept the old win binary and after restore the old binary and it works fine. Here I use the same edge.conf file copy(eg with same "route add" instruction in it etc), the other edge(linux based) and supernode are all upgraded to latest code(dev branch) as well with no problem

I don't know how to diag it, could you please check if any new code missed in win platform compile due to MACRO switch?

**Comment by galaxyskyknight** [comment]
here is the binary zip, the edge.exe is the latest code, the edge.exe.old is the previous code which works good for me.

[edge.zip](https://github.com/ntop/n2n/files/6859892/edge.zip)

**Comment by skyformat99** [comment]
The compiler failed to compile on Windows. The error is as follows:
file  n2n.c     line 397
// create thread
    ret = pthread_create(&((*param)->id), NULL, resolve_thread, (void *)*param);
    if(ret) {
        traceEvent(TRACE_WARNING, "resolve_create_thread failed to create resolver thread with error number %d", ret);
        return -1;
    }

build error info:
Severity	Code	Description	File	Project	Line
Error	C2440	'function': cannot convert from 'void *(__cdecl *)(void *)' to 'LPTHREAD_START_ROUTINE'	
  \n2n\src\n2n.c	n2n	397

**Comment by Logan007** [comment]
> it is unreachable from other edge via ping

Do you use `-I` and `-J`? If so, all your edges and supernode need to be same version (and eventually replaced) due to #731.

If not, do you use `-H`?

> The compiler failed to compile on Windows.

This is news to me, the automated compilation [seems to run fine](https://github.com/ntop/n2n/runs/3118253997?check_suite_focus=true). I will look deeper into it later.

**Comment by skyformat99** [comment]
> This is news to me, the automated compilation [seems to run fine](https://github.com/ntop/n2n/runs/3118253997?check_suite_focus=true). I will look deeper into it later.

In addition, the compilation environment  ( Windows  OS ) used is as follows:
     CMake  +   VS 2015    
Mingw is not used.

**Comment by Logan007** [comment]
I have just successfully compiled the latest code using Visual Studio 2019 command line build tools and it compiles well out here.

**Comment by galaxyskyknight** [comment]
> 
> 
> I have just successfully compiled the latest code using Visual Studio 2019 command line build tools and it compiles well out here.

seems weired, I just setup a new workspace and pull the latest code and issue gone, so weired, and I don't know why, probaby the windows build is always magic:) anyway, I will close it right now.

**Comment by galaxyskyknight** [comment]
> 
> 
> The compiler failed to compile on Windows. The error is as follows:
> file n2n.c line 397
> // create thread
> ret = pthread_create(&((*param)->id), NULL, resolve_thread, (void *)*param);
> if(ret) {
> traceEvent(TRACE_WARNING, "resolve_create_thread failed to create resolver thread with error number %d", ret);
> return -1;
> }
> 
> build error info:
> Severity Code Description File Project Line
> Error C2440 'function': cannot convert from 'void *(__cdecl *)(void *)' to 'LPTHREAD_START_ROUTINE'
> \n2n\src\n2n.c n2n 397

I didn't meet this, either x64-release or x64-debug construction runs out objs and binary with no errors but with a lot of warning is true.

**Comment by Logan007** [comment]
> I didn't meet this, either x64-release or x64-debug construction runs out objs and binary with no errors but with a lot of warning is true.

I am not too deep into Windows. Is it something serious?
