### ISSUE TITLE
WARNING: Supernode not responding, now trying ..

### ISSUE THREAD

**Issue by jonahzheng** [ntop/n2n#735]
n2n edge windows x64_v2.9.0_r876
edge.exe -c mynetwork -k mysecretpass -a 192.168.100.2 -f -l .....:1234
supernode n2n v.2.9.0.r930.5c1c65c ubuntu 18.04
 supernode -p 1234 -v -f

n2n echo
> 22/Jul/2021 17:08:20 [edge_utils.c:940] Successfully joined multicast group ...
22/Jul/2021 17:08:32 [edge_utils.c:1325] WARNING: Supernode not responding, now
trying ..
22/Jul/2021 17:08:48 [edge_utils.c:1325] WARNING: Supernode not responding, now
trying ..

supernode echo

> 22/Jul/2021 17:06:39 [sn.c:855] Dropping privileges to uid=65534, gid=65534
22/Jul/2021 17:06:39 [sn.c:872] Successfully created resolver thread
22/Jul/2021 17:06:39 [sn.c:875] supernode started
22/Jul/2021 17:06:44 [n2n.c:288] supernode2sock successfully resolves supernode IPv4 address for ....
22/Jul/2021 17:08:10 [sn_utils.c:1623] New community: mynetwork
22/Jul/2021 17:08:10 [sn_utils.c:898] Assigned sub-network 10.164.148.0/24 to community 'mynetwork'.
22/Jul/2021 17:08:10 [sn_utils.c:705] update_edge created  00:FF:76:19:61:D0 ==> ....:35849
22/Jul/2021 17:08:22 [sn_utils.c:722] update_edge updated  00:FF:76:19:61:D0 ==> ...:36597

**Comment by Logan007** [comment]
Could you please check some `-vvvvv` output of `edge` and `supernode` for "suspicious" entries, e.g. `Tx REGISTER_SUPER_ACK` at supernode but `Rx  REGISTER_SUPER_ACK` missing at edge, and so on?

Also, does it work better with both edge and supernode build from current dev?

By the way, I do not know how you can get `-f` working at Windows `edge.exe`. In case you have not built using MSVS as described in our [Building documentation](https://github.com/ntop/n2n/blob/dev/doc/Building.md#build-on-windows), you might indeed see some communication issues (#617 #631 #642) which still are subject to further investigation.

**Comment by jonahzheng** [comment]
thanks for you reply.

edge.exe -c mynetwork -k mysecretpass -a 192.168.100.2
-l ******:1234 -vvvvv >> edge.txt
supernode -p 1234 -vvvvv -f >> supernode.txt

log:
[edge.txt](https://github.com/ntop/n2n/files/6865609/edge.txt)
[supernode.txt](https://github.com/ntop/n2n/files/6865611/supernode.txt)

**Comment by Logan007** [comment]
@jonahzheng, I have taken a look into the logs you provided. It is the first time that I see a drop "due to wrong addressing". It shows the correct `00:FF:76:...` MAC at the supernode (same as reported by edge at start-up), but the answer seemingly contains the `8E:68:0F:...` MAC. So far, no idea why  this would happen.

I am not sure if the latest changes have solved your issue so I have re-opened, please close if done.

Also, does it work better with both edge and supernode build from current dev? I saw that edge r876 is as of February 2021 while supernode r930 must be quite fresh.

Furthermore, did you build the Windows binary with MSVS?

**Comment by jonahzheng** [comment]
yes it was really weird, but I use v2.8, everying works, the same environment.
windows exe:
V2.9 https://github.com/lucktu/n2n/blob/master/Windows/n2n_v3_windows_x64_v2.9.0_r876_static_by_Tim.zip
v2.8 https://github.com/lucktu/n2n/blob/master/Windows/n2n_v2_windows_x64_v2.8.0_r539_static_by_Tim.zip

so I build the Windows binary with MSVS for the latest version.

**Comment by Logan007** [comment]
Just to be sure, also build the current supernode as well... you never know! I am curious, let me know what you find.

**Comment by Logan007** [comment]
I have dug a bit into it... On March 16, #662 changed the packet format of REGISTER_SUPER_ACK, especially the use of the MAC field. That would explain why the edge of February does not communicate well with the supernode of June/July.

I guess, an update to the current edge will help it. Let us know.

Please keep in mind when testing 2.9 a.k.a. current _dev_: Always use the same code base for both supernode and edge as [we do not guarantee](https://github.com/ntop/n2n#manual-compilation) backward compatibility not even with earlier _dev_. :wink:

**Comment by Logan007** [comment]
@lucaderi has just checked the current packets for version mixes but was not able to find any. If this issue still persists after updating edge and supernode to the same version, please contact him directly with some more details, i.e. on [Discord](https://www.ntop.org/community/).

**Comment by Logan007** [comment]
Considered answered, please re-open if required.

**Comment by sweihub** [comment]
This thread solved my issue, I have both edge & supernode install at same host, 

`edge -f -vvvvv -l 127.0.0.1:34567 ... ` cause the packet from LAN IP not 127.0.0.1,  the packet was dropped as not the supernode IP, change to LAN IP solved my issue.
