### ISSUE TITLE
Installing stable apt packages is confusing

### ISSUE THREAD

**Issue by ghost** [ntop/n2n#737]
On  a raspberry pi running raspberry PI OS (based on arm debian 10)

- I google "atop n2n vpn"
- I go to https://www.ntop.org/products/n2n/
- CRTL + F "download" -> "Download(Link) and compile the code"
- Leads me to https://github.com/ntop/n2n
- I select the Branch 2.8-stable
- I scroll to "Quick Setup" -> "[...] are available on ntop repositories.(Link)"
- Leads me to https://packages.ntop.org/
- I select " Raspberry Raspbian"
- I copy paste the commands
- It installs testing:

```
$ apt-cache policy n2n
n2n:
  Installed: (none)
  Candidate: 2.9.0-930
  Version table:
     2.9.0-930 500
        500 http://apt.ntop.org/buster_pi armhf/ Packages
     1.3.1~svn3789-7 500
        500 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages
```

Also I noticed that the sources.list.d/ntop.list entry is different to the output of the dpkg -i command:

```
$ dpkg -i apt-ntop_1.0.190416-469_all.deb 
(Reading database ... 49777 files and directories currently installed.)
Preparing to unpack apt-ntop_1.0.190416-469_all.deb ...
Unpacking apt-ntop (1.0.190416-469) over (1.0.190416-469) ...
Setting up apt-ntop (1.0.190416-469) ...
Adding ntop key to apt keyring
Warning: apt-key should not be used in scripts (called from postinst maintainerscript of the package apt-ntop)
OK
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease                                                 
Hit:2 http://archive.raspberrypi.org/debian buster InRelease                                
Get:3 https://packages.ntop.org/apt/buster_pi armhf/ InRelease [2,155 B]
Get:4 https://packages.ntop.org/apt/buster_pi all/ InRelease [2,153 B]
Get:5 https://packages.ntop.org/apt/buster_pi armhf/ Packages [1,935 B]
Get:6 https://packages.ntop.org/apt/buster_pi all/ Packages [738 B]
Fetched 6,981 B in 8s (852 B/s)  
Reading package lists... Done

$ cat /etc/apt/sources.list.d/ntop.list 
deb http://apt.ntop.org/buster_pi armhf/
deb http://apt.ntop.org/buster_pi all/
```

So should I use packages.ntop.org or apt.ntop.org now..? I realize ofc that apt.ntop.org is a CNAME to packages, but its still confusingly inconsistent :P

### Feature request

At the top of https://packages.ntop.org/ it should be possible to select between stable and dev, or the versions.

I feel like this may have been the cause for my confusion in https://github.com/ntop/n2n/issues/735

**Comment by ghost** [comment]
Ah, found this alternative page: https://packages.ntop.org/apt-stable/

which states that raspbian has no stable packages maintained. meh :(

**Comment by Logan007** [comment]
@lucaderi has just checked the current packets for version mixes but was not able to find any. If this issue occurs ever again after updating edge and supernode to the same version, please contact him directly with some more details, i.e. on [Discord](https://www.ntop.org/community/).
