### ISSUE TITLE
Centos 7 make error

### ISSUE THREAD

**Issue by solaris24** [ntop/n2n#74]
I get several errors when building a package:

[root@centos]# make
rm -rf *~ *rpm
rpmbuild -bb ./n2n.spec
error: line 3: Empty tag: Version:
make: *** [pkg] Error 1

fixed after that changed the version in the file /n2n/packages/centos/n2n.spec 
but I get next error

[root@centos]# make
rm -rf *~ *rpm
rpmbuild -bb ./n2n.spec
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.W0jNwY
+ umask 022
+ cd /root/rpmbuild/BUILD
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.m04UQI
+ umask 022
+ cd /root/rpmbuild/BUILD
+ mkdir -p /root/rpmbuild/BUILDROOT/n2n-v2-104.x86_64/usr/sbin /root/rpmbuild/BUILDROOT/n2n-v2-104.x86_64/usr/share/man/man1 /root/rpmbuild/BUILDROOT/n2n-v2-104.x86_64/usr/share/man/man7 /root/rpmbuild/BUILDROOT/n2n-v2-104.x86_64/usr/share/man/man8
+ mkdir -p /root/rpmbuild/BUILDROOT/n2n-v2-104.x86_64/etc/n2n
+ mkdir -p /root/rpmbuild/BUILDROOT/n2n-v2-104.x86_64/usr/lib/systemd/system/
+ cp /root/n2n/edge /root/rpmbuild/BUILDROOT/n2n-v2-104.x86_64/usr/sbin
cp: cannot stat '/root/n2n/edge': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.m04UQI (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.m04UQI (%build)
make: *** [pkg] Error 1

**Comment by emanuele-f** [comment]
You need to follow a full compilation before creating the package, check out https://github.com/ntop/n2n/blob/dev/doc/Centos.md

**Comment by emanuele-f** [comment]
Closing as no feedback received.
