### ISSUE TITLE
Multiple super node

### ISSUE THREAD

**Issue by gzdaodao** [ntop/n2n#746]
Can n2n support multiple super node?
If n2n work with only one super node, the whole vpn network down if super node down

**Comment by gzdaodao** [comment]
n2n can add multiple -l to support multi super node

**Comment by Logan007** [comment]
You can find some details on federated supernodes [in the `/doc` folder](https://github.com/ntop/n2n/blob/dev/doc/Federation.md) and might to want to add your own federation name `-F mySecretFedName` to all your supernodes.

**Comment by lucktu** [comment]
"edge support multiple super nodes" is unreliable.
