### ISSUE TITLE
super node support password or token?

### ISSUE THREAD

**Issue by gzdaodao** [ntop/n2n#747]
Can super node support password or token to protect super node that only who provide the same token can link to the super node?

without protect,every one can use our super node and eat all of my bandwidth

**Comment by gzdaodao** [comment]
-c

**Comment by Logan007** [comment]
Please have a look at out [FAQ](https://github.com/ntop/n2n/blob/dev/doc/Faq.md#i-want-to-setup-a-supernode-that-only-i-can-use-perhaps-even-password-protected). You might also want to add `-H` to all your edges.
