### ISSUE TITLE
Packet loss on AES

### ISSUE THREAD

**Issue by Logan007** [ntop/n2n#75]
A floodping on TF or NULLTRANSFORM shows some initial packet loss, but then does not increase significantly. On AES, there also is this initial packet loss and then a slowly constantly further increasing packet loss.

Some details:

TF shows some initial packet loss (the points you can see) right in the beginning, remaining stable over the rest of the five minutes:
```
sudo timeout -s SIGINT 300 ping -f 10.19.49.14
PING 10.19.49.14 (10.19.49.14) 56(84) bytes of data.
...........                        
--- 10.19.49.14 ping statistics ---
18430 packets transmitted, 18419 received, 0.0596853% packet loss, 
time 1286ms rtt min/avg/max/mdev = 172.729/179.523/557.474/23.809 ms, 
pipe 35, ipg/ewma 16.277/174.319 ms
```

On AES (same command line but with -A), it also shows roughly the same initial packet loss but then increases constantly:
```
sudo timeout -s SIGINT 300 ping -f 10.19.49.14
PING 10.19.49.14 (10.19.49.14) 56(84) bytes of data.
..............................................................................................................................................................................................................................................................................................................................................     
--- 10.19.49.14 ping statistics ---
18390 packets transmitted, 18086 received, 1.65307% packet loss, 
time 1284ms rtt min/avg/max/mdev = 169.149/174.149/498.313/19.052 ms, 
pipe 30, ipg/ewma 16.313/170.976 ms
```
As you might see from the ping times, it is a connection half around the world using a supernode to bridge double-NAT in between.

But even if I chose two local nodes, I get relatively (!) similar results and behaviour (first loss only **vs.** first loss plus additional constantly increasing loss), not as many absolute losses, though. On TF:
```
sudo timeout -s SIGINT 300 ping -f 10.19.49.14
PING 10.19.49.14 (10.19.49.14) 56(84) bytes of data.
.              
--- 10.19.49.14 ping statistics ---
46688 packets transmitted, 46687 received, 0.00214188% packet loss, 
time 1291ms rtt min/avg/max/mdev = 2.975/6.776/251.459/7.324 ms, 
pipe 15, ipg/ewma 6.425/6.498 ms
```
On AES:
```
sudo timeout -s SIGINT 300 ping -f 10.19.49.14
PING 10.19.49.14 (10.19.49.14) 56(84) bytes of data.
.....................................................................              
--- 10.19.49.14 ping statistics ---
46119 packets transmitted, 46050 received, 0.149613% packet loss, 
time 1295ms rtt min/avg/max/mdev = 3.001/6.920/266.580/8.540 ms, 
pipe 16, ipg/ewma 6.504/6.393 ms
```

**Comment by Logan007** [comment]
I found that applying this [patch](https://github.com/ntop/n2n/files/2923058/fixAES.txt) prevents the increasing packet loss.

**Comment by Logan007** [comment]
@emanuele-f, you fixed it with this [change](https://github.com/ntop/n2n/commit/e989f475a1b7df8e8d51ea5805c1009b71b075f4), so this issue could be closed.

**Comment by emanuele-f** [comment]
Thank you for reporting, I though that fix might be linked to this issue
