### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by skyformat99** [ntop/n2n#758]
The latest version, after compiling, ran example_edge_embed_quick_edge_init and the following error occurred:

[root@demo build]# ./example_edge_embed_quick_edge_init
30/Aug/2021 09:56:48 [n2n.c:295] supernode2sock successfully resolves supernode IPv4 address for 7.8.9.10
30/Aug/2021 09:56:48 [edge_utils.c:3616] adding supernode = 7.8.9.10:1234
30/Aug/2021 09:56:48 [tuntap_linux.c:204] Waiting for TAP interface to be up and running...
30/Aug/2021 09:56:48 [tuntap_linux.c:225] Interface is up and running
30/Aug/2021 09:56:48 [edge_utils.c:331] number of supernodes in the list: 1
30/Aug/2021 09:56:48 [edge_utils.c:333] supernode 0 => 7.8.9.10:1234
30/Aug/2021 09:56:48 [transform_aes.c:210] setup_aes_key 128-bit key setup completed
30/Aug/2021 09:56:48 [edge_utils.c:1049] successfully joined multicast group 224.0.0.68:1968
30/Aug/2021 09:56:48 [edge_utils.c:1493] registering with supernode [7.8.9.10:1234][number of supernodes 1][attempts left 2]
30/Aug/2021 09:56:48 [edge_utils.c:1174] send REGISTER_SUPER to [7.8.9.10:1234]
30/Aug/2021 09:56:48 [edge_utils.c:526] registering with multicast group 224.0.0.68:1968
30/Aug/2021 09:56:48 [edge_utils.c:1318] send REGISTER to [224.0.0.68:1968]
30/Aug/2021 09:56:50 [n2n.c:614] Purging old registrations
30/Aug/2021 09:56:50 [n2n.c:619] Remove 0 registrations
30/Aug/2021 09:56:50 [edge_utils.c:1101] send PING to supernodes
Segmentation fault

After the previous version was compiled, the run was OK.

**Comment by skyformat99** [comment]
I think we know why,
This is caused by modifying the CMakefile.txt file.
The problem was resolved after only restoring the  4/June   CMakefile.txt  file.

**Comment by Logan007** [comment]
Thank you for reporting and fixing!

I am absolutely not confident with the build systems which still cause some confusion at my side. Excuses upfront!

It seems that after the fix, even regular edge's multi-threading is disabled on Linux build when building with cmake. It however is still enabled when building with make only – see edge's  (missing) `successfully created resolver thread` output but broken example.

So, somehow, we need to enable threading (macro `HAVE_PTHREAD`) for edge and supernode while keeping it disabled for building the examples OR properly setup the resolver thread for the embedding examples (which I wouldn't want to do because embedding should be easy).

Any idea?

**Comment by fengdaolong** [comment]
To solve the root of the problem, it cannot be simple and rude. 
When the root cause of the problem is not found, libpthread can be disabled by default when building, `OPTION (N2N_OPTION_USE_PTHREAD "USE PTHREAD Library" OFF)`.

**Comment by skyformat99** [comment]
Agreed. Maybe it needs some careful refix here.

There are two ways to compile on Linux:  CMake  ,    Makefile.
There are also two ways to compile for Windows :   CMake + Visual Studio ,   MinGW-w32/64

this pthread lib can be used entirely on Linux,  
on Windows,   if use MinGW-w32/64 compile n2n, this pthread lib can be used;
if use  CMake + Visual Studio , the pthread lib  is not required .

**Comment by Logan007** [comment]
I am a bit lost now... Is there a way to have the library used for edge and supernode but not for the embedding examples? And not at all on Windows if compiled with Visual Studio?

If I remember correctly,  we might switch exclusively to cmake sometime soon. Is anyone able to re-write the `doc/Building.md`, especially with a view to the additional configuration / compiler options?

**Comment by skyformat99** [comment]
> I am a bit lost now... Is there a way to have the library used for edge and supernode but not for the embedding examples? And not at all on Windows if compiled with Visual Studio?

 if compiled with Visual Studio,  the pthread lib is not required .
In fact, in file  n2n_win32.h ,  The Windows thread API was used to simulate pThreads.

**Comment by skyformat99** [comment]
I traced the code and found that the pointer was null.
I think PR #762 has fixed that.
Please review it

**Comment by skyformat99** [comment]
the null pointer issue is resolved, it should be Ok to use the pThread library by default.
so,  Can you revert yesterday's CMakefile.txt  files?   ->  "do not link if libpthread is not found (#757)"

**Comment by Logan007** [comment]
I was thinking to just turn pthreads  back on again (OFF -> ON). Doesn't the follow-up logic work correctly?

It compiles well here on Linux as well as on Windows. Even the embed_examples work well now on Linux – they require the fresh changes of #761, too.

**Comment by skyformat99** [comment]
> I was thinking to just turn pthreads back on again (OFF -> ON). Doesn't the follow-up logic work correctly?
> 
> It compiles well here on Linux as well as on Windows. Even the embed_examples work well now on Linux – they require the fresh changes of #761, too.

Now it #761  looks like it's all right.
thanks.

**Comment by Logan007** [comment]
Thank you everybody for sorting this out and getting it straight!!
