### ISSUE TITLE
Force v2 version 

### ISSUE THREAD

**Issue by RobJrCG** [ntop/n2n#764]
Hi, 

How to make n2n work on v2 version? I currently have problems with V2s and V3 ?

All clients is V2 version !

**Comment by Logan007** [comment]
> How to make n2n work on v2 version?

Given the short issue description, I can only make assumptions on the exact problem getting n2n to work.

If you are referring to 2.8, you just can download the [stable version](https://github.com/ntop/n2n/releases/tag/2.8) and follow the instructions from the included [README.md](https://github.com/ntop/n2n/blob/2.8-stable/README.md).

As far as I know, ntop's supernode at ntop.org is not version 2.8  anymore, it has been upgraded to 2.9 _dev_. So, you would need to setup your own 2.8 supernode.

> I currently have problems with V2s and V3 ?

As a rule of thumb, all edges require the same version as the supernode. v2.8 edges need a 2.8 supernode – mixing with 2.6 and maybe even 2.4 should work as well.

2.9 _dev_ (a.k.a future 3.0) is not compatible to 2.x versions anymore. It requires a supernode of the exact same _dev_ version. Note, that _dev_ is still under some development. If you want to try the 2.9 _dev_ version, be aware that changes may occur somewhat rapidly; it is essential to use same _dev_ version at all sides (edges and supernode).

I don't know about V2s.

> All clients is V2 version !

You would need a corresponding supernode then.

**Comment by RobJrCG** [comment]
Client Version

![Client](https://user-images.githubusercontent.com/25929252/131901042-1e713e11-c4f5-4b02-904a-dabaf1477a21.PNG)

Server Version

![Server](https://user-images.githubusercontent.com/25929252/131901100-9b90650f-0084-4f81-bb67-237ea42dab4f.PNG)

Error:

![Error](https://user-images.githubusercontent.com/25929252/131901489-62280751-865f-4fff-b3a4-4f1911a43323.PNG)

What could be causing this problem?

**Comment by Logan007** [comment]
Oh, 2.1!

That's n really old version... I can't even say because I have joined somewhat later.

Could you upgrade to latest stable (2.8) or current _dev_? They should be working way more flawlessly.

**Comment by RobJrCG** [comment]
My clients are all over the world, in this case I can't configure them.
Tried to put supernode in the current version, but it gives a communication error of type "WARNING: Supernode not responding - moving to 0 of 1".

**Comment by Logan007** [comment]
Current supernode will definitely not work with 2.1 edges.

> in this case I can't configure them

Your best chance is supernode [2.4](https://github.com/ntop/n2n/tree/2.4-stable) then – no guarantee here. Or, to manually debug the 2.1 supernode.

> "WARNING: Supernode not responding - moving to 0 of 1".

This just means that edge can't establish contact and trying again.

> Your 2.1 test above

Edge obviously rejects the REGISTER_SUPER_ACK with wrong cookie. But somehow, this is good news, because it shows that they basically communicate. That's a good point to start debugging if you dare (REGISTER_SUPER handling, especially cookie handling).

**Comment by RobJrCG** [comment]
Solved with version v2 from:

https://github.com/certik/n2n

**Comment by lucktu** [comment]
First: git  https://github.com/ntop/n2n.git
Then: git checkout 52efc6ffad8db8c81408ea50c3b5f0f702840bbb
