### ISSUE TITLE
number of edge's cli options

### ISSUE THREAD

**Issue by Logan007** [ntop/n2n#771]
`edge` has a lot of cli options, some even say that there are too many. Before we move on to 3.0 release, can we merge some of them?

I see potential for new `-b` being merged into `-p`, e.g. `-p 80` or `-p 192.168.0.100:80` or just `-p 192.168.0.100`... requires some parsing though.

Do you see potential for more options to be combined?

Please keep in mind to not merge overlay network options (for virtual network configuration) with options to configure the underlying real network behavior.

This issue emerges from [another discussion](https://github.com/ntop/n2n/issues/766#issuecomment-914936023), credits to @fengdaolong .

**Comment by skyformat99** [comment]
very good
