### ISSUE TITLE
This isn't a P2P

### ISSUE THREAD

**Issue by lucktu** [ntop/n2n#780]
Computer A
edge2 -a 172.20.10.12 -c n2n -k test -l supernode_1:10086 -d sads1 -EA
edge3 -a 172.30.10.12 -c n2n -k test -l supernode_2:10090 -d sads2 -e x.x.x.x -f -t 19617

Computer B
edge2 -a 172.20.10.22 -c n2n -k test -l supernode_1:10086 -d sads1 -EA
edge3 -a 172.30.10.22 -c n2n -k test -l supernode_2:10090 -d sads2 -e x.x.x.x -f -t 19617

In computer A
**nc -u 127.0.0.1 19617**
PEER TO PEER
   1 | 172.30.10.22  | 62:EA:B9:EA:B5:C4 | **172.20.10.22**:43161  | Computer B  |         1
**ping 172.30.10.22**
64 bytes from 172.30.10.22: icmp_seq=2320 ttl=64 time=328 ms
**ping 172.20.10.22**
64 bytes from 172.20.10.22: icmp_seq=2320 ttl=64 time=328 ms

When p2p, time=40 ms.

**Comment by Logan007** [comment]
With a view to the management port output, it seems that edge3 assumes the edge2 network as underlying _real_ network. With edge2 accepting multicast (`-E`), multicast REGISTERs can find their way through edge2's network between edge3's edges. So, if the underlying edge2 network is not p2p, the edge3 cannot perform faster in this case.

I see three ways to solve it:

First, you could try `-p <real network IP>` (probably same IP address as with `-e`). Or, compile edge3 with configured `DSKIP_MULTICAST_PEERS_DISCOVERY` or change `src/edge_utils.c:557`'s `N2N_LOCAL_REG_COOKIE` to `N2N_REGULAR_REG_COOKIE`.

Let me know what you find. If successful, it might help to find another way to regularly assign lower priority to multicasted REGISTERs than to `-e`-induced REGISTERs.

**Comment by lucktu** [comment]
No change: ()

First (-p <real network IP>)
edge3 -a 172.30.10.12 -c n2n -k test -l supernode_2:10090 -d sads2 -p 192.168.2.22 -e 192.168.2.22 -f -t 19617

Then (modefy src/edge_utils.c:557, compiles, ...) 

Can we rule out the "p2p" by lan (or n2n's lan)? ... ... o no, edge2 could be p2p, or it could be forward. Now it's p2p.

**Comment by Logan007** [comment]
> Then (modefy src/edge_utils.c:557, compiles, ...)

So, this did not help either?

Have you tried the third option configuring `./configure CFLAGS="-DSKIP_MULTICAST_PEERS_DISCOVERY"`? If this works, we can add a cli option , another expert level option, to disable multicast peer detection.

> Can we rule out the "p2p" by lan (or n2n's lan)?

n2n's edge looks like a normal LAN to all applications, also to all edges started later.

The point is that the `-e ...` provided socket only gets distributed by PEER_INFO which again is distributed only if p2p is not successful. In your scenario, p2p actually _is_ successful albeit through the "wrong" network interface.

Perhaps, we should disable multicast peer discovery if `-e ...` provided.

Thinking... :thinking:

**Comment by lucktu** [comment]
(Then (modefy src/edge_utils.c:557, compiles, ...))
It's not affected.

 (./configure CFLAGS ... ...)
It never happened again in several of my tests (about 3--5 times),  it's all wan's ip, not edge's ip. unfortunately, so does the old edge. so ... ... It's not easy to reappeare.

But does that reduce the rate of p2p?

**Comment by Logan007** [comment]
> The point is that the `-e ...` provided socket only gets distributed by PEER_INFO which again is distributed only if p2p is not successful. In your scenario, p2p actually _is_ successful albeit through the "wrong" network interface.

PEER_INFO distribution does not happen in some cases (only if no p2p yet). Maybe, we need to distribute the preferred socket along with the REGISTER to make sure it is being read under all circumstances... :thinking:

**Comment by Logan007** [comment]
#783 might help your scenario as it disables multicast peer detection if `-e ...` is provided so those REGISTERs cannot take precedence over the locally sent ones (via the preferred socket).

**Comment by lucktu** [comment]
Ha, ha. Here we go again,

With and no with "./configure CFLAGS="-DSKIP_MULTICAST_PEERS_DISCOVERY"", it's all the same. ( n2n v.2.9.0.r975.72d703c)

And I see a message, 
... ... 14/Sep/2021 16:41:02 [edge_utils.c:932] peer 92:31:88:1D:03:A6 changed [101.219.245.65:43925] -> [172.20.10.22:29469]

Sorry, I've been wrong about one thing. supernode_1 and supernode_2 are in the same pc with the same wan ip, different port.

**Comment by Logan007** [comment]
And if you use `-e <LAN IP address>` **and** `-p <LAN IP address>` with the current _dev_ which turns off multicast peer detection with `-e`?

**Comment by lucktu** [comment]
I'm sorry. now it's gone.

**Comment by Logan007** [comment]
> I'm sorry. now it's gone.

So, it works?

What parameters have you supplied?

**Comment by lucktu** [comment]
It never happened again in several of my tests, ... ...

**Comment by Logan007** [comment]
Good news... but a bit spooky, too :ghost:

**Comment by lucktu** [comment]
Continuing the test on the first post, 

On B, improve the network, get it in top shape, however, the connection state does not change, forward via 172.20.10.22:43161, time=328 ms.

If we kill "edge2 -a 172.20.10.22 ...", so they quickly became p2p via wanip:43161, time=40 ms.

**Comment by Logan007** [comment]
Have you tried the newest edge3 with `-e auto`? Or with `-e <local LAN or WiFi IP address>`?

`-e ...` option should disable the multicast peer detection in newest edge3, so it should not connect over the edge2 line then. If provided to **all** edge3 instances, there should not arrive a single REGISTER through the edge2 network.

If this does not help: Do you apply any special routing through the edge2-network in a way which could influence edge3's supernode connection?

If `-e auto` (or with IP address) does not help, please also put `-p <local LAN or WiFi IP address>` (in addition to `-e ...`).

**Comment by lucktu** [comment]
-e auto, lan not wifi. 
(edge3 -a 172.30.10.12 -c n2n -k test -l supernode_2:10090 -d sads2 -e auto -r -f -t 19617)

It connect over the edge2 line, It's the truth.

You're right. I've used some static routing like that, I'll stop the static routing at once.
route add -net 192.168.1.0/24 gw 172.20.10.22
route add 192.168.1.100 gw 172.20.10.25

I don't like using e and p at the same time, I'm just running some tests.

**Comment by Logan007** [comment]
> It connect over the edge2 line, It's the truth.

You need to apply it to **all** v3 edges of that network then.

> I don't like using e and p at the same time, I'm just running some tests.

Why dont you like to use them at the same time?

`-e ...` would disable the multicast and `-p ...` would – in addition – make sure that edge only connects to the LAN interface.

> I've used some static routing like that

I see. But you do not route the default route, so this does not route access to the supernode_2 via the edge2 line, right?

**Comment by lucktu** [comment]
It connect over the edge2 line only a edge3, other one no.
Using -p creates conflicts, which I encountered once, and I don't want to use too many options.
Although I set up forwarding and static routing, I did not use it.

**Comment by Logan007** [comment]
> Using -p creates conflicts, which I encountered once

Do you want to explain it?

> and I don't want to use too many options

Your scenario containing several edges at one computer is special, and so is the configuration to handle it.

**Comment by lucktu** [comment]
I set the port to be exactly the same as the others. -p -t
Mostly because I'm lazy, I don't want too many options. it's a long list. for example(Of course, I also know that the configuration file should be used ^_^, the simpler the better)

`edge3 -a 172.30.10.12 -c n2n -k test -l supernode_2:10090 -d sads2 -e x.x.x.x -f -t 19617 -p 32523 -S1 -A4 -z1 -m 10:20:30:40:50:60 -M 1384 -r -E -I It's_too_complicated_to_use -J asds -P dsfdsf -n ... ...`

All right, let's go back. hope to improve p2p success rate. Try Hard to change and try.

**Comment by Logan007** [comment]
> I also know that the configuration file should be used ^_^

I would like to compare to some other tools such as openssh daemon which also requires a lot of configuration. Users with advanced setup edit the `.conf` file with its many options and generate keys pairs and place them in user's directories all over the network. So yes, I would recommend to use the config files. Especially as they are a better way to provide the key – other users could see it, try `ps -Af`.


> `-p 32523`

You could change this to `-p <local  IP address>:32523` and add `-e auto`.

> the simpler the better

I agree and I wish we had a GUI to configure it all. Then, changing a flag would be as easy as clicking a check box.

**Comment by lucktu** [comment]
Well, now that you know, I'm shutting it down.
