### ISSUE TITLE
run error on windows

### ISSUE THREAD

**Issue by skyformat99** [ntop/n2n#782]
1) use VS2015+cmake  to  compile last code
2) run edge -c xxx -l 127.0.0.1:8888
3) error :
![image](https://user-images.githubusercontent.com/10938976/133044047-2946d2b3-9231-47e5-be88-8110c41a3c19.png)

**Comment by skyformat99** [comment]
trace last code, 
The error occurs where:

int detect_local_ip_address (n2n_sock_t* out_sock, const n2n_edge_t* eee) {
        .......................
            return -3;
        **close(probe_sock);**

The return value of the socket() function in Linux or Windows may be different.

**Comment by Logan007** [comment]
I think we shoud use `closesocket()` instead of close... will replace immediately.

**Comment by skyformat99** [comment]
> I think we shoud use `closesocket()` instead of close... will replace immediately.

probe_sock = socket(PF_INET, SOCK_DGRAM, 0);
socket() on Windows:
If no error occurs, socket returns a descriptor referencing the new socket. Otherwise, a value of INVALID_SOCKET is returned

INVALID_SOCKET is -1 ;

probe_sock type is :  typedef UINT_PTR        SOCKET;

so ,  when socket() fail ,  probe_sock is  0xFFFFFFFF,   So next  into the  
if(probe_sock >= 0) {  }

The correct one should just return -2

**Comment by Logan007** [comment]
> so , when socket() fail , probe_sock is 0xFFFFFFFF

But isn't `0xFFFFFFFF` == -1  and thus `< 0`? I am confused now.

**Comment by skyformat99** [comment]
in basetsd.h  and  WinSock2.h：
 
typedef _W64 unsigned int UINT_PTR, *PUINT_PTR;
typedef UINT_PTR        SOCKET;
#define INVALID_SOCKET  (SOCKET)(~0)
 
(SOCKET)(~0) ==>   hex:  0xFFFFFFFF （Dec:  4294967295）

This is because the SOCKET data type is different on Linux and Windows:
on Linux ,  SOCKET is int type
on Windows ,  SOCKET is  uint type  

so, I suggest modifying the following statement:
if(probe_sock >= 0)     ===>    if( (int)probe_sock >= 0)

**Comment by Logan007** [comment]
Thank you, will do immerdiately!

Do we need to change `open_socket()` as well?

**Comment by skyformat99** [comment]
> Thank you, will do immerdiately!
> 
> Do we need to change `open_socket()` as well?

thanks.  
you are right,  we need to change open_socket() as well.

in  open_socket() : 

if((sock_fd = socket(PF_INET, ((type == 0) ? SOCK_DGRAM : SOCK_STREAM) , 0)) < 0)  
===>
if( (int)(sock_fd = socket(PF_INET, ((type == 0) ? SOCK_DGRAM : SOCK_STREAM) , 0)) < 0)

**Comment by Logan007** [comment]
Okay, have just done it. Thank you for getting deeper into this, good catch!

I guess Windows run time error is fixed?

**Comment by skyformat99** [comment]
> Okay, have just done it. Thank you for getting deeper into this, good catch!
> 
> I guess Windows run time error is fixed?

thanks.
I compiled and tested it, and it was perfect.
close it.
