### ISSUE TITLE
about pinging between Windows and Linux

### ISSUE THREAD

**Issue by skyformat99** [ntop/n2n#785]
1) use last code to compile binary file on Windows and Linux;
2) On linux, Run the server and client separately:
     ./supernode -p 8888 -f
     ./edge -c xxx  -l 127.0.0.1:8888 -d zz -f -a 192.168.188.10 -k xxx
3) on Windows, run the client:
     edge -c xxx  -l   xx.xx.xx.xx:8888 -a 192.168.188.11 -k xxx
4)  from windows ping linux:
     ping 192.168.188.10
Pinging 192.168.188.10 with 32 bytes of data:
Reply from 192.168.188.11: Destination host unreachable.
Request timed out.
Request timed out.

The two edges cannot communicate with each other.

but,  if remove **-k xxx** ,   
They can communicate with each other.
It seems that the encryption method is different under different OS.

**Comment by Logan007** [comment]
Is it related to #631 #642 #617? Did you build Windows along the chain describede in`doc/Building.md`? There seem to be issues when done differently, especially when using MinGW.

**Comment by skyformat99** [comment]
> Is it related to #631 #642 #617? Did you build Windows along the chain describede in`doc/Building.md`? There seem to be issues when done differently, especially when using MinGW.

on Windows:   CMake +VS2015  to build.
It looks the same as  #617  #642

**Comment by skyformat99** [comment]
<font size=4>
_llfj commented 16 days ago.
After testing, the version before v2.9.0_r814 --hard 8089200 uses mingw to compile the edge of the windows platform and the ping succeeds after encrypted communication with the edge of the Linux platform.
Versions after v2.9.0_r814 --hard 8089200 use mingw to compile the edge of the windows platform to encrypt the communication with the edge of the linux platform and then the ping fails, but the ping succeeds when using "-A1" without encrypting the communication._
</font>

======================================================

test it again.
The above statement is correct.
The way to fix it is:  Restore to the previous version ( pearson.h  &  pearson.c ).
After replacing the 2 files, everything is ok.

**Comment by Logan007** [comment]
That's a very interesting finding! :muscle: 

I suspect some byte-swapping logic error... in the new Pearson hash code. If I remember correctly, that was the upgrade from Pearson Hash to PearsonB Hash.

I will have a deeper look and might need your assistance in testing as I am absolutely inexperienced with MinGW – probably the reason, why our Building instructions does not mention it... :wink:

**Comment by skyformat99** [comment]
> That's a very interesting finding! 
> 
> I suspect some byte-swapping logic error... 

> 
> I will have a deeper look and might need your assistance in testing as I am absolutely inexperienced with MinGW – probably the reason, why our Building instructions does not mention it...

thanks,
My compile environment is  CMake+VS2015 , I do not use the MinGW.
It seems that compiling with MinGW is the same problem.
It doesn't look like it's associated with the compiler
