### ISSUE TITLE
please give us a 2.9 beta binary thank you sir

### ISSUE THREAD

**Issue by introspection3** [ntop/n2n#786]
please give us a 2.9 beta binary thank you sir,we can test it

**Comment by fengdaolong** [comment]
You can get it from [here](https://github.com/fengdaolong/n2n/releases), and it will be updated from time to time.

**Comment by fengdaolong** [comment]
@Logan007 I suggest that when the 3.0 version is released, upload the binary files of different CPU platforms to the release page, which will greatly increase users and usage.

**Comment by lucktu** [comment]
> 
> 
> @Logan007 I suggest that when the 3.0 version is released, upload the binary files of different CPU platforms to the release page, which will greatly increase users and usage.

Serious support, just like that
https://github.com/fatedier/frp/releases/tag/v0.37.1

**Comment by Ling128** [comment]
> @Logan007 I suggest that when the 3.0 version is released, upload the binary files of different CPU platforms to the release page, which will greatly increase users and usage.

can't agree more. Just wondering when 3.0 version will be released

**Comment by Logan007** [comment]
> Just wondering when 3.0 version will be released

As all mandatory action items have been checked (#562), I expect it to come sometime soon.

> upload the binary files of different CPU platforms to the release page

Not sure about the binary distribution policy.

**Comment by Logan007** [comment]
> upload the binary files of different CPU platforms to the release page

You might get fresh binaries from the Action tab page though it is a bit complicated to click through the different categories until you reach the binaries. I will try to describe:

_Actions_ --> _Testing_ --> Latest Commit (uppermost item) --> _Artifacts_ (scroll down to section) --> Download _binaries_

**Comment by Logan007** [comment]
In addition, we have just added current binaries in a [pre-release for testing](https://github.com/ntop/n2n/releases).

Credits to @hamishcoleman

**Comment by Logan007** [comment]
Considered answered, closing. Please re-open if required.
