### ISSUE TITLE
Edge is not pingable even it is seen on supernode side via NC

### ISSUE THREAD

**Issue by galaxyskyknight** [ntop/n2n#788]
@Logan007 

hi man, I got a very strange problematic edge that it could be seen from supernode side via NC status
observing, but could not be pingable from other edges and this edge's log says the supernode is not responded, I captured both edge and supernode side logs and could you kind help to diag it for me? thanks a lot. 
btw: For privacy I replaced all real public IP address to a Macro-like style in the log, for easy read, all edge 's mac address is 00:90:10:00:00:xx(and the associate static ip is 10.0.0.xx), my problemtic edge is 10.0.0.4(00:90:10:00:00:04).

thanks
[n2n_supernode.log](https://github.com/ntop/n2n/files/7163893/n2n_supernode.log)
[n2n_edge.log](https://github.com/ntop/n2n/files/7163895/n2n_edge.log)

**Comment by Logan007** [comment]
It looks as if the edge sends the REGISTER_SUPER, the supernode receives it and answers it with a REGISTER_SUPER_ACK. But the edge never reveices this REGISTER_SUPER_ACK and thus retries to register with the supernode. The supernode has seen the REGISTER_SUPER and thus keeps that edge in the list.

Firewall preventing to read the answering REGISTER_SUPER_ACK? Supernode and edge built from same code version? Have you tried `-S2` with that edge?

**Comment by galaxyskyknight** [comment]
> It looks as if the edge sends the REGISTER_SUPER, the supernode receives it and answers it with a REGISTER_SUPER_ACK. But the edge never reveices this REGISTER_SUPER_ACK and thus retries to register with the supernode. The supernode has seen the REGISTER_SUPER and thus keeps that edge in the list.
> 
> Firewall preventing to read the answering REGISTER_SUPER_ACK? Supernode and edge built from same code version? Have you tried `-S2` with that edge?

thanks for the reply. Yes, the same code.  I am trying to understand what you said and check the firewall on the router, there is no different firewall configure to the other edge running stands on 
the snap on this problematic edge 4 for iptables:(n2n eth is forwarding table and n2n net is the NAT tables )
![image](https://user-images.githubusercontent.com/66289873/133355591-5d4dca8b-877b-4d14-b771-593b6625e1a6.png)
the snap on those good edge (like edge 2) iptables:
![image](https://user-images.githubusercontent.com/66289873/133357006-8b71131e-d602-4b5f-9d34-9f01d756d0a9.png)


the only difference above is there is no forwarding traffic fro edge 4 iptables relevant policy counter , futher more I compared the good edge and bad edge(edge 4) and seems no RX traffic on n2n IF of edge 4! this is may the cause for that you mentioned why the edge not got the REGISTER_SUPER_ACK.
Edge 4: (bad one)
![image](https://user-images.githubusercontent.com/66289873/133355922-4af2028c-a8f9-497f-8739-817552edae75.png)
Edge 2(good one)
![image](https://user-images.githubusercontent.com/66289873/133355970-fa0ff2da-a38a-41e2-9cbf-7ae5ae24aa87.png)
So I have some questions here:
1. Since the firewall of Iptables among good/bad edges are the same why the bad edge's n2n TAP interface cannot receive any packets on this paticular edge? I tried what you mentioned to enable '-S2'  for TCP and didn't help(btw: if using TCP any paticuar or addition port allow policy needed for firewall setting either superndoe side or edge side? I just simply add '-S2' in edge and didn't do any other further configure). 
2.  You mentioned there is an additional mutilcast menchanism for the edge regiester and discovery,to me I would take it as a backup mechanism? but here in my snenario is that not working well when the UDP unicast fail in this case  from log?
3. I am wondering whether this is the issue relevant to the network operator side or my localside,  maybe they denied such p2p punch hole menchanism on theire edge router in upper layer? not sure, do you have any idea that how to diag this and provide a easy way to collect proof so that  I can use that escalate to them if this is the root cause? 
and I am not sure why  P2P/PSP via TCP/UDP or mutlicast but there is none of those mechanism can work so may I conclude this is the operator side problem? any other check suggestion? Looking forward to your advice.

thanks a lot.

**Comment by Logan007** [comment]
> and seems no RX traffic on n2n IF of edge 4! this is may the cause for that you mentioned why the edge not got the REGISTER_SUPER_ACK.

The REGISTER_SUEPR_ACK needs to be received on the real network.

> Since the firewall of Iptables among good/bad edges are the same why the bad edge's n2n TAP interface cannot receive any packets on this paticular edge?

If the edge has not at all registered to a supernode yet, it might not accept any packets, not sure here. I remember ignoring packets before first supernode registration.

> I tried what you mentioned to enable '-S2' for TCP and didn't help(btw: if using TCP any paticuar or addition port allow policy needed for firewall setting either superndoe side or edge side? I just simply add '-S2' in edge and didn't do any other further configure).

Just add `-S2` to the command. I asked you to do it because it usually gets through a lot more firewalls.... if the firewall is the issue here. Cannot really say because it is strangely not working.

> You mentioned there is an additional mutilcast menchanism for the edge regiester and discovery,to me I would take it as a backup mechanism? but here in my snenario is that not working well when the UDP unicast fail in this case from log?

It only works inside your local network. Edges should detect themselves if no router between them (usually inside same broadcast domain). It is disabled if used with `-e ....`. But if no supernode registration, the edges probably cannot communicate.

So, do the edges share the same local network?

> I am wondering whether this is the issue relevant to the network operator side or my localside, maybe they denied such p2p punch hole menchanism on theire edge router in upper layer? not sure, do you have any idea that how to diag this and provide a easy way to collect proof so that I can use that escalate to them if this is the root cause?

This is a bit unlikely because the register  is just back-and-forth UDP. And even TCP did not work. Which is strange... 

> and I am not sure why P2P/PSP via TCP/UDP or mutlicast but there is none of those mechanism can work so may I conclude this is the operator side problem? any other check suggestion? Looking forward to your advice.

... but you might want to try to change supernode port to 80 or 443 and test TCP `-S2` again. Maybe, "unusual" ports are being blocked? It would not really explain the working one-way REGISTER_SUPER and REGISTER_SUPER_ACK being stuck on its way back.

**Comment by galaxyskyknight** [comment]
this issue resolved by replace with another router,I believe it is relevant to the configuration on this openwrt route, I will double check what's going on.

**Comment by Logan007** [comment]
> this issue resolved by replace with another router

Closing then. Please re-open if required.
