### ISSUE TITLE
Hopefully, we'll get a message from supernode

### ISSUE THREAD

**Issue by lucktu** [ntop/n2n#789]
By "netcat -u 127.0.0.1 xxxx"

For example, detailed version information, runtime, and what supernoder wants to say.
Especially for edge, so that we can correctly choose a better supernode.

**Comment by skyformat99** [comment]
It's not safe enough.

If you really want to do this, you can modify it like this
file  sn.c   line 605
sss_node.mgmt_sock = open_socket(sss_node.mport, INADDR_LOOPBACK, 0 /* UDP */);
.========>
sss_node.mgmt_sock = open_socket(sss_node.mport, INADDR_ANY, 0 /* UDP */);

**Comment by lucktu** [comment]
Doesn't seem to increase the risk. please discuss it.

This idea is based on the two points,
1, n2n changes, some new features is no longer supported by old supernode, this helps to eliminate some problem.
2, if my service(supernode) falls to a end, I also have a way to tell some users. I don't think that one is necessary.

**Comment by Logan007** [comment]
> please discuss it

I love discussions... :wink:

... and I think both of you are right!

> n2n changes, some new features is no longer supported by old supernode, this helps to eliminate some problem

The management port currently only binds to localhost, so it only is accessible to a person logged into the machine, be it locally or remotely. Such a person also could find out edge / supernode version by just running the executable from command prompt. So, I do not have any objections against outputting the version information and run-time _to the management port_. We certainly can do that!

> It's not safe enough.

What I would not want to change is the binding to localhost because of the sensitive nature of displayed information but also because of commands the supernode can or will accept (one day) through the management port.

Furthermore, we still have some kind of (not completely) silent behavior so no-one shall be able to detect if a supernode is running or not by port-scanning or so.

**Comment by lucktu** [comment]
"_Furthermore, we still have some kind of (not completely) silent behavior so no-one shall be able to detect if a supernode is running or not by port-scanning or so_", that's something to look forward to.

This idea is based on the two points (It's updated. easy to understand),
1, N2n changes, some new fetures is not supported by old supernode, this information helps to eliminate some problem.
2, If I wanted to stop supernode at some point in the future, I also have a way to tell my users (_but I don't think the one is necessary_).

Looking at these v2 of supernodes, it's confusing to not know if they're a modified version. because they're probably not the final version.
http://supernode.ml/

**Comment by Logan007** [comment]
I still am not sure if I understand correctly...

You _locally_ want some information about a supernode to publish it on the web page, such as version information and some other message?

If yes, we could think about some script such as `echo $(./edge --help 2&> >(grep Welcome))`. The web server could execute this command and publish the information on the web page. Also, we could extend management port output by version, up-time etc. if we keep it limited to _localhost_.

If you aim at opening a port to the world to share this information, you'd see me very reluctant. Especially for public messages on some port, I'd probably point you to "Quote of the Day" service.

**Comment by lucktu** [comment]
Oh, no, I just wish I could see it from my edge.

**Comment by Logan007** [comment]
We can talk about in-band information, after having successfully registered to a sueprnode. Some "peer info" on the supernode... 

This reminds me of one thing I still wanted to do even though it might break packet format again :wink: I want to separate the PING which currently is used as sub-type of PEER_INFO from it and make it its own message type. That might give some room to think about extending PEER_INFO to supernodes...

**Comment by fengdaolong** [comment]
These are inevitable when supernode and edge are merged in the future. Between them there is me in you, and you in me, basically there is no boundary between them.😏️

**Comment by Logan007** [comment]
So, we could add some information to the PONG message.

What information do you suggest?

- `char*[20]` excerpt of `GIT_RELEASE` macro, found at `include/config.h`?
- uptime as `uint32_t` in seconds? 

Parsing and storing would happen around `src/edge_utils.c:2812`. Output could happen to the management port, making the lines somewhat longer...

**Comment by lucktu** [comment]
EDGE GETS INFORMATION FROM SUPERNODE, LIKE THIS: 

1.  n2n v.2.9.0.r977.9c22d28
2.  up 9 days,  6:52

**Comment by fengdaolong** [comment]
Display the known number of edges for the supernode?

**Comment by lucktu** [comment]
I do not recommend displaying this information: "the known number of edges for the supernode"

But, can display a news from supernode, for example: service will end on January 1,2022.

**Comment by Logan007** [comment]
Do you think that #796 addresses this issue in an appropriate way?

> But, can display a news from supernode, for example: service will end on January 1,2022.

This would need top be transmitted over and over again with every PONG answer from every supernode to every edge every 30 seconds. It might sum up... If the 19 (+1) version field is long enough for your message, we might add (yet) another optional command line parameter to override the version text...

**Comment by lucktu** [comment]
#796  is enough.
"display a news" doesn't matter. Just do it for easy or don't do it. 

Do not be too complex, so as to affect the efficiency of n2n.

**Comment by lucktu** [comment]
I already tested it.  
Incompatible with previous information, it is recommended to place it separately under"===".
or SUPERNODES ---> SUPERNODES ( VERSION:2.9.0.r982.e924302  /  UPTIME: 9 days, 14:16 )

**Comment by Logan007** [comment]
> it is recommended to place it separately under"===".

In federations, we would list all supernodes again, each of them with a new line.

I will merge soon, the format can be changed later. Most important thing now is that the protocol is defined.

**Comment by lucktu** [comment]
It was so long that it crashed through my screen, it's probably better this way?

`   1 | -l  >>>>>       | 0A:C2:32:09:F0:20 | 120.175.20.130:10090  | load =        0 |        29 | 2.9.0.r982.e924302   |      23938` 

to

`   1 | ver: 2.9.0.r1982 | 0A:C2:32:09:F0:20 | 120.175.20.130:10090  | uptime: 10009 days, 20:43 `

![image](https://github.com/lucktu/other/raw/master/image/2021/21091701.PNG)

Even，you can take out the "uptime ... ...".

**Comment by Logan007** [comment]
I will have another look.

**Comment by lucktu** [comment]
Well, this is embarrassing, ... (1024x768)
![image](https://github.com/lucktu/other/raw/master/image/2021/21091702.png)

**Comment by lucktu** [comment]
Thank you! 
![image](https://github.com/lucktu/other/raw/master/image/2021/21091801.png)

![image](https://github.com/lucktu/other/raw/master/image/2021/21091802.png)

**Comment by lucktu** [comment]
**It's amazing. It's all done, I just found out. Thank you so much!!**

![image](https://github.com/lucktu/other/raw/master/image/2021/21092001.png)

Look at your code so simple, did not expect so powerful, programming is a very good thing!
