### ISSUE TITLE
some error message

### ISSUE THREAD

**Issue by skyformat99** [ntop/n2n#799]
After the #796 modification, there were some contradictory messages

1)
./supernode  -V  
17/Sep/2021 15:35:59 [sn_utils.c:241] **WARNING: File xxx not found**

2) ./supernode -h
options for under-        [-l <supernode host:port>]
 lying connection         ' [-M] [-V  <  version text  >] '

3) ./supernode -v
[root@demo]#
[root@demo]# ps axu |grep supernode
nobody   18315  0.0  0.0  11456  2432 ?        Ssl  15:33   0:00 ./supernode -V

 It run with a lowercase 'v'  ,  When ps checks, it changes to a capital ‘V’,  And the process  actually run?

**Comment by lucktu** [comment]
But there's nothing wrong with mine. Everything's fine in ubuntu18.

root@xxx:/opt# supernode3 -v
root@xxx:/opt# supernode3 -V
supernode3: invalid option -- 'V'

root@xxx:/opt# ps -ax|grep super
29836 ?        Ssl    0:00 supernode3 -v
