### ISSUE TITLE
Killing an edge node crashes the supernode

### ISSUE THREAD

**Issue by mginster** [ntop/n2n#80]
Machine A: running supernode AND edge node
Machine B: running edge node

Close Machine B edge node.  Supernode will crash on Machine A.

**Comment by emanuele-f** [comment]
What operating system are you using? Are you using latest n2n code from github?

**Comment by mginster** [comment]
Win10Pro for both machines.  It was using the latest code as of yesterday.  I compiled it to remove encryption and compression fyi.

**Comment by mginster** [comment]
[CMakeLists.txt](https://github.com/ntop/n2n/files/2989390/CMakeLists.txt)

[n2n.h.txt](https://github.com/ntop/n2n/files/2989395/n2n.h.txt)

**Comment by emanuele-f** [comment]
Cannot reproduce, supernode continues to run even if the nodes are stopped. Please try to build the unmodified version from github, following the steps in https://github.com/ntop/n2n/blob/dev/doc/Windows.md

**Comment by emanuele-f** [comment]
Oh wait, I can actually reproduce it sometimes, the supernode dies with `ERROR: recvfrom() failed -1 errno 0 (No error)`, is this the same error you get?

**Comment by emanuele-f** [comment]
I've made this fix, let me know if it works: 03761fc84cd05dd1712eb6c9f01ec4dff6723518

**Comment by emanuele-f** [comment]
Should you experience the issue again, please reopen
