### ISSUE TITLE
Incomplete modification: "Fix build error when libcap-dev is installed"

### ISSUE THREAD

**Issue by lucktu** [ntop/n2n#803]
It is correct when I compile as follows, no error prompt, ( #798 )
./autogen.sh
./configure
make

When compiled this way, however, the error message is still present,
cmake ./
make

Sorry to see that, this is't a good news for cross-compiling. 
 #795

**Comment by lucaderi** [comment]
I have just tested it (Debian 9) and it compiled. Please provide a complete trace of the problem

**Comment by lucktu** [comment]
I compiled in  Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-81-generic x86_64).  

n2n v.2.9.0.r987.d4e0f5a for Linux
![image](https://github.com/lucktu/other/raw/master/image/2021/21091803.png)

Process:  https://github.com/lucktu/other/blob/master/image/2021/21091801_ERROR
Update supernode of "supernode.ntop.org:7777", please.

 Thanks.

**Comment by hamishcoleman** [comment]
Hi @lucktu, I've just had a look at commit 0e48e2f24c33391ab9a0b73e5fba636089cabbfb when support for libcap was first added and it looks like it was never added to the cmake files and the run-time informative warning message you have outlined above has been happening for over a year.

**Comment by lucktu** [comment]
@hamishcoleman , Thank you very much for your patience and that you showed me more of the truth.

I've found a way. just make the following changes in CMakeLists.txt.
OPTION(N2N_OPTION_USE_PCAPLIB "USE PCAP Library" ON)

But there are problems with cross-compiling, so I'll work on that some other time

**Comment by lucktu** [comment]
But there are problems with cross-compiling, so I'll work on that some other time.
