### ISSUE TITLE
Is there any Android n2n client which could catch up the features developed on the latest code here?

### ISSUE THREAD

**Issue by galaxyskyknight** [ntop/n2n#804]
I know there is an Android client project on Github, howerver looks its development is half-abandom status which cannot catch up the code development here, thus a lot of adanvaced feature (like subnet routing/mutiple gateway/header encryption, federation .....configure with -I/-J/-n etc....) stands on supernode/edge is not compatiable to that Android client, I am running all well on both windows PC/linux openwrt router/and linux server with the latest code here but except the mobile Andriod client(no wonder to IOS.....)  and not want to go back, if the android client can support that it will be greate convinence for me to get management access to those devices on my mobile phone....so if there is anyone could be so kind to develop such features or enahance it on the Andriod client ? @lucktu ?:)

**Comment by lucktu** [comment]
I'm sorry, I'm not a programmer, and I'm powerless.

You can try compiling the latest n2n for android yourself.
https://github.com/lucktu/dockcross

I've compiled the latest hin2n for android.
https://github.com/lucktu/n2n/tree/master/Android/Client/noroot

In addition, my friends are developing hin2n for iphone.

**Comment by galaxyskyknight** [comment]
> I'm sorry, I'm not a programmer, and I'm powerless.
> 
> You can try compiling the latest n2n for android yourself.
> https://github.com/lucktu/dockcross
> 
> I've compiled the latest hin2n for android.
> https://github.com/lucktu/n2n/tree/master/Android/Client/noroot
> 
> In addition, my friends are developing hin2n for iphone.

Yes, I know this project, the problem is the code base not catch up here with those adavanced feature merged as I illustrated above, also no configuration opntions for them on the GUI of this client(or specified the parameters by manual configuration file as workaround even suppose the backend has the code support) , that's my suffering point. Anyway, thanks, If someone can help to merge those advanced features' code to 'v3' version options  and make them configurable on the Android GUI, that's will be so apperciate for me.

**Comment by lucktu** [comment]
In the absence of a better solution, you can use edge.

**Comment by Oliver0624** [comment]
As there is no stable version of n2n v3.0, any adapt work will be easily out-of-dated.
In fact, the latest code of n2n cannot pass the compilation when It is included in hin2n project.
In my opinion, I will try to do adaption as soon as release of v3.0, but not now. @galaxyskyknight .

**Comment by Logan007** [comment]
Considered answered, please refer to the other project site.

**Comment by YCJDWCJI** [comment]
If you have ROOT, you can use `termux`.

```Bash
pkg update
pkg install n2n
sudo edge -f -c xxx -l 1.1.1.1:111 -a 10.10.10.10……
```
