### ISSUE TITLE
2.9 windows supernode bug :can not change -f -p position

### ISSUE THREAD

**Issue by introspection3** [ntop/n2n#808]
![image](https://user-images.githubusercontent.com/12368358/134320656-196f527d-2a8f-4895-ac4f-770f6c1087ba.png)

**Comment by Logan007** [comment]
`-f` is not for federation. `-f` is for _foreground_ execution and is not available on Windows. Please do not use `-f` on Windows, the supernode then can parse the following `-p` correctly.

**Comment by Logan007** [comment]
>  `-f` is for foreground execution and is not available on Windows

Considered solved. Please re-open if required.
