### ISSUE TITLE
Automated Random Key Schedule

### ISSUE THREAD

**Issue by Logan007** [ntop/n2n#81]
The edges could use Diffie-Hellmann key generation to create random keys for node-to-node communication, leaving broadcasts encrypted using the pre-shared key.    These keys could be valid for a certain time span before the new ones are automatically regenerated.  The time interval could depend on available performance and degree of paranoia.  A relatively fast change of random keys enormously increases security.

To prevent man-in-the-middle attacks, this feature requires that communication is authenticated by some message authentication code, like in the revamped AES example. The authentication needs a signature/encryption step using a key, e.g. the secret pre-shared key.

The public prime p and the public generator g could be published by the supernode, signed / authenticated by the secret pre-shared key.

An even further security enhancement would be an automatism to replace p and g from time to time.  A good way of achieving this would be the edges to generate a new 4096-bit p and g alongside and with low priority - not to generate too heavy workload at a time. After authentication using the pre-shared key, it could be published to the supernode.

The whole feature would need extensions to the main protocol as well as the need to agree on one authentication algorithm (hash + encrypt with TF **or** AES **or** maybe something completely different) for that purpose. Which would be a good idea anyway, see #82.

**Comment by emanuele-f** [comment]
Please note that in the design of n2n, the supernode is just a relay of packets, it should not participate in encryption.

**Comment by Logan007** [comment]
That is a good point.  Shall this hold true also for public keys or public parts where the supernode would keep more like a directory functionality?

This might need some "in-band communication"... still thinking. Maybe for AES V3?

**Comment by emanuele-f** [comment]
Public key crypto is a requirement for #30, however random key schedule only requires some form of encryption (e.g. existing AES) for the key negotiation right? Also in a context of public key crypto, I think not relying on the supernode is a better approach for n2n, see the example of ssh in the linked issue.

**Comment by Logan007** [comment]
If _p_ and _g_ in Diffie-Hellmann are chosen wisely and big enough, they do not need to be changed yet they are public. Then, they could even be hardcoded in all the edges. That would avoid the supernode.

A possible V3 AES encryption scheme could then flag packets in a certain way to indicate an additional special payload, namely _(g ^ a)_ or _(g ^ b)_ respectively. This definitely should build upon the V2 features such as replay attack prevention and reliable message authentication, these are mandatory prerequisites.

**Comment by Logan007** [comment]
Having header encryption in place, I do not think that this is required anymore. Closing.
