### ISSUE TITLE
sir community.list can limit the communities which only be known by my own ,but my edge process will use  command

### ISSUE THREAD

**Issue by introspection3** [ntop/n2n#815]
sir community.list can limit the communities which only be known by my own ,but my edge process will use  command to start,
so my users can see the commutiy name by ps -ef |grep edge,
can I hide this?

**Comment by Logan007** [comment]
You can use [configuration files](https://github.com/ntop/n2n/blob/dev/doc/ConfigurationFiles.md).

**Comment by lucktu** [comment]
edge.config, do you know? 

For example,  
edge arpc    /     /usr/sbin/acpic arpc (rename: edge --> acpic, edge.config --> arpc )

**Comment by introspection3** [comment]
@Logan007 maybe an env is better,just like N2N_KEY

**Comment by Logan007** [comment]
> maybe an env is better,just like N2N_KEY

Yes, it would be nice to have. On the other hand. it would hit some more command line options such as `-J`... so, I consider this a bigger change. From my point of view, I do not see it before 3.2.

**Comment by introspection3** [comment]
> > maybe an env is better,just like N2N_KEY
> 
> Yes, it would be nice to have. On the other hand. it would hit some more command line options such as `-J`... so, I consider this a bigger change. From my point of view, I do not see it before 3.2.

I will add this function

**Comment by introspection3** [comment]
@Logan007 please check and merge it
add env for community_name just like N2N_KEY ,use N2N_CMTY

**Comment by Logan007** [comment]
Thank you, I will have a look.

**Comment by introspection3** [comment]
@Logan007 sir,on windows the fact is:
when ctrl+c,the  send_unregister_super(eee); must be called first,I have pull requested,but I think you can make the code better,so 
,how I will you would add this function other than 

![image](https://user-images.githubusercontent.com/12368358/134766837-a643dc46-b074-4d43-a39f-0bdbb60fb506.png)
can't work immediately

**Comment by Logan007** [comment]
By the way, I am not sure for the reasons of Windows version behavior. But from my experience, sending _CTRL_ + _C_ or _SIGINT_ **twice** should always end the edge.

**Comment by Logan007** [comment]
Another by the way... while working through that other pull request, I saw that your fork might need a `fetch upstream` to catch up with the latest _dev_...

**Comment by introspection3** [comment]
@Logan007 the reason why [[ when ctrl+c,the send_unregister_super(eee); must be called first]]
is that send_unregister_super will not called immediatelty  on windows

**Comment by Logan007** [comment]
> the send_unregister_super(eee); must be called first

Yes, current dev has it integrated now. It should at least counter the authentication error you observed.

Then, Windows edge's blocking at the end is some other issue I am not able to fully understand yet. But again, sending SIGINT **twice** (allow for a little sleep in between) should always work.

**Comment by introspection3** [comment]
ok,let's watch it

**Comment by Logan007** [comment]
So, does it work when sending two SIGINTs or press CTRL + C twice?

**Comment by Logan007** [comment]
Considered answered, please re-open if required.
