### ISSUE TITLE
sir ,how we can judge client 2 client is p2p or psp with version 2.9

### ISSUE THREAD

**Issue by introspection3** [ntop/n2n#816]
sir ,how we can judge client 2 client is p2p or psp with version 2.9

**Comment by lucktu** [comment]
edge ... ...  -v

Look at the output of edge, if show P2P is a p2p, show PSP is forwarding.
or
It shows the ip of supernode which is the forwarding.

**Comment by introspection3** [comment]
![image](https://user-images.githubusercontent.com/12368358/134519974-3dfe10bf-42ea-40c9-a03c-983692f2e012.png)
what's wrong @Logan007

**Comment by Logan007** [comment]
Looks like the connection to a local peer (`192.168.1.4`) switching back and forth between the direct, local address and the corresponding external, forwarded port. You router obviously supports hair-pinning and maps it back to the local address.

This is nothing to worry about even though it is not too beautiful.

You could try `-e auto` at all edges of that LAN and see if you get better behavior.

**Comment by Logan007** [comment]
> sir ,how we can judge client 2 client is p2p or psp with version 2.9

You could have a look at the [management port output](https://github.com/ntop/n2n/blob/dev/doc/Faq.md#how-can-i-know-if-peer-to-peer-connection-has-successfully-been-established).

**Comment by Logan007** [comment]
> edge ... ... -v

>  management port output

Considered answered, please re-open if required.
