### ISSUE TITLE
Hoping to get into upnp

### ISSUE THREAD

**Issue by lucktu** [ntop/n2n#817]
This will increase the rate of p2p.
https://github.com/miniupnp/miniupnp

Thanks!

### If you have any ideas, go over here please #147

**Comment by Logan007** [comment]
Thank you for the pointer, it has already been mentioned [here](https://github.com/ntop/n2n/issues/562#issuecomment-761186474).

UPnP support still is an open [action item](https://github.com/ntop/n2n/issues/562#issue-774467229) and has also been discussed at #147. I therefore consider this a duplicate.

As it might become a hard-to-follow topic when wide-spread, please keep the discussion somewhat contained to one of the above mentioned. Thank you!

**Comment by lucktu** [comment]
"it might become a hard-to-follow topic when wide-spread"?

I still don’t understand what this means. Something this good should be in it.

Anyone else have an opinion?

**Comment by skyformat99** [comment]
Lightweight is the best mark for N2N,  because there are so many embedded features to use.

if  increase the rate of p2p,  can use KCP with only two files：
https://github.com/skywind3000/kcp

**Comment by lucktu** [comment]
> 
> 
> Lightweight is the best mark for N2N, because there are so many embedded features to use.
> 
> if increase the rate of p2p, can use KCP with only two files：
> https://github.com/skywind3000/kcp

Can you put it in your repositorie(or a new pull) that let us to test?
It seems that kcp only improves the transmission quality, not increase the rate of p2p.

In addition, the size of upnpc-static is only 82KB.

**Comment by Logan007** [comment]
>  Something this good should be in it.

Yes, I fully  agree. And I am not speaking against it.

> what this means

I am just saying that we should not discuss UPnP across two or more different issues because the UPnP discussion is hard-to-follow then. Perhaps, we can discuss it at #147 or #562?

**Comment by lucktu** [comment]
Actually, it's pretty clear what that means. There's nothing to discuss.

**Comment by Logan007** [comment]
> Actually, it's pretty clear what that means. There's nothing to discuss.

No, it does not mean that there is nothing to discuss.

Au contraire, I would gladly discuss how to implement UPnP support.

I just think that topics should be discussed at **one** place (one Issue), and not in two or more. That's all I kindly ask for... just for the sake of being able to keep and later find or retrieve information at **one** place... (and not at two or more).

**Comment by skyformat99** [comment]
> > Actually, it's pretty clear what that means. There's nothing to discuss.
> 
> No, it does not mean that there is nothing to discuss.
> 
> Au contraire, I would gladly discuss how to implement UPnP support.
> 
> I just think that topics should be discussed at one place (one Issue), and not in two or more. That's all I kindly ask for... just for the sake of being able to keep and later find or retrieve information at one place... (and not in two or more).

agree,
close it  ^_^

**Comment by lucktu** [comment]
Without a post like mine as a guide, that post is nowhere to be found

### If you have any ideas, go over here please #147
