### ISSUE TITLE
Message Authentication for Whole Packet

### ISSUE THREAD

**Issue by Logan007** [ntop/n2n#82]
As stated in various other posts, message authentication is a feature well worth to consider.  Instead of leaving that to the respective transform-implementations, a whole-packet apporach should be considered taking also the unencrypted MACs into account.

That would require to hash the whole packet and sign the hash or  just encrypt that hash using secret pre-shared key derivate, e.g. the second half of the SHA512ed input key. This feature also requires to agree on one encryption method for signing/authenticating (TF, AES, somethin else...). 

In case of NULL transform, just hash without encryption.

**Comment by emanuele-f** [comment]
Can you please recap the benefits of implementing message authentication over the current AES implementation? I'm reading that [malleability](https://en.wikipedia.org/wiki/Malleability_(cryptography)) could be a potential issue if the attacker manages to assemble multiple cyphertexts in a new one. However, after the changes in bb07f0426e6b83e8851307590620245a6950f80b, this should be more difficult as the cyphertext is now bound to the IV in use, so the modified parts of the cyphertext would be decoded to invalid values by the receiver.

**Comment by Logan007** [comment]
A message authentication code (MAC, for this post) makes sure (as sure as it allows), that the message has not been altered.

As CBC decryption is not as chained as the encryption but could be considered more parallel, even a correctly decrypted last block with some padding length in it does not guarantee that the packet has no changes in its middle. It just means that the last cipher block and the cipher block before probably were not altered on their way.

Also, the packet could just be changed by appending more blocks as there is no length control. There is a chance of 15 / 256 that the last byte gets decrypted to a valid padding-length byte (1 through 15 make sense only). So far, the padding follows W3C padding scheme which does not allow for verification of the padding itself. Another scheme (ANSI, PCKS5, ...) with well defined padding pattern could lower these chances to something probably between 1 / 256 and 2 / 256 - which is still somewhat high. This would not be of any concern when using a MAC.

You are right, another packet that was created under a different IV would not properly decrypt nor would a randomly altered packet. It would result in garbage in the middle or the end of the payload. That is something an attacker might want to do to disturb the user. And it could be detected and prevented by using a MAC.

We could just use a MAC (minimum of 8 bytes recommended by government entities, better 12 or above, I could live with 4 for encryption scheme 1) for the whole packet (including outer and inner headers) for verification. Even padding scheme could remain the same. Every packet not matching its MAC needs to be discarded.

The CBC-MAC seems to be suitable as (at least for generation) it is already almost completely calculated for the probably longest part of the whole packet. That could be XORed to some hash of the remaining parts of inner and outer packet before it gets encrypted with AES128/ECB as a single block using the "signature key". The result could be cut down to the length needed. A full hash on the complete packet (leaving out the MAC field, of course, maybe set to zero) followed by one encryption step afterwards would probably be more expensive in terms of performance... but that's just a guess.

**Comment by Logan007** [comment]
I just want to add that we might not really need to do a cryptographically secure hash as we do not and do not need to prove anything to anybody while the "message to be verified" is not present (_verification_ – in its purest sense – purpose of cryptographic hash). In the n2n scenario, possession of the correct key is proven by en-/decrypting correctly.

So, what's left of a MAC's purpose is that we just want to make sure that the message has not been altered. Also, we want to make sure that no easy collision could be intentionally be injected without knowing the key¹. 

Therefore, a simple checksum would do. For that purpose, I would refrain from CRC32 (too collidy) even though it is guaranteed to indicate up to 31 errors. But a simple hash function (non-cryptographic) would do.

I recently came across [Pearson Hashing](https://en.wikipedia.org/wiki/Pearson_hashing) which could easily be extended to a reasonable tag size, for example 32 bit. Plus, we have the opportunity to make the permutation key-dependent (once during key-setup, no impact during hashing) and thus delivering a key-dependent hash of the plain text to put somewhere in the header. That should already be quite sufficient. But then, on top, if we additionally encrypt the whole header... (still working on #198).

I plan to bring forward a sample implementation. Any advice concerning the tag size?

¹ you could add "in a certain timeframe" if we also had replay-protection
