### ISSUE TITLE
AES psk setup: possible security issue in dev branch

### ISSUE THREAD

**Issue by Logan007** [ntop/n2n#83]
While working on the implementation of aes v2 and especially compatibility towards v1, I started thinking over line 418 in transform_aes.c:

```
memcpy(keybuf, padded_keybuf, pstat);
```
This might cause a huge security issue, allowing everybody to decrypt the packages using the zero-key in one of the three keysizes (128,192,256 - seem to deliver different results) or just any key added via setup_aes_key.

I suggest to apply the attached [patch](https://github.com/ntop/n2n/files/3000787/fixSetupAesKey.txt) to dev branch builds.

**Comment by emanuele-f** [comment]
Fixed in c71f629d1b9f34cf0b80556791e563b167bfa0ba. This was a severe security bug, the key (used both for aes and twofish) was zeroed, making it useless. This was introduced in 37233553a451df6caa3895c6197c1f8cf779cc11 . Thank you for reporting!
