### ISSUE TITLE
Unable to communicate with supernode

### ISSUE THREAD

**Issue by guojiazhuxi** [ntop/n2n#838]
I don't know why. Please help me

10月 04 17:02:20 localhost.localdomain systemd[1]: Started n2n edge process.
10月 04 17:02:20 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:20 [edge_utils.c:3753] adding supernode = xxxx
10月 04 17:02:20 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:20 [edge_utils.c:3753] adding supernode = xxxx
10月 04 17:02:20 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:20 [edge_utils.c:3753] adding supernode = xxxx
10月 04 17:02:20 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:20 [edge.c:1020] WARNING: switching to AES as key was provided
10月 04 17:02:20 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:20 [edge.c:1060] starting n2n edge 2.9.0 Oct  3 2021 03:00:51
10月 04 17:02:20 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:20 [edge.c:1066] using compression: none.
10月 04 17:02:20 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:20 [edge.c:1067] using AES cipher.
10月 04 17:02:20 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:20 [edge_utils.c:392] number of supernodes in the list: 3
10月 04 17:02:20 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:20 [edge_utils.c:394] supernode 0 => xxxx
10月 04 17:02:20 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:20 [edge_utils.c:394] supernode 1 => xxxx
10月 04 17:02:20 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:20 [edge_utils.c:394] supernode 2 => xxxx
10月 04 17:02:20 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:20 [transform_aes.c:210] setup_aes_key 128-bit key setup completed
10月 04 17:02:20 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:20 [edge_utils.c:483] successfully created resolver thread
10月 04 17:02:20 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:20 [edge.c:1091] use manually set IP address
10月 04 17:02:20 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:20 [edge_utils.c:265] binding to local port 47778
10月 04 17:02:20 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:20 [edge_utils.c:312] PMTU discovery disabled
10月 04 17:02:20 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:20 [edge_utils.c:1185] send PING to supernodes
10月 04 17:02:20 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:20 [edge_utils.c:1041] sent=38 to
10月 04 17:02:20 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:20 [edge_utils.c:1041] sent=38 to
10月 04 17:02:20 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:20 [edge_utils.c:1041] sent=38 to
10月 04 17:02:20 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:20 [edge.c:1128] send PING to supernodes
10月 04 17:02:23 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:23 [edge.c:1146] PONG timeout
10月 04 17:02:23 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:23 [edge_utils.c:1185] send PING to supernodes
10月 04 17:02:23 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:23 [edge_utils.c:1041] sent=38 to
10月 04 17:02:23 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:23 [edge_utils.c:1041] sent=38 to
10月 04 17:02:23 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:23 [edge_utils.c:1041] sent=38 to
10月 04 17:02:23 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:23 [edge.c:1128] send PING to supernodes
10月 04 17:02:25 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:25 [n2n.c:288] supernode2sock successfully resolves supernode IPv4 address for xxxx
10月 04 17:02:25 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:25 [n2n.c:288] supernode2sock successfully resolves supernode IPv4 address for xxxx
10月 04 17:02:25 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:25 [n2n.c:288] supernode2sock successfully resolves supernode IPv4 address for xxxx
10月 04 17:02:26 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:26 [edge.c:1146] PONG timeout
10月 04 17:02:26 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:26 [edge_utils.c:1185] send PING to supernodes
10月 04 17:02:26 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:26 [edge_utils.c:1041] sent=38 to
10月 04 17:02:26 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:26 [edge_utils.c:1041] sent=38 to
10月 04 17:02:26 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:26 [edge_utils.c:1041] sent=38 to
10月 04 17:02:26 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:26 [edge.c:1128] send PING to supernodes
10月 04 17:02:29 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:29 [edge.c:1146] PONG timeout
10月 04 17:02:29 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:29 [edge_utils.c:1185] send PING to supernodes
10月 04 17:02:29 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:29 [edge_utils.c:1041] sent=38 to
10月 04 17:02:29 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:29 [edge_utils.c:1041] sent=38 to
10月 04 17:02:29 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:29 [edge_utils.c:1041] sent=38 to
10月 04 17:02:29 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:29 [edge.c:1128] send PING to supernodes
10月 04 17:02:32 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:32 [edge.c:1146] PONG timeout
10月 04 17:02:32 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:32 [edge_utils.c:1185] send PING to supernodes
10月 04 17:02:32 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:32 [edge_utils.c:1041] sent=38 to
10月 04 17:02:32 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:32 [edge_utils.c:1041] sent=38 to
10月 04 17:02:32 localhost.localdomain edge[125329]: 04/Oct/2021 17:02:32 [edge_utils.c:1041] sent=38 to

**Comment by Logan007** [comment]
What is the exact `edge` command line? And what OS?

**Comment by guojiazhuxi** [comment]
centos7.9

**Comment by guojiazhuxi** [comment]
> What is the exact `edge` command line? And what OS?

centos7.9

**Comment by guojiazhuxi** [comment]
> What is the exact `edge` command line? And what OS?



> What is the exact `edge` command line? And what OS?

I’ve been using it stably for a few months and I suddenly can’t use it today.

**Comment by Logan007** [comment]
> I’ve been using it stably for a few months and I suddenly can’t use it today.

So, no changes to your setup?

What exact version? (just run `edge`, it shows the r....`)

Are you in control of all your supernodes and edges? Are they all the same version?

If your version already supports TCP, you could try `-S2` at the edges to test TCP, just to make sure that your firewall policies have not changed to block UDP.

**Comment by guojiazhuxi** [comment]
Nothing has changed, I will test the test, find out the problem and ask for your feedback. Thanks!

**Comment by Logan007** [comment]
Is this still an issue?

**Comment by Logan007** [comment]
Considered deprecated, please re-open if required.
