### ISSUE TITLE
Ambiguous version

### ISSUE THREAD

**Issue by emanuele-f** [ntop/n2n#84]
Running `./edge --help` shows an ambiguous `v.2.5.0` version. The n2n version should be based on the current git commit and should be unified with the repository package version.

**Comment by emanuele-f** [comment]
Fixed. Now full version `2.5.1.r198.4d36f9f` is shown. Version increased from `2.5.0` to `2.5.1` as revision number (198) is now lesser than the previous one (as `git rev-list --all` has been changed to `git rev-list --count HEAD` which is better since it only takes into account the current branch)

**Comment by lucktu** [comment]
Thank you!
