### ISSUE TITLE
 license exception for n2n ?

### ISSUE THREAD

**Issue by Oliver0624** [ntop/n2n#848]
@Logan007 
My colleague and I are developing hin2n-ios, an implementation of n2n on iOS platform and it is nearly completed.

But there are two problems. 
First, Apple APP Store will refuse any GPL software. 
Second, we want to do some custom work to adapt our running platform.

So we want to buy a license exception for hin2n-ios, is it possible ? ( Still we will open the source code of a public version of our software. )

**Comment by Logan007** [comment]
Thank you for raising the question. 

n2n is under GPL3 with all its consequences and everything that comes along with it. I am not sure if anyone could buy a license exception from it – especially for work that has already been done and published under GPL3.

I will escalate your question to @lucaderi for further consideration.

**Comment by lucaderi** [comment]
What is a license acceptable for both you and Apple?

**Comment by Oliver0624** [comment]
What we want is BSD, MIT, Apache License or LGPL license.
While Apache license surely can be applied to iOS app, I'm not sure whether the others are acceptable by Apple. 
I'm still googling...

**Comment by Oliver0624** [comment]
According to this [page](https://opensource.stackexchange.com/questions/12201/how-to-make-my-ios-project-source-closed-while-it-must-use-open-source-code), It looks like MIT and Apache license are both acceptable by Apple.

But to get a license exception we need permissions from ALL contributors. Which is extremely difficult.  
@Logan007 Is there any ways to get every contributor's permissions ?
Or is there a CLA which allows the maintainers to provide a license exception ?

**Comment by Logan007** [comment]
> But to get a license exception we need permissions from ALL contributors.

Oh.

> Which is extremely difficult.

I share this rating.

> @Logan007 Is there any ways to get every contributor's permissions ?

I did not know if calling everyone here (see [_Contributors_](https://github.com/ntop/n2n/graphs/contributors) page) would actually reach them and would be sufficient.

> Or is there a CLA which allows the maintainers to provide a license exception ?

@lucaderi ?

**Comment by Oliver0624** [comment]
@Logan007 
I've given up to publish in Apple app store. Here is the codes : https://github.com/oliver0624/hin2n-ios

**Comment by Logan007** [comment]
Thank you for trying! :orange_heart:
