### ISSUE TITLE
link error in windows platform

### ISSUE THREAD

**Issue by zwh6611** [ntop/n2n#85]
1>edge.obj : error LNK2019: unresolved external symbol _run_edge_loop referenced in function _main
1>edge.obj : error LNK2019: unresolved external symbol _update_supernode_reg referenced in function _main
1>edge.obj : error LNK2019: unresolved external symbol _edge_init_keyschedule referenced in function _main
1>edge.obj : error LNK2019: unresolved external symbol _edge_init_twofish_psk referenced in function _main
1>edge.obj : error LNK2019: unresolved external symbol _supernode2addr referenced in function _main
1>edge.obj : error LNK2019: unresolved external symbol _edge_init referenced in function _main
1>C:\sources\n2n-dev\win32\DotNet\Debug\edge.exe : fatal error LNK1120: 6 unresolved externals

**Comment by emanuele-f** [comment]
Please describe how you are compiling the software. You can find compilation instructions here https://github.com/ntop/n2n/blob/dev/doc/Windows.md

**Comment by zwh6611** [comment]
I open the n2n.sln with Visual C++ Express 2008 in Win7(x64) . And put libeay32.lib, ssleay32.lib in the lib path. And then build the solution.   The supernode project was build succeed with some warning, but the edge is failed with LNK2019 Error.

**Comment by zwh6611** [comment]
I have tried again with the compilation instructions. And i work for me. Thank you very much.
