### ISSUE TITLE
Version released recommended

### ISSUE THREAD

**Issue by fcwys** [ntop/n2n#86]
It is recommended that there are platform releases, such as Linux, Windows or Macos, thanks！

**Comment by lucktu** [comment]
Yes, I think so. for editing firmware is difficult for many people, including me.

This is my collection, but not the latest, you can refer to it.
https://pan.baidu.com/s/1eRNybCm   /    hq4i
http://n2n.lucktu.com/n2n/  (temporary)

**Comment by fcwys** [comment]
thank you

**Comment by lucktu** [comment]
For example, https://github.com/fatedier/frp/releases 
Very convenient。

**Comment by fcwys** [comment]
i know about frp

**Comment by emanuele-f** [comment]
For linux, we already package n2n for most distributions. We provide both a stable and dev release. Please check out http://packages.ntop.org

**Comment by emanuele-f** [comment]
Closing the issue as linux packages are already available (see link above) and for windows there is already a request open https://github.com/ntop/n2n/issues/79
