### ISSUE TITLE
how to make the CFLAGS="-DSN_SELECTION_RTT into Makefile and take effect?

### ISSUE THREAD

**Issue by galaxyskyknight** [ntop/n2n#862]
Seems I add it to Makefile separately doesn't take any effect but only works by using "./configure CFLAGS="-DSN_SELECTION_RTT""?  who can teach me how to make this consolidate in make file?

**Comment by hamishcoleman** [comment]
Can you explain why using the configure step to add this is not suitable for you?

If you wish to edit the Makefile to add this flag, you can look for the line that begins with `CFLAGS=` and append it to there - but remember it will be overwritten each time you run configure.

The current Makefile also has a number of environment variables that it appends to the CFLAGS - so if you were to set `OPTIONS=-DSN_SELECTION_RTT` on the make command line, that would also work.

**Comment by Logan007** [comment]
considered deprecated as of #864, closing
