### ISSUE TITLE
What is the purpose of the supernode 7654 tcp port?

### ISSUE THREAD

**Issue by laminux29** [ntop/n2n#868]
Supernode use 7654 tcp and udp port as default. Or use -p to changge it.

The udp port is work-port as we know, but what is the tcp port used for?

**Comment by Logan007** [comment]
Apart from the UDP port, the supernode also allows the edges to connect through TCP. This is useful in case of network components such as firewalls blocking UDP.

An edge can connect through TCP by providing the `-S2` command line switch, see `edge --help`. Note, that this disables p2p – supernode forwarding only – and that it is not working at Windows edges yet.

**Comment by Logan007** [comment]
Considered answered, closing. Please re-open if required.
