### ISSUE TITLE
Very slow data transfer

### ISSUE THREAD

**Issue by ghost** [ntop/n2n#87]
Hello,

when I copy a movie from my notebook the a Vmware machine hosted on the same notebook the speed is maxed out at ca. 10 MB/s. Also the transfer aborted several times and had to be restarted.

![Slow](https://user-images.githubusercontent.com/10000402/55292310-02b9f880-53e1-11e9-88ee-78cd6ea20000.png)

That seems to be a limitation of the TAP driver which "emulates" a 100MBit connection, thus limits itself to 12 MB/s. Maybe on Linux there is no such a limit as I read some users have much faster speeds with n2n.

Is there any way to drop TAP driver and its limitations and get a proper dedicated n2n network driver one day ?

**Comment by ghost** [comment]
I tried the n2n edition of myerd:
https://github.com/meyerd/n2n

![Better](https://user-images.githubusercontent.com/10000402/55292964-a2c75000-53e8-11e9-961c-06f1afee6272.png)

Speed is pretty constant at 12MB/s and the 3GB file was transferred without a single abort which is much better 🥇

**Comment by emanuele-f** [comment]
Have you performed the tests without encryption and with latest version from github?

**Comment by ghost** [comment]
Hello,

the compiled code is unchanged from current master.

How do you disable encryption ? The docs are not very clear how to set encryption modes.

**Comment by emanuele-f** [comment]
If you omit the `-k` option then the encryption will be disabled

**Comment by ghost** [comment]
Sry for the delay to reply. Just tested without -k and the result is the same. The main issue seems to be the link speed of 100 MBit of the Tap driver which somehow is enforced as a hard limit.  Maybe another Windows user can test this, too.

**Comment by emanuele-f** [comment]
I've found this https://github.com/OpenVPN/tap-windows/issues/6 but I don't know if such speed is actually relevant

**Comment by lucaderi** [comment]
@ghost Please update the code as with the latest enhancements the overall speed should have been greatly enhanced
