### ISSUE TITLE
How to access the subnet through the edge

### ISSUE THREAD

**Issue by zwh6611** [ntop/n2n#88]
Hi, Now I have two subnets, one is  192.168.3.0/255.255.255.0 (office net), and the other is 172.31.32.0/255.255.240.0 (home net)

Each net have a edge. one is 10.121.0.2/24 (n2n IP, host ip is 172.31.32.2 ) , and one is 10.121.0.46/24 (n2n IP, host ip is 192.168.3.46) .
The edges can ping each other. And I want to ping 192.168.3.0/24, which is same subnet with the edge host.

Any help I can get ?

**Comment by emanuele-f** [comment]
On the office edge you should enable the routing (add `-r` option to the edge startup line/config and restart n2n edge), then on the home node you should use 10.121.0.46 as a gateway for your office network (`ip route add 192.168.3.0/24 via 10.121.0.46`)

**Comment by zwh6611** [comment]
Thank you for your reply. 
I have done with your guide. And now I can ping 192.168.3.46. But I can not ping 192.168.3.58(which is another PC in office subnet).
Anything I have do ?

**Comment by zwh6611** [comment]
/etc/n2n/ntop_v2/edge -a 10.121.0.46 -s 255.255.0.0 -r -c topic -k test -l supernode:port

**Comment by zwh6611** [comment]
/proc/sys/net/ipv4/ip_forward   = 1

**Comment by zwh6611** [comment]
root@home# ip route
default via 172.31.47.253 dev eth0 
10.121.0.0/16 dev edge0  proto kernel  scope link  src 10.121.0.1 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 linkdown 
172.31.32.0/20 dev eth0  proto kernel  scope link  src 172.31.34.158 
192.168.3.0/24 via 10.121.0.46 dev edge0 

root@office# ip route
default via 192.168.3.1 dev eno1 proto static metric 100 
10.121.0.0/16 dev edge0 proto kernel scope link src 10.121.0.46 
169.254.0.0/16 dev eno1 scope link metric 1000 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
172.18.0.0/16 dev br-8e0f2fa5a27a proto kernel scope link src 172.18.0.1

**Comment by lucktu** [comment]
iptables -t nat -A POSTROUTING -j MASQUERADE

**Comment by zwh6611** [comment]
> iptables -t nat -A POSTROUTING -j MASQUERADE

if I add " iptables -t nat -A POSTROUTING -j MASQUERADE" , the edge can not connect to the Internet.
Below is the iptable settings before I add the command.  The PC with docker installed (which will add same nat rules). 

root@office:~# iptables -t nat -nvL
Chain PREROUTING (policy ACCEPT 7 packets, 587 bytes)
 pkts bytes target     prot opt in     out     source               destination         
 3075  172K DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 4 packets, 389 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 69 packets, 4464 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  662 39912 DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 70 packets, 4524 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    1    84 MASQUERADE  all  --  *      !docker0  172.17.0.0/16        0.0.0.0/0           
10741  673K MASQUERADE  all  --  *      !br-8e0f2fa5a27a  172.18.0.0/16        0.0.0.0/0           
    0     0 MASQUERADE  tcp  --  *      *       172.18.0.7           172.18.0.7           tcp dpt:10514
    0     0 MASQUERADE  tcp  --  *      *       172.18.0.9           172.18.0.9           tcp dpt:4443
    0     0 MASQUERADE  tcp  --  *      *       172.18.0.9           172.18.0.9           tcp dpt:443
    0     0 MASQUERADE  tcp  --  *      *       172.18.0.9           172.18.0.9           tcp dpt:80

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 RETURN     all  --  docker0 *       0.0.0.0/0            0.0.0.0/0           
   77  4620 RETURN     all  --  br-8e0f2fa5a27a *       0.0.0.0/0            0.0.0.0/0           
    0     0 DNAT       tcp  --  !br-8e0f2fa5a27a *       0.0.0.0/0            127.0.0.1            tcp dpt:1514 to:172.18.0.7:10514
    0     0 DNAT       tcp  --  !br-8e0f2fa5a27a *       0.0.0.0/0            0.0.0.0/0            tcp dpt:4443 to:172.18.0.9:4443
   71  4260 DNAT       tcp  --  !br-8e0f2fa5a27a *       0.0.0.0/0            0.0.0.0/0            tcp dpt:443 to:172.18.0.9:443
  675 40524 DNAT       tcp  --  !br-8e0f2fa5a27a *       0.0.0.0/0            0.0.0.0/0            tcp dpt:80 to:172.18.0.9:80

**Comment by zwh6611** [comment]
And I run 
"iptables -t nat -A POSTROUTING -s 10.121.0.0/16 -j MASQUERADE"
"iptables -t nat -A POSTROUTING -s 192.168.3.0/24 -j MASQUERADE"

still not work.

root@office:~# iptables -t nat -nvL POSTROUTING
Chain POSTROUTING (policy ACCEPT 278 packets, 18326 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    1    84 MASQUERADE  all  --  *      !docker0  172.17.0.0/16        0.0.0.0/0           
10805  677K MASQUERADE  all  --  *      !br-8e0f2fa5a27a  172.18.0.0/16        0.0.0.0/0           
    0     0 MASQUERADE  tcp  --  *      *       172.18.0.7           172.18.0.7           tcp dpt:10514
    0     0 MASQUERADE  tcp  --  *      *       172.18.0.9           172.18.0.9           tcp dpt:4443
    0     0 MASQUERADE  tcp  --  *      *       172.18.0.9           172.18.0.9           tcp dpt:443
    0     0 MASQUERADE  tcp  --  *      *       172.18.0.9           172.18.0.9           tcp dpt:80
    7   467 MASQUERADE  all  --  *      *       10.121.0.0/16        0.0.0.0/0           
  256 15451 MASQUERADE  all  --  *      *       192.168.3.0/24       0.0.0.0/0

**Comment by zwh6611** [comment]
from home PC ping 192.168.3.46

02/Apr/2019 15:27:17 [edge_utils.c:1337] ### Rx N2N UDP (149) from 47.10.18.10:81
02/Apr/2019 15:27:17 [edge_utils.c:1367] Rx PACKET from 47.10.18.10:81 (47.75.88.115:49538)
02/Apr/2019 15:27:17 [edge_utils.c:764] handle_PACKET size 107 transform 2
02/Apr/2019 15:27:17 [transform_tf.c:243] decode_twofish 107 with SA 0.
02/Apr/2019 15:27:17 [edge_utils.c:819] sending to TAP 98
02/Apr/2019 15:27:17 [edge_utils.c:1238] ### Rx TAP packet (  98) for DA:35:9B:6C:9D:7B
02/Apr/2019 15:27:17 [edge_utils.c:1194] encoded PACKET header of size=34 transform 2 (idx=1)
02/Apr/2019 15:27:17 [transform_tf.c:133] encode_twofish 98 with SA 0.
02/Apr/2019 15:27:17 [edge_utils.c:1071] Searching destination peer for MAC DA:35:9B:6C:9D:7B
02/Apr/2019 15:27:17 [edge_utils.c:1096] find_peer_address (DA:35:9B:6C:9D:7B) -> [47.10.18.10:81]
02/Apr/2019 15:27:17 [edge_utils.c:1125] send_packet to 47.10.18.10:81
02/Apr/2019 15:27:17 [edge_utils.c:468] sendto sent=141 to 


from home PC ping 192.168.3.58

02/Apr/2019 15:27:20 [edge_utils.c:1337] ### Rx N2N UDP (149) from 47.10.18.10:81
02/Apr/2019 15:27:20 [edge_utils.c:1367] Rx PACKET from 47.10.18.10:81 (47.75.88.115:49538)
02/Apr/2019 15:27:20 [edge_utils.c:764] handle_PACKET size 107 transform 2
02/Apr/2019 15:27:20 [transform_tf.c:243] decode_twofish 107 with SA 0.
02/Apr/2019 15:27:20 [edge_utils.c:819] sending to TAP 98
02/Apr/2019 15:27:21 [edge_utils.c:1337] ### Rx N2N UDP (149) from 47.10.18.10:81
02/Apr/2019 15:27:21 [edge_utils.c:1367] Rx PACKET from 47.10.18.10:81 (47.75.88.115:49538)
02/Apr/2019 15:27:21 [edge_utils.c:764] handle_PACKET size 107 transform 2
02/Apr/2019 15:27:21 [transform_tf.c:243] decode_twofish 107 with SA 0.
02/Apr/2019 15:27:21 [edge_utils.c:819] sending to TAP 98


It seems the office edge have received the packet. But can not receive the reply.

**Comment by emanuele-f** [comment]
You probably need to masquerade the IP on the office edge, for example `iptables -A POSTROUTING -o eth0 -j MASQUERADE` where eth0 is the interface connected to your office network

**Comment by zwh6611** [comment]
still not working
root@office:~# iptables -t nat -nvL POSTROUTING --line-number
Chain POSTROUTING (policy ACCEPT 1 packets, 73 bytes)
num   pkts bytes target     prot opt in     out     source               destination         
1        1    84 MASQUERADE  all  --  *      !docker0  172.17.0.0/16        0.0.0.0/0           
2    11373  716K MASQUERADE  all  --  *      !br-8e0f2fa5a27a  172.18.0.0/16        0.0.0.0/0           
3        0     0 MASQUERADE  tcp  --  *      *       172.18.0.7           172.18.0.7           tcp dpt:10514
4        0     0 MASQUERADE  tcp  --  *      *       172.18.0.9           172.18.0.9           tcp dpt:4443
5        0     0 MASQUERADE  tcp  --  *      *       172.18.0.9           172.18.0.9           tcp dpt:443
6        0     0 MASQUERADE  tcp  --  *      *       172.18.0.9           172.18.0.9           tcp dpt:80
7        1    84 MASQUERADE  all  --  *      eno1    0.0.0.0/0            0.0.0.0/0

**Comment by zwh6611** [comment]
I clear all the nat rules. and run "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE". And it work.
It seems the docker nat rules conflicted.

**Comment by zwh6611** [comment]
Nat issue

**Comment by emanuele-f** [comment]
Great. I've opened issue #89 for the documentation of this

**Comment by Logan007** [comment]
May I add that the router in the respective network (= default gateway) might need to have a static route added. Some home routers offer that option. The route should point all packets for the respective destination network (at home: those directed to office, and vice versa) to the edge node. In your example probably:

At home: route all packet for office net (192.168.3.0/255.255.255.0) via/to 172.31.32.x, with latter being the 'real' host ip which has the edge running. 

If ipforwarding is enabled, a route on the host is installed and edge is started with -r option, then linux will take care of the rest, especially the packet routing/forwarding: It will realize, that packets are for the office net and it hopefully will find an appropriate routing rule on the host, edge will only accept it with -r. You need to do that on both sides. You then have successfully setup a vpn network coupling.

There is no need for NAT in this constellation. It would only be needed on an edge node in that network in which you cannot manually add a static route to the router. In that case, the other clients in that network cannot start a connection to clients of the other network as they cannot be seen behind the NAT.
