### ISSUE TITLE
Why doesn't version 3.0 have a Windows version?

### ISSUE THREAD

**Issue by dbbao** [ntop/n2n#890]
3.0版本为啥没有Windows的版本呢？

_Why doesn't version 3.0 have a Windows version?_

**Comment by hamishcoleman** [comment]
> Why doesn't the .0 version have the Windows version?

There is no packaged installer built for Windows, so it is still an 'expert' action to install.

The build system does upload Windows EXE files as part of the github Actions workflow, but you have to dig a little to find it.  For example, the most recent 3.0-stable build can be found at https://github.com/ntop/n2n/actions/runs/1407575438 where you can download the binaries.zip from the Artifacts section and extract the Windows EXE files.

**Comment by youtehub** [comment]
If you search for n2n on Github, you'll find a developer who compiled various versions of n2N -- Lucktu /n2n. Lucktu has compiled n2N software for each platform and can download it directly. The latest version of N2N has also been compiled and published to his Github repository.
url location:  https://github.com/lucktu/n2n

**Comment by huddhudd** [comment]
Hope to compile the Windows version

**Comment by Logan007** [comment]
If you want pre-compiled binaries, please see the posts above. The Windows binaries from the [binaries.zip](https://github.com/ntop/n2n/suites/4219228486/artifacts/109069127) in the Artifacts section seem to work very well. Windows binaries can be found in the `x86_64-pc-mingw64` folder of that `.zip`-file.

If you want to compile yourself, our [Building document](https://github.com/ntop/n2n/blob/dev/doc/Building.md) has instructions.

**Comment by Logan007** [comment]
> Where can get VS compiler edition ? Thanks

Visual Studio has moved to 2022 in the meantime. Not sure if 2022 can build it.

However, you can still get the 2017 version. If you follow the link from our Building document, the 2022 page opens. At the bottom, they link to "older downloads". You need to sign in  – they have an option to use github credentials – to access the older downloads.  Once signed in, you would find the "Build Tools for Visual Studio 2017 (version 15.0)" at the download tab.

**Comment by Logan007** [comment]
Considered answered, please re-open if required.
