### ISSUE TITLE
An error about "-A"

### ISSUE THREAD

**Issue by lucktu** [ntop/n2n#90]
/opt/home/admin # edge2a -d T3 -a 10.0.3.21 -c n2n -k n2n -l n2n.lucktu.com:10086 -p 19833 -r -b -A -f &
/opt/home/admin # 06/Apr/2019 08:13:39 [edge.c:286] Adding supernode[0] = n2n.lucktu.com:10086
06/Apr/2019 08:13:39 [edge.c:620] Starting n2n edge 2.5.0 Apr  4 2019 15:38:29
06/Apr/2019 08:13:39 [edge.c:623] supernode 0 => n1.lucktu.com:10086
06/Apr/2019 08:13:39 [edge.c:663] ip_mode='static'
06/Apr/2019 08:13:39 [tuntap_linux.c:43] Interface T3 has MAC DA:AB:67:C3:CD:20
06/Apr/2019 08:13:39 [edge.c:680] Binding to local port 20083
06/Apr/2019 08:13:39 [edge.c:750] edge started

/opt/home/admin # 06/Apr/2019 08:14:03 [transform_aes.c:362] WARNING: UDP payload decryption failed.
06/Apr/2019 08:14:03 [transform_aes.c:362] WARNING: UDP payload decryption failed.
06/Apr/2019 08:14:04 [transform_aes.c:362] WARNING: UDP payload decryption failed.
06/Apr/2019 08:14:04 [transform_aes.c:362] WARNING: UDP payload decryption failed.
06/Apr/2019 08:14:05 [transform_aes.c:362] WARNING: UDP payload decryption failed.
06/Apr/2019 08:14:05 [transform_aes.c:362] WARNING: UDP payload decryption failed.
06/Apr/2019 08:14:07 [transform_aes.c:362] WARNING: UDP payload decryption failed.
06/Apr/2019 08:14:07 [transform_aes.c:362] WARNING: UDP payload decryption failed.
06/Apr/2019 08:14:08 [transform_aes.c:362] WARNING: UDP payload decryption failed.
06/Apr/2019 08:14:08 [transform_aes.c:362] WARNING: UDP payload decryption failed.
... ...

I run 2 edges in padavan, one is ok, the second is bad. kill and run it again,  it's ok maybe. it's not stable.

**Comment by lucktu** [comment]
I thought there was always a mistake when editing the original, so I commented out the following item in the actual editing.(edge.c)
"setsockopt(eee.udp_multicast_sock, SOL_SOCKET, SO_REUSEPORT, &enable_reuse, sizeof(enable_reuse));"
--------------------------------------------
edge.c: In function 'main':
edge.c:734: error: 'SO_REUSEPORT' undeclared (first use in this function)
edge.c:734: error: (Each undeclared identifier is reported only once
edge.c:734: error: for each function it appears in.)
Makefile:70: recipe for target 'edge' failed
make: *** [edge] Error 1
make n2n v2 failed

**Comment by Logan007** [comment]
Concerning the payload decryption error, are both edges built from the same source? The dev branch changed how the password gets used in the encryption process for aes about two weeks ago, see #83.

**Comment by lucktu** [comment]
oh, yes, thank you !

**Comment by Logan007** [comment]
Does your current build include already the changes from #67 and [this correction](https://github.com/ntop/n2n/commit/e989f475a1b7df8e8d51ea5805c1009b71b075f4), i.e. is your build younger than March 3rd?

**Comment by lucktu** [comment]
Yes, my firmware is the latest.

It can connect to older versions of firmware sometimes, sometimes not, and is unstable.
In terms of stability, n2n_v2s(meyerd's n2n) > n2n_v1 > n2n_v2.

**Comment by lucktu** [comment]
Yes, my n2n is the latest.

My n2n_v2 for padavan get rid of this row in edge.c, because with it, you can't build it. 
`//setsockopt(eee.udp_multicast_sock, SOL_SOCKET, SO_REUSEADDR, &enable_reuse, sizeof(enable_reuse));`

**Comment by emanuele-f** [comment]
Using -A with older n2n versions is not supported, because older n2n do not know how to decrypt AES. For the SOL_SOCKET issue, if you have a ifdef to exclude it for padavan, please provide a pull request

**Comment by lucktu** [comment]
ok

**Comment by lucktu** [comment]
https://github.com/ntop/n2n/issues/51

Someone had met it before.

**Comment by emanuele-f** [comment]
There was another call for SO_REUSEADDR, should now be fixed in https://github.com/ntop/n2n/commit/d4205d36fd588a8e7b78014ef17156a43d2b2dd0

**Comment by lucktu** [comment]
Thank you !   

My machine does not support this, so even if edited out, this feature is useless, so for my machine, I can only remove this parameter

uname -a
Linux KFRouter-S1 3.4.113 #1 SMP Sat Apr 6 12:27:55 CST 2019 mips GNU/Linux

**Comment by emanuele-f** [comment]
Yes, as pointed in issue #51 some older versions of kernel linux do not support SO_REUSEADDR. Please close this issue if the original problem is now solved.
