### ISSUE TITLE
Supernode releases edge IP too slow

### ISSUE THREAD

**Issue by dishangti** [ntop/n2n#901]
When I force a connected edge with auto IP close, and reconnect it immediately, I receive ERROR: authentication error, MAC or IP addresses already in use or not released by supernode.
It seems that supernode doesn't accept the old IP and cannot release a new IP to it.

**Comment by Logan007** [comment]
Please see our [FAQ](https://github.com/ntop/n2n/blob/dev/doc/Faq.md#the-edge-repeatedly-throws-an-authentication-error-mac-or-ip-address-already-in-use-or-not-released-yet-by-supernode-message-what-is-wrong) and another possible workaround at the last paragraph of [this section](https://github.com/ntop/n2n/blob/dev/doc/Authentication.md#identity-based-scheme).
