### ISSUE TITLE
How to use, Network filter for rules (-R) allowing and denying specific traffic to tunnel

### ISSUE THREAD

**Issue by huddhudd** [ntop/n2n#903]
Network filter for rules (-R) allowing and denying specific traffic to tunnel

How to use, can you give an example?

**Comment by Logan007** [comment]
Please see #489.

**Comment by Logan007** [comment]
You also might want to have a look into the [doc folder](https://github.com/ntop/n2n/blob/dev/doc/TrafficRestrictions.md).

Is it helpful?

**Comment by Logan007** [comment]
Considered answered, please re-open if required.
