### ISSUE TITLE
CMake build on Windows not possible

### ISSUE THREAD

**Issue by Logan007** [ntop/n2n#913]
It looks like we are having difficulties with the upnp/pmp 3rd party libraries, also see the output _CMake_ runner at _Actions_ tab.

**Comment by Logan007** [comment]
Might be different issues:

- Windows (on my VM) build works when libpmp is fully commented from CMakeLists.txt
- The github _CMake_ runner gets stuck at some libminiupnp related point

**Comment by Logan007** [comment]
Umm, at least locally, I am able to compile on Windows if I add

```
#ifdef  _WIN64
typedef unsigned __int64    ssize_t;
#else
typedef _W64 unsigned int   ssize_t;
#endif
```
to the very beginning of `thirdparty/libnatpmp/natpmpc.c` file...

**Comment by Logan007** [comment]
... and _CMake_ Action runs [green](https://github.com/Logan007/n2n/actions/runs/1619682319) with `libnatpmp` support [disabled](https://github.com/Logan007/n2n/tree/commentPmp).

- So, do we have to disable `libnatpmp` support on Windows/CMake?

- Or, is anyone aware of how to apply a patch to submodules on Windows? `git` must be installed (to fetch the submodules) anyway, but I have not found a way to have `git` apply a patch to untracked (submodule) files.

- Perhaps, we could create a fork of that `libnatpmp`, patch it, and use the patched commit as submodule instead?

Suggestions are welcome!

**Comment by hamishcoleman** [comment]
Just for a couple of datapoints:
- I can build miniupnpc on windows with cmake fine if I am building it by itself
- I can reproduce the github action build failure building n2n with cmake on windows
- the build failure is in a part of the miniupnp library that we dont use, dont want and shouldnt build

**Comment by Logan007** [comment]
I will try to change the `libnatpmp` submodule to [this](https://github.com/miniupnp/libnatpmp/pull/18/commits/647f908d01aedddd0cc39509c64576c6370ba26a) commit – keep your fingers crossed!

**Comment by hamishcoleman** [comment]
we really dont want to change the submodule - that defeats much of the purpose of submodules!

**Comment by Logan007** [comment]
To keep a compile-able _dev_, I see no other option than to disable `libnatpmp` support on Windows until we come up with a better solution.

**Comment by hamishcoleman** [comment]
Hrm, perhaps I have misunderstood - what does the libnatpmp part do?  with a quick look at the linux cmake build, it seemed like it was not compiled.

If simply removing it from the compile works, then what feature is lost?

**Comment by Logan007** [comment]
There are two protocols for enabling port forwarding, upnp and pmp. So, pmp would be lost on pure MSVC WIndows builds (not MinGW as it has uses different compiler I guess).

**Comment by hamishcoleman** [comment]
oh, but of course.  Why have one way that is fragile and takes an entire XML parser, when you could have several!

**Comment by Logan007** [comment]
Hereby, f0c37c7 officially is dedicated to you! :wink:

**Comment by miniupnp** [comment]
`ssize_t` is SIGNED !

**Comment by Logan007** [comment]
Thank you @miniupnp. The exemplary code [above](https://github.com/ntop/n2n/issues/913#issuecomment-1000869759) was given before we did the deeper dive over at [your repo](https://github.com/miniupnp/libnatpmp/pull/18).

**Comment by Logan007** [comment]
With upstream `libnatpmp` being [adapted for Windows compile](https://github.com/miniupnp/libnatpmp/commit/4b8b4470d78af2c209824b3e5d0e06168532ee2c), we can revert #914 and #917. Any objection?
