### ISSUE TITLE
build error with CMake

### ISSUE THREAD

**Issue by skyformat99** [ntop/n2n#916]
1) git clone  latest code
2) edit  CMakefiles.txt ,    line 44 :
        ->  OPTION(N2N_OPTION_USE_PORTMAPPING "USE MINIUPNP and NATPMP Libraries" **OFF**)
3) mkdir  build && cd build
4) cmake  .. 
    then  error message:

-- Build for version: 3.1.0-49-g5d0c395-dirty
CMake Error at CMakeLists.txt:173 (add_subdirectory):
  add_subdirectory given source
  "/var/n2ngit/n2n/thirdparty/miniupnp/miniupnpc" which is not an
  existing directory.

CMake Warning (dev) at CMakeLists.txt:177 (add_subdirectory):
  The source directory

    /var/n2ngit/n2n/thirdparty/libnatpmp

  does not contain a CMakeLists.txt file.

**Comment by Logan007** [comment]
Is this specific to a certain platform? Just asking because I cannot reproduce this error. Will merge anyway, proper indention always is a good idea! :wink:

**Comment by Logan007** [comment]
With upstream `libnatpmp` being [adapted for Windows compile](https://github.com/miniupnp/libnatpmp/commit/4b8b4470d78af2c209824b3e5d0e06168532ee2c), we can revert #914 and #917. Any objection?
