### ISSUE TITLE
select-rtt mode, supernode drop causes edge node to go offline

### ISSUE THREAD

**Issue by xuan880** [ntop/n2n#923]
If the edge node is connected to only one super node at the beginning, then all nodes are normal (Figure 1).
and there is no problem when the second super node joins the original network through the -l parameter to form Federation mode (Figure 2).
but once the second super node is offline after forming the Federation mode, it will cause all edge nodes under the current network to connect to the offline super node, thus causing all edge nodes to be offline (Figure 3).

From the screenshot you can always see that the 139 super node alone can be used without problems, and later join the 107 node to form Federation can also be used, but when 107 is offline, the edge node will be connected to the 107 node, thus causing the node offline
![Screenshot_20220106_222039](https://user-images.githubusercontent.com/2383369/148404247-de64becc-b6fa-4f19-a96d-5ba7c975f527.png)
![Screenshot_20220106_223557](https://user-images.githubusercontent.com/2383369/148404257-cd2d5b51-f6cd-4fbb-b9a8-96ec3ab8795e.png)
![Screenshot_20220106_223905](https://user-images.githubusercontent.com/2383369/148404262-30e94686-2f74-4c1d-8046-fe51b74970c1.png)

**Comment by Logan007** [comment]
Thank you for your very clean report!

I see that your supernode is from commit d2683f2. After the release, we had some more commits to the stable branch, especially [this](https://github.com/ntop/n2n/commit/0177e140262911781d5d92371e40de94c504c8ac) one – 0177e14. It fixes some supernode selection issue.

May I ask you to verify if this issue persists with the fixed version, too? For testing, it should be sufficient to only replace the edge because supernode selection basically happens at the edge. But to be sure, you could also try to replace the supernode.

Please let us know what you find!

**Comment by xuan880** [comment]
> Thank you for your very clean report!
> 
> I see that your supernode is from commit [d2683f2](https://github.com/ntop/n2n/commit/d2683f2c2350a6d5765611611e748af25ad2ac98). After the release, we had some more commits to the stable branch, especially [this](https://github.com/ntop/n2n/commit/0177e140262911781d5d92371e40de94c504c8ac) one – [0177e14](https://github.com/ntop/n2n/commit/0177e140262911781d5d92371e40de94c504c8ac). It fixes some supernode selection issue.
> 
> May I ask you to verify if this issue persists with the fixed version, too? For testing, it should be sufficient to only replace the edge because supernode selection basically happens at the edge. But to be sure, you could also try to replace the supernode.
> 
> Please let us know what you find!

I tested it with version 3.1.0 published in the releases page, and the same problem still occurs when both the edge node and the super node are 3.1.0.
![Screenshot_20220107_000327](https://user-images.githubusercontent.com/2383369/148412835-9253c992-2ecb-417b-a1c5-61fe884b962b.png)

**Comment by Logan007** [comment]
Thank you, I will have a deeper look. 

_(I suspect the sorting in `sn_selection.c` going wrong here)_

**Comment by Logan007** [comment]
Although I have found some irregularity in the code (#936), I have not been able to re-produce the situation you describe.

I am still on it.

**Comment by Logan007** [comment]
I have been trying but not been able to re-produce the situation you describe. I always get the fail-over working correctly.

It seems that I need more data points here. Everybody please provide details about your setup if you encounter this same situation. Thank you!

**Comment by xuan880** [comment]
> I have been trying but not been able to re-produce the situation you describe. I always get the fail-over working correctly.
> 
> It seems that I need more data points here. Everybody please provide details about your setup if you encounter this same situation. Thank you!

I compiled the latest and tested it, and it really returned to normal.

**Comment by Logan007** [comment]
Thank you @xuan880 for providing the really detailed report and feedback. I was about to note the older release which got some fixes meanwhile, when I saw that you have already done a new test with latest code. You are fast!

And, I am glad that it is working for you now the way it is intended to be. Please let us know if you find anything else.

**Comment by Logan007** [comment]
considered solved, please re-open if required
