### ISSUE TITLE
ManagementAPI can add query options

### ISSUE THREAD

**Issue by seayxu** [ntop/n2n#924]
Add community and ip options for edges of supernode, like below.
```
r 999:0 edges c1
r 999:0 edges c1 10.1.2.3
# or
r 999:0 edges c1,c2
```

It is very necessary when community is too much.

**Comment by hamishcoleman** [comment]
I assumed that the client would do any needed filtering, as that allows the server to remain simple.

How many edges are you dealing with?

**Comment by seayxu** [comment]
Thousands but not now,will continue to increase

**Comment by hamishcoleman** [comment]
Have you done any testing with that number of edges?  Are you seeing any specific issues?

Remember the ManagementAPI is not expected to be typed in by humans, so the client is a good place to add any complex filtering system (Are you using the n2n-ctl example client?)

**Comment by seayxu** [comment]
Understood,thank you.

**Comment by hamishcoleman** [comment]
Please do return with more info if you find scaling issues.  I don't believe anyone has tested the ManagementAPI with that number of edges.
