### ISSUE TITLE
Data loss on AWS 

### ISSUE THREAD

**Issue by tonybarba** [ntop/n2n#931]
Where can I find information on data loss or drop packets when using n2n across AWS regions? Also, any information on best practices for AWS implementation/deployment.

Thank you.

**Comment by Logan007** [comment]
Some of n2n's older version is known to work on AWS as depicted in the article linked [in this post](https://www.ntop.org/n2n/using-n2n-with-amazon-aws-ec2/). My sincere hope is that it holds true for the newer versions as well. Other than that, I have never heard of special AWS-related practices or precautions.

n2n does not stamp-in packet counters in its UDP packets thus it is not capable of self-diagnostic packet loss detection – it is an interesting thought though; we might consider it for future versions starting from 4.0 (maybe complement current replay protection scheme with it).

Other than that, I would think of using `ping -f` (or other tools) over the n2n connection probing for packet loss.

**Comment by Logan007** [comment]
Considered answered, please re-open if required.

Your idea of packet loss detection has been [well noted](https://github.com/ntop/n2n/issues/920#issuecomment-1003448736) for 4.0.
