### ISSUE TITLE
When using the v3 of supernode, the cpu usage is high

### ISSUE THREAD

**Issue by lucktu** [ntop/n2n#933]
On my pc,  running v1, v2, v2s, and v3, but the cpu usage varies greatly:
ver--edges---%cpu
v1--- 3------0%  (often 0%)
v2s-- 4------0%  (often 0%)
v2----31---0.3% (0-0.3%, often 0%)
v3----10---1.3% (1-2.3%, often 1.3%)
![001](https://user-images.githubusercontent.com/30952545/150054902-e5ec8158-673e-49ce-8cc6-843039b2efae.png)

**Comment by Logan007** [comment]
Supernode CPU load can depend on a lot of factors.

There could be some influence in terms of a basic load by newly added features such as full header encryption, edge authentication and federated supernodes which were not available before 2.8 or 3.0 respectively. This basic load should be very low but present – no matter if these features are enabled/used or not.

If these features are enabled or used, it will further add to CPU load.

Also, please keep in mind that supernode's CPU load does not only depend on the number of edges but also on edge-dependent activities. For example, load might be higher if the supernode has to forward packets as opposed to only connecting edges via p2p. This can have a huge impact on CPU load especially on smaller systems, even depending on actual traffic then.

Finally, it can make a difference how optimized the executable are compiled, e.g. `-march=native -O3` etc.

**Comment by lucktu** [comment]
Ok, I see.
Thank you!

**Comment by lucktu** [comment]
Now it’s normal, and in the same way as v2, it could be a bug of federation.
![001](https://user-images.githubusercontent.com/30952545/153000883-15c77901-bca4-4d7e-ae18-96af4a60d111.PNG)

I disabled the ip(from iftop) on a higher-level router, and it went back to normal.
![002](https://user-images.githubusercontent.com/30952545/153001165-5f350d33-e334-4c71-a849-57e9df6a3c72.png)

**Comment by lucktu** [comment]
Now it’s normal, and in the same way as v2, it could be a bug of federation.
![001](https://user-images.githubusercontent.com/30952545/153004089-9a38b983-b85c-4d1b-84d2-daf82a4d39b4.PNG)

I disabled the ip_(from iftop: it’s always sending me data, but there’s no data back)_ on superior router, and it went back to normal.
![002](https://user-images.githubusercontent.com/30952545/153004133-e5dadddf-e157-4423-891f-f1479f7c9fe5.png)
iptables -I FORWARD 1 -s 82.157.65.12 -j DROP
