### ISSUE TITLE
Upnp is missing

### ISSUE THREAD

**Issue by lucktu** [ntop/n2n#934]
"v.3.1.0-52-gda9ba27" is normal, but only the compiled with cmakeLists.txt is, and the compiled with makefile is not.

after that, no upnp.

**Comment by lucktu** [comment]
It’s easier this way:
git clone https://github.com/ntop/n2n.git --recurse-submodules

**Comment by Logan007** [comment]
The makefile way looks for libraries _installed_ on the system and compiles with port forwarding support if present.

**Comment by hamishcoleman** [comment]
Actually, the automatic probing for libraries was prone to errors and caused issues with cross compilation and openwrt builds, so the change was to turn off any automated checks for the installed libraries.

You now need to explicitly turn on any feature that you want to compile during your ./configure step.

See https://github.com/ntop/n2n/blob/dev/doc/BuildConfig.md for all the options

**Comment by lucktu** [comment]
Use cmake, modify CMakeLists.txt:

1, After "_if(N2N_OPTION_USE_PORTMAPPING)_", add (by fengdaolong )
ADD_DEFINITIONS("-DHAVE_PORT_FORWARDING")

2, And open "USE PTHREAD Library" & "USE MINIUPNP and NATPMP Libraries" is ON

3, Then it is ok (ubuntu 18)
mkdir build
cd build
cmake ..
make

**Comment by hamishcoleman** [comment]
Thanks @lucktu , that missing definition is a bug.

Also, you should never need to edit the CMakeLists.txt file unless you are developing - you can turn on those libraries by adding options to your cmake configure step:

```
cmake .. -DN2N_OPTION_USE_PTHREAD=ON -DN2N_OPTION_USE_PORTMAPPING=ON
```

**Comment by lucktu** [comment]
@hamishcoleman Yes, it's ok, Thank you very much!

**Comment by lucktu** [comment]
@hamishcoleman Yes, it's ok, Thank you very much!
Oddly enough, no pthread no upnp.
Also, there is no upnp for this operation:
./autogen.sh
./configure --enable-pthread --enable-natpmp --enable-miniupnp
... ...
configure: error: miniupnp library not found

**Comment by hamishcoleman** [comment]
Yes, the upnp support requires the threading support from pthread.

The upnp support enabled with the Makefiles and the ./configure takes advantage of the shared library support provided by the operating system, so you need to install those packages first: `apt-get install libminiupnpc-dev libnatpmp-dev`

**Comment by lucktu** [comment]
Well, it is now:
<blockquote>
libn2n.a(edge_utils.o): In function `supernode_connect':
/opt/n2n/src/edge_utils.c:341: undefined reference to `n2n_chg_port_mapping'
libn2n.a(edge_utils.o): In function `edge_init':
/opt/n2n/src/edge_utils.c:498: undefined reference to `port_map_create_thread'
libn2n.a(edge_utils.o): In function `edge_term':
/opt/n2n/src/edge_utils.c:3213: undefined reference to `port_map_cancel_thread'
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'src/edge' failed
make: *** [src/edge] Error 1
</blockquote>

**Comment by hamishcoleman** [comment]
@lucktu , thats an statement ordering bug - which is now fixed in the current dev

**Comment by lucktu** [comment]
@hamishcoleman , Thank you! have you tested it? 

This is my:
![002](https://user-images.githubusercontent.com/30952545/153378852-01f28453-8caa-4c42-86ff-7f69902c3a39.png)

**Comment by hamishcoleman** [comment]
Yes, my test compiled with no errors.

I am using
```
libminiupnpc-dev/stable,now 2.2.1-1 amd64 [installed]
libnatpmp-dev/stable,now 20150609-7.1 amd64 [installed]
```

**Comment by hamishcoleman** [comment]
The UPNP_LOCAL_PORT_ANY definition was introduced in 2015, so whatever library you are using is seriously old.

**Comment by lucktu** [comment]
OK, Thanks!
Let’s put that aside. maybe it’s for my environment.

**Comment by lucktu** [comment]
@hamishcoleman ,
Maybe. I’ll test it some other time.
Thank you!
