### ISSUE TITLE
MacOS n2n fail with wrong URL

### ISSUE THREAD

**Issue by michaelzhye** [ntop/n2n#935]
Fail to join network on MacOS Version 12.1 (MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports))
Error info with URL https://github.com/ntop/n2n/blob/dev/doc/n2n_on_MacOS.txt is a 404 error .

```
$ omniedge join
INFO[0000] You are in mode: prod                        

INFO[2022-01-20T10:35:31] List Virtual Network response                
🌶 My Omni Network
You choose number 1: My Omni Network
INFO[2022-01-20T10:35:32] Success to join virtual network              
INFO[2022-01-20T10:35:32] Start to connect omniedge                    
ERROR[2022-01-20T10:35:32] Unable to open any tap devices /dev/tap0 through /dev/tap254. Is this user properly authorized to access those descriptors?
ERROR[2022-01-20T10:35:32] Please read https://github.com/ntop/n2n/blob/dev/doc/n2n_on_MacOS.txt
ERROR[2022-01-20T10:35:32] fail to open TUN/TAP device  
```
`

**Comment by lucktu** [comment]
no TUN/TAP device?

**Comment by Logan007** [comment]
> Error info with URL https://github.com/ntop/n2n/blob/dev/doc/n2n_on_MacOS.txt is a 404 error .
> `$ omniedge join`
> `...`

Our `src/tuntap_osx.c:55` correctly links to our building documentation at `doc/Building.md`.

Maybe OmniEdge maintainers know?

**Comment by harley-byte** [comment]
add sudo

**Comment by baurine** [comment]
> add sudo

Same issue, and adding `sudo` doesn't work for me.

**Comment by baurine** [comment]
https://github.com/ntop/n2n/blob/dev/doc/Building.md#build-on-macos

> In order to use n2n on macOS, you first need to install support for TUN/TAP interfaces:
>
> ```
> brew tap homebrew/cask
> brew cask install tuntap
> ```

Hope this works.

**Comment by baurine** [comment]
```
> brew cask install tuntap
Error: `brew cask` is no longer a `brew` command. Use `brew <command> --cask` instead.
                                                                                                                                               × 8:38
> brew install --cask tuntap
Error: Cask 'tuntap' is unavailable: No Cask with this name exists.
```

Oops...

**Comment by baurine** [comment]
Fixed by manually installing it according to: https://omniedge.io/docs/article/Install

```
To use OmniEdge on MacOS, please instal Tun/Tap Driver first

3.1 Install Tun/Tap Driver:
For Intel Mac:
Download tuntap driver from https://sourceforge.net/projects/tuntaposx/files/latest/download
Extract tuntap_20150118.tar.gz and Install tuntap by running tuntap_20150118.pkg
For M1 Mac user:
Download https://github.com/Tunnelblick/Tunnelblick/tree/master/third_party/tap-notarized.kext
Download https://github.com/Tunnelblick/Tunnelblick/tree/master/third_party/tun-notarized.kext
Change the name to tap.kext and tap.kext,
Copy to /Library/Extensions
add net.tunnelblick.tap.plist and net.tunnelblick.tun.plist to /Library/LaunchDaemons/
```

**Comment by zybzzc** [comment]
> 

Why did my installation fail? Is there a system security policy that needs to be turned on?
Im MacOS 12.3.1 on nuc8

**Comment by baurine** [comment]
> > 
> 
> Why did my installation fail? Is there a system security policy that needs to be turned on? Im MacOS 12.3.1 on nuc8

When I manually install the tuntap driver, the installation fails at first and asks me to allow app in the `Security & Privacy`, after allowing and restarting the mac, install it again, success.

![image](https://user-images.githubusercontent.com/1284531/168852267-6985c344-1e1b-48bf-a534-a6559e589b49.png)
