### ISSUE TITLE
cmake error  ==> Harmonise configuration defaults #937

### ISSUE THREAD

**Issue by skyformat99** [ntop/n2n#939]
1) git clone lastest code   (Harmonise configuration defaults #937  version)
2) mkdir build  && cd build
3) cmake ..

CMake Warning (dev) in CMakeLists.txt:
  A logical block opening on the line

    /var/n2ngit/n2n/CMakeLists.txt:50 (if)

  closes on the line

    /var/n2ngit/n2n/CMakeLists.txt:52 (endif)

  with mis-matching arguments.
This warning is for project developers.  Use -Wno-dev to suppress it.

INFOUsing libpthread.
CMake Error at CMakeLists.txt:55 (target_link_libraries):
  Cannot specify link libraries for target "n2n" which is not built by this
  project.

-- Configuring incomplete, errors occurred!

**Comment by skyformat99** [comment]
sorry.
This issue has been resolved.

**Comment by hamishcoleman** [comment]
Thanks @skyformat99, this is actually a real bug that needed fixing - you should be able to compile with pthread enabled again now!
