### ISSUE TITLE
Edge exit without no more log

### ISSUE THREAD

**Issue by zwh6611** [ntop/n2n#94]
Hi, 
Now I build n2n in the armhf linux. and it was succeed. When I ran it as below. It seems no error. 
But I found the edge is exit without log. ( ps -aux | grep edge ==> return nothing).
And not n2n0 created at all ( ifconfig -a ==>can not see n2n0 ).
So how can I see more detail message ? 
```
root@htnice:~/n2n# ./edge -d n2n0 -c mynetwork -k encryptme -u 99 -g 99 -m 3C:A0:12:34:56:78 -a 1.2.3.4 -l edge.mydomain.com:81 -v
22/Apr/2019 19:57:58 [edge.c:285] Adding supernode[0] = edge.mydomain.com:81
22/Apr/2019 19:57:58 [edge.c:619] Starting n2n edge 2.5.0 Apr 22 2019 19:55:15
22/Apr/2019 19:57:58 [edge.c:622] supernode 0 => edge.mydomain.com:81

```

**Comment by zwh6611** [comment]
My OS is ubuntu 16.04 with Customized. Running on Industrial Controlling Computer.
And I try install n2n by type "apt-get install n2n", get  n2n v.1.3.2 for armv7l.
I ran it. 
And the error message is below.
`ERROR: ioctl() [No such file or directory][2]`

**Comment by zwh6611** [comment]
I found my OS is missing tun modules. I load it, and edge run fine.  But I suppose the message should be more detail

**Comment by Logan007** [comment]
Please try "-vvvv" or so instead of just "-v" .

**Comment by zwh6611** [comment]
> Please try "-vvvv" or so instead of just "-v" .

Can not see error message either when the OS is out of tun module. The edge program was build with dev branch.

**Comment by Logan007** [comment]
Oh, I see. You would like to see a dedicated error message in case the tun module is not loaded?

Interesting point. Never thought about that as for prod environment I start up the edges using some bash scripts that also include the modprobes (tun and tap - just to be safe) before and some routing after calling the edge command.

**Comment by emanuele-f** [comment]
Thank you for the suggestion.
