### ISSUE TITLE
macOS  Monterey 12.1  complile error

### ISSUE THREAD

**Issue by spacexnasa** [ntop/n2n#941]
git clone latest xxx 
cd n2n && mkdir build
cmake ../ 

-- The C compiler identification is AppleClang 13.0.0.13000029
-- The CXX compiler identification is AppleClang 13.0.0.13000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at CMakeLists.txt:2 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Build for version: 3.1.0-56-g3856d62
INFOUsing libpthread.
CMake Error at CMakeLists.txt:55 (target_link_libraries):
  Cannot specify link libraries for target "n2n" which is not built by this
  project.

-- Configuring incomplete, errors occurred!

**i have to change CMakeLists.txt
cmake_minimum_required(VERSION 2.6...3.22.2)**

and still have proble

-- Build for version: 3.1.0-56-g3856d62-dirty
INFOUsing libpthread.
CMake Error at CMakeLists.txt:55 (target_link_libraries):
  Cannot specify link libraries for target "n2n" which is not built by this
  project.

-- Configuring incomplete, errors occurred!

Harmonise configuration defaults #937 #939

still have problem

**Comment by hamishcoleman** [comment]
Hi @spacexnasa, I believe that the config issue you discovered is fixed in the latest dev commit - can you test and confirm?

(The CMake build path is not the most well supported one, so apologies for the disruptions - have you considered building with the Makefiles?)

**Comment by spacexnasa** [comment]
> Hi @spacexnasa, I believe that the config issue you discovered is fixed in the latest dev commit - can you test and confirm?
> 
> (The CMake build path is not the most well supported one, so apologies for the disruptions - have you considered building with the Makefiles?)

ok, tomorrow i will test again

**Comment by spacexnasa** [comment]
hello,@hamishcoleman
this is my step
cd n2n
git fetch

autogen.sh
LDFLAGS="-L/usr/local/opt/openssl@3/lib" CPPFLAGS="-I/usr/local/opt/openssl@3/include" ./configure --prefix=/usr/local/Cellar/n2n--enable-miniupnp --enable-natpmp --enable-pcap --enable-cap --enable-pthread --with-edgex --with-openssl

LDFLAGS="-L/usr/local/opt/openssl@1.1/lib" CPPFLAGS="-I/usr/local/opt/openssl@1.1/include" ./configure --prefix=/usr/local/Cellar/n2n--enable-miniupnp --enable-natpmp --enable-pcap --enable-cap --enable-pthread --with-edgex --with-openssl


checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
configure: Please contact us with your use case
checking for EVP_CIPHER_CTX_reset in -lcrypto... no
configure: error: openssl library not found

**Comment by spacexnasa** [comment]
again 
git clone https://github.com/ntop/n2n.git --recurse-submodules


mkdir -p build && cd build \
/usr/local/bin/cmake ../ -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1 \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/n2n \
-DCMAKE_OSX_ARCHITECTURES=x86_64 \
-DN2N_OPTION_USE_OPENSSL=ON \
-DN2N_OPTION_USE_PCAPLIB=ON \
-DN2N_OPTION_USE_PORTMAPPING=ON \
-DN2N_OPTION_USE_PTHREAD=ON \
-DN2N_OPTION_USE_ZSTD=OFF \
-DNO_GETADDRINFO=ON \
-DUPNPC_BUILD_SAMPLE=OFF \
-DUPNPC_BUILD_SHARED=ON \
-DUPNPC_BUILD_STATIC=ON \
-DUPNPC_BUILD_TESTS=OOFF \
-DUPNPC_NO_INSTALL=OFF

CMake Error at CMakeLists.txt:92 (MESSAGE):
  libpcap not support pcap_set_immediate_mode()
have to delete PCAPLIB 
so can work

**Comment by spacexnasa** [comment]
> > Hi @spacexnasa, I believe that the config issue you discovered is fixed in the latest dev commit - can you test and confirm?
> > (The CMake build path is not the most well supported one, so apologies for the disruptions - have you considered building with the Makefiles?)
> 
> ok, tomorrow i will test again

ok now

**Comment by hamishcoleman** [comment]
Looking at the makefile steps you pasted above, I am curious about a couple of things.  

Are you trying to cross compile?  There is a config option you have used (`--with-edgex`) that is only used during cross compiling, but the rest of your command doesnt suggest cross compiling to me.  This is probably why your configure is failing.

Also, the CPPFLAGS that you are using might not be the best way to pass paths into the build system (You could st instead setting CPATH to a colon separated list of dirs) but you will definitely need to set either of these env vars for both the configure and make steps.

Are you able to look at your config log to see what the compile/check error you are getting is?

Something like `grep -B3 "failed program" config.log` would give you a good starting point.
