### ISSUE TITLE
edge fails to compile

### ISSUE THREAD

**Issue by jfmaes** [ntop/n2n#944]
clean windows 10 vm; installed recommended toolchain 

compilation works for majority of exes but for edge; which is the most important one, it fails because of unresolved symbols
```
 C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt\stdio.h(1961): note: see declaration of '_snprintf'
libcrypto32MD.lib(libcrypto-lib-e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertOpenStore@20 referen
ced in function _capi_open_store [C:\Users\admin\Documents\n2n\build\edge.vcxproj]
libcrypto32MD.lib(libcrypto-lib-e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertCloseStore@8 referen
ced in function _capi_find_key [C:\Users\admin\Documents\n2n\build\edge.vcxproj]
libcrypto32MD.lib(libcrypto-lib-e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertEnumCertificatesInSt
ore@8 referenced in function _capi_find_cert [C:\Users\admin\Documents\n2n\build\edge.vcxproj]
libcrypto32MD.lib(libcrypto-lib-e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertFindCertificateInSto
re@24 referenced in function _capi_find_cert [C:\Users\admin\Documents\n2n\build\edge.vcxproj]
libcrypto32MD.lib(libcrypto-lib-e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertDuplicateCertificate
Context@4 referenced in function _capi_load_ssl_client_cert [C:\Users\admin\Documents\n2n\build\edge.vcxproj]
libcrypto32MD.lib(libcrypto-lib-e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertFreeCertificateConte
xt@4 referenced in function _capi_dsa_free [C:\Users\admin\Documents\n2n\build\edge.vcxproj]
libcrypto32MD.lib(libcrypto-lib-e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertGetCertificateContex
tProperty@16 referenced in function _capi_cert_get_fname [C:\Users\admin\Documents\n2n\build\edge.vcxproj]
C:\Users\admin\Documents\n2n\build\Release\edge.exe : fatal error LNK1120: 7 unresolved externals [C:\Users\admin\Docum
ents\n2n\build\edge.vcxproj]
```

**Comment by jfmaes** [comment]
this seems to have to do with trying to statically link the openssl library

**Comment by hamishcoleman** [comment]
can you describe fully your build process?

We have an auto-build for windows, which is currently succeeding - so it would be even better if you could start from that build and describe your differences.
(see `.github/workflows/tests.yml` section `test_windows`)

**Comment by jfmaes** [comment]
I'm following the exact build steps as outlined in the documentation. 
the `test.yml` file you are referencing is using the hacky bash script, I am compiling on Windows itself 

```
git submodule update --init --recursive
cmake -E make_directory build
cd build
cmake .. -DN2N_OPTION_USE_OPENSSL=ON -DOPENSSL_USE_STATIC_LIBS=true
cmake --build . --config Release
```

I should note without the static compilation, the build succeeds.

**Comment by hamishcoleman** [comment]
Oh, you are using cmake - the cmake build system is less well maintained.  

The hacky script is because windows is not friendly to automation, as opposed to the build is hacky.

I believe that some other people are building with static libraries, but none of them have shared their exact build steps.

Did this build process used to work for you and has stopped working as part of the recent  changes?

**Comment by jfmaes** [comment]
it is the first time I am trying to utilize n2n, I dont really have a lot of experience with this stuff 😅 
just tried to follow the documentation, will try doing it with the hack

**Comment by hamishcoleman** [comment]
Just tried a compile-test of your build process on Debian and it does indeed create a build with a static openssl binary.  So, I'm going to assume that this is a bug internal to the upstream cmake framework, and thus unlikely to be something we can fix.

However, there /should/ be a documented way to compile statically - I have not even tried to do any static builds, so I cannot really advise you.  But, I am happy to try and help you try it :-)

**Comment by hamishcoleman** [comment]
(Oh, and my medium-term plan is to remove that hack from the Makefile Windows build - it is case of slowly shrinking the things that depend on it)

**Comment by jfmaes** [comment]
I'll just build on a debian, no worries, I think that will be easier
could be that I just have a wrong openssl version or something, this can be hard to troubleshoot.
thanks for the superfast responsetimes

tried to compile in debian using the workflow but now I do not see any .exes

**Comment by hamishcoleman** [comment]
No worries - and happy compiling!

I've made a note to go and refactor the documentation you followed - hopefully we will not be recommending broken things to people :-S

**Comment by jfmaes** [comment]
hey @hamishcoleman  
ever seen this before 

```
8/Jan/2022 13:52:11 [supernode.c: 317] WARNING: Received packet too short [len=75]
28/Jan/2022 13:52:15 [supernode.c: 317] WARNING: Received packet too short [len=75]
28/Jan/2022 13:52:19 [supernode.c: 317] WARNING: Received packet too short [len=75]
28/Jan/2022 13:52:23 [supernode.c: 317] WARNING: Received packet too short [len=75]
28/Jan/2022 13:52:27 [supernode.c: 317] WARNING: Received packet too short [len=75]
28/Jan/2022 13:52:31 [supernode.c: 317] WARNING: Received packet too short [len=75]
28/Jan/2022 13:52:35 [supernode.c: 317] WARNING: Received packet too short [len=75]
28/Jan/2022 13:52:39 [supernode.c: 317] WARNING: Received packet too short [len=75]
28/Jan/2022 13:52:41 [supernode.c: 317] WARNING: Received packet too short [len=36]
28/Jan/2022 13:52:43 [supernode.c: 317] WARNING: Received packet too short [len=75]
28/Jan/2022 13:52:47 [supernode.c: 317] WARNING: Received packet too short [len=75]
28/Jan/2022 13:52:51 [supernode.c: 317] WARNING: Received packet too short [len=75]

```

seems like my windows edge is screwing up somehow

**Comment by hamishcoleman** [comment]
I cannot find that string in the current source code - what version is this from?
(Actually, I cannot find it in the history of supernode.c either)

**Comment by jfmaes** [comment]
i used apt install, but now I built it from source and it works fine.. meh :D closing this issue

**Comment by hamishcoleman** [comment]
Oh, yeah, the version of n2n in the debian repos is from the stone age :-(

**Comment by hamishcoleman** [comment]
Just for a small amount of closure, I had a chance to do a quick build on my windows test VM and got exactly the same errors with `-DOPENSSL_USE_STATIC_LIBS=true`, and a successful build with dynamic linking.

Clearly, something has broken since the original instructions were written :-(
