### ISSUE TITLE
udp hole

### ISSUE THREAD

**Issue by zjbdiy** [ntop/n2n#946]
Sorry to bother you, this paragraph is machine translation, please forgive me
I try to implement udp hole punching algorithm with c#
Now there are 3 devices a,b,s
a, b are windows s are centos7
There is a fixed ip on the s side and open ports 3000 and 3001
a and b are both registered to the s side
The s side obtains the same external network ports as a and b, and judges that the network type is cone

now i have a problem
a->b or b->a
All need b to send a message to a first to make a hole to establish

This is different from what I expected, a->b , b first b->a , a first

any help

**Comment by Logan007** [comment]
I do not know your algorithm in detail, but [this](https://luca.ntop.org/n2n.pdf) explains how n2n does it.

**Comment by Logan007** [comment]
considered answered, please re-open if required
