### ISSUE TITLE
Do you have a benchmark on n2n VPN?

### ISSUE THREAD

**Issue by maxyang2008** [ntop/n2n#95]
Hello,
I am sorry for disturbing you.
I just want to know if you have a network benchmark on n2n VPN?

I am using the 2.5.0 version of n2n VPN.
I have a benchmark on my lab environment and have a maxspeed around 400 mbps in a 1Gbps environment.
What is the highest speed you get in you lab environment?

Thanks.

**Comment by emanuele-f** [comment]
Hi, for the encryption test you can run the `./benchmark` program from this repository, which yields the following results on my pc (i3):
```
Run enc[transop_null] for 3s (512 bytes):   	    10934945 packets	  3645.0 Kpps	  1866.2 MB/s
Run enc[transop_twofish] for 3s (512 bytes):   	       59450 packets	    19.8 Kpps	    10.1 MB/s
Run enc[transop_aes] for 3s (512 bytes):   	      441449 packets	   147.1 Kpps	    75.3 MB/s
```

That would give you upper bounds for throughput, network rates should be a little lower than that. Maybe you can try the following tests:
- transop_null: is n2n without encryption, (remove the `-k` parameter from n2n)
- transop_twofish: is n2n with twofish encryption, (with the -`k` parameter)
- transop_aes: is n2n with AES encryption, (with the -`k` and `-A` parameters)

**Comment by maxyang2008** [comment]
Thanks a lot, I will try to use the benchmark utility.

**Comment by emanuele-f** [comment]
You are welcome! Please open a issue if you have further questions!
