### ISSUE TITLE
can you help to check what happened?

### ISSUE THREAD

**Issue by galaxyskyknight** [ntop/n2n#955]
when I configure to use portmap and upnp enabled, then compile there are errors. see the screen out

```

root@al:~/n2n-3.0# make clean
rm -rf  src/auth.o  src/transform_aes.o  src/network_traffic_filter.o  src/tuntap_osx.o  src/n2n_port_mapping.o  src/speck.o  src/sn_management.o  src/minilzo.o  src/example_edge_embed.o  src/sn_utils.o  src/tf.o  src/cc20.o  src/edge_utils_win32.o  src/example_sn_embed.o  src/edge.o  src/transform_speck.o  src/hexdump.o  src/tuntap_linux.o  src/tuntap_netbsd.o  src/transform_null.o  src/pearson.o  src/example_edge_embed_quick_edge_init.o  src/transform_tf.o  src/n2n_regex.o  src/curve25519.o  src/n2n.o  src/random_numbers.o  src/wire.o  src/aes.o  src/edge_management.o  src/header_encryption.o  src/edge_utils.o  src/tuntap_freebsd.o  src/supernode.o  src/sn_selection.o  src/transform_cc20.o libn2n.a edge supernode example_edge_embed_quick_edge_init example_edge_embed example_sn_embed edge.8.gz supernode.1.gz n2n.7.gz coverage/ *.dSYM *~
rm -f tests/*.out src/*.gcno src/*.gcda
for dir in tools; do make -C $dir clean; done
make[1]: Entering directory '/root/n2n-3.0/tools'
rm -rf n2n-benchmark n2n-keygen  *.o *.dSYM *~
rm -f tests-compress tests-elliptic tests-hashing tests-transform tests-wire tests-auth *.gcno *.gcda
make[1]: Leaving directory '/root/n2n-3.0/tools'

root@al:~/n2n-3.0# git pull
remote: Enumerating objects: 46, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 46 (delta 28), reused 20 (delta 13), pack-reused 0
Unpacking objects: 100% (46/46), done.
From https://github.com/ntop/n2n
   45520f3..af39fa1  dev        -> origin/dev
   0177e14..bde7831  3.0-stable -> origin/3.0-stable
Updating 45520f3..af39fa1
Fast-forward
 .github/workflows/tests.yml |   1 +
 CMakeLists.txt              | 162 +++++++++++++++++++++++++++++++++++++++++++--------------------------------
 configure.ac                |   4 ++
 doc/BuildConfig.md          | 132 +++++++++++++++++++++++++++++++++++++++----------------------
 doc/Building.md             | 126 +++++++++++++++++++++++++++++++++-------------------------
 scripts/cmake_all.sh        |  38 ++++++++++++++++++
 src/n2n_port_mapping.c      |   3 +-
 7 files changed, 295 insertions(+), 171 deletions(-)
 create mode 100755 scripts/cmake_all.sh
root@al:~/n2n-3.0# ./autogen.sh
Wait please...
root@al:~/n2n-3.0# ./configure --enable-natpmp --enable-miniupnp
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for upnpDiscover in -lminiupnpc... yes
checking for initnatpmp in -lnatpmp... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating tools/Makefile
config.status: creating include/config.h
root@al:~/n2n-3.0# make all
Build for version: 3.1.0-62-gaf39fa1
gcc -g -O2 -I ./include    -Wall     -c -o src/edge.o src/edge.c
gcc -g -O2 -I ./include    -Wall     -c -o src/transform_aes.o src/transform_aes.c
gcc -g -O2 -I ./include    -Wall     -c -o src/tuntap_osx.o src/tuntap_osx.c
gcc -g -O2 -I ./include    -Wall     -c -o src/n2n_port_mapping.o src/n2n_port_mapping.c
src/n2n_port_mapping.c:482:13: warning: ‘n2n_del_port_mapping’ defined but not used [-Wunused-function]
 static void n2n_del_port_mapping (const uint16_t port) {
             ^~~~~~~~~~~~~~~~~~~~
src/n2n_port_mapping.c:468:13: warning: ‘n2n_set_port_mapping’ defined but not used [-Wunused-function]
 static void n2n_set_port_mapping (const uint16_t port) {
             ^~~~~~~~~~~~~~~~~~~~
gcc -g -O2 -I ./include    -Wall     -c -o src/speck.o src/speck.c
gcc -g -O2 -I ./include    -Wall     -c -o src/sn_management.o src/sn_management.c
gcc -g -O2 -I ./include    -Wall     -c -o src/example_edge_embed.o src/example_edge_embed.c
gcc -g -O2 -I ./include    -Wall     -c -o src/sn_utils.o src/sn_utils.c
gcc -g -O2 -I ./include    -Wall     -c -o src/network_traffic_filter.o src/network_traffic_filter.c
gcc -g -O2 -I ./include    -Wall     -c -o src/tf.o src/tf.c
gcc -g -O2 -I ./include    -Wall     -c -o src/cc20.o src/cc20.c
gcc -g -O2 -I ./include    -Wall     -c -o src/edge_utils_win32.o src/edge_utils_win32.c
gcc -g -O2 -I ./include    -Wall     -c -o src/example_sn_embed.o src/example_sn_embed.c
gcc -g -O2 -I ./include    -Wall     -c -o src/auth.o src/auth.c
gcc -g -O2 -I ./include    -Wall     -c -o src/transform_cc20.o src/transform_cc20.c
gcc -g -O2 -I ./include    -Wall     -c -o src/hexdump.o src/hexdump.c
gcc -g -O2 -I ./include    -Wall     -c -o src/tuntap_linux.o src/tuntap_linux.c
gcc -g -O2 -I ./include    -Wall     -c -o src/tuntap_netbsd.o src/tuntap_netbsd.c
gcc -g -O2 -I ./include    -Wall     -c -o src/wire.o src/wire.c
gcc -g -O2 -I ./include    -Wall     -c -o src/transform_null.o src/transform_null.c
gcc -g -O2 -I ./include    -Wall     -c -o src/pearson.o src/pearson.c
gcc -g -O2 -I ./include    -Wall     -c -o src/supernode.o src/supernode.c
gcc -g -O2 -I ./include    -Wall     -c -o src/example_edge_embed_quick_edge_init.o src/example_edge_embed_quick_edge_init.c
gcc -g -O2 -I ./include    -Wall     -c -o src/transform_tf.o src/transform_tf.c
gcc -g -O2 -I ./include    -Wall     -c -o src/n2n_regex.o src/n2n_regex.c
gcc -g -O2 -I ./include    -Wall     -c -o src/curve25519.o src/curve25519.c
gcc -g -O2 -I ./include    -Wall     -c -o src/random_numbers.o src/random_numbers.c
gcc -g -O2 -I ./include    -Wall     -c -o src/minilzo.o src/minilzo.c
gcc -g -O2 -I ./include    -Wall     -c -o src/aes.o src/aes.c
gcc -g -O2 -I ./include    -Wall     -c -o src/edge_management.o src/edge_management.c
gcc -g -O2 -I ./include    -Wall     -c -o src/header_encryption.o src/header_encryption.c
gcc -g -O2 -I ./include    -Wall     -c -o src/edge_utils.o src/edge_utils.c
gcc -g -O2 -I ./include    -Wall     -c -o src/n2n.o src/n2n.c
gcc -g -O2 -I ./include    -Wall     -c -o src/tuntap_freebsd.o src/tuntap_freebsd.c
gcc -g -O2 -I ./include    -Wall     -c -o src/transform_speck.o src/transform_speck.c
gcc -g -O2 -I ./include    -Wall     -c -o src/sn_selection.o src/sn_selection.c
ar rcs libn2n.a  src/example_sn_embed.o  src/auth.o  src/tuntap_osx.o  src/example_edge_embed.o  src/network_traffic_filter.o  src/minilzo.o  src/sn_utils.o  src/wire.o  src/transform_aes.o  src/pearson.o  src/supernode.o  src/example_edge_embed_quick_edge_init.o  src/cc20.o  src/tuntap_netbsd.o  src/edge_management.o  src/edge_utils.o  src/n2n.o  src/tuntap_freebsd.o  src/n2n_port_mapping.o  src/random_numbers.o  src/speck.o  src/sn_management.o  src/transform_tf.o  src/edge_utils_win32.o  src/edge.o  src/transform_cc20.o  src/hexdump.o  src/tuntap_linux.o  src/n2n_regex.o  src/transform_null.o  src/tf.o  src/curve25519.o  src/aes.o  src/header_encryption.o  src/transform_speck.o  src/sn_selection.o
gcc -L .  src/edge.o libn2n.a   -ln2n -lnatpmp -lminiupnpc  -o src/edge
/usr/bin/ld: libn2n.a(edge_utils.o): in function `supernode_connect':
/root/n2n-3.0/src/edge_utils.c:341: undefined reference to `n2n_chg_port_mapping'
collect2: error: ld returned 1 exit status
make: *** [<builtin>: src/edge] Error 1
root@al:~/n2n-3.0#

```

**Comment by hamishcoleman** [comment]
both the upnp options require pthread to be enabled.

**Comment by galaxyskyknight** [comment]
> pthread

I remember in the past those options are enabled by default, why now change it to specify by manual

**Comment by hamishcoleman** [comment]
All the options have been changed to not autodetect, this was done for several reasons.
- there were multiple different strategies in the enable logic, this made them all the same
- autodetection logic is needs to be significantly more complicated once you start to cross-compile and what we had was not working
- some options were not even possible to turn off
- the build becomes less repeatable as it relied on externalities to decide what features to include.

**Comment by lucktu** [comment]
It is recommended that you select upnp, turn on pthread by default, or give a clear error message.

**Comment by hamishcoleman** [comment]
For the moment, I will be adding a clear error message. (We already have clarified the documentation)

I'm trying to simplify the configuration logic, so I am hesitant to add the default turn on of options.

**Comment by galaxyskyknight** [comment]
> For the moment, I will be adding a clear error message. (We already have clarified the documentation)
> 
> I'm trying to simplify the configuration logic, so I am hesitant to add the default turn on of options.

btw: can you illustarte how to enable natmap and miniupnp under windows compile? ( I use VS2019) thanks

**Comment by hamishcoleman** [comment]
Sorry @galaxyskyknight , I have never used Visual Studio.  We do have two documented methods to compile on Windows, but nothing specific for enabling natpmp or miniupnp.

**Comment by galaxyskyknight** [comment]
> Sorry @galaxyskyknight , I have never used Visual Studio. We do have two documented methods to compile on Windows, but nothing specific for enabling natpmp or miniupnp.

@Logan007 do you have any idea? I cannot find any clue in doc that illustrace how to enable natpmp/miniupnpc under windows compile, since this is not enabled by defaut and need manuelly enable, how come it does not described in document but take it away instead of  being default enabled?

**Comment by Logan007** [comment]
> I cannot find any clue in doc that illustrace how to enable natpmp/miniupnpc under windows compile

> how come it does not described in document

We do the development on Linux which has the advantage of being a good blueprint for quite a lot of other OS. From a programmer's perspective, Windows is the one systems standing out a bit in terms of requiring additional efforts to make it run. 

We definitely want to have n2n run on Windows, but it is not our very first top priority during the currently up-ramping development phase of _dev_ branch. Especially, as we might see some changes in how functionalities are divided among the n2n core and n2n utilities. I am confident that we will see Windows version being built much easier at some point.

I do not use Windows on a regular basis. Mabye the old instructions still work, just try to turn on the required features in the CMake file?

> take it away instead of being default enabled?

We have disabled **all** additional libraries by default to allow for better testing of a core version of n2n. This core version shall have a minimum of dependencies – if any at all.

**Comment by galaxyskyknight** [comment]
> > I cannot find any clue in doc that illustrace how to enable natpmp/miniupnpc under windows compile
> 
> > how come it does not described in document
> 
> We do the development on Linux which has the advantage of being a good blueprint for quite a lot of other OS. From a programmer's perspective, Windows is the one systems standing out a bit in terms of requiring additional efforts to make it run.
> 
I believe the basic two senario are that the users need this build running on a windows PC is:
1) connect to intranet or internal infrastructure to do some maintenance job
2) like Game playing, 
so I think this windows build is still have the proper senario to support.
 
> We definitely want to have n2n run on Windows, but it is not our very first top priority during the currently up-ramping development phase of _dev_ branch. Especially, as we might see some changes in how functionalities are divided among the n2n core and n2n utilities. I am confident that we will see Windows version being built much easier at some point.
> 
> I do not use Windows on a regular basis. Mabye the old instructions still work, just try to turn on the required features in the CMake file?
> 
> > take it away instead of being default enabled?
> 
> We have disabled **all** additional libraries by default to allow for better testing of a core version of n2n. This core version shall have a minimum of dependencies – if any at all.

So I still not got the points and answers, is there any way to enable the natpmp and miniupnpc function for windows build? you mentioned turn on the CMakefile, should I use the compile macro like -DXXXX for both above two modules? for windows, it there any addtional library need to be pre-installed or it is system embedded there?

**Comment by Logan007** [comment]
> basic two senario are that the users need this build running on a windows PC

Yes, those scenarios are very likely.

> so I think this windows build is still have the proper senario to support.

Sure. And **stable** versions for Windows are available.

With a view to port forwarding, please keep in mind that we are talking about **_dev_** branch which is still under _development_. I should have emphasized more that we currently are focusing on n2n core before turning back to the other functionalities again. 

> So I still not got the points and answers, is there any way to enable the natpmp and miniupnpc function for windows build?

I actually do not know. The following hints are just guesses without having tried it (for the reasons given above).

> for windows, it there any addtional library need to be pre-installed or it is system embedded there?

You should have downloaded the submodules as described in our [Building documentation](https://github.com/ntop/n2n/blob/dev/doc/Building.md#git-submodules).

> you mentioned turn on the CMakefile, should I use the compile macro like -DXXXX for both above two modules? 

You might want to try turning `N2N_OPTION_USE_PTHREAD` and `N2N_OPTION_USE_PORTMAPPING` options from `OFF` to `ON` in `CMakeLists.txt` file (line 40 and line 45). It can be achieved using the corresponding command line options as described in our [Build Config documentation](https://github.com/ntop/n2n/blob/dev/doc/BuildConfig.md#cmake-configuration).

**Comment by galaxyskyknight** [comment]
>
I followed you steps and successfully build the windows binary WITHOUT enable pthread/portmapping, however when I try to enable pthread/portmapping, it prompts that the libpthread not found, where can I get this for windows? is it supported on windows platform?

![image](https://user-images.githubusercontent.com/66289873/153987071-91d46fc9-3dd6-4f6c-a9bf-c29affe1ae5b.png)

**Comment by Logan007** [comment]
You could try without the PTHREAD option (only with the PORTMAPPING then)  because Windows version already has its own replacement for thread related things.

**Comment by galaxyskyknight** [comment]
> You could try without the PTHREAD option (only with the PORTMAPPING then) because Windows version already has its own replacement for thread related things.

awesome！it fianlly worked! thanks a lot.
btw:  how the natpmp and upnp works? Can it work across the different subnet? say I have 192.168.1.x and 192.168.2.x behind two different routers and two routers are connected via n2n edges running on these two OpenWRT routers with P2P mode and the traffic  pass through the internet. Can those UPNP devices behind each router discovery the peer subnet's UPNP devices like a transparent local LAN does(on each routers have previously assigned the static routes for 1.x/2.x subnet and make sure the subnets could be icmp ping reachable via n2n )? is that the proper senario?

sorry I still confused what can natpmp and upnp can do for its function. please help to clarify those two functions' meaning on top of n2n.   thanks again.

**Comment by Logan007** [comment]
> awesome！it fianlly worked! thanks a lot

I am glad you got it working.

> how the natpmp and upnp works?

As far as I know, it should help to have the local router (same subnet) open a port for an n2n edge to the outside world. This way, it should be easier for edges behind the router to connect p2p to other edges.

I am not sure about your scenario.

> sorry I still confused what can natpmp and upnp can do for its function. please help to clarify those two functions' meaning on top of n2n.

Maybe @lucktu or @fengdaolong know?

**Comment by lucktu** [comment]
If edge_a has an external ip address and router set port_mapping to the edge_a, then the edge_a can be directly connected to others(p2p).

And upnp(natpmp) can automatically complete port_mapping operations.

**Comment by fengdaolong** [comment]
>sorry I still confused what can natpmp and upnp can do for its function. please help to clarify those two functions' meaning on top of n2n.

upnp/natpmp is to map the internal network port to the external network port. It just forces the NAT mode of the edge in your internal network to `full cone` to improve the probability of point-to-point direct connection.

**Comment by Logan007** [comment]
considered answered, please re-open if required

**Comment by stardustzh** [comment]
> > sorry I still confused what can natpmp and upnp can do for its function. please help to clarify those two functions' meaning on top of n2n.
> 
> upnp/natpmp is to map the internal network port to the external network port. It just forces the NAT mode of the edge in your internal network to `full cone` to improve the probability of point-to-point direct connection.

Can edge use upnp and nat-pmp functions automatically?

**Comment by Logan007** [comment]
We have just moved the upnp/pmp feature into its very own `tools/n2n-portfwd` tool to relieve the n2n core from non-essential non-core functionality.

It will not start up automatically with the edge, you would have to put it into your start-up script or batch file.

The tool works very well on Linux (_and probably Windows_) and handles everything automatically. ~~It probably will still have issues in Windows due to a lacking call to [`WSAStartup()`](https://github.com/ntop/n2n/pull/1023/commits/863e2b89bd7a1456160cc0dfdcc12c0608227853)~~ ... ~~coming soon~~ _done_.
