### ISSUE TITLE
#svn co https://svn.ntop.org/svn/ntop/trunk/n2n

### ISSUE THREAD

**Issue by loveys-dev** [ntop/n2n#957]
Hi,

I'm trying to use this code for initiating aa peer to peer VPN connection, to install Oracle RAC on Azure, however, by executing the URL: https://svn.ntop.org/svn/ntop/trunk/n2n , it gave a 404 (Sorry, This Page Does not exist.
Go [home](https://www.ntop.org/) or try a search?

Linux version: 7
Oracle DB Version: 19c

Any help?
Thank,

**Comment by hamishcoleman** [comment]
The n2n source code is not stored in SVN - you can get the source code from this github repository (https://github.com/ntop/n2n)

Are you following some documentation?  Can you let us know what it is?  Perhaps we can get them to remove any reference to SVN.

**Comment by loveys-dev** [comment]
HI,
I'm following this document.

https://blog.pythian.com/network-multicast-support-azure/

Thanks,

**Comment by hamishcoleman** [comment]
An interesting post - and still a good use case for n2n - however, I was hoping that you had found some documentation under the control of the n2n project.  It is difficult to update 8 year old blog posts!

That being said, you should be able to follow our current documentation to install n2n and would be able to achieve the multicast support from that article.  You can even turn off encryption and compression these days without applying any patches.

**Comment by loveys-dev** [comment]
Is there any specific link to download the software along with a document for a step by step installation?
I want to install this on RHEL version 7.

Thank you again,

**Comment by hamishcoleman** [comment]
We dont specifically test with RHEL, but we do build an RPM, so you can try the latest stable release: 
- https://github.com/ntop/n2n/releases/tag/3.0

I cannot recall if there is a step-by-step guide, you should look at the extensive documentation: https://github.com/ntop/n2n/tree/dev/doc

But the basic steps are:
- The rpm comes with systemd units and example config in /etc/n2n
- You will need a supernode to use - there is a public one at supernode.ntop.org:7777 or you could run your own
- On each of your nodes, you should copy `/etc/n2n/edge.conf.sample` to `/etc/n2n/edge-$yourname.conf` and edit it to set your supernode, local ip, community name and add the options for multicast support (and any compression and encryption settings) from the man page
- Once you have the config file, you can start the edge with `systemctl start edge@$yourname`

**Comment by loveys-dev** [comment]
Dear,

Kindly we need your assistance, to get more information to understand what exactly need to done in order to prevent / by-pass multicast issue by using this,

I have gone through the entire N2N blog couldn’t find any suitable information,

**Comment by Logan007** [comment]
If you got a working n2n connection by following the steps listed [above](https://github.com/ntop/n2n/issues/957#issuecomment-1037199931), it is the `-E` parameter at the edges which makes them accept multicast packets at the TAP. By default, i.e. without `-E`, multicast packets are dropped and not forwarded.

**Comment by loveys-dev** [comment]
Hi,
Multicast issue still exist,  

	Supernode daemon configured.
	Edge configured on Private interface (both nodes).
	Node1 all cluster stack working.
	Node2 failing.

Please assist by checking, if there any other specific configuration required for Edge/supernode.

**Comment by loveys-dev** [comment]
any thoughts of how i can overcome this issuer, and continue the installation of my DB?

**Comment by Logan007** [comment]
I do not know about the database, but were able to get a working n2n connection between the two nodes?

And both edges have `-E` and `-r` as additional parameters?

**Comment by loveys-dev** [comment]
Edge configuration doesn’t contain those variables in the conf. please find below the configuration:

```
[root@testvm2 bin]# cat /etc/n2n/edge.conf
#
#         The configuration file is similar to the command line, with one option per line. An equal
#        sign '=' should be used between key and value. Example: -c=mynetwork or --community=mynetwork
#        This file contains a basic configuration example, please refer to the help (-h) for the full
#        list of available options.
#
#       -d|--tun-device
#        Specifies the name of the TUN interface.
#
-d=n2n0
#
#       -c|--community
#        Specifies the n2n community name the edge belongs to.
#
-c=eth1
#
#       -k
#        Sets the encryption key (ASCII). The environment variable N2N_KEY=<key> can also be used.
#
-k=mypassword
#
#       -m
#        Specified the MAC address for the TAP interface (random otherwise).
#
# -m=DE:AD:BE:EF:99:99
#
#       -a
#        Sets the interface address. For DHCP use '-r -a dhcp:0.0.0.0'.
#
-a=192.168.4.7
#
#       -p
#        Sets the local UDP port to a fixed port.
#
-p=50001
#
#       -l|--supernode-list
#        Specifies the supernode IP and port.
#
-l=192.168.5.29:8888
#
```

**Comment by loveys-dev** [comment]
any help here?

**Comment by loveys-dev** [comment]
@Logan007  @emanuele-f I would like to seek your support

**Comment by lucktu** [comment]
Here's some information, you can look:
supernode.ml

**Comment by Logan007** [comment]
> @Logan007 @emanuele-f I would like to seek your support

I need to ask again, were you able to get a working n2n connection between the two nodes? Does a `ping 192.168.4.7` or vice versa work?

> > And both edges have `-E` and `-r` as additional parameters?

> Edge configuration doesn’t contain those variables in the conf.

Then please add `-E` and `-r` to the edges. As stated above (and in that other article), these options are required for enabling multicast.

**Comment by baqarkhan** [comment]
Hello,

I have done adding -E -r additional parameters for edges , still it shows multicast issue.
n2n is working from both end able to ping each other.

**Comment by Logan007** [comment]
> n2n is working from both end able to ping each other

This is a good basis to start from.

> I have done adding -E -r additional parameters for edges 

This should have enabled multicast.

> still it shows multicast issue

I am not sure what you mean by _multicast issue_. I have multicast working with `-E` (and `-r`).

But you can generally check if multicast works: Just run an `omping <local_n2n_ip_address> <remote_n2n_ip_address>` command at both edges.

**Comment by baqarkhan** [comment]
Hello

When i install Grid infrastructure, Only Node1 run root.sh successfully,
where as Node2 failing with the Multicast issue.

Do you have any reference to plum n2n with mtu size 1500..?

**Comment by Logan007** [comment]
> When i install Grid infrastructure, Only Node1 run root.sh successfully

I do not think that `root.sh` is part of n2n. I am not sure if anyone around _here_ can offer support for that.

> where as Node2 failing with the Multicast issue.

What exactly is the _Multicast issue_? I do not understand.

> Do you have any reference to plum n2n with mtu size 1500..?

Would edge's `-M 1500` work for you?

You might want to check `edge --help` and maybe our advanced documentation on [MTU](https://github.com/ntop/n2n/blob/dev/doc/TapConfiguration.md#mtu) from the project's `doc/` folder.

**Comment by Logan007** [comment]
considered answered as far as n2n is concerned, please re-open if required
