### ISSUE TITLE
is there any impact to the broadcast traffic which make the P2P network unreachable from recent change?

### ISSUE THREAD

**Issue by galaxyskyknight** [ntop/n2n#962]
I saw a lot of logs there like this in OpenWRT system log from edge daemon: and the p2p network is unreachable, I am wondering if this is related to the recent broadcast limitation change, what is that change did and impact at all? can you guys give a hint? thanks

Mon Feb 21 17:11:21 2022 daemon.info n2n[9646]: WARNING: sendto failed (101) Network unreachable
Mon Feb 21 17:11:21 2022 daemon.info n2n[9646]: WARNING: sendto failed (101) Network unreachable
Mon Feb 21 17:11:21 2022 daemon.info n2n[9646]: WARNING: sendto failed (101) Network unreachable
Mon Feb 21 17:11:22 2022 daemon.info n2n[9646]: WARNING: sendto failed (101) Network unreachable
Mon Feb 21 17:11:23 2022 daemon.info n2n[9646]: WARNING: sendto failed (101) Network unreachable
Mon Feb 21 17:11:23 2022 daemon.info n2n[9646]: WARNING: sendto failed (101) Network unreachable
Mon Feb 21 17:11:23 2022 daemon.info n2n[9646]: WARNING: sendto failed (101) Network unreachable
Mon Feb 21 17:11:24 2022 daemon.info n2n[9646]: WARNING: sendto failed (101) Network unreachable
Mon Feb 21 17:11:24 2022 daemon.info n2n[9646]: WARNING: sendto failed (101) Network unreachable
Mon Feb 21 17:11:24 2022 daemon.info n2n[9646]: WARNING: sendto failed (101) Network unreachable
Mon Feb 21 17:11:24 2022 daemon.info n2n[9646]: WARNING: sendto failed (101) Network unreachable
Mon Feb 21 17:11:24 2022 daemon.info n2n[9646]: WARNING: sendto failed (101) Network unreachable
Mon Feb 21 17:11:24 2022 daemon.info n2n[9646]: WARNING: sendto failed (101) Network unreachable

**Comment by Logan007** [comment]
> recent broadcast limitation change

What exact change are you referring to?

> can you guys give a hint?

Just guessing here and in case it actually is broadcast-related (which I do not know), does your system have a default gateway configured?

**Comment by GreatMichaelLee** [comment]
> > recent broadcast limitation change
> 
> What exact change are you referring to?
> 
> > can you guys give a hint?
> 
> Just guessing here and in case it actually is broadcast-related (which I do not know), does your system have a default gateway configured?

I mean change #958

**Comment by Logan007** [comment]
#958 is for making sure that broadcasts inside the **virtual** network only get forwarded to active federated supernodes (not the inactive ones anymore).

The `sendto` error message from your log indicates some issue with the underlying **real** network.

So my first guess here would be that it is not related. But maybe we can hear more opinions on this?

**Comment by galaxyskyknight** [comment]
Checked. Configuration problem, thanks!
