### ISSUE TITLE
I don't understand Supernode IP address assignment with -a

### ISSUE THREAD

**Issue by jradxl** [ntop/n2n#967]
In documentation and --help, -a example is:-
```
-a <net-net/n>, --autoip=<net-net/n>
              subnet range for auto ip address service,
              e.g.  '-a 192.168.0.0-192.168.255.0/24',
```
OK, someone might want these number of networks!!!
I just want a single /24 range from 192.168.195.0 to 192.168.195.255

but -a does not like this....
```
#supernode /etc/n2n/supernode.conf -f
15/Mar/2022 17:32:45 [supernode.c:255] WARNING: bad network range '192.168.195.0...192.168.195.255/24' in '192.168.195.0-192.168.195.255/24', defaulting to '10.128.0.0...10.255.255.0/24'
```
To get what I want, I need to specify...
-a=192.168.194.0-192.168.195.0/24
OR
-a=192.168.195.0-192.168.195.0/24

```(faked IP numbers)
# supernode /etc/n2n/supernode.conf -f
15/Mar/2022 17:34:26 [supernode.c:268] the network range for community ip address service is '192.168.194.0...192.168.195.0/24'
15/Mar/2022 17:34:26 [n2n.c:288] supernode2sock successfully resolves supernode IPv4 address for 51.89.999.999
15/Mar/2022 17:34:26 [sn_utils.c:1396] send REGISTER_SUPER to 51.89.999.999:6432
15/Mar/2022 17:34:26 [sn_utils.c:569] sent 79 bytes to [51.89.999.999:6432]
15/Mar/2022 17:34:26 [sn_utils.c:485] ERROR: sendto failed (88) Socket operation on non-socket
15/Mar/2022 17:34:26 [sn_utils.c:400] added allowed community 'foobarnetwork' [total: 1]
15/Mar/2022 17:34:26 [sn_utils.c:1295] assigned sub-network 192.168.195.0/24 to community 'foobarnetwork'
```
It's as if someone has made an elementary programming mistake with either -1 or counting from Zero!

Version
n2n/now 3.0.0-1038 amd64 [installed,local]
Ubuntu Focal

Go on, tell me I'm rather old fashioned!

**Comment by jradxl** [comment]
OK. now I've noticed
<net-net/n>
So ignore me...
Just I've having to go through in detail as n2n isn't working for me..

**Comment by Logan007** [comment]
Hey there,

Oh, you are very fast in answering your questions ... :wink:

Yes, at the supernode, `-a` specifies the **net**work range, so first and last usable network.

> `-a=192.168.194.0-192.168.195.0/24`

This would allow two different networks (depending on the community name and which one is still is available).

> Just I've having to go through in detail as n2n isn't working for me..

Do you need any help with your use case?

**Comment by Logan007** [comment]
Let me add as a post script that you also could specify the network along with a fixed community name in the `-c <community.list>`-provided file to the supernode, see the comments in exemplary `community.list` file from the repo.

**Comment by jradxl** [comment]
Thank you!
I'd not scrolled down that document far enough and had missed.
That's a much better way of assigning a network.
Thx
