### ISSUE TITLE
Oracle Cloud Free Tier has an internal network?

### ISSUE THREAD

**Issue by jradxl** [ntop/n2n#968]
As with Scaleway and Upcloud, Oracle Cloud has an internal network
Or course there is a public IP address too!

```
# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 02:00:17:05:5c:82 brd ff:ff:ff:ff:ff:ff
    altname enp0s3
    inet 10.0.0.56/24 brd 10.0.0.255 scope global ens3
       valid_lft forever preferred_lft forever
    inet6 fe80::17ff:fe05:5c82/64 scope link 
       valid_lft forever preferred_lft forever
10: n2n0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1290 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/ether 62:da:23:e0:c4:a3 brd ff:ff:ff:ff:ff:ff
    inet 192.168.195.3/24 brd 192.168.195.255 scope global n2n0
       valid_lft forever preferred_lft forever
```

On 10.0.0.51 (public 777.666.555.139)  (another of my free Oracle Cloud instances) I get this...
(Faked IP numbers)
```
Mar 16 13:44:30 vps-may edge[36360]: 16/Mar/2022 13:44:30 [edge_utils.c:2730] [OK] edge <<< ================ >>> supernode
Mar 16 14:05:21 vps-may edge[36360]: 16/Mar/2022 14:05:21 [edge_utils.c:975] peer 62:DA:23:E0:C4:A3 changed [777.666.555.139:5432] -> [10.0.0.56:5432]
Mar 16 14:05:25 vps-may edge[36360]: 16/Mar/2022 14:05:25 [edge_utils.c:975] peer 62:DA:23:E0:C4:A3 changed [10.0.0.56:5432] -> [777.666.555.139:5432]
```
Clearly the two edges are communicating on port 5432

Edge.conf in use
```
# cat edge.conf
-d=n2n0
-c=jsrsoft
-k=<secret>
-m=62:DA:23:E0:C4:A2
-e=auto
-a=192.168.195.2/24
-p=5432
-H
-P=<verysecret>
-A5
-I=vps-may
-J=<mypassword>
-l=XXX.YYY.148.78:6432
-l=777.666.444.119:6432
#-v
```

I am proposing using these two Instances as Fedoration Supernodes
Is this OK, or will I have problems?

Thx

**Comment by hamishcoleman** [comment]
I have used some Oracle Free Tier VM's for testing n2n and it appeared to work fine.  You do need to expose the supernode port publicly in the oracle firewall rules (And the same again for the edge ports, if you also want these VMs's to be fully part of the Peer-to-Peer network)

**Comment by Logan007** [comment]
Actually, I get the `... changed ...` messages a lot at some of my nodes. It happens because the supernode reports the public address/port back for communication with a specific peer while the local edges might have found out the local socket/port already (by multicast peer detection or `-e ...` information). There is no selection/override logic to prefer certain reported sockets over others as we do not want to miss an edge eventually roaming – the edges just take and use peer addresses as they come in.

If the NAT instance supports hairpinning, it usually is no issue.

**Comment by Logan007** [comment]
considered answered, please re-open if required
