### ISSUE TITLE
Directory structure changes are recommended

### ISSUE THREAD

**Issue by lucktu** [ntop/n2n#97]
Put the current project in n2n_v2, create a new directory n2n_v1, n2n_v3 reserved location, there is n2n_v3?

n2n_v1: Small fix, because many people still use it, After all, n2n_v1 is your child, isn't it?
n2n_v2: Current main project, the -A parameter is not compatible with the previous one and should be put into v3, for testing purposes only here. it's better not to use -A, for example, -f, in v1 and v2 it's just the opposite, confusing and easy to make mistakes.

Just a suggestion, respect the official final decision.

**Comment by emanuele-f** [comment]
The proper way to do this is via git branches. Anyway, meyerd already provides v1 and v2 so I think it's not necessary to replicate the work here. If he decides to merge all the stuff in this repo, then I would put v1 and v2 in separate branches.

**Comment by lucktu** [comment]
Yes, I see.
