### ISSUE TITLE
Some problems about the networking mode of each client on the network

### ISSUE THREAD

**Issue by yzazzx2021** [ntop/n2n#972]
Hello

At present, I am using the same point-to-point networking scheme as n2n,However, when there are symmetric NAT clients outside the network that need to join the network,There will be an embarrassing situation that you can only join and can't communicate with other clients on the network,Then the current server will directly abandon the symmetric NAT client.Because point-to-point networking only includes NAT traversal，So I want to ask,Can the current n2n server automatically switch to the server to forward all the data of the failed client after the NAT traversal fails?

**Comment by Logan007** [comment]
n2n's edges automatically perform packet forwarding through the supernode as long as a peer-to-peer connection is not established.

By providing `-S` (or: `-S2` for TCP, not on Windows) to the edges, you can even force (certain or all) the edges to always remain in forwarding mode.
