### ISSUE TITLE
OmniEdge: A n2n based service with dashboard, security key, customize supernode service, offer clients for windows, macOS Cli, Linux Cli, android and iOS

### ISSUE THREAD

**Issue by yongqianme** [ntop/n2n#979]
OmniEdge: 

A n2n based online service with dashboard, security key, customized supernode service, offer clients for windows, macOS Cli, Linux Cli, android and iOS

https://omniedge.io/docs/article/Opensource

**Comment by yanyuechuixue** [comment]
A commen : It seems that the ios version can not set a customized supernode service?

Edited: Well, I see. It needs $10 per month to set a customized supernode.

**Comment by Logan007** [comment]
Let me just point out here that omniewdge is selling their product (which is based on n2n). The omniedge version is not managed by ntop team nor conducted by n2n maintainers.

**Comment by yongqianme** [comment]
Thanks @Logan007 for pointing out. 

By the way, @yanyuechuixue,  we can offer you free access to team plan if you can contribute to n2n project.
