### ISSUE TITLE
Is there any way to get rid of this situation?

### ISSUE THREAD

**Issue by galaxyskyknight** [ntop/n2n#980]
Hello

I run the edge on the OpenWRT router and recently(I reported this issue before but can't stop to report it again) I am still  disturbed and confused with the following logs output on the router, it doesn't impact any n2n function, but very noisy and it prints continously day and night ..... I wonder if you can kindly help to diag and investigate it and helo me find the root cause? I see there are some analysis articles on the internet given the solution and I listed here FYI, please see if there is any setsockopt function missing for the socket properties set in the code? Does the following help?

https://topic.alibabacloud.com/a/broadcast-boradcast-socket-font-colorredsendtofont-error-errno101-network-is-unreachable_8_8_20221678.html

the openwrt logs:

Fri Apr 15 17:13:48 2022 daemon.info n2n[17543]: WARNING: sendto failed (101) Network unreachable
Fri Apr 15 17:13:48 2022 daemon.info n2n[17543]: WARNING: sendto failed (101) Network unreachable
Fri Apr 15 17:13:51 2022 daemon.info n2n[17543]: WARNING: sendto failed (101) Network unreachable
Fri Apr 15 17:13:57 2022 daemon.info n2n[17543]: WARNING: sendto failed (101) Network unreachable
Fri Apr 15 17:13:57 2022 daemon.info n2n[17543]: WARNING: sendto failed (101) Network unreachable
Fri Apr 15 17:13:57 2022 daemon.info n2n[17543]: WARNING: sendto failed (101) Network unreachable
Fri Apr 15 17:13:57 2022 daemon.info n2n[17543]: WARNING: sendto failed (101) Network unreachable
Fri Apr 15 17:14:12 2022 daemon.info n2n[17543]: WARNING: sendto failed (101) Network unreachable
Fri Apr 15 17:14:18 2022 daemon.info n2n[17543]: WARNING: sendto failed (101) Network unreachable
Fri Apr 15 17:14:18 2022 daemon.info n2n[17543]: WARNING: sendto failed (101) Network unreachable
Fri Apr 15 17:14:18 2022 daemon.info n2n[17543]: WARNING: sendto failed (101) Network unreachable
Fri Apr 15 17:14:18 2022 daemon.info n2n[17543]: WARNING: sendto failed (101) Network unreachable
Fri Apr 15 17:14:30 2022 daemon.info n2n[17543]: WARNING: sendto failed (101) Network unreachable
Fri Apr 15 17:14:30 2022 daemon.info n2n[17543]: WARNING: sendto failed (101) Network unreachable
Fri Apr 15 17:14:33 2022 daemon.info n2n[17543]: WARNING: sendto failed (101) Network unreachable
Fri Apr 15 17:14:39 2022 daemon.info n2n[17543]: WARNING: sendto failed (101) Network unreachable
Fri Apr 15 17:14:39 2022 daemon.info n2n[17543]: WARNING: sendto failed (101) Network unreachable
Fri Apr 15 17:14:39 2022 daemon.info n2n[17543]: WARNING: sendto failed (101) Network unreachable
Fri Apr 15 17:14:39 2022 daemon.info n2n[17543]: WARNING: sendto failed (101) Network unreachable

**Comment by hamishcoleman** [comment]
This error you are seeing is a real error that gets created when there is a peer that is on a network that is not routeable.

As a first step, we can probably add some more details to the error output to make it clear which IP addresses are causing this, and you could use that to look at your routing tables and peers to figure this out.

**Comment by Logan007** [comment]
Hey @galaxyskyknight,

Have you set a default route on your router?

**Comment by galaxyskyknight** [comment]
> Hey @galaxyskyknight,
> 
> Have you set a default route on your router?

of couse, sure, no default route on router, no internet, right? it is a home network router :)

**Comment by hamishcoleman** [comment]
@galaxyskyknight what version are you running?  Are you able to compile a dev version and try that out?  I am adding the extra details to the error messages in a dev branch (#981)

**Comment by galaxyskyknight** [comment]
> @galaxyskyknight what version are you running? Are you able to compile a dev version and try that out? I am adding the extra details to the error messages in a dev branch (#981)

I am running the latest dev code, OK, I will try yours.

**Comment by hamishcoleman** [comment]
I am quite interested in what your results are.

Also, do you have automation to build your Openwrt binaries?  If so, is it published somewhere?

**Comment by galaxyskyknight** [comment]
> I am quite interested in what your results are.
> 
> Also, do you have automation to build your Openwrt binaries? If so, is it published somewhere?

I believe I may found the issue cause, I have 3 WAN ports, and using the mwan3 (a WAN load balance plugin in OpenWRT), I configured all 3 WAN ports in a LB group, and they displayed as all default routes with metric 1, however, recently one of WAN is dropped from the LB group and it is no longer as default route, then the log generated even other 2 WAN still running as default routes. I believe the edge is trying to send the broadcast to all of them, so probably the sendto 101 error generated, after I correct this, the log disappered.

For some reason, I haven't got the chance to run your code yet.

**Comment by hamishcoleman** [comment]
From reading the code, it is unlikely to be a broadcast packet - have you seen something that suggests it is a broadcast?

**Comment by GreatMichaelLee** [comment]
> From reading the code, it is unlikely to be a broadcast packet - have you seen something that suggests it is a broadcast?

I reproduce the issue, my soft router has a mwan3 plugin which I installed mutiple WAN and load balance on it, when there are some configure change for the mwan3 and after applying, due to the mwan3 saving configure  it will trigger a firewall restart, hence, there are logs for n2n as I reported above, I am wodnering if the n2n code can detect this situation and adapt to it? looks to me it is a layer 2 topology update and in bottom layer, does it change the socket fd or something like that so that will make the error happen?

sorry, for some reason, I am not convinence to run your debug code....

**Comment by galaxyskyknight** [comment]
> From reading the code, it is unlikely to be a broadcast packet - have you seen something that suggests it is a broadcast?

For a quick solution, May I suggest that you change this log to DEBUG level from WARNING? it is really noisy but not impact anything in my system.And from soft engineering perspective, It should be debug level anyway. thanks.  @hamishcoleman

the log in Openwrt output is like this, is it generated by edge binary?

Mon Apr 25 21:05:35 2022 daemon.info n2n[15381]: WARNING: sendto failed (101) Network unreachable
Mon Apr 25 21:05:35 2022 daemon.info n2n[15381]: WARNING: sendto failed (101) Network unreachable

**Comment by hamishcoleman** [comment]
This error message is a legitimate sign of a real issue with sending actual traffic, it is in no way a DEBUG message.  If you can try the branch I created with additional informational output, it might be possible to determine why your setup is triggering so many of these sending errors.

**Comment by galaxyskyknight** [comment]
> This error message is a legitimate sign of a real issue with sending actual traffic, it is in no way a DEBUG message. If you can try the branch I created with additional informational output, it might be possible to determine why your setup is triggering so many of these sending errors.

I am not convinence to try that yet as I mentioned, so is there any conf option to specify the log level for edge? I would prefer to make the log level lower than warning to get rid of it. I really just only wanna to stop this continously printing damn legitimate  but noisy log which flusing the whole log contents in my system, it floods out the other daemon/service generated logs in my soft router , whatever the error is , it indeed do no any harmful to the any edge's basic function....And It is not urgent for me to determine how and why it is triggered currently. can you help if there is any log level setting parameter? thanks

**Comment by Logan007** [comment]
> And from soft engineering perspective, It should be debug level anyway. 

As n2n is network software, a working "shipping of packets" is to be considered essential function. So it deserves (at least) a `WARNING` in case of error because it indicates exceptional, i.e. unexpected, conditions of the underlying network. 

> May I suggest that you change this log to DEBUG level from WARNING?

With their rare occurrence, we need to be sure to catch them and even with greater details. A general downgrade would also disable all users from the opportunity to fix their network issues because they do not get aware of this exceptional condition.

We already allow one special case for downgrade namely unresolved supernodes (EAFNOSUPPORT) which is acceptable because it is an expected program/system condition.

> sorry, for some reason, I am not convinence to run your debug code....

I checked the code and it is very good. It even addresses one point which I was not able to solve earlier (#725 – my first trials in using a dynamic log level until I realized logging uses macros which I was not able to handle at that time, resulting in the awkward `if/else` construction repeating the log instructions differing only by log level, now solvable with `int level` as parameter – thanks @hamishcoleman ).

I would recommend to add that code permanently to _dev_ branch for users will benefit from the more detailed information in case of network errors.

@galaxyskyknight The `WARNING` message is most likely caused by some known or unknown network configuration error. If this is the case, I do not think it is n2n's responsibility to work around this. My best recommendation would be to encircle the underlying cause (and the enhanced debug output would help you or maybe even us to help you if you shared) **or** (and I am reluctant here because I think it is wrong) enhance the `if(errno == ...` statement at `src/edge_utils.c:1036/1053` with an additional check for the 101 error you see to adapt it to your own personal needs.

**Comment by galaxyskyknight** [comment]
> > And from soft engineering perspective, It should be debug level anyway.
> 
> As n2n is network software, a working "shipping of packets" is to be considered essential function. So it deserves (at least) a `WARNING` in case of error because it indicates exceptional, i.e. unexpected, conditions of the underlying network.
> 
> > May I suggest that you change this log to DEBUG level from WARNING?
> 
> With their rare occurrence, we need to be sure to catch them and even with greater details. A general downgrade would also disable all users from the opportunity to fix their network issues because they do not get aware of this exceptional condition.
> 
> We already allow one special case for downgrade namely unresolved supernodes (EAFNOSUPPORT) which is acceptable because it is an expected program/system condition.
> 
> > sorry, for some reason, I am not convinence to run your debug code....
> 
> I checked the code and it is very good. It even addresses one point which I was not able to solve earlier (#725 – my first trials in using a dynamic log level until I realized logging uses macros which I was not able to handle at that time, resulting in the awkward `if/else` construction repeating the log instructions differing only by log level, now solvable with `int level` as parameter – thanks @hamishcoleman ).
> 
> I would recommend to add that code permanently to _dev_ branch for users will benefit from the more detailed information in case of network errors.
> 
> @galaxyskyknight The `WARNING` message is most likely caused by some known or unknown network configuration error. If this is the case, I do not think it is n2n's responsibility to work around this. My best recommendation would be to encircle the underlying cause (and the enhanced debug output would help you or maybe even us to help you if you shared) **or** (and I am reluctant here because I think it is wrong) enhance the `if(errno == ...` statement at `src/edge_utils.c:1036/1053` with an additional check for the 101 error you see to adapt it to your own personal needs.

I don't think you exactly got my point, my point is:
1) whatever the software is commercial or opensource ,the best engineering practice or  software industry standared is generally to make the log level design to 5-6 levels like :  CRITIACAL/ERROR/WARNING/INFO/DEBUG/TRACE, I think this is no question and common sense
2) the log level should be configurable in any software design for both easy debug and easy switch on/off to adaptive to production enviroment.

So based on above, the point there is, I really don't care you insist this log should be warning is proper design or legitimate  or not, you think it is OK, its OK, what I asked is, for now, I don't wanna resolve this problem, I just wanna this log get out. so my way is that how to adjust the edge log level above WARNING e.g  ERROR or CRITICAL? so that I can get it out. Could this be configurable in the edge.conf via any parameters? Don't tell me it is not support yet... if it is the situation, may I ask an enhancment request that you guys could help to do that? And I think this is the true responsibility of the n2n software...

It will be more compliance to the software log design standared and will be more easier for your debug purpose, right? Later on, you can add more debug log as you like but will not impact any users which they don't wanna see them per the log level configured with their circumstance or willing or priority, whatever. And also, once the user has the will or chance to help your debug, they just easily to switch the log level to debug and collect the logs  which may previously massive coded here and there for you but not need to wait a debug info may still non implemented and just let user to do an engineering version upgrade for debug purpose. I understood there still needed some afterwards debug coding, but this would major decline the probability of engineering debug version.

Thanks, sorry for the critical words....

**Comment by Logan007** [comment]
Oh no, I really did not get your point!

> 1. whatever the software is commercial or opensource ,the best engineering practice or software industry standared is generally to make the log level design to 5-6 levels like : CRITIACAL/ERROR/WARNING/INFO/DEBUG/TRACE, I think this is no question and common sense

We actually have five different log levels, see `src/n2n.c:171`: `ERROR`, `WARNING`, `INFO`, `NORMAL`, `DEBUG`.

> 2. the log level should be configurable in any software design for both easy debug and easy switch on/off to adaptive to production enviroment.

And it already is configurable, see `-v` command line option to increase verbosity and `+verb` as well `-verb` at management port.

> Could this be configurable in the edge.conf via any parameters? 

Yes, see above.

> Don't tell me it is not support yet... 

What we do not have yet is a command line parameter for decreasing verbosity, but you can use the management port.

> if it is the situation, may I ask an enhancment request that you guys could help to do that?

We could add "cli parameter for decreasing verbosity" to the list.

> And I think this is the true responsibility of the n2n software...

Maybe we can agree on that log levels are **part** of n2n's responsibility or feature set. 

However, I still think that current log levels are well balanced, see the explanation of `WARNING` in case of `send()` failing above as an example. So, a feature "cli parameter for decreasing verbosity" might not be top priority.

Talking about responsibility, this is still open source and a community-driven project. Perhaps someone is interested in contributing and implementing it?

> Thanks, sorry for the critical words....

Don't worry, we love discussions!

**Comment by GreatMichaelLee** [comment]
> This error message is a legitimate sign of a real issue with sending actual traffic, it is in no way a DEBUG message. If you can try the branch I created with additional informational output, it might be possible to determine why your setup is triggering so many of these sending errors.

I tried your latest code on dev here, seems led to coredump

[  162.907765] traps: edge[15759] trap stack segment ip:41a686 sp:7ffc802cf230 error:0 in edge[403000+80000]

**Comment by Logan007** [comment]
I have not encountered it yet with current _dev_. Just a quick thought, did you do `make clean` before re-building?

**Comment by GreatMichaelLee** [comment]
> I have not encountered it yet with current _dev_. Just a quick thought, did you do `make clean` before re-building?

no, but I revert to previous commit, no core dump anymore. it only happened on the openwrt softrouter boot up which the edge is started via /etc/rc.d/ init scripts, and later on it could be  run up by mannul service restart.

**Comment by Logan007** [comment]
Then please try to build with `make clean` as a first step (as always recommended before re-building) and the issue might be gone...

If you did not do `make clean` it is very understandable that the previously built commit will work because all the object files (or so) from that previous built are still present and the new build relies on old files and is not "clean".

**Comment by Logan007** [comment]
> . it only happened on the openwrt softrouter boot up which the edge is started via /etc/rc.d/ init scripts, and later on it could be run up by mannul service restart.

This indeed is strange.

**Comment by Logan007** [comment]
Could you please confirm that `make clean` did not help?
