### ISSUE TITLE
Ping by hostname?

### ISSUE THREAD

**Issue by Sadtrxsh** [ntop/n2n#986]
Hello, I am wondering how to make edges able to ping each other by hostname without adding them manually to /etc/hosts
Any suggestions? Thanks in advance

**Comment by Logan007** [comment]
How about [mDNS](https://unix.stackexchange.com/a/255713) (or other solutions suggested in that thread)?

As you mention `/etc/hosts`, I assume you are on Linux. [Avahi](https://wiki.archlinux.org/title/Avahi) seems one or the way to go then – should you decide for mDNS. It can possibly be limited to n2n's VPN netowork interface, see [`allow-interfaces=`](https://linux.die.net/man/5/avahi-daemon.conf).

**Comment by Logan007** [comment]
Considered answered. Please re-open if required.
