### ISSUE TITLE
Supernode failed to start

### ISSUE THREAD

**Issue by harryzcy** [ntop/n2n#988]
`supernode` can not start on Ubuntu 20.04.4 LTS. I compiled from source from `3.0-stable` branch.

When I try to run it using `sudo supernode -p 1234 -v`, it exit immediately with an exit code `0`.

My `supernode` version:
```
Welcome to n2n v.3.0.0.r1044.6dac89f for Debian bullseye/sid
Built on May  2 2022 03:21:24
Copyright 2007-2021 - ntop.org and contributors

   basic usage:  supernode <config file> (see supernode.conf)

            or   supernode [optional parameters, at least one] 
                      
 technically, all parameters are optional, but the supernode executable
 requires at least one parameter to run, .e.g. -v or -f, as otherwise this
 short help text is displayed

  -h    shows a quick reference including all available options
 --help gives a detailed parameter description
   man  files for n2n, edge, and superndode contain in-depth information
```

**Comment by Logan007** [comment]
On Linux and without providing `-f`, it will usually run in the background. You'd probably see the supernode using `ps` or `top` then.

Please try to add `-f` to see it run in foreground.

**Comment by hamishcoleman** [comment]
Did you run the supernode as root?

Unfortunately, the 3.0-stable supernode fails and exits immediately if it is not run as root.

**Comment by harryzcy** [comment]
> On Linux and without providing `-f`, it will usually run in the background. You'd probably see the supernode using `ps` or `top` then.
> 
> Please try to add `-f` to see it run in foreground.

That solves it. Thank you!
