### ISSUE TITLE
macos 10.14.4

### ISSUE THREAD

**Issue by hucs2542** [ntop/n2n#99]
gcc -g3  -Wall -Wshadow -Wpointer-arith -Wmissing-declarations -Wnested-externs    -DN2N_HAVE_AES -c n2n.c
gcc -g3  -Wall -Wshadow -Wpointer-arith -Wmissing-declarations -Wnested-externs    -DN2N_HAVE_AES -c n2n_keyfile.c
gcc -g3  -Wall -Wshadow -Wpointer-arith -Wmissing-declarations -Wnested-externs    -DN2N_HAVE_AES -c wire.c
gcc -g3  -Wall -Wshadow -Wpointer-arith -Wmissing-declarations -Wnested-externs    -DN2N_HAVE_AES -c minilzo.c
gcc -g3  -Wall -Wshadow -Wpointer-arith -Wmissing-declarations -Wnested-externs    -DN2N_HAVE_AES -c twofish.c
gcc -g3  -Wall -Wshadow -Wpointer-arith -Wmissing-declarations -Wnested-externs    -DN2N_HAVE_AES -c edge_utils.c
gcc -g3  -Wall -Wshadow -Wpointer-arith -Wmissing-declarations -Wnested-externs    -DN2N_HAVE_AES -c transform_null.c
gcc -g3  -Wall -Wshadow -Wpointer-arith -Wmissing-declarations -Wnested-externs    -DN2N_HAVE_AES -c transform_tf.c
gcc -g3  -Wall -Wshadow -Wpointer-arith -Wmissing-declarations -Wnested-externs    -DN2N_HAVE_AES -c transform_aes.c
gcc -g3  -Wall -Wshadow -Wpointer-arith -Wmissing-declarations -Wnested-externs    -DN2N_HAVE_AES -c tuntap_freebsd.c
gcc -g3  -Wall -Wshadow -Wpointer-arith -Wmissing-declarations -Wnested-externs    -DN2N_HAVE_AES -c tuntap_netbsd.c
gcc -g3  -Wall -Wshadow -Wpointer-arith -Wmissing-declarations -Wnested-externs    -DN2N_HAVE_AES -c tuntap_linux.c
gcc -g3  -Wall -Wshadow -Wpointer-arith -Wmissing-declarations -Wnested-externs    -DN2N_HAVE_AES -c tuntap_osx.c
gcc -g3  -Wall -Wshadow -Wpointer-arith -Wmissing-declarations -Wnested-externs    -DN2N_HAVE_AES -DN2N_VERSION='"2.4"' -DN2N_OSNAME='"i386"' -c version.c
ar rcs libn2n.a n2n.o n2n_keyfile.o wire.o minilzo.o twofish.o edge_utils.o transform_null.o transform_tf.o transform_aes.o tuntap_freebsd.o tuntap_netbsd.o tuntap_linux.o tuntap_osx.o version.o
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libn2n.a(tuntap_freebsd.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libn2n.a(tuntap_netbsd.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libn2n.a(tuntap_linux.o) has no symbols
gcc -g3  -Wall -Wshadow -Wpointer-arith -Wmissing-declarations -Wnested-externs    -DN2N_HAVE_AES edge.c libn2n.a  -lcrypto -o edge
ld: library not found for -lcrypto
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [edge] Error 1

**Comment by emanuele-f** [comment]
The `-lcrypto` linker flag is giving the error, openssl seems missing in your system, what is the output of `./configure`?

**Comment by lucktu** [comment]
Compiling is not easy, especially for those of us who can't program. don't even think about it if your English is poor, to succeed, you must also be patient. This is the fifth time I have compiled in Windows according to someone else's tutorial. I only succeeded once before, and now I can't.

Today, with the help of a friend, I tried to compile n2n for windows7 x86 with MinGW & Cmake (gcc version 6.3.0 <MinGW.org GCC-6.3.0-1>).

<blockquote><pre>
cd /c/n2n-dev/
mkdir build
cd build
cmake -G "MSYS Makefiles" --build ./ ../
make
</pre></blockquote>

1. wintap.c:213:8:error: 'ERROR_IO_PENDING' undeclared <first use in this function>
Add the comment line "#define ERROR_IO_PENDING 997" in wintap.c

2. edge_utils.c: 1779:67: warning: passing argument 4 of 'setsockopt' from incompatible pointer type [-Wincompatible-pointer-types]
 ... ...
Add the following information in  transform_aes.c & sn.c  # Would I write code like this? Oh, no! I don't even know what went wrong.
<blockquote><pre>
#ifdef __MINGW32__
typedef unsigned int u_int32_t;
typedef unsigned short u_int16_t;
typedef unsigned char u_int8_t;
#endif
</blockquote></pre>

3. Then I get edge & supernode, initial run, prompt missing "libcrypto.dll"
copy C:\Windows\System32\libcrypto-1_1.dll to C:\Windows\System32\libcrypto.dll

4. Run it again, error:
<blockquote><pre>
28/Apr/2019 16:51:51 [c:/n2n-dev/edge.c:285] Adding supernode[0] = n2n.lucktu.com:10086
28/Apr/2019 16:51:51 [c:/n2n-dev/edge.c:619] Starting n2n edge 2.5.0 Apr 28 2019 16:09:39
28/Apr/2019 16:51:51 [c:/n2n-dev/edge.c:622] supernode 0 => n2n.lucktu.com:10086
28/Apr/2019 16:51:51 [c:/n2n-dev/edge.c:662] ip_mode='static'
Open device [name={23E846C8-16E3-4D0F-945A-6F22490784E0}][ip=10.10.0.15][ifName=TAP-Adapter1][MTU=1400][mac=00:FF:23:E8:46:C8]
Setting TAP-Adapter1 device address...
Device TAP-Adapter1 set to 10.10.0.15/255.255.255.0
28/Apr/2019 16:51:52 [c:/n2n-dev/edge_utils.c:1787] ERROR: Failed to bind to local multicast group 224.0.0.68:1968 [errno 0]
28/Apr/2019 16:51:52 [c:/n2n-dev/edge_utils.c:1791] ERROR: WSAGetLastError(): 10065
28/Apr/2019 16:51:52 [c:/n2n-dev/edge.c:695] ERROR: Error: socket setup failed
</blockquote></pre>

Now, it still doesn't work, and he can't do anything about it temporarily.

**Comment by emanuele-f** [comment]
@lucktu please note that your comment is not related to this issue, as the topic is Mac OS here. Please open a separate issue if you need help. Windows is not a programmer friendly framework so I can understand. On windows 10 I can successfully compile and run with these instructions https://github.com/ntop/n2n/blob/dev/doc/Windows.md .

**Comment by lucktu** [comment]
Yes, I used that link to compile, but again it didn't work. 
https://github.com/ntop/n2n/blob/dev/doc/Windows.md

I don't need help yet because I feel like it's about to be transformed. I've successfully tested it on my padavan, synology, ubuntu. My friend compiles in windows7x64 is normal, but windowsx86 is also abnormal. I tried to compile for Windows, mainly for other friends. After all, Windows, android, and ios are widely used.

**Comment by emanuele-f** [comment]
@hucs2542 have you managed to compile it on macos?

**Comment by whiler** [comment]
@hucs2542 it works for me, maybe it can help you too.
```#!/bin/bash

git clone https://github.com/ntop/n2n.git
brew install openssl
pushd n2n
	git checkout 2.4-stable
	OPTIONS="-I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib" make
popd
```

**Comment by hucs2542** [comment]
> @ hucs2542你有没有设法在macos上编译它？

macos 10.13.6   OK

**Comment by hucs2542** [comment]
> @ hucs2542它适合我，也许它也可以帮助你。
> 
> ```
> 
> git clone https://github.com/ntop/n2n.git
> brew install openssl
> pushd n2n
> 	git checkout 2.4-stable
> 	OPTIONS="-I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib" make
> popd
> ```

 thank you

**Comment by emanuele-f** [comment]
Please close this github issue if it's solved, thank you. The instructions above should be added to https://github.com/ntop/n2n/blob/dev/doc/n2n_on_MacOS.txt , @whiler do you want to provide a pull request?

**Comment by whiler** [comment]
> Please close this github issue if it's solved, thank you. The instructions above should be added to https://github.com/ntop/n2n/blob/dev/doc/n2n_on_MacOS.txt , @whiler do you want to provide a pull request?

@emanuele-f it only works for branch 2.4-stable . Current branch dev has fixed the issue.

**Comment by kumekay** [comment]
One more issue I've encountered with compilation on macos after following these steps https://github.com/ntop/n2n/issues/99#issuecomment-499381639 is:

```
OPTIONS="-I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib" make
gcc -g3  -Wall -Wshadow -Wpointer-arith -Wmissing-declarations -Wnested-externs -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib   -DN2N_HAVE_AES edge.c libn2n.a  -lcrypto -o edge
ld: warning: ignoring file libn2n.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 0x20 )
Undefined symbols for architecture x86_64:
  "_edge_init", referenced from:
      _main in edge-a9fa43.o
  "_edge_init_keyschedule", referenced from:
      _main in edge-a9fa43.o
  "_edge_init_twofish", referenced from:
      _main in edge-a9fa43.o
  "_n2n_sw_buildDate", referenced from:
      _main in edge-a9fa43.o
  "_n2n_sw_version", referenced from:
      _main in edge-a9fa43.o
  "_open_socket", referenced from:
      _main in edge-a9fa43.o
  "_print_n2n_version", referenced from:
      _help in edge-a9fa43.o
  "_run_edge_loop", referenced from:
      _main in edge-a9fa43.o
  "_supernode2addr", referenced from:
      _main in edge-a9fa43.o
  "_traceEvent", referenced from:
      _main in edge-a9fa43.o
      _loadFromFile in edge-a9fa43.o
      _setOption in edge-a9fa43.o
      _daemonize in edge-a9fa43.o
  "_traceLevel", referenced from:
      _setOption in edge-a9fa43.o
  "_tuntap_open", referenced from:
      _main in edge-a9fa43.o
  "_update_supernode_reg", referenced from:
      _main in edge-a9fa43.o
  "_useSyslog", referenced from:
      _main in edge-a9fa43.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [edge] Error 1
```
Solution to this for me was to

```
brew unlink binutils
```

and please don't forget to `make clean` before rerun `make`

**Comment by emanuele-f** [comment]
Please modify n2n_on_MacOS.txt and provide a pull request in order to add it to the instructions, thank you
