### ISSUE TITLE
V3.0-stable, Maximum number of communities

### ISSUE THREAD

**Issue by xiangbinwu-allen** [ntop/n2n#990]
We install V3.0-stable. 
We have the following questions
1. Maximum number of communities ? 
2. Maximum number of edge under supernode ? 
3. Maximum number of edge under one community ?

**Comment by Logan007** [comment]
Hello,

There is no maximum number of allowed communities, edges under a supernode nor edges per community in the code. You can chose as many as your hardware allows. Limiting factors might be the supernode's network bandwidth and CPU power.

Please keep in mind that you can federate several supernodes to better scale for a lager number of edges and share the load, see `doc/Federation.md` for details.

We have heard of someone trying 5,000 edges connected to only one supernode (no supernode federation) which seemed to be too much to handle in that case, but again, it will depend on your hardware and if you use federated supernodes.

Perhaps, users can share their network sizes here?
