### ISSUE TITLE
[enhancement]Another N2N Windows GUI Package

### ISSUE THREAD

**Issue by happyntec** [ntop/n2n#994]
Dear N2N developers：

I've released another n2n windows package named [happynet](https://github.com/happynclient/happynwindows);

It's a GUI program for N2N Client packaging, for N2N users to provide easy to use interface control;

And happynet install package integrates TUN driver, users can easily install TUN Ethernet device;

#### screenshots
![basic_gui](https://user-images.githubusercontent.com/86546534/167811976-5e3c5e0a-6ead-4edc-8921-140e70430cc5.png)
![ad_gui](https://user-images.githubusercontent.com/86546534/167811988-06340e09-9627-49b6-ad2b-eda7bb89311d.png)

#### Project URL

https://github.com/happynclient/happynwindows

**Comment by Logan007** [comment]
Hello,

it looks good! Is it fully compatible with current dev? And can your client connect to regular supernode?

Also, I saw you have some nice compatibility fixes for Windows XP wich could fix #847 and perhaps even #625. Would you like to create a pull request and contribute your changes to ntop's n2n _dev_ branch in a way it can handle both, the XP and current Windows versions?

**Comment by happyntec** [comment]
Hi, 

thank you for reply;

#### it looks good! Is it fully compatible with current dev? And can your client connect to regular supernode?
Sure. Now the install package integrated N2N Edge 3.0.0 client, and the main program just a GUI Wrapper； Users can replace the happynedge.exe by any version of edge client which compatible with edge3.0.0 params;It works fine;

![1](https://user-images.githubusercontent.com/86546534/168198891-355adc60-3c71-42b4-a43a-11a2929a4858.png)

#### Would you like to create a pull request and contribute your changes to ntop's n2n dev branch in a way it can handle both, the XP and current Windows versions

Sorry I just do a dirty monkey patch with 2.9 branch for winxp compatibility; There is something wrong for winxp <--> win10 communication；And Very few users need winxp support, So i no longer work for lastest version;
