### ISSUE TITLE
edge print Warning supernode not responsing

### ISSUE THREAD

**Issue by xiangbinwu-allen** [ntop/n2n#995]
n2n: V3.1.1-dev
edge(The edge is mounted on the router device, and the openwrt system) print
      Warning supernode not responsing, now trying [ip:posrt] for about 8 seconds
The supernode(non-Federation) log shows that the node was successfully created. How to judge whether it is a supernode problem or an edge problem.

what could be the cause of the problem? 
What are the common diagnostic options? 

![image](https://user-images.githubusercontent.com/52592063/167838472-cffc06e3-c316-4fd6-9653-872b559ab5ea.png)
![image](https://user-images.githubusercontent.com/52592063/167839070-b79506b5-16e9-47be-9fae-703241a5dc32.png)

**Comment by Logan007** [comment]
You probably already know the `-vvvvvv` at edge and supernode for more verbose log output.

It seems as if supernode's `REGISTER_SUPER_ACK` (answer to `REGISTER_SUPER` from edge to supernode) never reaches back to the edge. But you could see if it arrives with more verbose output.

It also reminds me of #245. Anyone more ideas?

**Comment by xiangbinwu-allen** [comment]
Thank you very much, the reason should be that the -P parameter is not added to edge
